import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Select,SelectItem } from '@/components/ui/select'
import { PageHeader,DataTable,SearchInput,FilterBar,StatusBadge,Modal } from '@/components/shared'
import { can,permissions,type CurrentUser } from '@/permissions'
import { requestJSON } from '@/services/api'
import { amount } from '../purchases/types'
import { dateLabel } from '../shipments/types'
type Batch={id:string;product_name:string;sku:string;base_unit:string;batch_number:string;received_at:string;manufactured_on:string|null;expires_on:string|null;expiry_status:string;received_quantity:string;received_damaged_quantity:string;missing_quantity:string;initial_sellable_quantity:string;available_quantity:string;finalized:boolean;purchase_cost_mmk?:string;transport_cost_mmk?:string;other_cost_mmk?:string;total_cost_mmk?:string;unit_cost_mmk?:string|null}
const labels:Record<string,string>={NO_EXPIRY:'No expiry',EXPIRED:'Expired',EXPIRING_30:'Expires within 30 days',EXPIRING_60:'Expires in 31–60 days',CURRENT:'Current'}
export default function Batches({current}:{current:CurrentUser}){
 const [q,setQ]=useState(''),[expiry,setExpiry]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<Batch|null>(null)
 const query=useQuery({queryKey:['batches',q,expiry,page],queryFn:({signal})=>requestJSON<{total:number;business_date:string;batches:Batch[]}>(`/batches?q=${encodeURIComponent(q)}&expiry=${expiry}&page=${page}&page_size=20`,{signal})})
 return <><PageHeader eyebrow="Warehouse / Batch history" title="Batches & expiry" description="Original received quantities and finalized costs stay with each batch. FIFO uses received date; expired stock is excluded from POS." actions={<Button asChild variant="outline"><a href="/inventory">Inventory</a></Button>}/><FilterBar><SearchInput label="Search batches" value={q} onValueChange={v=>{setQ(v);setPage(1)}} placeholder="Batch, product or SKU…"/><Select aria-label="Expiry filter" value={expiry} onValueChange={v=>{setExpiry(v);setPage(1)}} className="sm:w-64"><SelectItem value="">All batches</SelectItem>{Object.entries(labels).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</Select></FilterBar><p className="mb-4 text-xs text-muted-foreground">Myanmar business date: {query.data?.business_date||'…'} · Valid through the printed expiry date.</p><DataTable caption="Batch history" rows={query.data?.batches||[]} rowKey={r=>r.id} loading={query.isPending} error={query.error?.message} onRetry={()=>void query.refetch()} pagination={{page,pageSize:20,total:query.data?.total||0,onPageChange:setPage}} columns={[
 {id:'batch',header:'Batch / Product',cell:b=><button className="text-left text-sm font-medium text-primary" onClick={()=>setSelected(b)}>{b.batch_number}<span className="block text-xs font-normal text-muted-foreground">{b.product_name} · {b.sku}</span></button>},
 {id:'dates',header:'Dates',cell:b=><div className="whitespace-nowrap text-xs">Received {dateLabel(b.received_at)}<p>Made {b.manufactured_on||'Not recorded'}</p><p>Expires {b.expires_on||'Not applicable'}</p></div>},
 {id:'status',header:'Expiry',cell:b=><StatusBadge tone={b.expiry_status==='EXPIRED'?'danger':b.expiry_status.startsWith('EXPIRING')?'warning':'neutral'}>{labels[b.expiry_status]}</StatusBadge>},
 {id:'quantity',header:'Received / Available',cell:b=><span className="whitespace-nowrap tabular-nums">{amount(b.received_quantity)} / {amount(b.available_quantity)} {b.base_unit}</span>},
 ...(can(current,permissions.financeViewLandedCost)?[{id:'cost',header:'Historical cost (MMK)',cell:(b:Batch)=><div className="whitespace-nowrap tabular-nums">{amount(b.total_cost_mmk||'0')}<p className="text-xs text-muted-foreground">{b.unit_cost_mmk?`${amount(b.unit_cost_mmk)} / ${b.base_unit}`:'No sellable unit cost'}</p></div>}]:[])
 ]}/>{selected&&<Modal open onOpenChange={o=>{if(!o)setSelected(null)}} title={selected.batch_number} description={`${selected.product_name} · ${selected.base_unit}`} footer={<Button asChild variant="outline"><a href={`/inventory/movements?batch_id=${selected.id}`}>Stock movements</a></Button>}><dl className="grid grid-cols-2 gap-4 text-sm">{[['Received',amount(selected.received_quantity)],['Initially sellable',amount(selected.initial_sellable_quantity)],['Received damaged',amount(selected.received_damaged_quantity)],['Missing at receipt',amount(selected.missing_quantity)],['Available now',amount(selected.available_quantity)],['Cost status',selected.finalized?'Finalized':'Not finalized'],...(selected.total_cost_mmk!==undefined?[['Purchase (MMK)',amount(selected.purchase_cost_mmk!)],['Transport (MMK)',amount(selected.transport_cost_mmk!)],['Other (MMK)',amount(selected.other_cost_mmk!)],['Total batch cost (MMK)',amount(selected.total_cost_mmk)]]:[])].map(([k,v])=><div key={k}><dt className="text-xs text-muted-foreground">{k}</dt><dd className="mt-1 tabular-nums">{v}</dd></div>)}</dl></Modal>}</>
}
