import { useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Select,SelectItem } from '@/components/ui/select'
import { PageHeader,DataTable,FilterBar,SearchInput,Modal,FormField,QuantityInput } from '@/components/shared'
import { can,permissions,type CurrentUser } from '@/permissions'
import { requestJSON } from '@/services/api'
import { Field } from '../shipments/Fields'
import { amount } from '../purchases/types'
import { dateLabel } from '../shipments/types'
import { cartonCost,sumQuantities,quantityParts,type Stock } from './types'
export default function Inventory({current}:{current:CurrentUser}){return window.location.pathname==='/inventory/movements'?<Movements/>:<StockList current={current}/>}
function StockList({current}:{current:CurrentUser}){
 const [q,setQ]=useState(()=>new URLSearchParams(window.location.search).get('q')||'');const [warehouse,setWarehouse]=useState('');const [group,setGroup]=useState('batch');const [page,setPage]=useState(1);const [selected,setSelected]=useState<Stock|null>(null)
 const warehouses=useQuery({queryKey:['inventory-warehouses'],queryFn:()=>requestJSON<{id:string;name:string}[]>('/inventory/warehouses')})
 const query=useQuery({enabled:group==='batch',queryKey:['inventory',q,warehouse,page],queryFn:({signal})=>requestJSON<{total:number;stock:Stock[]}>(`/inventory?q=${encodeURIComponent(q)}&warehouse_id=${warehouse}&page=${page}&page_size=20`,{signal})})
 return <><PageHeader eyebrow="Warehouse / Stock control" title="Inventory" description="Available = sellable − reserved. Damaged goods are held separately. Quantities are in base units." actions={<Button asChild variant="outline"><a href="/inventory/movements">Stock movements</a></Button>}/><FilterBar><SearchInput label="Search inventory" value={q} onValueChange={v=>{setQ(v);setPage(1)}} placeholder="Product, SKU or batch…"/><Select aria-label="Inventory warehouse" value={warehouse} onValueChange={v=>{setWarehouse(v);setPage(1);setSelected(null)}}><SelectItem value="">All warehouses</SelectItem>{warehouses.data?.map(w=><SelectItem key={w.id} value={w.id}>{w.name}</SelectItem>)}</Select><Select aria-label="Stock grouping" value={group} onValueChange={v=>{setGroup(v);setPage(1);setSelected(null)}}><SelectItem value="batch">Separate batches</SelectItem><SelectItem value="product">Combine matching product stock</SelectItem><SelectItem value="brand">Group variants by brand</SelectItem></Select></FilterBar>{warehouses.error&&<p role="alert">{warehouses.error.message}</p>}{group!=='batch'?<GroupedStock key={`${group}-${warehouse}-${q}`} group={group} warehouse={warehouse} search={q} current={current} select={setSelected}/>:<DataTable caption="Batch stock" rows={query.data?.stock||[]} rowKey={r=>`${r.warehouse_id}-${r.batch_id}`} loading={query.isPending} error={query.error?.message} onRetry={()=>void query.refetch()} pagination={{page,pageSize:20,total:query.data?.total||0,onPageChange:setPage}} columns={[
 {id:'product',header:'Product / Batch',cell:r=><div className="min-w-36 font-medium">{r.product_name}<p className="text-xs font-normal text-muted-foreground">{r.sku} · {r.batch_number}</p><p className="text-xs font-normal text-muted-foreground">{r.warehouse_name} · {r.base_unit}</p>{r.expires_on&&<p className="text-xs font-normal">Expires {r.expires_on}</p>}</div>},
 {id:'available',header:'Available',cell:r=><div className="whitespace-nowrap tabular-nums"><strong>{amount(r.available_quantity)}</strong>{r.carton_size&&<p className="text-xs text-muted-foreground">{amount(r.available_cartons||'0')} cartons + {amount(r.available_units)} {r.base_unit}</p>}</div>},
 ...(['sellable_quantity','reserved_quantity','damaged_quantity'] as const).map((key,i)=>({id:key,header:['Sellable','Reserved','Damaged'][i],cell:(r:Stock)=><span className="tabular-nums">{amount(r[key])}</span>})),
 ...(can(current,permissions.financeViewLandedCost)?[{id:'carton-cost',header:'Landed Cost per Carton (MMK)',cell:(r:Stock)=>amount(cartonCost(r.unit_cost_mmk,r.carton_size))},{id:'cost',header:'Landed Cost per Piece (MMK)',cell:(r:Stock)=>r.unit_cost_mmk?amount(r.unit_cost_mmk):'No sellable cost'}]:[]),
 {id:'actions',header:'Actions',cell:r=><div className="flex gap-2"><Button size="sm" variant="ghost" asChild><a href={`/inventory/movements?batch_id=${r.batch_id}&warehouse_id=${r.warehouse_id}`}>History</a></Button>{can(current,permissions.inventoryAdjust)&&<Button size="sm" variant="outline" onClick={()=>setSelected(r)}>Adjust</Button>}</div>}
 ]}/>} {selected&&<Adjustment stock={selected} onClose={()=>setSelected(null)}/>}</>
}
function Adjustment({stock:s,onClose}:{stock:Stock;onClose:()=>void}){
 const client=useQueryClient();const [requestID]=useState(()=>crypto.randomUUID());const [bucket,setBucket]=useState('SELLABLE');const [delta,setDelta]=useState('');const [reason,setReason]=useState('')
 const mutation=useMutation({mutationFn:()=>requestJSON('/inventory/adjustments',{method:'POST',body:JSON.stringify({request_id:requestID,warehouse_id:s.warehouse_id,batch_id:s.batch_id,version:s.version,bucket,quantity_delta:delta,reason})}),onSuccess:async()=>{await client.invalidateQueries({queryKey:['inventory']});onClose()}})
 return <Modal open onOpenChange={v=>{if(!v)onClose()}} title="Adjust stock" description={`${s.product_name} · ${s.batch_number} · ${s.warehouse_name}`} busy={mutation.isPending}><form className="space-y-4" onSubmit={e=>{e.preventDefault();mutation.mutate()}}><fieldset disabled={mutation.isPending} className="space-y-4"><p className="text-xs text-muted-foreground">Sellable {amount(s.sellable_quantity)} · Reserved {amount(s.reserved_quantity)} · Damaged {amount(s.damaged_quantity)} {s.base_unit}</p><FormField label="Stock bucket" required>{p=><Select {...p} value={bucket} onValueChange={setBucket}><SelectItem value="SELLABLE">Sellable</SelectItem><SelectItem value="DAMAGED">Damaged</SelectItem><SelectItem value="RESERVED">Reserved</SelectItem></Select>}</FormField><FormField label="Quantity change" required hint="Enter a positive quantity to add, or a negative quantity to remove. Use base units.">{p=><QuantityInput {...p} value={delta} onValueChange={setDelta} allowNegative unit={s.base_unit}/>}</FormField><Field label="Adjustment reason" value={reason} onChange={setReason} required maxLength={1000}/><p className="text-xs text-muted-foreground">Posting creates an immutable movement and audit record. Reservations reduce available stock without changing sellable stock.</p></fieldset>{mutation.error&&<p role="alert" className="text-sm text-destructive">{mutation.error.message}</p>}<Button disabled={mutation.isPending}>{mutation.isPending?'Posting…':'Post adjustment'}</Button></form></Modal>
}
type Movement={id:string;batch_number:string;product_name:string;warehouse_name:string;movement_type:string;reference_number:string|null;sellable_delta:string;reserved_delta:string;damaged_delta:string;reason:string;occurred_at:string;recorded_by:string;unit_cost_mmk?:string|null}
function Movements(){
 const params=new URLSearchParams(window.location.search);const batch=params.get('batch_id')||'',warehouse=params.get('warehouse_id')||'';const [page,setPage]=useState(1)
 const q=useQuery({queryKey:['inventory-movements',batch,warehouse,page],queryFn:({signal})=>requestJSON<{total:number;movements:Movement[]}>(`/inventory/movements?batch_id=${encodeURIComponent(batch)}&warehouse_id=${encodeURIComponent(warehouse)}&page=${page}&page_size=20`,{signal})})
 return <><PageHeader eyebrow="Warehouse / Audit trail" title="Stock movements" description="Every stock change is recorded. Positive quantities add to a bucket; negative quantities remove from it." actions={<><Button asChild variant="outline"><a href="/inventory">Inventory</a></Button>{(batch||warehouse)&&<Button asChild variant="outline"><a href="/inventory/movements">All movements</a></Button>}</>}/><DataTable caption="Inventory movements" rows={q.data?.movements||[]} rowKey={r=>r.id} loading={q.isPending} error={q.error?.message} onRetry={()=>void q.refetch()} pagination={{page,pageSize:20,total:q.data?.total||0,onPageChange:setPage}} columns={[{id:'date',header:'Recorded',cell:r=><div className="min-w-32">{dateLabel(r.occurred_at)}<p className="text-xs text-muted-foreground">{r.recorded_by}</p></div>},{id:'batch',header:'Product / Batch',cell:r=><div className="min-w-36">{r.product_name}<p className="text-xs text-muted-foreground">{r.batch_number} · {r.warehouse_name}</p></div>},{id:'reference',header:'Record ID',cell:r=>r.reference_number||'—'},{id:'type',header:'Movement',cell:r=>r.movement_type},...(['sellable_delta','reserved_delta','damaged_delta'] as const).map((key,i)=>({id:key,header:['Sellable Δ','Reserved Δ','Damaged Δ'][i],cell:(r:Movement)=><span className="tabular-nums">{amount(r[key])}</span>})),{id:'reason',header:'Reason',cell:r=><span className="block min-w-40 max-w-64 text-xs">{r.reason}</span>}]}/></>
}

type StockGroup={group_id:string;group_name:string;warehouse_id:string;warehouse_name:string;stock:Stock[]}
function GroupedStock({group,warehouse,search,current,select}:{group:string;warehouse:string;search:string;current:CurrentUser;select:(s:Stock)=>void}){
 const [page,setPage]=useState(1)
 const query=useQuery({queryKey:['inventory','groups',group,warehouse,search,page],queryFn:({signal})=>requestJSON<{groups:StockGroup[];total:number}>(`/inventory/groups?group_by=${group}&warehouse_id=${warehouse}&q=${encodeURIComponent(search)}&page=${page}&page_size=20`,{signal})})
 return <><p className="mb-3 text-sm text-muted-foreground">Matching stock is combined for viewing. Expand each product to see its separate batches and landed costs. Variants keep their own SKU, quantity and warehouse prices. Set the same Brand on product records to group flavors or colors.</p><DataTable caption="Grouped inventory" rows={query.data?.groups||[]} rowKey={r=>r.group_id+r.warehouse_id} loading={query.isPending} error={query.error?.message} pagination={{page,pageSize:20,total:query.data?.total||0,onPageChange:setPage}} columns={[{id:'group',header:group==='brand'?'Brand / Warehouse':'Product / Warehouse',cell:r=><div className="min-w-36 font-semibold">{r.group_name}<p className="text-xs font-normal">{r.warehouse_name}</p></div>},{id:'stock',header:'Combined stock / Variants',cell:r=><div className="min-w-72 space-y-3">{Array.from(new Set(r.stock.map(b=>b.product_id))).map(id=>{const batches=r.stock.filter(b=>b.product_id===id),first=batches[0],available=sumQuantities(batches.map(b=>b.available_quantity));const size=batches.every(b=>b.carton_size===first.carton_size)?first.carton_size:null;const parts=quantityParts(available,size);return <details key={id} className="rounded-lg border p-3"><summary className="cursor-pointer"><strong>{first.product_name}</strong> · {first.sku}<p className="mt-1 text-sm">Available {amount(available)} {first.base_unit}{size&&` · ${amount(parts.cartons)} cartons + ${amount(parts.units)} pieces`}</p><p className="text-xs text-muted-foreground">Sellable {amount(sumQuantities(batches.map(b=>b.sellable_quantity)))} · Reserved {amount(sumQuantities(batches.map(b=>b.reserved_quantity)))} · Damaged {amount(sumQuantities(batches.map(b=>b.damaged_quantity)))} · {batches.length} batches</p></summary><div className="mt-3 space-y-3">{batches.map(b=><div key={b.batch_id} className="border-t pt-3 text-xs"><p className="font-medium">{b.batch_number} · Available {amount(b.available_quantity)} {b.base_unit}{b.expires_on&&` · Expires ${b.expires_on}`}</p>{can(current,permissions.financeViewLandedCost)&&<p>Landed Cost per Carton: {amount(cartonCost(b.unit_cost_mmk,b.carton_size))} MMK · Landed Cost per Piece: {amount(b.unit_cost_mmk)} MMK</p>}<div className="mt-2 flex gap-2"><Button size="sm" variant="outline" asChild><a href={`/inventory/movements?batch_id=${b.batch_id}&warehouse_id=${b.warehouse_id}`}>History</a></Button>{can(current,permissions.inventoryAdjust)&&<Button size="sm" variant="outline" onClick={()=>select(b)}>Adjust</Button>}</div></div>)}<Button size="sm" variant="outline" asChild><a href={`/warehouse-prices?warehouse_id=${r.warehouse_id}&q=${encodeURIComponent(first.sku)}`}>Variant selling prices</a></Button></div></details>})}</div>}]}/></>
}
