import { useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Select,SelectItem } from '@/components/ui/select'
import { PageHeader,DataTable,FilterBar,SearchInput,Modal,FormField,QuantityInput } from '@/components/shared'
import { can,permissions,type CurrentUser } from '@/permissions'
import { requestJSON } from '@/services/api'
import { Field } from '../shipments/Fields'
import { amount } from '../purchases/types'
import { dateLabel } from '../shipments/types'
import type { Stock } from './types'
export default function Inventory({current}:{current:CurrentUser}){return window.location.pathname==='/inventory/movements'?<Movements/>:<StockList current={current}/>}
function StockList({current}:{current:CurrentUser}){
 const [q,setQ]=useState(()=>new URLSearchParams(window.location.search).get('q')||'');const [warehouse,setWarehouse]=useState('');const [page,setPage]=useState(1);const [selected,setSelected]=useState<Stock|null>(null)
 const warehouses=useQuery({queryKey:['inventory-warehouses'],queryFn:()=>requestJSON<{id:string;name:string}[]>('/inventory/warehouses')})
 const query=useQuery({queryKey:['inventory',q,warehouse,page],queryFn:({signal})=>requestJSON<{total:number;stock:Stock[]}>(`/inventory?q=${encodeURIComponent(q)}&warehouse_id=${warehouse}&page=${page}&page_size=20`,{signal})})
 return <><PageHeader eyebrow="Warehouse / Stock control" title="Inventory" description="Available = sellable − reserved. Damaged goods are held separately. Quantities are in base units." actions={<Button asChild variant="outline"><a href="/inventory/movements">Stock movements</a></Button>}/><FilterBar><SearchInput label="Search inventory" value={q} onValueChange={v=>{setQ(v);setPage(1)}} placeholder="Product, SKU or batch…"/><Select aria-label="Inventory warehouse" value={warehouse} onValueChange={v=>{setWarehouse(v);setPage(1)}}><SelectItem value="">All warehouses</SelectItem>{warehouses.data?.map(w=><SelectItem key={w.id} value={w.id}>{w.name}</SelectItem>)}</Select></FilterBar>{warehouses.error&&<p role="alert">{warehouses.error.message}</p>}<DataTable caption="Batch stock" rows={query.data?.stock||[]} rowKey={r=>`${r.warehouse_id}-${r.batch_id}`} loading={query.isPending} error={query.error?.message} onRetry={()=>void query.refetch()} pagination={{page,pageSize:20,total:query.data?.total||0,onPageChange:setPage}} columns={[
 {id:'product',header:'Product / Batch',cell:r=><div className="min-w-36 font-medium">{r.product_name}<p className="text-xs font-normal text-muted-foreground">{r.sku} · {r.batch_number}</p><p className="text-xs font-normal text-muted-foreground">{r.warehouse_name} · {r.base_unit}</p>{r.expires_on&&<p className="text-xs font-normal">Expires {r.expires_on}</p>}</div>},
 {id:'available',header:'Available',cell:r=><div className="whitespace-nowrap tabular-nums"><strong>{amount(r.available_quantity)}</strong>{r.carton_size&&<p className="text-xs text-muted-foreground">{amount(r.available_cartons||'0')} cartons + {amount(r.available_units)} {r.base_unit}</p>}</div>},
 ...(['sellable_quantity','reserved_quantity','damaged_quantity'] as const).map((key,i)=>({id:key,header:['Sellable','Reserved','Damaged'][i],cell:(r:Stock)=><span className="tabular-nums">{amount(r[key])}</span>})),
 ...(can(current,permissions.financeViewLandedCost)?[{id:'cost',header:'Unit cost (MMK)',cell:(r:Stock)=>r.unit_cost_mmk?amount(r.unit_cost_mmk):'No sellable cost'}]:[]),
 {id:'actions',header:'Actions',cell:r=><div className="flex gap-2"><Button size="sm" variant="ghost" asChild><a href={`/inventory/movements?batch_id=${r.batch_id}&warehouse_id=${r.warehouse_id}`}>History</a></Button>{can(current,permissions.inventoryAdjust)&&<Button size="sm" variant="outline" onClick={()=>setSelected(r)}>Adjust</Button>}</div>}
 ]}/>{selected&&<Adjustment stock={selected} onClose={()=>setSelected(null)}/>}</>
}
function Adjustment({stock:s,onClose}:{stock:Stock;onClose:()=>void}){
 const client=useQueryClient();const [requestID]=useState(()=>crypto.randomUUID());const [bucket,setBucket]=useState('SELLABLE');const [delta,setDelta]=useState('');const [reason,setReason]=useState('')
 const mutation=useMutation({mutationFn:()=>requestJSON('/inventory/adjustments',{method:'POST',body:JSON.stringify({request_id:requestID,warehouse_id:s.warehouse_id,batch_id:s.batch_id,version:s.version,bucket,quantity_delta:delta,reason})}),onSuccess:async()=>{await client.invalidateQueries({queryKey:['inventory']});onClose()}})
 return <Modal open onOpenChange={v=>{if(!v)onClose()}} title="Adjust stock" description={`${s.product_name} · ${s.batch_number} · ${s.warehouse_name}`} busy={mutation.isPending}><form className="space-y-4" onSubmit={e=>{e.preventDefault();mutation.mutate()}}><fieldset disabled={mutation.isPending} className="space-y-4"><p className="text-xs text-muted-foreground">Sellable {amount(s.sellable_quantity)} · Reserved {amount(s.reserved_quantity)} · Damaged {amount(s.damaged_quantity)} {s.base_unit}</p><FormField label="Stock bucket" required>{p=><Select {...p} value={bucket} onValueChange={setBucket}><SelectItem value="SELLABLE">Sellable</SelectItem><SelectItem value="DAMAGED">Damaged</SelectItem><SelectItem value="RESERVED">Reserved</SelectItem></Select>}</FormField><FormField label="Quantity change" required hint="Enter a positive quantity to add, or a negative quantity to remove. Use base units.">{p=><QuantityInput {...p} value={delta} onValueChange={setDelta} allowNegative unit={s.base_unit}/>}</FormField><Field label="Adjustment reason" value={reason} onChange={setReason} required maxLength={1000}/><p className="text-xs text-muted-foreground">Posting creates an immutable movement and audit record. Reservations reduce available stock without changing sellable stock.</p></fieldset>{mutation.error&&<p role="alert" className="text-sm text-destructive">{mutation.error.message}</p>}<Button disabled={mutation.isPending}>{mutation.isPending?'Posting…':'Post adjustment'}</Button></form></Modal>
}
type Movement={id:string;batch_number:string;product_name:string;warehouse_name:string;movement_type:string;sellable_delta:string;reserved_delta:string;damaged_delta:string;reason:string;occurred_at:string;recorded_by:string;unit_cost_mmk?:string|null}
function Movements(){
 const params=new URLSearchParams(window.location.search);const batch=params.get('batch_id')||'',warehouse=params.get('warehouse_id')||'';const [page,setPage]=useState(1)
 const q=useQuery({queryKey:['inventory-movements',batch,warehouse,page],queryFn:({signal})=>requestJSON<{total:number;movements:Movement[]}>(`/inventory/movements?batch_id=${encodeURIComponent(batch)}&warehouse_id=${encodeURIComponent(warehouse)}&page=${page}&page_size=20`,{signal})})
 return <><PageHeader eyebrow="Warehouse / Audit trail" title="Stock movements" description="Every stock change is recorded. Positive quantities add to a bucket; negative quantities remove from it." actions={<><Button asChild variant="outline"><a href="/inventory">Inventory</a></Button>{(batch||warehouse)&&<Button asChild variant="outline"><a href="/inventory/movements">All movements</a></Button>}</>}/><DataTable caption="Inventory movements" rows={q.data?.movements||[]} rowKey={r=>r.id} loading={q.isPending} error={q.error?.message} onRetry={()=>void q.refetch()} pagination={{page,pageSize:20,total:q.data?.total||0,onPageChange:setPage}} columns={[{id:'date',header:'Recorded',cell:r=><div className="min-w-32">{dateLabel(r.occurred_at)}<p className="text-xs text-muted-foreground">{r.recorded_by}</p></div>},{id:'batch',header:'Product / Batch',cell:r=><div className="min-w-36">{r.product_name}<p className="text-xs text-muted-foreground">{r.batch_number} · {r.warehouse_name}</p></div>},{id:'type',header:'Movement',cell:r=>r.movement_type},...(['sellable_delta','reserved_delta','damaged_delta'] as const).map((key,i)=>({id:key,header:['Sellable Δ','Reserved Δ','Damaged Δ'][i],cell:(r:Movement)=><span className="tabular-nums">{amount(r[key])}</span>})),{id:'reason',header:'Reason',cell:r=><span className="block min-w-40 max-w-64 text-xs">{r.reason}</span>}]}/></>
}
