export type ReceivingItem={arrival_received_quantity?:string|null;arrival_damaged_quantity?:string|null;id:string;product_name:string;sku:string;base_unit:string;expected_quantity:string;sellable_quantity:string|null;carton_size:string|null;tracks_expiry:boolean}
export type ReceivingShipment={id:string;shipment_number:string;version:string;warehouse_name:string;status:string;costs_finalized:boolean;items:ReceivingItem[]}
export type Receipt={id:string;receipt_number:string;shipment_id:string;shipment_number:string;warehouse_name:string;received_at:string;received_by:string;status:string;notes:string|null;items:(ReceivingItem&{received_quantity:string;damaged_quantity:string;missing_quantity:string;batch_number:string;batch_id:string;manufactured_on:string|null;expires_on:string|null;notes:string|null})[]}
export type Count={shipment_item_id:string;carton_size:string;received_cartons:string;received_units:string;damaged_quantity:string;batch_number:string;manufactured_on:string;expires_on:string;notes:string}
export type Stock={product_id:string;brand_name?:string|null;batch_id:string;warehouse_id:string;warehouse_name:string;product_name:string;sku:string;base_unit:string;batch_number:string;expires_on:string|null;version:string;sellable_quantity:string;available_quantity:string;reserved_quantity:string;damaged_quantity:string;carton_size:string|null;available_cartons:string|null;available_units:string;unit_cost_mmk?:string|null}
const scaled=(v:string)=>{if(!/^\d{1,14}(\.\d{1,6})?$/.test(v))throw Error();const[w,f='']=v.split('.');return BigInt(w+f.padEnd(6,'0'))}
const fixed=(n:bigint)=>{const neg=n<0n;const s=(neg?-n:n).toString().padStart(7,'0');return `${neg?'-':''}${s.slice(0,-6)}.${s.slice(-6)}`}
export function counts(row:Count,item:ReceivingItem){try{const cartons=scaled(row.received_cartons)*scaled(row.carton_size||'0');if(cartons%1000000n!==0n)return null;const received=cartons/1000000n+scaled(row.received_units),damaged=scaled(row.damaged_quantity),expected=scaled(item.expected_quantity),sellable=received-damaged;return{received:fixed(received),sellable:fixed(sellable),missing:fixed(expected-received),valid:received<=expected&&damaged<=received&&(item.sellable_quantity===null||sellable===scaled(item.sellable_quantity))&&(item.arrival_received_quantity==null||(received===scaled(item.arrival_received_quantity)&&damaged===scaled(item.arrival_damaged_quantity!)))}}catch{return null}}

export function arrivalSellable(received:string,damaged:string,expected:string){try{const r=scaled(received),d=scaled(damaged);return d<=r&&r<=scaled(expected)?fixed(r-d):null}catch{return null}}

export function cartonCost(unit:string|null|undefined,size:string|null|undefined){try{if(unit==null||!size)return null;const [w,f='']=unit.split('.');const n=BigInt(w+f.padEnd(8,'0'))*scaled(size);const v=((n+500000n)/1000000n).toString().padStart(9,'0');return `${v.slice(0,-8)}.${v.slice(-8)}`}catch{return null}}
export function quantityParts(quantity:string,size:string|null){try{const n=scaled(quantity),pack=size?scaled(size):0n;return {cartons:pack?(n/pack).toString():'0',units:fixed(pack?n%pack:n)}}catch{return {cartons:'0',units:quantity}}}
export function receivedAfterLoss(expected:string,lostCartons:string,lostUnits:string,size:string){try{const cartons=scaled(lostCartons)*scaled(size||'0');if(cartons%1000000n!==0n)return '';return fixed(scaled(expected)-cartons/1000000n-scaled(lostUnits))}catch{return ''}}

export function sumQuantities(values:string[]){return fixed(values.reduce((n,v)=>n+scaled(v),0n))}
