import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { PageHeader, SearchInput, DataTable, Modal, FormField } from '@/components/shared'
import { Button } from '@/components/ui/button'
import { Select, SelectItem } from '@/components/ui/select'
import { requestJSON, ApiError } from '@/services/api'
import { can, permissions, type CurrentUser } from '@/permissions'
import { amount, today } from '../purchases/types'
import SupplierPayments from '../purchases/SupplierPayments'
import { Payment as CustomerPayment, type Invoice } from '../customers/Customers'
type Target={id:string;kind:string;shipment_id:string;shipment_number:string;shipment_status:string;reference:string;payee:string;currency_code:string;total:string;paid:string;remaining:string}
type History={id:string;payment_number:string;amount:string;currency_code:string;method:string;paid_at:string;reference_number:string;bank_account:string;notes:string;created_by:string}
const positive=(v:string)=>!v.startsWith('-')&&!/^0(?:\.0*)?$/.test(v)
export default function Payments({current}:{current:CurrentUser}){
 const allowed=[can(current,permissions.purchasesView)&&can(current,permissions.purchasesViewCost)&&'Supplier Payments',can(current,permissions.customersManage)&&'Customer Payments',can(current,permissions.shipmentsView)&&can(current,permissions.shipmentsViewCost)&&'Transportation Payments'].filter(Boolean) as string[]
 const [chosen,setChosen]=useState('');const category=chosen||allowed[0]
 return <><PageHeader title="Payments" eyebrow="Finance / Payment centre" description="Manage supplier, customer and cargo-terminal payments linked to their original transactions."/><div className="mb-5 flex flex-wrap gap-2">{allowed.map(name=><Button key={name} variant={category===name?'default':'outline'} onClick={()=>setChosen(name)}>{name}</Button>)}</div>{!allowed.length?<p>No payment categories are available with your current permissions.</p>:category==='Supplier Payments'?<SupplierPayments embedded current={current}/>:category==='Customer Payments'?<CustomerCollections current={current}/>:<TransportPayments current={current}/>}</>
}
function Filters({search,setSearch,status,setStatus,customer=false}:{search:string;setSearch:(v:string)=>void;status:string;setStatus:(v:string)=>void;customer?:boolean}){return <div className="mb-4 flex flex-wrap gap-3"><SearchInput label="Search payment transactions" value={search} onValueChange={setSearch}/><Select aria-label="Transaction payment status" value={status} onValueChange={setStatus}><SelectItem value="">All statuses</SelectItem>{['UNPAID','PARTIALLY_PAID','PAID',...(customer?['OVERDUE']:[])].map(v=><SelectItem key={v} value={v}>{v.replaceAll('_',' ')}</SelectItem>)}</Select></div>}
function CustomerCollections({current}:{current:CurrentUser}){
 const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<(Invoice&{customer_id:string;customer_name:string})|null>(null),[pay,setPay]=useState(false)
 const query=useQuery({queryKey:['central-customers',search,status,page],queryFn:()=>requestJSON<{invoices:(Invoice&{customer_id:string;customer_name:string})[];total:number}>(`/customer-payments?q=${encodeURIComponent(search)}&status=${status}&page=${page}`)})
 const history=useQuery({queryKey:['customers',selected?.customer_id,'payments'],queryFn:()=>requestJSON<{id:string;payment_number:string;invoice_number:string;amount_mmk:string;method:string;direction:string}[]>(`/customers/${selected!.customer_id}/payments`),enabled:!!selected})
 return <><Filters customer search={search} setSearch={v=>{setSearch(v);setPage(1)}} status={status} setStatus={v=>{setStatus(v);setPage(1)}}/><DataTable caption="Customer invoice balances" rows={query.data?.invoices||[]} rowKey={r=>r.id} loading={query.isPending} error={query.error?.message} pagination={{page,pageSize:20,total:query.data?.total||0,onPageChange:setPage}} columns={[{id:'invoice',header:'Invoice / customer',cell:r=><><a href={`/sales/${r.id}`} className="text-primary">{r.invoice_number}</a><p>{r.customer_name}</p></>},{id:'total',header:'Total / Paid / Remaining (MMK)',cell:r=>`${amount(r.total_mmk)} / ${amount(r.amount_paid_mmk)} / ${amount(r.outstanding_mmk)}`},{id:'status',header:'Status',cell:r=>r.payment_status.replaceAll('_',' ')},{id:'action',header:'Action',cell:r=><div className="flex gap-2"><Button variant="outline" onClick={()=>{setSelected(r);setPay(false)}}>History</Button>{can(current,permissions.paymentsManage)&&positive(r.outstanding_mmk)&&<Button onClick={()=>{setSelected(r);setPay(true)}}>Record payment</Button>}</div>}]}/>{selected&&<section className="panel mt-5 p-4"><h2 className="mb-3 font-semibold">{selected.customer_name} · payment history</h2><DataTable caption="Customer payment history" rows={history.data||[]} rowKey={r=>r.id} loading={history.isPending} error={history.error?.message} columns={[{id:'number',header:'Payment / Invoice',cell:r=>`${r.payment_number} · ${r.invoice_number}`},{id:'amount',header:'Amount (MMK)',cell:r=>amount(r.amount_mmk)},{id:'method',header:'Method / Direction',cell:r=>`${r.method} · ${r.direction}`} ]}/></section>}{pay&&selected&&<CustomerPayment customer={selected.customer_id} invoice={selected} close={()=>setPay(false)}/>}</>
}
function TransportPayments({current}:{current:CurrentUser}){
 const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<Target|null>(null),[pay,setPay]=useState(false)
 const query=useQuery({queryKey:['transport-payments',search,status,page],queryFn:()=>requestJSON<{records:Target[];total:number}>(`/transport-payments?q=${encodeURIComponent(search)}&status=${status}&page=${page}`)})
 const history=useQuery({queryKey:['transport-history',selected?.id],queryFn:()=>requestJSON<History[]>(`/transport-payments/${selected!.id}`),enabled:!!selected})
 return <><p className="mb-4 text-sm text-muted-foreground">Transportation fees are owed to the cargo terminal. Additional shipment costs remain separate charges. Neither increases supplier invoice debt.</p><Filters search={search} setSearch={v=>{setSearch(v);setPage(1)}} status={status} setStatus={v=>{setStatus(v);setPage(1)}}/><DataTable caption="Transportation balances" rows={query.data?.records||[]} rowKey={r=>r.id} loading={query.isPending} error={query.error?.message} pagination={{page,pageSize:20,total:query.data?.total||0,onPageChange:setPage}} columns={[{id:'reference',header:'Shipment / Charge',cell:r=><><a className="text-primary" href={`/shipments/${r.shipment_id}`}>{r.shipment_number}</a><p>{r.shipment_status==='CANCELLED'?'Cancelled shipment · ':''}{r.reference} · {r.kind==='TRANSPORT'?'Cargo terminal':'Additional cost'}</p></>},{id:'payee',header:'Cargo terminal / cost description',cell:r=>r.payee},{id:'balance',header:'Total / Paid / Remaining',cell:r=>`${amount(r.total)} / ${amount(r.paid)} / ${amount(r.remaining)} ${r.currency_code}`},{id:'status',header:'Status',cell:r=>!positive(r.remaining)?'Paid':positive(r.paid)?'Partially Paid':'Unpaid'},{id:'action',header:'Action',cell:r=><div className="flex gap-2"><Button variant="outline" onClick={()=>{setSelected(r);setPay(false)}}>History</Button>{positive(r.remaining)&&can(current,permissions.paymentsManage)&&<Button onClick={()=>{setSelected(r);setPay(true)}}>Record payment</Button>}</div>}]}/>{selected&&<section className="panel mt-5 p-4"><h2 className="mb-3 font-semibold">{selected.reference} · payment history</h2><DataTable caption="Transportation payment history" rows={history.data||[]} rowKey={r=>r.id} loading={history.isPending} error={history.error?.message} columns={[{id:'number',header:'Payment / Date',cell:r=>`${r.payment_number} · ${new Date(r.paid_at).toLocaleDateString()}`},{id:'amount',header:'Amount',cell:r=>`${amount(r.amount)} ${r.currency_code}`},{id:'method',header:'Method / Reference',cell:r=>`${r.method} · ${r.reference_number||''} ${r.bank_account||''}`},{id:'audit',header:'Recorded by / Notes',cell:r=>`${r.created_by} · ${r.notes||''}`} ]}/></section>}{pay&&selected&&<TransportPayment target={selected} close={()=>setPay(false)}/>}</>
}
function TransportPayment({target:t,close}:{target:Target;close:()=>void}){
 const client=useQueryClient();const [request]=useState(()=>crypto.randomUUID()),[value,setValue]=useState(t.remaining),[method,setMethod]=useState('CASH'),[date,setDate]=useState(today()),[reference,setReference]=useState(''),[bank,setBank]=useState(''),[notes,setNotes]=useState('')
 const methods=useQuery({queryKey:['supplier-payment-methods'],queryFn:()=>requestJSON<{code:string;name:string}[]>('/supplier-payment-methods')})
 const save=useMutation({mutationFn:()=>requestJSON('/transport-payments',{method:'POST',body:JSON.stringify({request_id:request,target_id:t.id,kind:t.kind,amount:value,method_code:method,paid_at:`${date}T23:59:59+06:30`,reference_number:reference,bank_account:bank,notes})}),onSuccess:async()=>{await client.invalidateQueries();close()}})
 const uncertain=save.error instanceof ApiError&&(save.error.status===0||save.error.status>=500),locked=save.isPending||uncertain
 return <Modal open onOpenChange={v=>{if(!v&&!locked)close()}} title="Record transportation payment" busy={locked}><form className="space-y-4" onSubmit={e=>{e.preventDefault();if(!save.isPending)save.mutate()}}><p>{t.payee} · {t.reference}</p><p>Remaining: {amount(t.remaining)} {t.currency_code}</p><fieldset disabled={locked} className="space-y-3">{[['Payment amount',value,setValue],['Payment date',date,setDate],['Reference number',reference,setReference],['Bank account',bank,setBank],['Notes',notes,setNotes]].map(([label,v,set])=><FormField key={label as string} label={label as string} required={label==='Payment amount'||label==='Payment date'}>{p=><input {...p} className="field" type={label==='Payment date'?'date':'text'} value={v as string} onChange={e=>(set as (v:string)=>void)(e.target.value)}/>}</FormField>)}<Select aria-label="Transportation payment method" value={method} onValueChange={setMethod}>{methods.data?.map(m=><SelectItem key={m.code} value={m.code}>{m.name}</SelectItem>)}</Select></fieldset>{(save.error||methods.error)&&<p role="alert">{save.error?.message||methods.error?.message}</p>}<Button disabled={save.isPending||!methods.data}>{uncertain?'Retry same payment':'Confirm payment'}</Button></form></Modal>
}
