import { useState } from 'react'
import { Select, SelectItem } from '@/components/ui/select'
import { FormField } from './form-field'
export type Fulfillment = { mode: 'DELIVERY' | 'COLLECTION'; person_name?: string; vehicle_number?: string }
export function FulfillmentFields({value,onChange,inbound=false}:{value:Fulfillment;onChange:(v:Fulfillment)=>void;inbound?:boolean}) {
 const [details,setDetails]=useState(!!(value.person_name||value.vehicle_number))
 return <div className="space-y-3"><FormField label={inbound?'Warehouse arrival method':'Customer collection / delivery'}>{p=><Select {...p} value={value.mode} onValueChange={mode=>onChange({...value,mode:mode as Fulfillment['mode']})}><SelectItem value="DELIVERY">{inbound?'Cargo terminal delivers to warehouse':'Delivery by us'}</SelectItem><SelectItem value="COLLECTION">{inbound?'We collect from cargo terminal':'Customer collects with own vehicle'}</SelectItem></Select>}</FormField><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={details} onChange={e=>{setDetails(e.target.checked);if(!e.target.checked)onChange({mode:value.mode})}}/>Record person and vehicle details</label>{details&&<div className="grid gap-3 sm:grid-cols-2"><FormField label="Person’s name">{p=><input {...p} className="field" maxLength={200} value={value.person_name||''} onChange={e=>onChange({...value,person_name:e.target.value})}/>}</FormField><FormField label="Vehicle number">{p=><input {...p} className="field" maxLength={100} value={value.vehicle_number||''} onChange={e=>onChange({...value,vehicle_number:e.target.value})}/>}</FormField></div>}</div>
}
export function FulfillmentSummary({value,inbound=false}:{value?:Fulfillment;inbound?:boolean}) {if(!value)return null;return <p className="text-sm">{value.mode==='DELIVERY'?(inbound?'Cargo terminal delivery to warehouse':'Delivery by us'):(inbound?'Collection from cargo terminal':'Customer collection')} {value.person_name&&`· ${value.person_name}`} {value.vehicle_number&&`· ${value.vehicle_number}`}</p>}
