// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authentication.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserPermissions = `-- name: ClearUserPermissions :exec
DELETE FROM app.user_permissions WHERE user_id=$1
`

func (q *Queries) ClearUserPermissions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearUserPermissions, userID)
	return err
}

const consumeLoginAttempt = `-- name: ConsumeLoginAttempt :one
INSERT INTO app.login_throttles(key_hash,attempts) VALUES($1,1)
ON CONFLICT(key_hash) DO UPDATE SET
 attempts=CASE WHEN app.login_throttles.window_started_at<now()-interval '15 minutes' THEN 1 ELSE least(app.login_throttles.attempts+1,10000) END,
 window_started_at=CASE WHEN app.login_throttles.window_started_at<now()-interval '15 minutes' THEN now() ELSE app.login_throttles.window_started_at END
RETURNING attempts
`

func (q *Queries) ConsumeLoginAttempt(ctx context.Context, keyHash []byte) (int32, error) {
	row := q.db.QueryRow(ctx, consumeLoginAttempt, keyHash)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO app.user_sessions(user_id,token_hash,created_at,expires_at) VALUES($1,$2,clock_timestamp(),clock_timestamp()+interval '8 hours') RETURNING id
`

type CreateSessionParams struct {
	UserID    pgtype.UUID
	TokenHash []byte
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO app.users(username,display_name,password_hash,role_code) VALUES($1,$2,$3,$4) RETURNING id
`

type CreateUserParams struct {
	Username     string
	DisplayName  string
	PasswordHash string
	RoleCode     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.RoleCode,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const effectivePermissions = `-- name: EffectivePermissions :many
SELECT p.code FROM app.permissions p JOIN app.users u ON u.id=$1
WHERE u.is_active AND (u.role_code='SUPER_ADMIN' OR EXISTS(SELECT 1 FROM app.user_permissions up WHERE up.user_id=u.id AND up.permission_code=p.code)) ORDER BY p.code
`

func (q *Queries) EffectivePermissions(ctx context.Context, id pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, effectivePermissions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLoginUser = `-- name: FindLoginUser :one
SELECT id,username,display_name,password_hash,role_code,is_active FROM app.users WHERE lower(username)=lower($1)
`

type FindLoginUserRow struct {
	ID           pgtype.UUID
	Username     string
	DisplayName  string
	PasswordHash string
	RoleCode     string
	IsActive     bool
}

func (q *Queries) FindLoginUser(ctx context.Context, lower string) (FindLoginUserRow, error) {
	row := q.db.QueryRow(ctx, findLoginUser, lower)
	var i FindLoginUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.RoleCode,
		&i.IsActive,
	)
	return i, err
}

const findUser = `-- name: FindUser :one
SELECT id,username,display_name,role_code,is_active FROM app.users WHERE id=$1 FOR UPDATE
`

type FindUserRow struct {
	ID          pgtype.UUID
	Username    string
	DisplayName string
	RoleCode    string
	IsActive    bool
}

func (q *Queries) FindUser(ctx context.Context, id pgtype.UUID) (FindUserRow, error) {
	row := q.db.QueryRow(ctx, findUser, id)
	var i FindUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.RoleCode,
		&i.IsActive,
	)
	return i, err
}

const grantPermission = `-- name: GrantPermission :exec
INSERT INTO app.user_permissions(user_id,permission_code,granted_by) VALUES($1,$2,$3)
`

type GrantPermissionParams struct {
	UserID         pgtype.UUID
	PermissionCode string
	GrantedBy      pgtype.UUID
}

func (q *Queries) GrantPermission(ctx context.Context, arg GrantPermissionParams) error {
	_, err := q.db.Exec(ctx, grantPermission, arg.UserID, arg.PermissionCode, arg.GrantedBy)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id,username,display_name,role_code,is_active FROM app.users ORDER BY lower(username)
`

type ListUsersRow struct {
	ID          pgtype.UUID
	Username    string
	DisplayName string
	RoleCode    string
	IsActive    bool
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.RoleCode,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLoginUser = `-- name: LockLoginUser :one
SELECT id,password_hash,is_active FROM app.users WHERE id=$1 FOR UPDATE
`

type LockLoginUserRow struct {
	ID           pgtype.UUID
	PasswordHash string
	IsActive     bool
}

func (q *Queries) LockLoginUser(ctx context.Context, id pgtype.UUID) (LockLoginUserRow, error) {
	row := q.db.QueryRow(ctx, lockLoginUser, id)
	var i LockLoginUserRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.IsActive)
	return i, err
}

const markLogin = `-- name: MarkLogin :exec
UPDATE app.users SET last_login_at=clock_timestamp() WHERE id=$1
`

func (q *Queries) MarkLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markLogin, id)
	return err
}

const pruneLoginAttempts = `-- name: PruneLoginAttempts :exec
DELETE FROM app.login_throttles WHERE window_started_at<now()-interval '1 day'
`

func (q *Queries) PruneLoginAttempts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneLoginAttempts)
	return err
}

const recordAuthAudit = `-- name: RecordAuthAudit :exec
INSERT INTO app.audit_logs(actor_id,action,entity_type,entity_id,reason) VALUES($1,$2,'users',$3,$4)
`

type RecordAuthAuditParams struct {
	ActorID  pgtype.UUID
	Action   string
	EntityID pgtype.UUID
	Reason   pgtype.Text
}

func (q *Queries) RecordAuthAudit(ctx context.Context, arg RecordAuthAuditParams) error {
	_, err := q.db.Exec(ctx, recordAuthAudit,
		arg.ActorID,
		arg.Action,
		arg.EntityID,
		arg.Reason,
	)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE app.user_sessions SET revoked_at=clock_timestamp() WHERE token_hash=$1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}
