// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateSession = `-- name: AuthenticateSession :one
SELECT u.id, u.role_code, u.username, u.display_name
FROM app.user_sessions s JOIN app.users u ON u.id=s.user_id
WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now()
  AND s.created_at>=u.password_changed_at AND u.is_active
`

type AuthenticateSessionRow struct {
	ID          pgtype.UUID
	RoleCode    string
	Username    string
	DisplayName string
}

func (q *Queries) AuthenticateSession(ctx context.Context, tokenHash []byte) (AuthenticateSessionRow, error) {
	row := q.db.QueryRow(ctx, authenticateSession, tokenHash)
	var i AuthenticateSessionRow
	err := row.Scan(
		&i.ID,
		&i.RoleCode,
		&i.Username,
		&i.DisplayName,
	)
	return i, err
}

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS (
 SELECT 1 FROM app.users u CROSS JOIN app.permissions p
 WHERE u.id=$1 AND p.code=$2 AND u.is_active
 AND (u.role_code='SUPER_ADMIN' OR EXISTS (
   SELECT 1 FROM app.user_permissions up WHERE up.user_id=u.id AND up.permission_code=p.code
 ))
)::boolean
`

type HasPermissionParams struct {
	ID   pgtype.UUID
	Code string
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermission, arg.ID, arg.Code)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT code,description,is_sensitive FROM app.permissions ORDER BY code
`

type ListPermissionsRow struct {
	Code        string
	Description string
	IsSensitive bool
}

func (q *Queries) ListPermissions(ctx context.Context) ([]ListPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsRow
	for rows.Next() {
		var i ListPermissionsRow
		if err := rows.Scan(&i.Code, &i.Description, &i.IsSensitive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
