// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batches.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBatches = `-- name: ListBatches :one
WITH filtered AS (
 SELECT b.id, b.product_id, b.receiving_item_id, b.batch_number, b.received_at, b.manufactured_on, b.expires_on, b.purchase_cost_mmk, b.transport_cost_mmk, b.other_cost_mmk, b.sellable_quantity, b.total_cost_mmk, b.actual_unit_cost_mmk, b.finalized_at, b.created_at, b.updated_at,p.name AS product_name,p.sku,p.base_unit_code,r.received_quantity,r.damaged_quantity AS received_damaged_quantity,r.missing_quantity,
 app.expiry_status(b.expires_on,app.business_date()) AS expiry_status,
 coalesce((SELECT sum(i.available_quantity) FROM app.inventory i WHERE i.batch_id=b.id),0) AS available_quantity
 FROM app.batches b JOIN app.products p ON p.id=b.product_id JOIN app.goods_receiving_items r ON r.id=b.receiving_item_id
 WHERE ($2::text='' OR strpos(lower(p.name||' '||p.sku||' '||b.batch_number),lower($2))>0)
 AND ($3::text='' OR app.expiry_status(b.expires_on,app.business_date())=$3)
 AND ($4::uuid IS NULL OR b.id=$4)
), page AS (SELECT id, product_id, receiving_item_id, batch_number, received_at, manufactured_on, expires_on, purchase_cost_mmk, transport_cost_mmk, other_cost_mmk, sellable_quantity, total_cost_mmk, actual_unit_cost_mmk, finalized_at, created_at, updated_at, product_name, sku, base_unit_code, received_quantity, received_damaged_quantity, missing_quantity, expiry_status, available_quantity FROM filtered ORDER BY received_at,id LIMIT $6::int OFFSET $5::int)
SELECT jsonb_build_object('business_date',app.business_date(),'total',(SELECT count(*) FROM filtered),'batches',coalesce((SELECT jsonb_agg(
 jsonb_build_object('id',id,'product_name',product_name,'sku',sku,'base_unit',base_unit_code,'batch_number',batch_number,'received_at',received_at,'manufactured_on',manufactured_on,'expires_on',expires_on,'expiry_status',expiry_status,'received_quantity',received_quantity::text,'received_damaged_quantity',received_damaged_quantity::text,'missing_quantity',missing_quantity::text,'initial_sellable_quantity',sellable_quantity::text,'available_quantity',available_quantity::text,'finalized',finalized_at IS NOT NULL)
 || CASE WHEN $1::boolean THEN jsonb_build_object('purchase_cost_mmk',purchase_cost_mmk::text,'transport_cost_mmk',transport_cost_mmk::text,'other_cost_mmk',other_cost_mmk::text,'total_cost_mmk',total_cost_mmk::text,'unit_cost_mmk',actual_unit_cost_mmk::text) ELSE '{}'::jsonb END ORDER BY received_at,id) FROM page),'[]'::jsonb))::jsonb
`

type ListBatchesParams struct {
	Costs      bool
	Search     string
	Expiry     string
	BatchID    pgtype.UUID
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ListBatches(ctx context.Context, arg ListBatchesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, listBatches,
		arg.Costs,
		arg.Search,
		arg.Expiry,
		arg.BatchID,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
