// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO app.brands(name) VALUES($1) RETURNING id,name,is_active
`

type CreateBrandRow struct {
	ID       pgtype.UUID
	Name     string
	IsActive bool
}

func (q *Queries) CreateBrand(ctx context.Context, name string) (CreateBrandRow, error) {
	row := q.db.QueryRow(ctx, createBrand, name)
	var i CreateBrandRow
	err := row.Scan(&i.ID, &i.Name, &i.IsActive)
	return i, err
}

const createCatalogUnit = `-- name: CreateCatalogUnit :one
INSERT INTO app.units(code,name) VALUES($1,$2) RETURNING code,name
`

type CreateCatalogUnitParams struct {
	Code string
	Name string
}

type CreateCatalogUnitRow struct {
	Code string
	Name string
}

func (q *Queries) CreateCatalogUnit(ctx context.Context, arg CreateCatalogUnitParams) (CreateCatalogUnitRow, error) {
	row := q.db.QueryRow(ctx, createCatalogUnit, arg.Code, arg.Name)
	var i CreateCatalogUnitRow
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO app.categories(name) VALUES($1) RETURNING id,name,is_active
`

type CreateCategoryRow struct {
	ID       pgtype.UUID
	Name     string
	IsActive bool
}

func (q *Queries) CreateCategory(ctx context.Context, name string) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory, name)
	var i CreateCategoryRow
	err := row.Scan(&i.ID, &i.Name, &i.IsActive)
	return i, err
}

const lockBrand = `-- name: LockBrand :one
SELECT id,name,is_active FROM app.brands WHERE id=$1 FOR UPDATE
`

type LockBrandRow struct {
	ID       pgtype.UUID
	Name     string
	IsActive bool
}

func (q *Queries) LockBrand(ctx context.Context, id pgtype.UUID) (LockBrandRow, error) {
	row := q.db.QueryRow(ctx, lockBrand, id)
	var i LockBrandRow
	err := row.Scan(&i.ID, &i.Name, &i.IsActive)
	return i, err
}

const lockCategory = `-- name: LockCategory :one
SELECT id,name,is_active FROM app.categories WHERE id=$1 FOR UPDATE
`

type LockCategoryRow struct {
	ID       pgtype.UUID
	Name     string
	IsActive bool
}

func (q *Queries) LockCategory(ctx context.Context, id pgtype.UUID) (LockCategoryRow, error) {
	row := q.db.QueryRow(ctx, lockCategory, id)
	var i LockCategoryRow
	err := row.Scan(&i.ID, &i.Name, &i.IsActive)
	return i, err
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE app.brands SET name=$2,is_active=$3 WHERE id=$1 RETURNING id,name,is_active
`

type UpdateBrandParams struct {
	ID       pgtype.UUID
	Name     string
	IsActive bool
}

type UpdateBrandRow struct {
	ID       pgtype.UUID
	Name     string
	IsActive bool
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (UpdateBrandRow, error) {
	row := q.db.QueryRow(ctx, updateBrand, arg.ID, arg.Name, arg.IsActive)
	var i UpdateBrandRow
	err := row.Scan(&i.ID, &i.Name, &i.IsActive)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE app.categories SET name=$2,is_active=$3 WHERE id=$1 RETURNING id,name,is_active
`

type UpdateCategoryParams struct {
	ID       pgtype.UUID
	Name     string
	IsActive bool
}

type UpdateCategoryRow struct {
	ID       pgtype.UUID
	Name     string
	IsActive bool
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.IsActive)
	var i UpdateCategoryRow
	err := row.Scan(&i.ID, &i.Name, &i.IsActive)
	return i, err
}
