// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: central_payments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const customerPaymentList = `-- name: CustomerPaymentList :one
WITH filtered AS(SELECT s.id,s.customer_id,c.name AS customer_name,s.invoice_number,d.total_mmk::text AS total_mmk,d.amount_paid_mmk::text AS amount_paid_mmk,d.outstanding_mmk::text AS outstanding_mmk,d.payment_status FROM app.sales s JOIN app.customer_debts d ON d.sale_id=s.id JOIN app.customers c ON c.id=s.customer_id WHERE ($1::text='' OR strpos(lower(s.invoice_number||' '||c.name),lower($1))>0) AND ($2::text='' OR d.payment_status=$2)),page AS(SELECT id, customer_id, customer_name, invoice_number, total_mmk, amount_paid_mmk, outstanding_mmk, payment_status FROM filtered ORDER BY invoice_number DESC,id LIMIT $4::int OFFSET $3::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'invoices',coalesce((SELECT jsonb_agg(to_jsonb(page)) FROM page),'[]'))::jsonb
`

type CustomerPaymentListParams struct {
	Search     string
	Status     string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) CustomerPaymentList(ctx context.Context, arg CustomerPaymentListParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, customerPaymentList,
		arg.Search,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const transportPaymentHistory = `-- name: TransportPaymentHistory :one
SELECT coalesce(jsonb_agg(jsonb_build_object('id',p.id,'payment_number',p.payment_number,'amount',p.amount_original::text,'currency_code',p.currency_code,'method',coalesce(p.method_name_snapshot,p.method),'paid_at',p.paid_at,'reference_number',p.reference_number,'bank_account',p.bank_account,'notes',p.notes,'created_by',u.display_name) ORDER BY p.paid_at,p.id),'[]')::jsonb FROM app.payments p JOIN app.payment_allocations a ON a.payment_id=p.id JOIN app.users u ON u.id=p.recorded_by WHERE a.transportation_stage_id=$1::uuid OR a.shipment_expense_id=$1::uuid
`

func (q *Queries) TransportPaymentHistory(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, transportPaymentHistory, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const transportPaymentList = `-- name: TransportPaymentList :one
WITH filtered AS(SELECT id,kind,shipment_id,shipment_number,shipment_status,reference,payee,currency_code,total::text,paid::text,(total-paid)::text AS remaining FROM app.transport_balances WHERE ($1::text='' OR strpos(lower(shipment_number||' '||reference||' '||payee),lower($1))>0) AND ($2::text='' OR CASE WHEN paid>=total THEN 'PAID' WHEN paid>0 THEN 'PARTIALLY_PAID' ELSE 'UNPAID' END=$2)), page AS(SELECT id, kind, shipment_id, shipment_number, shipment_status, reference, payee, currency_code, total, paid, remaining FROM filtered ORDER BY shipment_number DESC,id LIMIT $4::int OFFSET $3::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'records',coalesce((SELECT jsonb_agg(to_jsonb(page)) FROM page),'[]'))::jsonb
`

type TransportPaymentListParams struct {
	Search     string
	Status     string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) TransportPaymentList(ctx context.Context, arg TransportPaymentListParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, transportPaymentList,
		arg.Search,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const transportPaymentPost = `-- name: TransportPaymentPost :one
SELECT app.transport_payment($1::jsonb,$2::uuid)::uuid
`

type TransportPaymentPostParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) TransportPaymentPost(ctx context.Context, arg TransportPaymentPostParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, transportPaymentPost, arg.Data, arg.Actor)
	var column_1 pgtype.UUID
	err := row.Scan(&column_1)
	return column_1, err
}
