// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cost_journeys.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const costJourneys = `-- name: CostJourneys :one
WITH matching AS (
 SELECT si.id, si.shipment_id, si.purchase_item_id, si.product_id, si.expected_quantity, si.weight_kg, si.carton_quantity, si.allocated_transport_mmk, si.allocated_expense_mmk, si.created_at, si.updated_at, si.purchase_cost_mmk, si.costing_sellable_quantity, si.landed_cost_mmk, si.actual_unit_cost_mmk,coalesce(pi.product_name_snapshot,pr.name) AS product_name,s.shipment_number,s.costs_finalized_at,pi.total_original,pi.base_quantity,p.currency_code,p.mmk_per_unit,p.purchase_number
 FROM app.shipment_items si JOIN app.shipments s ON s.id=si.shipment_id JOIN app.shipment_costings sc ON sc.shipment_id=s.id JOIN app.purchase_items pi ON pi.id=si.purchase_item_id JOIN app.purchases p ON p.id=pi.purchase_id JOIN app.products pr ON pr.id=si.product_id
 WHERE ($1::uuid IS NULL OR si.product_id=$1) AND ($2::uuid IS NULL OR pi.purchase_id=$2)
), page AS (SELECT id, shipment_id, purchase_item_id, product_id, expected_quantity, weight_kg, carton_quantity, allocated_transport_mmk, allocated_expense_mmk, created_at, updated_at, purchase_cost_mmk, costing_sellable_quantity, landed_cost_mmk, actual_unit_cost_mmk, product_name, shipment_number, costs_finalized_at, total_original, base_quantity, currency_code, mmk_per_unit, purchase_number FROM matching ORDER BY costs_finalized_at DESC,id LIMIT $4::int OFFSET $3::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM matching),'journeys',coalesce((SELECT jsonb_agg(jsonb_build_object('id',id,'product_name',product_name,'shipment_id',shipment_id,'shipment_number',shipment_number,'purchase_mmk',purchase_cost_mmk::text,'transport_mmk',allocated_transport_mmk::text,'expense_mmk',allocated_expense_mmk::text,'landed_mmk',landed_cost_mmk::text,'sellable_quantity',costing_sellable_quantity::text,'unit_cost_mmk',actual_unit_cost_mmk::text,'sources',jsonb_build_array(jsonb_build_object('amount',total_original::text,'currency',currency_code,'rate',mmk_per_unit::text,'reference',purchase_number,'quantity',base_quantity::text,'allocated_quantity',expected_quantity::text))) ORDER BY costs_finalized_at DESC,id) FROM page),'[]'::jsonb))::jsonb
`

type CostJourneysParams struct {
	ProductID  pgtype.UUID
	PurchaseID pgtype.UUID
	PageOffset int32
	PageSize   int32
}

func (q *Queries) CostJourneys(ctx context.Context, arg CostJourneysParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, costJourneys,
		arg.ProductID,
		arg.PurchaseID,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const shipmentJourneySources = `-- name: ShipmentJourneySources :one
SELECT coalesce(jsonb_agg(jsonb_build_object('amount',pi.total_original::text,'currency',p.currency_code,'rate',p.mmk_per_unit::text,'reference',p.purchase_number,'quantity',pi.base_quantity::text,'allocated_quantity',si.expected_quantity::text) ORDER BY p.purchase_number,pi.line_number),'[]'::jsonb)::jsonb FROM app.shipment_items si JOIN app.purchase_items pi ON pi.id=si.purchase_item_id JOIN app.purchases p ON p.id=pi.purchase_id WHERE si.shipment_id=$1
`

func (q *Queries) ShipmentJourneySources(ctx context.Context, shipmentID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, shipmentJourneySources, shipmentID)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
