// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const customerCatalog = `-- name: CustomerCatalog :one
SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb)::jsonb FROM (SELECT p.id,p.name,p.sku,(SELECT jsonb_agg(u.unit_code ORDER BY u.unit_code) FROM app.product_units u WHERE u.product_id=p.id) AS units FROM app.products p WHERE p.is_active AND p.archived_at IS NULL AND ($1::text='' OR strpos(lower(p.name||' '||p.sku),lower($1))>0) ORDER BY p.name,p.id LIMIT 50) x
`

func (q *Queries) CustomerCatalog(ctx context.Context, search string) ([]byte, error) {
	row := q.db.QueryRow(ctx, customerCatalog, search)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const customerDetail = `-- name: CustomerDetail :one
SELECT (to_jsonb(c)||jsonb_build_object('version',c.version::text,'credit_limit_mmk',c.credit_limit_mmk::text,
 'outstanding_mmk',coalesce((SELECT sum(greatest(outstanding_mmk,0)) FROM app.customer_debts d WHERE d.customer_id=c.id),0)::text,
 'credit_mmk',coalesce((SELECT sum(greatest(-outstanding_mmk,0)) FROM app.customer_debts d WHERE d.customer_id=c.id),0)::text))::jsonb
FROM app.customers c WHERE id=$1::uuid
`

func (q *Queries) CustomerDetail(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, customerDetail, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const customerHistory = `-- name: CustomerHistory :one
WITH filtered AS (SELECT s.id,s.invoice_number,s.sold_at,d.due_date,d.total_mmk::text AS total_mmk,d.amount_paid_mmk::text AS amount_paid_mmk,d.return_credit_mmk::text AS return_credit_mmk,d.refunded_mmk::text AS refunded_mmk,d.outstanding_mmk::text AS outstanding_mmk,d.payment_status
 FROM app.sales s JOIN app.customer_debts d ON d.sale_id=s.id WHERE s.customer_id=$1::uuid), page AS (SELECT id, invoice_number, sold_at, due_date, total_mmk, amount_paid_mmk, return_credit_mmk, refunded_mmk, outstanding_mmk, payment_status FROM filtered ORDER BY sold_at DESC,id LIMIT $3::int OFFSET $2::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'invoices',coalesce((SELECT jsonb_agg(to_jsonb(page) ORDER BY sold_at DESC,id) FROM page),'[]'))::jsonb
`

type CustomerHistoryParams struct {
	ID         pgtype.UUID
	PageOffset int32
	PageSize   int32
}

func (q *Queries) CustomerHistory(ctx context.Context, arg CustomerHistoryParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, customerHistory, arg.ID, arg.PageOffset, arg.PageSize)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const customerPayment = `-- name: CustomerPayment :one
SELECT app.customer_payment($1::jsonb,$2::uuid)::uuid
`

type CustomerPaymentParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) CustomerPayment(ctx context.Context, arg CustomerPaymentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, customerPayment, arg.Data, arg.Actor)
	var column_1 pgtype.UUID
	err := row.Scan(&column_1)
	return column_1, err
}

const customerPayments = `-- name: CustomerPayments :one
SELECT coalesce(jsonb_agg(to_jsonb(x) ORDER BY paid_at DESC,id),'[]'::jsonb)::jsonb FROM (SELECT p.id,p.payment_number,p.paid_at,p.direction,p.method,p.amount_mmk::text,p.reference_number,s.invoice_number FROM app.payments p LEFT JOIN app.payment_allocations a ON a.payment_id=p.id LEFT JOIN app.sales s ON s.id=a.sale_id WHERE p.customer_id=$1::uuid AND p.status='POSTED' ORDER BY p.paid_at DESC,p.id LIMIT 200) x
`

func (q *Queries) CustomerPayments(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, customerPayments, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const customerPrice = `-- name: CustomerPrice :exec
SELECT app.customer_price($1::jsonb,$2::uuid)
`

type CustomerPriceParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) CustomerPrice(ctx context.Context, arg CustomerPriceParams) error {
	_, err := q.db.Exec(ctx, customerPrice, arg.Data, arg.Actor)
	return err
}

const customerPrices = `-- name: CustomerPrices :one
SELECT coalesce(jsonb_agg(jsonb_build_object('product_id',p.product_id,'product_name',pr.name,'sku',pr.sku,'unit_code',p.unit_code,'price_mmk',p.price_mmk::text) ORDER BY pr.name,p.unit_code),'[]'::jsonb)::jsonb FROM app.customer_prices p JOIN app.products pr ON pr.id=p.product_id WHERE p.customer_id=$1::uuid
`

func (q *Queries) CustomerPrices(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, customerPrices, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const customerSave = `-- name: CustomerSave :one
SELECT app.customer_save($1::jsonb,$2::uuid)::uuid
`

type CustomerSaveParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) CustomerSave(ctx context.Context, arg CustomerSaveParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, customerSave, arg.Data, arg.Actor)
	var column_1 pgtype.UUID
	err := row.Scan(&column_1)
	return column_1, err
}

const customersList = `-- name: CustomersList :one
WITH filtered AS (SELECT c.id,c.code,c.name,c.phone,c.customer_type,c.is_active,c.credit_limit_mmk::text AS credit_limit_mmk,
 coalesce((SELECT sum(greatest(outstanding_mmk,0)) FROM app.customer_debts d WHERE d.customer_id=c.id),0)::text AS outstanding_mmk
 FROM app.customers c WHERE ($1::text='' OR strpos(lower(c.code||' '||c.name||' '||coalesce(c.phone,'')),lower($1))>0)
 AND ($2::text='' OR c.customer_type=$2)
 AND ($3::text='' OR c.is_active=($3='ACTIVE'))), page AS (SELECT id, code, name, phone, customer_type, is_active, credit_limit_mmk, outstanding_mmk FROM filtered ORDER BY name,id LIMIT $5::int OFFSET $4::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'customers',coalesce((SELECT jsonb_agg(to_jsonb(page) ORDER BY name,id) FROM page),'[]'))::jsonb
`

type CustomersListParams struct {
	Search     string
	Kind       string
	Status     string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) CustomersList(ctx context.Context, arg CustomersListParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, customersList,
		arg.Search,
		arg.Kind,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
