// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expenseCategories = `-- name: ExpenseCategories :one
SELECT coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) ORDER BY name),'[]'::jsonb)::jsonb FROM app.expense_categories
`

func (q *Queries) ExpenseCategories(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, expenseCategories)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const expensePost = `-- name: ExpensePost :one
SELECT app.expense_post($1::jsonb,$2::uuid)::uuid
`

type ExpensePostParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) ExpensePost(ctx context.Context, arg ExpensePostParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, expensePost, arg.Data, arg.Actor)
	var column_1 pgtype.UUID
	err := row.Scan(&column_1)
	return column_1, err
}

const expenseReverse = `-- name: ExpenseReverse :one
SELECT app.expense_reverse($1::jsonb,$2::uuid)::uuid
`

type ExpenseReverseParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) ExpenseReverse(ctx context.Context, arg ExpenseReverseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, expenseReverse, arg.Data, arg.Actor)
	var column_1 pgtype.UUID
	err := row.Scan(&column_1)
	return column_1, err
}

const expensesList = `-- name: ExpensesList :one
WITH filtered AS(SELECT e.id,c.name AS category,e.description,e.incurred_at,e.amount_mmk::text AS amount_mmk,CASE WHEN EXISTS(SELECT 1 FROM app.expense_reversals r WHERE r.expense_id=e.id) THEN 'REVERSED' ELSE e.status END AS status,e.notes,u.display_name AS recorded_by,
 coalesce((SELECT sum(a.applied_mmk) FROM app.payment_allocations a JOIN app.payments p ON p.id=a.payment_id WHERE a.expense_id=e.id AND p.status='POSTED' AND NOT EXISTS(SELECT 1 FROM app.expense_reversal_payments rp WHERE rp.original_payment_id=p.id)),0)::text AS paid_mmk
 FROM app.expenses e JOIN app.expense_categories c ON c.id=e.category_id JOIN app.users u ON u.id=e.recorded_by
 WHERE ($1::text='' OR strpos(lower(e.description||' '||c.name),lower($1))>0)
 AND e.incurred_at>=coalesce(nullif($2::text,'')::date,date_trunc('month',app.business_date())::date)::timestamp AT TIME ZONE 'Asia/Yangon'
 AND e.incurred_at<(coalesce(nullif($3::text,'')::date,app.business_date())+1)::timestamp AT TIME ZONE 'Asia/Yangon'),page AS(SELECT id, category, description, incurred_at, amount_mmk, status, notes, recorded_by, paid_mmk FROM filtered ORDER BY incurred_at DESC,id LIMIT $5::int OFFSET $4::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'expenses',coalesce((SELECT jsonb_agg(to_jsonb(page) ORDER BY incurred_at DESC,id) FROM page),'[]'))::jsonb
`

type ExpensesListParams struct {
	Search     string
	StartOn    string
	EndOn      string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ExpensesList(ctx context.Context, arg ExpensesListParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, expensesList,
		arg.Search,
		arg.StartOn,
		arg.EndOn,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const profitReport = `-- name: ProfitReport :one
WITH dates AS(SELECT coalesce(nullif($1::text,'')::date,date_trunc('month',app.business_date())::date) AS start_on,coalesce(nullif($2::text,'')::date,app.business_date()) AS end_on)
SELECT (app.profit_summary(start_on,end_on)||jsonb_build_object('expense_categories',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.name) FROM(SELECT c.name,round(sum(e.amount_mmk),4)::text AS amount_mmk FROM app.profit_expense_events e JOIN app.expense_categories c ON c.id=e.category_id WHERE e.occurred_at>=dates.start_on::timestamp AT TIME ZONE 'Asia/Yangon' AND e.occurred_at<(dates.end_on+1)::timestamp AT TIME ZONE 'Asia/Yangon' GROUP BY c.name)x),'[]')))::jsonb FROM dates
`

type ProfitReportParams struct {
	StartOn string
	EndOn   string
}

func (q *Queries) ProfitReport(ctx context.Context, arg ProfitReportParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, profitReport, arg.StartOn, arg.EndOn)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
