// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: landed_cost.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finalizeShipmentCost = `-- name: FinalizeShipmentCost :exec
UPDATE app.shipments SET costs_finalized_at=now(),costs_finalized_by=$2,allocation_method=$3,version=version+1 WHERE id=$1
`

type FinalizeShipmentCostParams struct {
	ID               pgtype.UUID
	CostsFinalizedBy pgtype.UUID
	AllocationMethod string
}

func (q *Queries) FinalizeShipmentCost(ctx context.Context, arg FinalizeShipmentCostParams) error {
	_, err := q.db.Exec(ctx, finalizeShipmentCost, arg.ID, arg.CostsFinalizedBy, arg.AllocationMethod)
	return err
}

const getFinalizedCost = `-- name: GetFinalizedCost :one
SELECT document FROM app.shipment_costings WHERE shipment_id=$1
`

func (q *Queries) GetFinalizedCost(ctx context.Context, shipmentID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getFinalizedCost, shipmentID)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const landedCostSources = `-- name: LandedCostSources :one
SELECT jsonb_build_object('version',s.version::text,'status',s.status,'finalized',s.costs_finalized_at IS NOT NULL,
 'transport_mmk',(SELECT coalesce(sum(total_mmk),0)::text FROM app.transportation_stages WHERE shipment_id=s.id),
 'expense_mmk',(SELECT coalesce(sum(amount_mmk),0)::text FROM app.shipment_expenses WHERE shipment_id=s.id AND voided_at IS NULL),
 'items',coalesce((SELECT jsonb_agg(jsonb_build_object('id',si.id,'product_name',coalesce(pi.product_name_snapshot,pr.name),'sku',coalesce(pi.sku_snapshot,pr.sku),'base_unit_code',pr.base_unit_code,'expected_quantity',si.expected_quantity::text,'purchase_quantity',pi.base_quantity::text,'purchase_total_mmk',lc.total_mmk::text,
 'used_quantity',coalesce((SELECT sum(other.expected_quantity) FROM app.shipment_items other JOIN app.shipment_costings sc ON sc.shipment_id=other.shipment_id WHERE other.purchase_item_id=si.purchase_item_id AND other.id<>si.id),0)::text,
 'used_purchase_mmk',coalesce((SELECT sum(other.purchase_cost_mmk) FROM app.shipment_items other JOIN app.shipment_costings sc ON sc.shipment_id=other.shipment_id WHERE other.purchase_item_id=si.purchase_item_id AND other.id<>si.id),0)::text,
 'purchase_status',p.status) ORDER BY si.id) FROM app.shipment_items si JOIN app.purchase_items pi ON pi.id=si.purchase_item_id JOIN app.purchases p ON p.id=pi.purchase_id JOIN app.purchase_line_costs lc ON lc.id=pi.id JOIN app.products pr ON pr.id=si.product_id WHERE si.shipment_id=s.id),'[]'::jsonb))::jsonb FROM app.shipments s WHERE s.id=$1
`

func (q *Queries) LandedCostSources(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, landedCostSources, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const lockCostPurchaseItems = `-- name: LockCostPurchaseItems :many
SELECT pi.id FROM app.purchase_items pi JOIN app.shipment_items si ON si.purchase_item_id=pi.id WHERE si.shipment_id=$1 ORDER BY pi.id FOR UPDATE OF pi
`

func (q *Queries) LockCostPurchaseItems(ctx context.Context, shipmentID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockCostPurchaseItems, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCostDocument = `-- name: SaveCostDocument :exec
INSERT INTO app.shipment_costings(shipment_id,document,finalized_by) VALUES($1,$2,$3)
`

type SaveCostDocumentParams struct {
	ShipmentID  pgtype.UUID
	Document    []byte
	FinalizedBy pgtype.UUID
}

func (q *Queries) SaveCostDocument(ctx context.Context, arg SaveCostDocumentParams) error {
	_, err := q.db.Exec(ctx, saveCostDocument, arg.ShipmentID, arg.Document, arg.FinalizedBy)
	return err
}

const saveCostItem = `-- name: SaveCostItem :exec
UPDATE app.shipment_items SET purchase_cost_mmk=(d->>'purchase_mmk')::numeric,costing_sellable_quantity=(d->>'sellable_quantity')::numeric,allocated_transport_mmk=(d->>'transport_mmk')::numeric,allocated_expense_mmk=(d->>'expense_mmk')::numeric,weight_kg=nullif(d->>'weight_kg','')::numeric,carton_quantity=nullif(d->>'carton_quantity','')::numeric FROM (SELECT $2::jsonb d) x WHERE id=(d->>'id')::uuid AND shipment_id=$1
`

type SaveCostItemParams struct {
	ShipmentID pgtype.UUID
	Data       []byte
}

func (q *Queries) SaveCostItem(ctx context.Context, arg SaveCostItemParams) error {
	_, err := q.db.Exec(ctx, saveCostItem, arg.ShipmentID, arg.Data)
	return err
}
