// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppApproval struct {
	ID                pgtype.UUID
	PermissionCode    string
	SaleID            pgtype.UUID
	PurchaseID        pgtype.UUID
	SalesReturnID     pgtype.UUID
	PurchaseReturnID  pgtype.UUID
	StockAdjustmentID pgtype.UUID
	ShipmentID        pgtype.UUID
	PaymentID         pgtype.UUID
	StockTakeID       pgtype.UUID
	RequestedBy       pgtype.UUID
	RequestedAt       pgtype.Timestamptz
	Reason            string
	RequestPayload    []byte
	RequestHash       []byte
	Status            string
	DecidedBy         pgtype.UUID
	DecidedAt         pgtype.Timestamptz
	DecisionNote      pgtype.Text
	ConsumedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AppAttachment struct {
	ID               pgtype.UUID
	StorageKey       string
	OriginalFilename string
	MediaType        string
	SizeBytes        int64
	Sha256           []byte
	UploadedBy       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	ArchivedAt       pgtype.Timestamptz
}

type AppAttachmentLink struct {
	ID                    pgtype.UUID
	AttachmentID          pgtype.UUID
	ProductID             pgtype.UUID
	PurchaseID            pgtype.UUID
	ShipmentID            pgtype.UUID
	TransportationStageID pgtype.UUID
	PaymentID             pgtype.UUID
	ExpenseID             pgtype.UUID
	DamagedProductID      pgtype.UUID
	MissingProductID      pgtype.UUID
	GoodsReceivingID      pgtype.UUID
	SaleID                pgtype.UUID
	SalesReturnID         pgtype.UUID
	PurchaseReturnID      pgtype.UUID
	CreatedAt             pgtype.Timestamptz
}

type AppAuditLog struct {
	ID         pgtype.UUID
	ActorID    pgtype.UUID
	Action     string
	EntityType string
	EntityID   pgtype.UUID
	OldValue   []byte
	NewValue   []byte
	RequestID  pgtype.Text
	Reason     pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type AppBatch struct {
	ID                pgtype.UUID
	ProductID         pgtype.UUID
	ReceivingItemID   pgtype.UUID
	BatchNumber       string
	ReceivedAt        pgtype.Timestamptz
	ManufacturedOn    pgtype.Date
	ExpiresOn         pgtype.Date
	PurchaseCostMmk   pgtype.Numeric
	TransportCostMmk  pgtype.Numeric
	OtherCostMmk      pgtype.Numeric
	SellableQuantity  pgtype.Numeric
	TotalCostMmk      pgtype.Numeric
	ActualUnitCostMmk pgtype.Numeric
	FinalizedAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AppBrand struct {
	ID        pgtype.UUID
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AppCatalogBarcode struct {
	Barcode   string
	ProductID pgtype.UUID
	UnitCode  pgtype.Text
}

type AppCategory struct {
	ID        pgtype.UUID
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AppCurrency struct {
	Code       string
	Name       string
	MinorUnits int16
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type AppCustomer struct {
	ID             pgtype.UUID
	Code           string
	Name           string
	BusinessName   pgtype.Text
	Phone          pgtype.Text
	Address        pgtype.Text
	CustomerType   string
	CreditLimitMmk pgtype.Numeric
	Notes          pgtype.Text
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type AppCustomerDebt struct {
	SaleID          pgtype.UUID
	CustomerID      pgtype.UUID
	DueDate         pgtype.Date
	TotalMmk        pgtype.Numeric
	AmountPaidMmk   pgtype.Numeric
	ReturnCreditMmk pgtype.Numeric
	RefundedMmk     pgtype.Numeric
	OutstandingMmk  pgtype.Numeric
	PaymentStatus   string
}

type AppDamagedProduct struct {
	ID               pgtype.UUID
	ProductID        pgtype.UUID
	BatchID          pgtype.UUID
	ShipmentItemID   pgtype.UUID
	WarehouseID      pgtype.UUID
	Quantity         pgtype.Numeric
	EstimatedLossMmk pgtype.Numeric
	Reason           string
	OccurredAt       pgtype.Timestamptz
	RecordedBy       pgtype.UUID
	Disposition      string
	OriginalPriceMmk pgtype.Numeric
	ReducedPriceMmk  pgtype.Numeric
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type AppExchangeRate struct {
	ID           pgtype.UUID
	CurrencyCode string
	MmkPerUnit   pgtype.Numeric
	EffectiveAt  pgtype.Timestamptz
	Source       string
	RecordedBy   pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type AppExpense struct {
	ID             pgtype.UUID
	CategoryID     pgtype.UUID
	Description    string
	IncurredAt     pgtype.Timestamptz
	CurrencyCode   string
	AmountOriginal pgtype.Numeric
	MmkPerUnit     pgtype.Numeric
	AmountMmk      pgtype.Numeric
	Status         string
	PostedAt       pgtype.Timestamptz
	RecordedBy     pgtype.UUID
	Notes          pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type AppExpenseCategory struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AppGoodsReceiving struct {
	ID             pgtype.UUID
	ReceiptNumber  string
	ShipmentID     pgtype.UUID
	WarehouseID    pgtype.UUID
	ReceivedAt     pgtype.Timestamptz
	ReceivedBy     pgtype.UUID
	Status         string
	PostedAt       pgtype.Timestamptz
	Notes          pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	RequestID      pgtype.UUID
	RequestPayload []byte
}

type AppGoodsReceivingItem struct {
	ID               pgtype.UUID
	GoodsReceivingID pgtype.UUID
	ShipmentID       pgtype.UUID
	ShipmentItemID   pgtype.UUID
	ProductID        pgtype.UUID
	ExpectedQuantity pgtype.Numeric
	ReceivedQuantity pgtype.Numeric
	DamagedQuantity  pgtype.Numeric
	MissingQuantity  pgtype.Numeric
	ExcessQuantity   pgtype.Numeric
	BatchNumber      string
	ManufacturedOn   pgtype.Date
	ExpiresOn        pgtype.Date
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CartonSize       pgtype.Numeric
	ReceivedCartons  pgtype.Numeric
	ReceivedUnits    pgtype.Numeric
}

type AppInventory struct {
	WarehouseID       pgtype.UUID
	BatchID           pgtype.UUID
	SellableQuantity  pgtype.Numeric
	ReservedQuantity  pgtype.Numeric
	DamagedQuantity   pgtype.Numeric
	AvailableQuantity pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Version           int64
}

type AppInventoryMovement struct {
	ID                    pgtype.UUID
	WarehouseID           pgtype.UUID
	BatchID               pgtype.UUID
	MovementType          string
	SellableDelta         pgtype.Numeric
	ReservedDelta         pgtype.Numeric
	DamagedDelta          pgtype.Numeric
	UnitCostMmk           pgtype.Numeric
	ReceivingItemID       pgtype.UUID
	SaleItemBatchID       pgtype.UUID
	SalesReturnItemID     pgtype.UUID
	PurchaseReturnItemID  pgtype.UUID
	StockAdjustmentItemID pgtype.UUID
	StockTransferItemID   pgtype.UUID
	DamagedProductID      pgtype.UUID
	MissingProductID      pgtype.UUID
	ReservationSaleID     pgtype.UUID
	ReversesMovementID    pgtype.UUID
	IdempotencyKey        string
	OccurredAt            pgtype.Timestamptz
	RecordedBy            pgtype.UUID
	Reason                pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

type AppLoginThrottle struct {
	KeyHash         []byte
	Attempts        int32
	WindowStartedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AppMissingProduct struct {
	ID               pgtype.UUID
	ProductID        pgtype.UUID
	BatchID          pgtype.UUID
	ShipmentItemID   pgtype.UUID
	WarehouseID      pgtype.UUID
	Quantity         pgtype.Numeric
	EstimatedLossMmk pgtype.Numeric
	Reason           string
	OccurredAt       pgtype.Timestamptz
	RecordedBy       pgtype.UUID
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type AppPayment struct {
	ID                pgtype.UUID
	PaymentNumber     string
	Direction         string
	Method            string
	CurrencyCode      string
	AmountOriginal    pgtype.Numeric
	MmkPerUnit        pgtype.Numeric
	AmountMmk         pgtype.Numeric
	CustomerID        pgtype.UUID
	SupplierID        pgtype.UUID
	PaidAt            pgtype.Timestamptz
	ReferenceNumber   pgtype.Text
	Notes             pgtype.Text
	Status            string
	PostedAt          pgtype.Timestamptz
	ReversesPaymentID pgtype.UUID
	RecordedBy        pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AppPaymentAllocation struct {
	ID                    pgtype.UUID
	PaymentID             pgtype.UUID
	SaleID                pgtype.UUID
	PurchaseID            pgtype.UUID
	SalesReturnID         pgtype.UUID
	PurchaseReturnID      pgtype.UUID
	ExpenseID             pgtype.UUID
	TransportationStageID pgtype.UUID
	ShipmentExpenseID     pgtype.UUID
	SettlementMmk         pgtype.Numeric
	AppliedMmk            pgtype.Numeric
	AppliedOriginal       pgtype.Numeric
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type AppPermission struct {
	Code        string
	Description string
	IsSensitive bool
	CreatedAt   pgtype.Timestamptz
}

type AppPosEligibleStock struct {
	WarehouseID       pgtype.UUID
	BatchID           pgtype.UUID
	SellableQuantity  pgtype.Numeric
	ReservedQuantity  pgtype.Numeric
	DamagedQuantity   pgtype.Numeric
	AvailableQuantity pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Version           int64
	ProductID         pgtype.UUID
	ReceivedAt        pgtype.Timestamptz
	ExpiresOn         pgtype.Date
	ActualUnitCostMmk pgtype.Numeric
}

type AppProduct struct {
	ID           pgtype.UUID
	Sku          string
	Name         string
	Barcode      pgtype.Text
	CategoryID   pgtype.UUID
	BrandID      pgtype.UUID
	CountryCode  pgtype.Text
	Description  pgtype.Text
	BaseUnitCode string
	MinimumStock pgtype.Numeric
	TracksExpiry bool
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ArchivedAt   pgtype.Timestamptz
	Version      int64
}

type AppProductSupplier struct {
	ProductID   pgtype.UUID
	SupplierID  pgtype.UUID
	SupplierSku pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type AppProductUnit struct {
	ProductID         pgtype.UUID
	UnitCode          string
	UnitsPerPack      pgtype.Numeric
	Barcode           pgtype.Text
	RetailPriceMmk    pgtype.Numeric
	WholesalePriceMmk pgtype.Numeric
	IsDefaultPurchase bool
	IsDefaultSale     bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AppPurchase struct {
	ID                    pgtype.UUID
	PurchaseNumber        string
	SupplierID            pgtype.UUID
	SupplierInvoiceNumber pgtype.Text
	PurchasedAt           pgtype.Timestamptz
	DueDate               pgtype.Date
	CurrencyCode          string
	ExchangeRateID        pgtype.UUID
	MmkPerUnit            pgtype.Numeric
	Status                string
	PostedAt              pgtype.Timestamptz
	CreatedBy             pgtype.UUID
	Notes                 pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RequestID             pgtype.UUID
	RequestHash           pgtype.Text
}

type AppPurchaseAmount struct {
	PurchaseID     pgtype.UUID
	CurrencyCode   string
	MmkPerUnit     pgtype.Numeric
	AmountOriginal pgtype.Numeric
	AmountMmk      pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
}

type AppPurchaseItem struct {
	ID                  pgtype.UUID
	PurchaseID          pgtype.UUID
	LineNumber          int32
	ProductID           pgtype.UUID
	UnitCode            string
	Quantity            pgtype.Numeric
	UnitsPerPack        pgtype.Numeric
	BaseQuantity        pgtype.Numeric
	UnitPriceOriginal   pgtype.Numeric
	DiscountOriginal    pgtype.Numeric
	TaxOriginal         pgtype.Numeric
	TotalOriginal       pgtype.Numeric
	Notes               pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ProductNameSnapshot pgtype.Text
	SkuSnapshot         pgtype.Text
	UnitNameSnapshot    pgtype.Text
}

type AppPurchaseLineCost struct {
	ID           pgtype.UUID
	PurchaseID   pgtype.UUID
	BaseQuantity pgtype.Numeric
	TotalMmk     int32
}

type AppPurchaseReturn struct {
	ID           pgtype.UUID
	ReturnNumber string
	PurchaseID   pgtype.UUID
	ReturnedAt   pgtype.Timestamptz
	Resolution   string
	Reason       string
	Status       string
	PostedAt     pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AppPurchaseReturnItem struct {
	ID               pgtype.UUID
	PurchaseReturnID pgtype.UUID
	PurchaseID       pgtype.UUID
	PurchaseItemID   pgtype.UUID
	ProductID        pgtype.UUID
	BatchID          pgtype.UUID
	Quantity         pgtype.Numeric
	CreditOriginal   pgtype.Numeric
	CreditMmk        pgtype.Numeric
	InventoryCostMmk pgtype.Numeric
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type AppPurchaseTotal struct {
	PurchaseID    pgtype.UUID
	SupplierID    pgtype.UUID
	CurrencyCode  string
	MmkPerUnit    pgtype.Numeric
	TotalOriginal pgtype.Numeric
	TotalMmk      pgtype.Numeric
}

type AppRole struct {
	Code      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type AppSale struct {
	ID            pgtype.UUID
	InvoiceNumber string
	CustomerID    pgtype.UUID
	WarehouseID   pgtype.UUID
	PricingMode   string
	SoldAt        pgtype.Timestamptz
	DueDate       pgtype.Date
	Status        string
	PostedAt      pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	Notes         pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AppSaleItem struct {
	ID           pgtype.UUID
	SaleID       pgtype.UUID
	LineNumber   int32
	ProductID    pgtype.UUID
	UnitCode     string
	UnitsPerPack pgtype.Numeric
	Quantity     pgtype.Numeric
	BaseQuantity pgtype.Numeric
	UnitPriceMmk pgtype.Numeric
	DiscountMmk  pgtype.Numeric
	TaxMmk       pgtype.Numeric
	TotalMmk     pgtype.Numeric
	PriceReason  pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AppSaleItemBatch struct {
	ID           pgtype.UUID
	SaleItemID   pgtype.UUID
	BatchID      pgtype.UUID
	ProductID    pgtype.UUID
	Quantity     pgtype.Numeric
	UnitCostMmk  pgtype.Numeric
	TotalCostMmk pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
}

type AppSaleTotal struct {
	SaleID     pgtype.UUID
	CustomerID pgtype.UUID
	TotalMmk   pgtype.Numeric
}

type AppSalesReturn struct {
	ID                pgtype.UUID
	ReturnNumber      string
	SaleID            pgtype.UUID
	ReturnType        string
	ReplacementSaleID pgtype.UUID
	ReturnedAt        pgtype.Timestamptz
	Reason            string
	Status            string
	PostedAt          pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AppSalesReturnItem struct {
	ID              pgtype.UUID
	SalesReturnID   pgtype.UUID
	SaleID          pgtype.UUID
	SaleItemID      pgtype.UUID
	SaleItemBatchID pgtype.UUID
	ProductID       pgtype.UUID
	Quantity        pgtype.Numeric
	RefundMmk       pgtype.Numeric
	Disposition     string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AppShipment struct {
	ID                     pgtype.UUID
	ShipmentNumber         string
	StartLocation          string
	DestinationWarehouseID pgtype.UUID
	ShippedAt              pgtype.Timestamptz
	ExpectedArrivalAt      pgtype.Timestamptz
	ArrivedAt              pgtype.Timestamptz
	Status                 string
	AllocationMethod       string
	CostsFinalizedAt       pgtype.Timestamptz
	CostsFinalizedBy       pgtype.UUID
	CreatedBy              pgtype.UUID
	Notes                  pgtype.Text
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Version                int64
	RequestID              pgtype.UUID
}

type AppShipmentCosting struct {
	ShipmentID  pgtype.UUID
	Document    []byte
	FinalizedBy pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type AppShipmentExpense struct {
	ID             pgtype.UUID
	ShipmentID     pgtype.UUID
	Category       string
	Description    string
	CurrencyCode   string
	AmountOriginal pgtype.Numeric
	MmkPerUnit     pgtype.Numeric
	AmountMmk      pgtype.Numeric
	IncurredAt     pgtype.Timestamptz
	RecordedBy     pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	RequestID      pgtype.UUID
	Notes          pgtype.Text
	VoidedAt       pgtype.Timestamptz
	VoidReason     pgtype.Text
}

type AppShipmentItem struct {
	ID                      pgtype.UUID
	ShipmentID              pgtype.UUID
	PurchaseItemID          pgtype.UUID
	ProductID               pgtype.UUID
	ExpectedQuantity        pgtype.Numeric
	WeightKg                pgtype.Numeric
	CartonQuantity          pgtype.Numeric
	AllocatedTransportMmk   pgtype.Numeric
	AllocatedExpenseMmk     pgtype.Numeric
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	PurchaseCostMmk         pgtype.Numeric
	CostingSellableQuantity pgtype.Numeric
	LandedCostMmk           pgtype.Numeric
	ActualUnitCostMmk       pgtype.Numeric
}

type AppStockAdjustment struct {
	ID             pgtype.UUID
	WarehouseID    pgtype.UUID
	Reason         string
	AdjustedAt     pgtype.Timestamptz
	Status         string
	PostedAt       pgtype.Timestamptz
	CreatedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	RequestID      pgtype.UUID
	RequestPayload []byte
}

type AppStockAdjustmentItem struct {
	ID                pgtype.UUID
	StockAdjustmentID pgtype.UUID
	BatchID           pgtype.UUID
	QuantityDelta     pgtype.Numeric
	StockBucket       string
	UnitCostMmk       pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AppStockTake struct {
	ID           pgtype.UUID
	WarehouseID  pgtype.UUID
	CountedAt    pgtype.Timestamptz
	CountedBy    pgtype.UUID
	Status       string
	AdjustmentID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AppStockTakeItem struct {
	ID              pgtype.UUID
	StockTakeID     pgtype.UUID
	BatchID         pgtype.UUID
	StockBucket     string
	SystemQuantity  pgtype.Numeric
	CountedQuantity pgtype.Numeric
	Difference      pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AppStockTransfer struct {
	ID              pgtype.UUID
	TransferNumber  string
	FromWarehouseID pgtype.UUID
	ToWarehouseID   pgtype.UUID
	Status          string
	DispatchedAt    pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AppStockTransferItem struct {
	ID               pgtype.UUID
	TransferID       pgtype.UUID
	BatchID          pgtype.UUID
	Quantity         pgtype.Numeric
	ReceivedQuantity pgtype.Numeric
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type AppSupplier struct {
	ID            pgtype.UUID
	Code          string
	Name          string
	ContactPerson pgtype.Text
	Phone         pgtype.Text
	Address       pgtype.Text
	CountryCode   pgtype.Text
	SupplierType  pgtype.Text
	PaymentTerms  pgtype.Text
	Notes         pgtype.Text
	IsActive      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ArchivedAt    pgtype.Timestamptz
	Version       int64
}

type AppSupplierPayable struct {
	PurchaseID          pgtype.UUID
	SupplierID          pgtype.UUID
	DueDate             pgtype.Date
	CurrencyCode        string
	TotalOriginal       pgtype.Numeric
	TotalMmk            pgtype.Numeric
	AmountPaidMmk       pgtype.Numeric
	OutstandingOriginal pgtype.Numeric
	OutstandingMmk      pgtype.Numeric
	PaymentStatus       string
}

type AppTransportationStage struct {
	ID                   pgtype.UUID
	ShipmentID           pgtype.UUID
	StageNumber          int32
	StartLocation        string
	Destination          string
	ProviderName         string
	TransportationType   pgtype.Text
	VehicleInformation   pgtype.Text
	DepartedAt           pgtype.Timestamptz
	ArrivedAt            pgtype.Timestamptz
	TransportationFeeMmk pgtype.Numeric
	LoadingFeeMmk        pgtype.Numeric
	UnloadingFeeMmk      pgtype.Numeric
	OtherFeeMmk          pgtype.Numeric
	TotalMmk             pgtype.Numeric
	Notes                pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RequestID            pgtype.UUID
}

type AppUnit struct {
	Code      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type AppUser struct {
	ID                pgtype.UUID
	Username          string
	DisplayName       string
	PasswordHash      string
	RoleCode          string
	IsActive          bool
	PasswordChangedAt pgtype.Timestamptz
	LastLoginAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AppUserPermission struct {
	UserID         pgtype.UUID
	PermissionCode string
	GrantedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type AppUserSession struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type AppWarehouse struct {
	ID           pgtype.UUID
	Code         string
	Name         string
	Address      pgtype.Text
	LocationType string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
