// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pos.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const pOSCheckout = `-- name: POSCheckout :one
SELECT app.pos_public_document(app.pos_sale($1::jsonb,$2::uuid,$3::boolean,$4::boolean,$5::boolean),$6::boolean,$7::boolean)::jsonb
`

type POSCheckoutParams struct {
	Data      []byte
	Actor     pgtype.UUID
	Discounts bool
	BelowCost bool
	Preview   bool
	Costs     bool
	Profits   bool
}

func (q *Queries) POSCheckout(ctx context.Context, arg POSCheckoutParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, pOSCheckout,
		arg.Data,
		arg.Actor,
		arg.Discounts,
		arg.BelowCost,
		arg.Preview,
		arg.Costs,
		arg.Profits,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const pOSCreateCustomer = `-- name: POSCreateCustomer :one
WITH created AS (INSERT INTO app.customers(code,name,phone,customer_type,credit_limit_mmk) SELECT 'C-'||gen_random_uuid(),d->>'name',nullif(d->>'phone',''),d->>'customer_type',(d->>'credit_limit_mmk')::numeric FROM (SELECT $1::jsonb d) src RETURNING id, code, name, business_name, phone, address, customer_type, credit_limit_mmk, notes, is_active, created_at, updated_at, version), audit AS (INSERT INTO app.audit_logs(actor_id,action,entity_type,entity_id,new_value) SELECT $2::uuid,'customers.create','customers',id,to_jsonb(created) FROM created)
SELECT id FROM created
`

type POSCreateCustomerParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) POSCreateCustomer(ctx context.Context, arg POSCreateCustomerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, pOSCreateCustomer, arg.Data, arg.Actor)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const pOSCustomers = `-- name: POSCustomers :one
SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb)::jsonb FROM (SELECT id,code,name,phone,customer_type,credit_limit_mmk::text FROM app.customers WHERE is_active AND ($1::text='' OR strpos(lower(code||' '||name||' '||coalesce(phone,'')),lower($1))>0) ORDER BY name,id LIMIT 50) x
`

func (q *Queries) POSCustomers(ctx context.Context, search string) ([]byte, error) {
	row := q.db.QueryRow(ctx, pOSCustomers, search)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const pOSInvoice = `-- name: POSInvoice :one
SELECT (jsonb_build_object('id',s.id,'invoice_number',s.invoice_number,'sold_at',s.sold_at,'status',s.status,'cashier',u.display_name)||app.pos_public_document(s.invoice_document,$1::boolean,$2::boolean))::jsonb FROM app.sales s JOIN app.users u ON u.id=s.created_by WHERE s.id=$3::uuid AND s.invoice_document IS NOT NULL AND ($4::boolean OR s.created_by=$5::uuid)
`

type POSInvoiceParams struct {
	Costs    bool
	Profits  bool
	ID       pgtype.UUID
	AllSales bool
	Actor    pgtype.UUID
}

func (q *Queries) POSInvoice(ctx context.Context, arg POSInvoiceParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, pOSInvoice,
		arg.Costs,
		arg.Profits,
		arg.ID,
		arg.AllSales,
		arg.Actor,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const pOSPrices = `-- name: POSPrices :exec
SELECT app.pos_prices($1::jsonb,$2::uuid)
`

type POSPricesParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) POSPrices(ctx context.Context, arg POSPricesParams) error {
	_, err := q.db.Exec(ctx, pOSPrices, arg.Data, arg.Actor)
	return err
}

const pOSProducts = `-- name: POSProducts :one
SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb)::jsonb FROM (
 SELECT p.id,p.name,p.sku,p.barcode,p.base_unit_code,p.version::text,
 coalesce((SELECT sum(available_quantity)::text FROM app.pos_eligible_stock i WHERE i.product_id=p.id AND i.warehouse_id=$1::uuid),'0') AS available_quantity,
 (SELECT coalesce(jsonb_agg(jsonb_build_object('unit_code',u.unit_code,'units_per_pack',u.units_per_pack::text,'barcode',u.barcode,'retail_price_mmk',u.retail_price_mmk::text,'wholesale_price_mmk',u.wholesale_price_mmk::text,'is_default_sale',u.is_default_sale) ORDER BY u.is_default_sale DESC,u.unit_code),'[]'::jsonb) FROM app.product_units u WHERE u.product_id=p.id) AS packaging
 FROM app.products p WHERE p.is_active AND p.archived_at IS NULL AND ($2::text='' OR strpos(lower(p.name||' '||p.sku),lower($2))>0 OR p.barcode=$2 OR EXISTS(SELECT 1 FROM app.product_units u WHERE u.product_id=p.id AND u.barcode=$2))
 ORDER BY (p.barcode=$2 OR EXISTS(SELECT 1 FROM app.product_units u WHERE u.product_id=p.id AND u.barcode=$2)) DESC NULLS LAST,p.name,p.id LIMIT 50
) x
`

type POSProductsParams struct {
	WarehouseID pgtype.UUID
	Search      string
}

func (q *Queries) POSProducts(ctx context.Context, arg POSProductsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, pOSProducts, arg.WarehouseID, arg.Search)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const pOSSales = `-- name: POSSales :one
WITH filtered AS (SELECT s.id,s.invoice_number,s.sold_at,s.invoice_document->>'customer_name' AS customer_name,s.invoice_document->>'total_mmk' AS total_mmk,s.invoice_document->>'paid_mmk' AS paid_mmk,s.invoice_document->>'outstanding_mmk' AS outstanding_mmk FROM app.sales s WHERE s.invoice_document IS NOT NULL AND ($1::text='' OR strpos(lower(s.invoice_number||' '||(s.invoice_document->>'customer_name')),lower($1))>0)),page AS (SELECT id, invoice_number, sold_at, customer_name, total_mmk, paid_mmk, outstanding_mmk FROM filtered ORDER BY sold_at DESC,id LIMIT $3::int OFFSET $2::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'sales',coalesce((SELECT jsonb_agg(to_jsonb(page) ORDER BY sold_at DESC,id) FROM page),'[]'::jsonb))::jsonb
`

type POSSalesParams struct {
	Search     string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) POSSales(ctx context.Context, arg POSSalesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, pOSSales, arg.Search, arg.PageOffset, arg.PageSize)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const pOSWarehouses = `-- name: POSWarehouses :one
SELECT coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) ORDER BY name),'[]'::jsonb)::jsonb FROM app.warehouses WHERE is_active
`

func (q *Queries) POSWarehouses(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, pOSWarehouses)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
