// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProduct = `-- name: ArchiveProduct :exec
UPDATE app.products SET is_active=false,archived_at=clock_timestamp() WHERE id=$1
`

func (q *Queries) ArchiveProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveProduct, id)
	return err
}

const catalogMetadata = `-- name: CatalogMetadata :one
SELECT jsonb_build_object('categories',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',id,'name',name,'is_active',is_active) ORDER BY lower(name),id) FROM app.categories),'[]'::jsonb),'brands',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',id,'name',name,'is_active',is_active) ORDER BY lower(name),id) FROM app.brands),'[]'::jsonb),'units',(SELECT jsonb_agg(jsonb_build_object('code',code,'name',name) ORDER BY name) FROM app.units))::jsonb
`

func (q *Queries) CatalogMetadata(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, catalogMetadata)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const getProduct = `-- name: GetProduct :one
SELECT app.product_document(p)::jsonb FROM app.products p WHERE p.id=$1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO app.products(sku,name,barcode,category_id,brand_id,country_code,description,base_unit_code,minimum_stock,tracks_expiry,is_active)
SELECT d->>'sku',d->>'name',NULLIF(d->>'barcode',''),NULLIF(d->>'category_id','')::uuid,NULLIF(d->>'brand_id','')::uuid,NULLIF(d->>'country_code',''),NULLIF(d->>'description',''),d->>'base_unit_code',NULLIF(d->>'minimum_stock','')::numeric,(d->>'tracks_expiry')::boolean,(d->>'is_active')::boolean FROM (SELECT $1::jsonb d) t RETURNING id
`

func (q *Queries) InsertProduct(ctx context.Context, data []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertProduct, data)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listProducts = `-- name: ListProducts :one
WITH filtered AS (
 SELECT p.id, p.sku, p.name, p.barcode, p.category_id, p.brand_id, p.country_code, p.description, p.base_unit_code, p.minimum_stock, p.tracks_expiry, p.is_active, p.created_at, p.updated_at, p.archived_at, p.version FROM app.products p WHERE
 (CASE $1::text WHEN 'archived' THEN p.archived_at IS NOT NULL WHEN 'active' THEN p.archived_at IS NULL AND p.is_active WHEN 'inactive' THEN p.archived_at IS NULL AND NOT p.is_active ELSE p.archived_at IS NULL END)
 AND ($2::uuid IS NULL OR p.category_id=$2)
 AND ($3::uuid IS NULL OR p.brand_id=$3)
 AND ($4::text='' OR strpos(lower(p.name),lower($4))>0 OR strpos(lower(p.sku),lower($4))>0 OR strpos(COALESCE(p.barcode,''),$4)>0 OR EXISTS(SELECT 1 FROM app.product_units pu WHERE pu.product_id=p.id AND strpos(COALESCE(pu.barcode,''),$4)>0))
), page AS (SELECT id, sku, name, barcode, category_id, brand_id, country_code, description, base_unit_code, minimum_stock, tracks_expiry, is_active, created_at, updated_at, archived_at, version FROM filtered ORDER BY created_at DESC,id LIMIT $6::int OFFSET $5::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'products',COALESCE((SELECT jsonb_agg(app.product_document(p) ORDER BY p.created_at DESC,p.id) FROM app.products p JOIN page f USING(id)),'[]'::jsonb))::jsonb
`

type ListProductsParams struct {
	Status     string
	CategoryID pgtype.UUID
	BrandID    pgtype.UUID
	Search     string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, listProducts,
		arg.Status,
		arg.CategoryID,
		arg.BrandID,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const lockProduct = `-- name: LockProduct :one
SELECT id,base_unit_code,version,archived_at FROM app.products WHERE id=$1 FOR UPDATE
`

type LockProductRow struct {
	ID           pgtype.UUID
	BaseUnitCode string
	Version      int64
	ArchivedAt   pgtype.Timestamptz
}

func (q *Queries) LockProduct(ctx context.Context, id pgtype.UUID) (LockProductRow, error) {
	row := q.db.QueryRow(ctx, lockProduct, id)
	var i LockProductRow
	err := row.Scan(
		&i.ID,
		&i.BaseUnitCode,
		&i.Version,
		&i.ArchivedAt,
	)
	return i, err
}

const productInUse = `-- name: ProductInUse :one
SELECT EXISTS(SELECT 1 FROM app.purchase_items x WHERE x.product_id=$1 UNION ALL SELECT 1 FROM app.sale_items x WHERE x.product_id=$1 UNION ALL SELECT 1 FROM app.batches x WHERE x.product_id=$1 UNION ALL SELECT 1 FROM app.damaged_products x WHERE x.product_id=$1 UNION ALL SELECT 1 FROM app.missing_products x WHERE x.product_id=$1)::boolean
`

func (q *Queries) ProductInUse(ctx context.Context, productID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, productInUse, productID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const productReferencesValid = `-- name: ProductReferencesValid :one
SELECT (EXISTS(SELECT 1 FROM app.units WHERE code=$1::text)
 AND ($2::uuid IS NULL OR EXISTS(SELECT 1 FROM app.categories WHERE id=$2 AND is_active))
 AND ($3::uuid IS NULL OR EXISTS(SELECT 1 FROM app.brands WHERE id=$3 AND is_active)))::boolean
`

type ProductReferencesValidParams struct {
	BaseUnit   string
	CategoryID pgtype.UUID
	BrandID    pgtype.UUID
}

func (q *Queries) ProductReferencesValid(ctx context.Context, arg ProductReferencesValidParams) (bool, error) {
	row := q.db.QueryRow(ctx, productReferencesValid, arg.BaseUnit, arg.CategoryID, arg.BrandID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const recordProductAudit = `-- name: RecordProductAudit :exec
INSERT INTO app.audit_logs(actor_id,action,entity_type,entity_id,old_value,new_value) VALUES($1,$2,$3,$4,$5,$6)
`

type RecordProductAuditParams struct {
	ActorID    pgtype.UUID
	Action     string
	EntityType string
	EntityID   pgtype.UUID
	OldValue   []byte
	NewValue   []byte
}

func (q *Queries) RecordProductAudit(ctx context.Context, arg RecordProductAuditParams) error {
	_, err := q.db.Exec(ctx, recordProductAudit,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const removeProductUnits = `-- name: RemoveProductUnits :exec
DELETE FROM app.product_units WHERE product_id=$1 AND NOT(unit_code=ANY($2::text[]))
`

type RemoveProductUnitsParams struct {
	ProductID pgtype.UUID
	KeepCodes []string
}

func (q *Queries) RemoveProductUnits(ctx context.Context, arg RemoveProductUnitsParams) error {
	_, err := q.db.Exec(ctx, removeProductUnits, arg.ProductID, arg.KeepCodes)
	return err
}

const resetProductDefaults = `-- name: ResetProductDefaults :exec
UPDATE app.product_units SET is_default_purchase=false,is_default_sale=false WHERE product_id=$1
`

func (q *Queries) ResetProductDefaults(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetProductDefaults, productID)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE app.products SET sku=d->>'sku',name=d->>'name',barcode=NULLIF(d->>'barcode',''),category_id=NULLIF(d->>'category_id','')::uuid,brand_id=NULLIF(d->>'brand_id','')::uuid,country_code=NULLIF(d->>'country_code',''),description=NULLIF(d->>'description',''),base_unit_code=d->>'base_unit_code',minimum_stock=NULLIF(d->>'minimum_stock','')::numeric,tracks_expiry=(d->>'tracks_expiry')::boolean,is_active=(d->>'is_active')::boolean FROM (SELECT $2::jsonb d) t WHERE id=$1
`

type UpdateProductParams struct {
	ID   pgtype.UUID
	Data []byte
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct, arg.ID, arg.Data)
	return err
}

const upsertProductUnit = `-- name: UpsertProductUnit :exec
INSERT INTO app.product_units(product_id,unit_code,units_per_pack,barcode,is_default_purchase,is_default_sale)
VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(product_id,unit_code) DO UPDATE SET units_per_pack=excluded.units_per_pack,barcode=excluded.barcode,is_default_purchase=excluded.is_default_purchase,is_default_sale=excluded.is_default_sale
`

type UpsertProductUnitParams struct {
	ProductID         pgtype.UUID
	UnitCode          string
	UnitsPerPack      pgtype.Numeric
	Barcode           pgtype.Text
	IsDefaultPurchase bool
	IsDefaultSale     bool
}

func (q *Queries) UpsertProductUnit(ctx context.Context, arg UpsertProductUnitParams) error {
	_, err := q.db.Exec(ctx, upsertProductUnit,
		arg.ProductID,
		arg.UnitCode,
		arg.UnitsPerPack,
		arg.Barcode,
		arg.IsDefaultPurchase,
		arg.IsDefaultSale,
	)
	return err
}
