// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchasing.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurchaseCurrency = `-- name: CreatePurchaseCurrency :exec
INSERT INTO app.currencies(code,name,minor_units) VALUES($1,$2,$3)
`

type CreatePurchaseCurrencyParams struct {
	Code       string
	Name       string
	MinorUnits int16
}

func (q *Queries) CreatePurchaseCurrency(ctx context.Context, arg CreatePurchaseCurrencyParams) error {
	_, err := q.db.Exec(ctx, createPurchaseCurrency, arg.Code, arg.Name, arg.MinorUnits)
	return err
}

const createPurchaseRate = `-- name: CreatePurchaseRate :one
INSERT INTO app.exchange_rates(currency_code,mmk_per_unit,effective_at,source,recorded_by) VALUES($1,$2,$3,$4,$5) RETURNING id
`

type CreatePurchaseRateParams struct {
	CurrencyCode string
	MmkPerUnit   pgtype.Numeric
	EffectiveAt  pgtype.Timestamptz
	Source       string
	RecordedBy   pgtype.UUID
}

func (q *Queries) CreatePurchaseRate(ctx context.Context, arg CreatePurchaseRateParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPurchaseRate,
		arg.CurrencyCode,
		arg.MmkPerUnit,
		arg.EffectiveAt,
		arg.Source,
		arg.RecordedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findPurchaseRequest = `-- name: FindPurchaseRequest :one
SELECT id,request_hash FROM app.purchases WHERE request_id=$1
`

type FindPurchaseRequestRow struct {
	ID          pgtype.UUID
	RequestHash pgtype.Text
}

func (q *Queries) FindPurchaseRequest(ctx context.Context, requestID pgtype.UUID) (FindPurchaseRequestRow, error) {
	row := q.db.QueryRow(ctx, findPurchaseRequest, requestID)
	var i FindPurchaseRequestRow
	err := row.Scan(&i.ID, &i.RequestHash)
	return i, err
}

const getPurchaseDocument = `-- name: GetPurchaseDocument :one
SELECT app.purchase_document(p,$1::boolean,true)::jsonb FROM app.purchases p WHERE id=$2
`

type GetPurchaseDocumentParams struct {
	Costs bool
	ID    pgtype.UUID
}

func (q *Queries) GetPurchaseDocument(ctx context.Context, arg GetPurchaseDocumentParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPurchaseDocument, arg.Costs, arg.ID)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const getPurchaseRate = `-- name: GetPurchaseRate :one
SELECT currency_code,mmk_per_unit::text AS rate,effective_at FROM app.exchange_rates WHERE id=$1
`

type GetPurchaseRateRow struct {
	CurrencyCode string
	Rate         string
	EffectiveAt  pgtype.Timestamptz
}

func (q *Queries) GetPurchaseRate(ctx context.Context, id pgtype.UUID) (GetPurchaseRateRow, error) {
	row := q.db.QueryRow(ctx, getPurchaseRate, id)
	var i GetPurchaseRateRow
	err := row.Scan(&i.CurrencyCode, &i.Rate, &i.EffectiveAt)
	return i, err
}

const insertPurchase = `-- name: InsertPurchase :one
INSERT INTO app.purchases(purchase_number,supplier_id,supplier_invoice_number,purchased_at,due_date,currency_code,exchange_rate_id,mmk_per_unit,created_by,notes,request_id,request_hash)
SELECT d->>'purchase_number',(d->>'supplier_id')::uuid,NULLIF(d->>'supplier_invoice_number',''),(d->>'purchased_at')::timestamptz,NULLIF(d->>'due_date','')::date,d->>'currency_code',NULLIF(d->>'exchange_rate_id','')::uuid,(d->>'mmk_per_unit')::numeric,$1,NULLIF(d->>'notes',''),(d->>'request_id')::uuid,$2 FROM (SELECT $3::jsonb d) x RETURNING id
`

type InsertPurchaseParams struct {
	ActorID     pgtype.UUID
	RequestHash pgtype.Text
	Data        []byte
}

func (q *Queries) InsertPurchase(ctx context.Context, arg InsertPurchaseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertPurchase, arg.ActorID, arg.RequestHash, arg.Data)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPurchaseItem = `-- name: InsertPurchaseItem :exec
INSERT INTO app.purchase_items(purchase_id,line_number,product_id,unit_code,quantity,units_per_pack,unit_price_original,discount_original,tax_original,product_name_snapshot,sku_snapshot,unit_name_snapshot)
SELECT $1,$2,(d->>'product_id')::uuid,d->>'unit_code',(d->>'quantity')::numeric,(d->>'units_per_pack')::numeric,(d->>'unit_price_original')::numeric,(d->>'discount_original')::numeric,(d->>'tax_original')::numeric,$3,$4,$5 FROM (SELECT $6::jsonb d) x
`

type InsertPurchaseItemParams struct {
	PurchaseID  pgtype.UUID
	LineNumber  int32
	ProductName pgtype.Text
	Sku         pgtype.Text
	UnitName    pgtype.Text
	Data        []byte
}

func (q *Queries) InsertPurchaseItem(ctx context.Context, arg InsertPurchaseItemParams) error {
	_, err := q.db.Exec(ctx, insertPurchaseItem,
		arg.PurchaseID,
		arg.LineNumber,
		arg.ProductName,
		arg.Sku,
		arg.UnitName,
		arg.Data,
	)
	return err
}

const listPurchaseDocuments = `-- name: ListPurchaseDocuments :one
WITH filtered AS (SELECT p.id, p.purchase_number, p.supplier_id, p.supplier_invoice_number, p.purchased_at, p.due_date, p.currency_code, p.exchange_rate_id, p.mmk_per_unit, p.status, p.posted_at, p.created_by, p.notes, p.created_at, p.updated_at, p.request_id, p.request_hash FROM app.purchases p WHERE ($2::text='' OR strpos(lower(p.purchase_number||' '||COALESCE(p.supplier_invoice_number,'')),lower($2))>0 OR EXISTS(SELECT 1 FROM app.suppliers s WHERE s.id=p.supplier_id AND strpos(lower(s.name),lower($2))>0)) AND ($3::text='' OR p.currency_code=$3) AND ($4::text='' OR p.status=$4)),
page AS (SELECT id FROM filtered ORDER BY purchased_at DESC,id LIMIT $6::int OFFSET $5::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'purchases',COALESCE((SELECT jsonb_agg(app.purchase_document(p,$1::boolean,false) ORDER BY p.purchased_at DESC,p.id) FROM app.purchases p JOIN page f USING(id)),'[]'::jsonb))::jsonb
`

type ListPurchaseDocumentsParams struct {
	Costs      bool
	Search     string
	Currency   string
	Status     string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ListPurchaseDocuments(ctx context.Context, arg ListPurchaseDocumentsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, listPurchaseDocuments,
		arg.Costs,
		arg.Search,
		arg.Currency,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const lockPurchaseCurrency = `-- name: LockPurchaseCurrency :one
SELECT code FROM app.currencies WHERE code=$1 AND is_active FOR SHARE
`

func (q *Queries) LockPurchaseCurrency(ctx context.Context, code string) (string, error) {
	row := q.db.QueryRow(ctx, lockPurchaseCurrency, code)
	var code_2 string
	err := row.Scan(&code_2)
	return code_2, err
}

const lockPurchasePackaging = `-- name: LockPurchasePackaging :one
SELECT p.name,p.sku,u.name AS unit_name,pu.units_per_pack::text AS units_per_pack FROM app.products p JOIN app.product_units pu ON pu.product_id=p.id JOIN app.units u ON u.code=pu.unit_code WHERE p.id=$1 AND pu.unit_code=$2 AND p.is_active AND p.archived_at IS NULL FOR SHARE OF p,pu,u
`

type LockPurchasePackagingParams struct {
	ID       pgtype.UUID
	UnitCode string
}

type LockPurchasePackagingRow struct {
	Name         string
	Sku          string
	UnitName     string
	UnitsPerPack string
}

func (q *Queries) LockPurchasePackaging(ctx context.Context, arg LockPurchasePackagingParams) (LockPurchasePackagingRow, error) {
	row := q.db.QueryRow(ctx, lockPurchasePackaging, arg.ID, arg.UnitCode)
	var i LockPurchasePackagingRow
	err := row.Scan(
		&i.Name,
		&i.Sku,
		&i.UnitName,
		&i.UnitsPerPack,
	)
	return i, err
}

const lockPurchaseRequest = `-- name: LockPurchaseRequest :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text,0))
`

func (q *Queries) LockPurchaseRequest(ctx context.Context, requestKey string) error {
	_, err := q.db.Exec(ctx, lockPurchaseRequest, requestKey)
	return err
}

const lockPurchaseSupplier = `-- name: LockPurchaseSupplier :one
SELECT id FROM app.suppliers WHERE id=$1 AND is_active AND archived_at IS NULL FOR SHARE
`

func (q *Queries) LockPurchaseSupplier(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockPurchaseSupplier, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const postPurchase = `-- name: PostPurchase :exec
UPDATE app.purchases SET status='POSTED',posted_at=clock_timestamp() WHERE id=$1 AND status='DRAFT'
`

func (q *Queries) PostPurchase(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, postPurchase, id)
	return err
}

const purchaseCurrencies = `-- name: PurchaseCurrencies :one
SELECT COALESCE(jsonb_agg(jsonb_build_object('code',code,'name',name,'minor_units',minor_units) ORDER BY code),'[]'::jsonb)::jsonb FROM app.currencies WHERE is_active
`

func (q *Queries) PurchaseCurrencies(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, purchaseCurrencies)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const purchaseProductOptions = `-- name: PurchaseProductOptions :one
SELECT COALESCE(jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'sku',p.sku,'packaging',COALESCE((SELECT jsonb_agg(jsonb_build_object('unit_code',u.unit_code,'unit_name',un.name,'units_per_pack',u.units_per_pack::text,'is_default_purchase',u.is_default_purchase) ORDER BY u.units_per_pack) FROM app.product_units u JOIN app.units un ON un.code=u.unit_code WHERE u.product_id=p.id),'[]'::jsonb)) ORDER BY p.name,p.id),'[]'::jsonb)::jsonb FROM (SELECT id,name,sku FROM app.products WHERE is_active AND archived_at IS NULL AND ($1::text='' OR strpos(lower(name||' '||sku),lower($1))>0) ORDER BY name,id LIMIT 50) p
`

func (q *Queries) PurchaseProductOptions(ctx context.Context, search string) ([]byte, error) {
	row := q.db.QueryRow(ctx, purchaseProductOptions, search)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const purchaseRates = `-- name: PurchaseRates :one
SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'currency_code',currency_code,'mmk_per_unit',mmk_per_unit::text,'effective_at',effective_at,'source',source) ORDER BY effective_at DESC,id),'[]'::jsonb)::jsonb FROM (SELECT id, currency_code, mmk_per_unit, effective_at, source, recorded_by, created_at FROM app.exchange_rates WHERE currency_code=$1::text AND effective_at<=$2::timestamptz ORDER BY effective_at DESC,id LIMIT 100) r
`

type PurchaseRatesParams struct {
	Currency string
	AsOf     pgtype.Timestamptz
}

func (q *Queries) PurchaseRates(ctx context.Context, arg PurchaseRatesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, purchaseRates, arg.Currency, arg.AsOf)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const purchaseSupplierOptions = `-- name: PurchaseSupplierOptions :one
SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'name',name,'code',code) ORDER BY name,id),'[]'::jsonb)::jsonb FROM (SELECT id,name,code FROM app.suppliers WHERE is_active AND archived_at IS NULL AND ($1::text='' OR strpos(lower(name||' '||code),lower($1))>0) ORDER BY name,id LIMIT 50) s
`

func (q *Queries) PurchaseSupplierOptions(ctx context.Context, search string) ([]byte, error) {
	row := q.db.QueryRow(ctx, purchaseSupplierOptions, search)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const supplierPurchaseBalance = `-- name: SupplierPurchaseBalance :one
SELECT jsonb_build_object('supplier_id',s.id,'total_outstanding_mmk',COALESCE((SELECT sum(outstanding_mmk)::text FROM app.supplier_payables WHERE supplier_id=s.id),'0'),'currencies',COALESCE((SELECT jsonb_agg(to_jsonb(b) ORDER BY currency_code) FROM (SELECT currency_code,sum(outstanding_original)::text AS outstanding_original,sum(outstanding_mmk)::text AS outstanding_mmk,sum(amount_paid_mmk)::text AS amount_paid_mmk,count(*) AS purchase_count FROM app.supplier_payables WHERE supplier_id=s.id GROUP BY currency_code) b),'[]'::jsonb))::jsonb FROM app.suppliers s WHERE s.id=$1
`

func (q *Queries) SupplierPurchaseBalance(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, supplierPurchaseBalance, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
