// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AuthenticateSession(ctx context.Context, tokenHash []byte) (AuthenticateSessionRow, error)
	CheckDatabase(ctx context.Context) (int32, error)
	ClearUserPermissions(ctx context.Context, userID pgtype.UUID) error
	ConsumeLoginAttempt(ctx context.Context, keyHash []byte) (int32, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error)
	EffectivePermissions(ctx context.Context, id pgtype.UUID) ([]string, error)
	FindLoginUser(ctx context.Context, lower string) (FindLoginUserRow, error)
	FindUser(ctx context.Context, id pgtype.UUID) (FindUserRow, error)
	GrantPermission(ctx context.Context, arg GrantPermissionParams) error
	HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error)
	ListPermissions(ctx context.Context) ([]ListPermissionsRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	LockLoginUser(ctx context.Context, id pgtype.UUID) (LockLoginUserRow, error)
	MarkLogin(ctx context.Context, id pgtype.UUID) error
	PruneLoginAttempts(ctx context.Context) error
	RecordAuthAudit(ctx context.Context, arg RecordAuthAuditParams) error
	RevokeSession(ctx context.Context, tokenHash []byte) error
}

var _ Querier = (*Queries)(nil)
