// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddSupplierPaymentMethod(ctx context.Context, arg AddSupplierPaymentMethodParams) error
	AdjustInventory(ctx context.Context, arg AdjustInventoryParams) (pgtype.UUID, error)
	ArchiveProduct(ctx context.Context, id pgtype.UUID) error
	ArchiveSupplier(ctx context.Context, id pgtype.UUID) error
	AuthenticateSession(ctx context.Context, tokenHash []byte) (AuthenticateSessionRow, error)
	CatalogMetadata(ctx context.Context) ([]byte, error)
	CheckDatabase(ctx context.Context) (int32, error)
	ClearUserPermissions(ctx context.Context, userID pgtype.UUID) error
	ConsumeLoginAttempt(ctx context.Context, keyHash []byte) (int32, error)
	CostJourneys(ctx context.Context, arg CostJourneysParams) ([]byte, error)
	CreateBrand(ctx context.Context, name string) (CreateBrandRow, error)
	CreateCatalogUnit(ctx context.Context, arg CreateCatalogUnitParams) (CreateCatalogUnitRow, error)
	CreateCategory(ctx context.Context, name string) (CreateCategoryRow, error)
	CreatePurchaseCurrency(ctx context.Context, arg CreatePurchaseCurrencyParams) error
	CreatePurchaseRate(ctx context.Context, arg CreatePurchaseRateParams) (pgtype.UUID, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error)
	CreateShipmentWarehouse(ctx context.Context, arg CreateShipmentWarehouseParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error)
	CustomerCatalog(ctx context.Context, search string) ([]byte, error)
	CustomerDetail(ctx context.Context, id pgtype.UUID) ([]byte, error)
	CustomerHistory(ctx context.Context, arg CustomerHistoryParams) ([]byte, error)
	CustomerPayment(ctx context.Context, arg CustomerPaymentParams) (pgtype.UUID, error)
	CustomerPaymentList(ctx context.Context, arg CustomerPaymentListParams) ([]byte, error)
	CustomerPayments(ctx context.Context, id pgtype.UUID) ([]byte, error)
	CustomerPrice(ctx context.Context, arg CustomerPriceParams) error
	CustomerPrices(ctx context.Context, id pgtype.UUID) ([]byte, error)
	CustomerSave(ctx context.Context, arg CustomerSaveParams) (pgtype.UUID, error)
	CustomersList(ctx context.Context, arg CustomersListParams) ([]byte, error)
	Dashboard(ctx context.Context, access []byte) ([]byte, error)
	DeleteUnpaidShipmentStage(ctx context.Context, arg DeleteUnpaidShipmentStageParams) (int64, error)
	EffectivePermissions(ctx context.Context, id pgtype.UUID) ([]string, error)
	ExpenseCategories(ctx context.Context) ([]byte, error)
	ExpensePost(ctx context.Context, arg ExpensePostParams) (pgtype.UUID, error)
	ExpenseReverse(ctx context.Context, arg ExpenseReverseParams) (pgtype.UUID, error)
	ExpensesList(ctx context.Context, arg ExpensesListParams) ([]byte, error)
	FinalizeShipmentCost(ctx context.Context, arg FinalizeShipmentCostParams) error
	FindLoginUser(ctx context.Context, lower string) (FindLoginUserRow, error)
	FindPurchaseRequest(ctx context.Context, requestID pgtype.UUID) (FindPurchaseRequestRow, error)
	FindUser(ctx context.Context, id pgtype.UUID) (FindUserRow, error)
	GetFinalizedCost(ctx context.Context, shipmentID pgtype.UUID) ([]byte, error)
	GetManagedWarehouse(ctx context.Context, id pgtype.UUID) ([]byte, error)
	GetProduct(ctx context.Context, id pgtype.UUID) ([]byte, error)
	GetPurchaseDocument(ctx context.Context, arg GetPurchaseDocumentParams) ([]byte, error)
	GetPurchaseRate(ctx context.Context, id pgtype.UUID) (GetPurchaseRateRow, error)
	GetReceiving(ctx context.Context, id pgtype.UUID) ([]byte, error)
	GetShipment(ctx context.Context, arg GetShipmentParams) ([]byte, error)
	GetShipmentExpense(ctx context.Context, arg GetShipmentExpenseParams) ([]byte, error)
	GetShipmentStage(ctx context.Context, arg GetShipmentStageParams) ([]byte, error)
	GetSupplier(ctx context.Context, id pgtype.UUID) ([]byte, error)
	GrantPermission(ctx context.Context, arg GrantPermissionParams) error
	HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error)
	InsertProduct(ctx context.Context, data []byte) (pgtype.UUID, error)
	InsertPurchase(ctx context.Context, arg InsertPurchaseParams) (pgtype.UUID, error)
	InsertPurchaseItem(ctx context.Context, arg InsertPurchaseItemParams) error
	InsertShipment(ctx context.Context, arg InsertShipmentParams) (pgtype.UUID, error)
	InsertShipmentExpense(ctx context.Context, arg InsertShipmentExpenseParams) (pgtype.UUID, error)
	InsertShipmentItem(ctx context.Context, arg InsertShipmentItemParams) error
	InsertShipmentStage(ctx context.Context, arg InsertShipmentStageParams) (pgtype.UUID, error)
	InsertSupplier(ctx context.Context, data []byte) (pgtype.UUID, error)
	InventoryMovements(ctx context.Context, arg InventoryMovementsParams) ([]byte, error)
	InventoryWarehouses(ctx context.Context) ([]byte, error)
	LandedCostSources(ctx context.Context, id pgtype.UUID) ([]byte, error)
	LandedWarehousePricesSave(ctx context.Context, arg LandedWarehousePricesSaveParams) error
	ListBatches(ctx context.Context, arg ListBatchesParams) ([]byte, error)
	ListInventory(ctx context.Context, arg ListInventoryParams) ([]byte, error)
	ListPermissions(ctx context.Context) ([]ListPermissionsRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]byte, error)
	ListPurchaseDocuments(ctx context.Context, arg ListPurchaseDocumentsParams) ([]byte, error)
	ListReceiving(ctx context.Context, arg ListReceivingParams) ([]byte, error)
	ListShipments(ctx context.Context, arg ListShipmentsParams) ([]byte, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]byte, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	LockBrand(ctx context.Context, id pgtype.UUID) (LockBrandRow, error)
	LockCategory(ctx context.Context, id pgtype.UUID) (LockCategoryRow, error)
	LockCostPurchaseItems(ctx context.Context, shipmentID pgtype.UUID) ([]pgtype.UUID, error)
	LockLoginUser(ctx context.Context, id pgtype.UUID) (LockLoginUserRow, error)
	LockProduct(ctx context.Context, id pgtype.UUID) (LockProductRow, error)
	LockPurchaseCurrency(ctx context.Context, code string) (string, error)
	LockPurchasePackaging(ctx context.Context, arg LockPurchasePackagingParams) (LockPurchasePackagingRow, error)
	LockPurchaseRequest(ctx context.Context, requestKey string) error
	LockPurchaseSupplier(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	LockShipment(ctx context.Context, id pgtype.UUID) (LockShipmentRow, error)
	LockShipmentPurchaseItem(ctx context.Context, id pgtype.UUID) (LockShipmentPurchaseItemRow, error)
	LockShipmentWarehouse(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	LockSupplier(ctx context.Context, id pgtype.UUID) (LockSupplierRow, error)
	MarkLogin(ctx context.Context, id pgtype.UUID) error
	POSCheckout(ctx context.Context, arg POSCheckoutParams) ([]byte, error)
	POSCreateCustomer(ctx context.Context, arg POSCreateCustomerParams) (pgtype.UUID, error)
	POSCustomers(ctx context.Context, search string) ([]byte, error)
	POSInvoice(ctx context.Context, arg POSInvoiceParams) ([]byte, error)
	POSPrices(ctx context.Context, arg POSPricesParams) error
	POSProducts(ctx context.Context, arg POSProductsParams) ([]byte, error)
	POSSales(ctx context.Context, arg POSSalesParams) ([]byte, error)
	POSWarehouses(ctx context.Context) ([]byte, error)
	PostPurchase(ctx context.Context, id pgtype.UUID) error
	PostReceiving(ctx context.Context, arg PostReceivingParams) (pgtype.UUID, error)
	ProductInUse(ctx context.Context, productID pgtype.UUID) (bool, error)
	ProductReferencesValid(ctx context.Context, arg ProductReferencesValidParams) (bool, error)
	ProfitReport(ctx context.Context, arg ProfitReportParams) ([]byte, error)
	PruneLoginAttempts(ctx context.Context) error
	PurchaseCurrencies(ctx context.Context) ([]byte, error)
	PurchaseProductOptions(ctx context.Context, search string) ([]byte, error)
	PurchaseRates(ctx context.Context, arg PurchaseRatesParams) ([]byte, error)
	PurchaseReturnPost(ctx context.Context, arg PurchaseReturnPostParams) ([]byte, error)
	PurchaseSupplierOptions(ctx context.Context, search string) ([]byte, error)
	PurchaseWorkflow(ctx context.Context, arg PurchaseWorkflowParams) ([]byte, error)
	ReceivingOptions(ctx context.Context, search string) ([]byte, error)
	ReceivingShipment(ctx context.Context, id pgtype.UUID) ([]byte, error)
	RecordAuthAudit(ctx context.Context, arg RecordAuthAuditParams) error
	RecordProductAudit(ctx context.Context, arg RecordProductAuditParams) error
	RecordSupplierPayment(ctx context.Context, arg RecordSupplierPaymentParams) (pgtype.UUID, error)
	RemoveProductUnits(ctx context.Context, arg RemoveProductUnitsParams) error
	ReportCurrency(ctx context.Context, arg ReportCurrencyParams) ([]byte, error)
	ReportCustomerDebt(ctx context.Context, arg ReportCustomerDebtParams) ([]byte, error)
	ReportDamage(ctx context.Context, arg ReportDamageParams) ([]byte, error)
	ReportExpenses(ctx context.Context, arg ReportExpensesParams) ([]byte, error)
	ReportInventory(ctx context.Context, arg ReportInventoryParams) ([]byte, error)
	ReportMissing(ctx context.Context, arg ReportMissingParams) ([]byte, error)
	ReportMovements(ctx context.Context, arg ReportMovementsParams) ([]byte, error)
	ReportProducts(ctx context.Context, arg ReportProductsParams) ([]byte, error)
	ReportProfit(ctx context.Context, arg ReportProfitParams) ([]byte, error)
	ReportPurchases(ctx context.Context, arg ReportPurchasesParams) ([]byte, error)
	ReportSales(ctx context.Context, arg ReportSalesParams) ([]byte, error)
	ReportShipments(ctx context.Context, arg ReportShipmentsParams) ([]byte, error)
	ReportSupplierPayables(ctx context.Context, arg ReportSupplierPayablesParams) ([]byte, error)
	ReportTransportation(ctx context.Context, arg ReportTransportationParams) ([]byte, error)
	ResetProductDefaults(ctx context.Context, productID pgtype.UUID) error
	ReturnPurchaseChoices(ctx context.Context, search string) ([]byte, error)
	ReturnPurchaseSource(ctx context.Context, id pgtype.UUID) ([]byte, error)
	ReturnSaleChoices(ctx context.Context, search string) ([]byte, error)
	ReturnSaleSource(ctx context.Context, id pgtype.UUID) ([]byte, error)
	ReturnsHistory(ctx context.Context, arg ReturnsHistoryParams) ([]byte, error)
	ReverseUnallocatedPurchase(ctx context.Context, arg ReverseUnallocatedPurchaseParams) error
	RevokeSession(ctx context.Context, tokenHash []byte) error
	SalesReturnPost(ctx context.Context, arg SalesReturnPostParams) ([]byte, error)
	SaveCostDocument(ctx context.Context, arg SaveCostDocumentParams) error
	SaveCostItem(ctx context.Context, arg SaveCostItemParams) error
	SetProductUnitPrices(ctx context.Context, arg SetProductUnitPricesParams) error
	ShipmentChildHasPayment(ctx context.Context, transportationStageID pgtype.UUID) (bool, error)
	ShipmentExpenses(ctx context.Context, arg ShipmentExpensesParams) ([]byte, error)
	ShipmentHasReceiving(ctx context.Context, shipmentID pgtype.UUID) (bool, error)
	ShipmentItems(ctx context.Context, shipmentID pgtype.UUID) ([]byte, error)
	ShipmentJourneySources(ctx context.Context, shipmentID pgtype.UUID) ([]byte, error)
	ShipmentPurchaseChoices(ctx context.Context, search string) ([]byte, error)
	ShipmentReservedQuantity(ctx context.Context, purchaseItemID pgtype.UUID) (string, error)
	ShipmentStages(ctx context.Context, arg ShipmentStagesParams) ([]byte, error)
	ShipmentWarehouses(ctx context.Context) ([]byte, error)
	StockIssue(ctx context.Context, arg StockIssueParams) ([]byte, error)
	StockIssueChoices(ctx context.Context, search string) ([]byte, error)
	StockIssuesHistory(ctx context.Context, arg StockIssuesHistoryParams) ([]byte, error)
	SupplierPaymentHistory(ctx context.Context, purchaseID pgtype.UUID) ([]byte, error)
	SupplierPaymentMethods(ctx context.Context) ([]byte, error)
	SupplierPaymentPurchases(ctx context.Context, arg SupplierPaymentPurchasesParams) ([]byte, error)
	SupplierPurchaseBalance(ctx context.Context, id pgtype.UUID) ([]byte, error)
	SupplierPurchaseHistory(ctx context.Context, arg SupplierPurchaseHistoryParams) ([]byte, error)
	TouchShipment(ctx context.Context, id pgtype.UUID) error
	TransportPaymentHistory(ctx context.Context, id pgtype.UUID) ([]byte, error)
	TransportPaymentList(ctx context.Context, arg TransportPaymentListParams) ([]byte, error)
	TransportPaymentPost(ctx context.Context, arg TransportPaymentPostParams) (pgtype.UUID, error)
	UpdateBrand(ctx context.Context, arg UpdateBrandParams) (UpdateBrandRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error)
	UpdateManagedWarehouse(ctx context.Context, arg UpdateManagedWarehouseParams) error
	UpdateOpenShipmentDetails(ctx context.Context, arg UpdateOpenShipmentDetailsParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateShipmentStage(ctx context.Context, arg UpdateShipmentStageParams) (int64, error)
	UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) error
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) error
	UpsertProductUnit(ctx context.Context, arg UpsertProductUnitParams) error
	VoidShipmentExpense(ctx context.Context, arg VoidShipmentExpenseParams) (int64, error)
	WarehousePricesSave(ctx context.Context, arg WarehousePricesSaveParams) error
	WarehousePricingCosts(ctx context.Context, arg WarehousePricingCostsParams) ([]byte, error)
}

var _ Querier = (*Queries)(nil)
