// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receiving.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustInventory = `-- name: AdjustInventory :one
SELECT app.adjust_inventory($1::jsonb,$2::uuid)::uuid
`

type AdjustInventoryParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) AdjustInventory(ctx context.Context, arg AdjustInventoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, adjustInventory, arg.Data, arg.Actor)
	var column_1 pgtype.UUID
	err := row.Scan(&column_1)
	return column_1, err
}

const getReceiving = `-- name: GetReceiving :one
SELECT jsonb_build_object('id',r.id,'receipt_number',r.receipt_number,'shipment_id',s.id,'shipment_number',s.shipment_number,'warehouse_name',w.name,'received_at',r.received_at,'received_by',u.display_name,'status',r.status,'notes',r.notes,
 'items',coalesce((SELECT jsonb_agg(jsonb_build_object('id',i.id,'product_name',p.name,'base_unit',p.base_unit_code,'expected_quantity',i.expected_quantity::text,'received_quantity',i.received_quantity::text,'damaged_quantity',i.damaged_quantity::text,'missing_quantity',i.missing_quantity::text,'sellable_quantity',(i.received_quantity-i.damaged_quantity)::text,'batch_number',i.batch_number,'batch_id',b.id,'manufactured_on',i.manufactured_on,'expires_on',i.expires_on,'notes',i.notes,'carton_size',i.carton_size::text) ORDER BY i.id) FROM app.goods_receiving_items i JOIN app.products p ON p.id=i.product_id LEFT JOIN app.batches b ON b.receiving_item_id=i.id WHERE i.goods_receiving_id=r.id),'[]'::jsonb))::jsonb FROM app.goods_receiving r JOIN app.shipments s ON s.id=r.shipment_id JOIN app.warehouses w ON w.id=r.warehouse_id JOIN app.users u ON u.id=r.received_by WHERE r.id=$1
`

func (q *Queries) GetReceiving(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getReceiving, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const inventoryMovements = `-- name: InventoryMovements :one
WITH filtered AS (
 SELECT m.id, m.warehouse_id, m.batch_id, m.movement_type, m.sellable_delta, m.reserved_delta, m.damaged_delta, m.unit_cost_mmk, m.receiving_item_id, m.sale_item_batch_id, m.sales_return_item_id, m.purchase_return_item_id, m.stock_adjustment_item_id, m.stock_transfer_item_id, m.damaged_product_id, m.missing_product_id, m.reservation_sale_id, m.reverses_movement_id, m.idempotency_key, m.occurred_at, m.recorded_by, m.reason, m.created_at,b.batch_number,p.name AS product_name,w.name AS warehouse_name,u.display_name AS recorded_by_name
 FROM app.inventory_movements m JOIN app.batches b ON b.id=m.batch_id JOIN app.products p ON p.id=b.product_id JOIN app.warehouses w ON w.id=m.warehouse_id JOIN app.users u ON u.id=m.recorded_by
 WHERE ($2::uuid IS NULL OR m.batch_id=$2) AND ($3::uuid IS NULL OR m.warehouse_id=$3)
), page AS (SELECT id, warehouse_id, batch_id, movement_type, sellable_delta, reserved_delta, damaged_delta, unit_cost_mmk, receiving_item_id, sale_item_batch_id, sales_return_item_id, purchase_return_item_id, stock_adjustment_item_id, stock_transfer_item_id, damaged_product_id, missing_product_id, reservation_sale_id, reverses_movement_id, idempotency_key, occurred_at, recorded_by, reason, created_at, batch_number, product_name, warehouse_name, recorded_by_name FROM filtered ORDER BY occurred_at DESC,id DESC LIMIT $5::int OFFSET $4::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'movements',coalesce((SELECT jsonb_agg(jsonb_build_object('id',id,'batch_number',batch_number,'product_name',product_name,'warehouse_name',warehouse_name,'movement_type',movement_type,'sellable_delta',sellable_delta::text,'reserved_delta',reserved_delta::text,'damaged_delta',damaged_delta::text,'reason',reason,'occurred_at',occurred_at,'recorded_by',recorded_by_name)||CASE WHEN $1::boolean THEN jsonb_build_object('unit_cost_mmk',unit_cost_mmk::text) ELSE '{}'::jsonb END ORDER BY occurred_at DESC,id DESC) FROM page),'[]'::jsonb))::jsonb
`

type InventoryMovementsParams struct {
	Costs       bool
	BatchID     pgtype.UUID
	WarehouseID pgtype.UUID
	PageOffset  int32
	PageSize    int32
}

func (q *Queries) InventoryMovements(ctx context.Context, arg InventoryMovementsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, inventoryMovements,
		arg.Costs,
		arg.BatchID,
		arg.WarehouseID,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const inventoryWarehouses = `-- name: InventoryWarehouses :one
SELECT coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) ORDER BY name),'[]'::jsonb)::jsonb FROM app.warehouses
`

func (q *Queries) InventoryWarehouses(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, inventoryWarehouses)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const listInventory = `-- name: ListInventory :one
WITH filtered AS (
 SELECT i.warehouse_id, i.batch_id, i.sellable_quantity, i.reserved_quantity, i.damaged_quantity, i.available_quantity, i.created_at, i.updated_at, i.version,b.batch_number,b.expires_on,b.actual_unit_cost_mmk,p.id AS product_id,p.name AS product_name,p.sku,p.base_unit_code,w.name AS warehouse_name,r.carton_size
 FROM app.inventory i JOIN app.batches b ON b.id=i.batch_id JOIN app.products p ON p.id=b.product_id JOIN app.warehouses w ON w.id=i.warehouse_id JOIN app.goods_receiving_items r ON r.id=b.receiving_item_id
 WHERE ($2::uuid IS NULL OR i.warehouse_id=$2) AND ($3::text='' OR strpos(lower(p.name||' '||p.sku||' '||b.batch_number),lower($3))>0)
), page AS (SELECT warehouse_id, batch_id, sellable_quantity, reserved_quantity, damaged_quantity, available_quantity, created_at, updated_at, version, batch_number, expires_on, actual_unit_cost_mmk, product_id, product_name, sku, base_unit_code, warehouse_name, carton_size FROM filtered ORDER BY product_name,batch_number,batch_id,warehouse_id LIMIT $5::int OFFSET $4::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'stock',coalesce((SELECT jsonb_agg(jsonb_build_object('batch_id',batch_id,'warehouse_id',warehouse_id,'warehouse_name',warehouse_name,'product_id',product_id,'product_name',product_name,'sku',sku,'base_unit',base_unit_code,'batch_number',batch_number,'expires_on',expires_on,'version',version::text,'sellable_quantity',sellable_quantity::text,'available_quantity',available_quantity::text,'damaged_quantity',damaged_quantity::text,'reserved_quantity',reserved_quantity::text,'carton_size',carton_size::text,'available_cartons',floor(available_quantity/carton_size)::text,'available_units',(CASE WHEN carton_size IS NULL THEN available_quantity ELSE mod(available_quantity,carton_size) END)::text)||CASE WHEN $1::boolean THEN jsonb_build_object('unit_cost_mmk',actual_unit_cost_mmk::text) ELSE '{}'::jsonb END ORDER BY product_name,batch_number,batch_id,warehouse_id) FROM page),'[]'::jsonb))::jsonb
`

type ListInventoryParams struct {
	Costs       bool
	WarehouseID pgtype.UUID
	Search      string
	PageOffset  int32
	PageSize    int32
}

func (q *Queries) ListInventory(ctx context.Context, arg ListInventoryParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, listInventory,
		arg.Costs,
		arg.WarehouseID,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const listReceiving = `-- name: ListReceiving :one
WITH filtered AS (SELECT r.id,r.receipt_number,r.shipment_id,s.shipment_number,w.name AS warehouse_name,r.received_at,r.status FROM app.goods_receiving r JOIN app.shipments s ON s.id=r.shipment_id JOIN app.warehouses w ON w.id=r.warehouse_id WHERE $1::text='' OR strpos(lower(r.receipt_number||' '||s.shipment_number),lower($1))>0), page AS (SELECT id, receipt_number, shipment_id, shipment_number, warehouse_name, received_at, status FROM filtered ORDER BY received_at DESC,id LIMIT $3::int OFFSET $2::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'receipts',coalesce((SELECT jsonb_agg(to_jsonb(page) ORDER BY received_at DESC,id) FROM page),'[]'::jsonb))::jsonb
`

type ListReceivingParams struct {
	Search     string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ListReceiving(ctx context.Context, arg ListReceivingParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, listReceiving, arg.Search, arg.PageOffset, arg.PageSize)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const postReceiving = `-- name: PostReceiving :one
SELECT app.post_receiving($1::jsonb,$2::uuid)::uuid
`

type PostReceivingParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) PostReceiving(ctx context.Context, arg PostReceivingParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, postReceiving, arg.Data, arg.Actor)
	var column_1 pgtype.UUID
	err := row.Scan(&column_1)
	return column_1, err
}

const receivingOptions = `-- name: ReceivingOptions :one
SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb)::jsonb FROM (SELECT s.id,s.shipment_number,w.name AS warehouse_name FROM app.shipments s JOIN app.warehouses w ON w.id=s.destination_warehouse_id JOIN app.shipment_costings sc ON sc.shipment_id=s.id WHERE s.status='ARRIVED' AND NOT EXISTS(SELECT 1 FROM app.goods_receiving r WHERE r.shipment_id=s.id AND r.status NOT IN ('CANCELLED','REVERSED')) AND ($1::text='' OR strpos(lower(s.shipment_number),lower($1))>0) ORDER BY s.arrived_at,s.id LIMIT 50) x
`

func (q *Queries) ReceivingOptions(ctx context.Context, search string) ([]byte, error) {
	row := q.db.QueryRow(ctx, receivingOptions, search)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const receivingShipment = `-- name: ReceivingShipment :one
SELECT jsonb_build_object('id',s.id,'shipment_number',s.shipment_number,'version',s.version::text,'status',s.status,'warehouse_name',w.name,'arrived_at',s.arrived_at,'costs_finalized',s.costs_finalized_at IS NOT NULL,
 'items',coalesce((SELECT jsonb_agg(jsonb_build_object('id',si.id,'product_name',pr.name,'sku',pr.sku,'base_unit',pr.base_unit_code,'expected_quantity',si.expected_quantity::text,'sellable_quantity',si.costing_sellable_quantity::text,'carton_size',pu.units_per_pack::text,'tracks_expiry',pr.tracks_expiry) ORDER BY si.id) FROM app.shipment_items si JOIN app.products pr ON pr.id=si.product_id LEFT JOIN app.product_units pu ON pu.product_id=pr.id AND pu.unit_code='CARTON' WHERE si.shipment_id=s.id),'[]'::jsonb))::jsonb FROM app.shipments s JOIN app.warehouses w ON w.id=s.destination_warehouse_id WHERE s.id=$1
`

func (q *Queries) ReceivingShipment(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, receivingShipment, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
