// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_sales.sql

package database

import (
	"context"
)

const reportSales = `-- name: ReportSales :one
WITH bounds AS (SELECT $1::text::date AS start_on,$2::text::date AS end_on), dates AS (SELECT start_on, end_on,start_on::timestamp AT TIME ZONE 'Asia/Yangon' AS start_at,(end_on+1)::timestamp AT TIME ZONE 'Asia/Yangon' AS end_at FROM bounds),
filtered AS (
SELECT e.id,e.occurred_at,e.event_type,CASE WHEN e.event_type='SALE' THEN s.invoice_number ELSE r.return_number END AS reference,
 coalesce(c.name,'Walk-in customer') AS customer,s.pricing_mode,e.revenue_mmk
 FROM app.profit_sales_events e LEFT JOIN app.sales_returns r ON e.event_type='RETURN' AND r.id=e.id
 JOIN app.sales s ON s.id=CASE WHEN e.event_type='SALE' THEN e.id ELSE r.sale_id END
 LEFT JOIN app.customers c ON c.id=s.customer_id CROSS JOIN dates
 WHERE e.occurred_at>=start_at AND e.occurred_at<end_at
), page AS (SELECT id, occurred_at, event_type, reference, customer, pricing_mode, revenue_mmk FROM filtered ORDER BY occurred_at DESC,id LIMIT $4::int OFFSET $3::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'summary',(SELECT jsonb_build_object('revenue_mmk',round(coalesce(sum(revenue_mmk),0),4)::text) FROM filtered),'rows',coalesce((SELECT jsonb_agg(app.report_decimal_row(to_jsonb(page)) ORDER BY occurred_at DESC,id) FROM page),'[]'))::jsonb
`

type ReportSalesParams struct {
	StartOn    string
	EndOn      string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ReportSales(ctx context.Context, arg ReportSalesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, reportSales,
		arg.StartOn,
		arg.EndOn,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
