// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_currency.sql

package database

import (
	"context"
)

const reportCurrency = `-- name: ReportCurrency :one
WITH bounds AS (SELECT $1::text::date AS start_on,$2::text::date AS end_on), dates AS (SELECT start_on, end_on,start_on::timestamp AT TIME ZONE 'Asia/Yangon' AS start_at,(end_on+1)::timestamp AT TIME ZONE 'Asia/Yangon' AS end_at FROM bounds),
events AS (
 SELECT p.id,p.purchased_at AS occurred_at,'PURCHASE' AS event_type,p.purchase_number AS reference,p.supplier_id,p.currency_code,p.mmk_per_unit,t.total_original AS amount_original,t.total_mmk AS amount_mmk
 FROM app.purchases p JOIN app.purchase_totals t ON t.purchase_id=p.id WHERE p.status='POSTED'
 UNION ALL SELECT r.id,r.returned_at,'RETURN',r.return_number,p.supplier_id,p.currency_code,p.mmk_per_unit,-sum(i.credit_original),-sum(i.credit_mmk)
 FROM app.purchase_returns r JOIN app.purchase_return_items i ON i.purchase_return_id=r.id JOIN app.purchases p ON p.id=r.purchase_id WHERE r.status='POSTED' GROUP BY r.id,p.id
),
filtered AS (
SELECT e.currency_code AS id,e.currency_code,count(*) AS event_count,
 coalesce(sum(amount_original) FILTER(WHERE event_type='PURCHASE'),0) AS purchases_original,
 coalesce(-sum(amount_original) FILTER(WHERE event_type='RETURN'),0) AS returns_original,
 sum(amount_original) AS net_original,sum(amount_mmk) AS amount_mmk
 FROM events e CROSS JOIN dates WHERE occurred_at>=start_at AND occurred_at<end_at GROUP BY e.currency_code
), page AS (SELECT id, currency_code, event_count, purchases_original, returns_original, net_original, amount_mmk FROM filtered ORDER BY currency_code LIMIT $4::int OFFSET $3::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'summary',(SELECT jsonb_build_object('amount_mmk',round(coalesce(sum(amount_mmk),0),4)::text) FROM filtered),'rows',coalesce((SELECT jsonb_agg(app.report_decimal_row(to_jsonb(page)) ORDER BY currency_code) FROM page),'[]'))::jsonb
`

type ReportCurrencyParams struct {
	StartOn    string
	EndOn      string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ReportCurrency(ctx context.Context, arg ReportCurrencyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, reportCurrency,
		arg.StartOn,
		arg.EndOn,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
