// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_profit.sql

package database

import (
	"context"
)

const reportProfit = `-- name: ReportProfit :one
WITH bounds AS (SELECT $1::text::date AS start_on,$2::text::date AS end_on), dates AS (SELECT start_on, end_on,start_on::timestamp AT TIME ZONE 'Asia/Yangon' AS start_at,(end_on+1)::timestamp AT TIME ZONE 'Asia/Yangon' AS end_at FROM bounds),
profit AS MATERIALIZED (SELECT app.profit_summary(start_on,end_on) AS document FROM dates),
filtered AS (
SELECT 'profit' AS id,document->>'sales_mmk' AS sales_mmk,document->>'returns_mmk' AS returns_mmk,document->>'revenue_mmk' AS revenue_mmk,document->>'cogs_mmk' AS cogs_mmk,document->>'expenses_mmk' AS expenses_mmk,document->>'gross_profit_mmk' AS gross_profit_mmk,document->>'net_profit_mmk' AS net_profit_mmk,document->>'incomplete_cost_sales' AS incomplete_cost_sales FROM profit
), page AS (SELECT id, sales_mmk, returns_mmk, revenue_mmk, cogs_mmk, expenses_mmk, gross_profit_mmk, net_profit_mmk, incomplete_cost_sales FROM filtered ORDER BY id LIMIT $4::int OFFSET $3::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'summary',(SELECT document FROM profit),'rows',coalesce((SELECT jsonb_agg(app.report_decimal_row(to_jsonb(page)) ORDER BY id) FROM page),'[]'))::jsonb
`

type ReportProfitParams struct {
	StartOn    string
	EndOn      string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ReportProfit(ctx context.Context, arg ReportProfitParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, reportProfit,
		arg.StartOn,
		arg.EndOn,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
