// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_movements.sql

package database

import (
	"context"
)

const reportMovements = `-- name: ReportMovements :one
WITH bounds AS (SELECT $1::text::date AS start_on,$2::text::date AS end_on), dates AS (SELECT start_on, end_on,start_on::timestamp AT TIME ZONE 'Asia/Yangon' AS start_at,(end_on+1)::timestamp AT TIME ZONE 'Asia/Yangon' AS end_at FROM bounds),
filtered AS (
SELECT m.id,m.occurred_at,p.name AS product,p.base_unit_code AS unit,b.batch_number,w.name AS warehouse,m.movement_type,m.sellable_delta,m.reserved_delta,m.damaged_delta,m.reason,u.display_name AS recorded_by
 FROM app.inventory_movements m JOIN app.batches b ON b.id=m.batch_id JOIN app.products p ON p.id=b.product_id JOIN app.warehouses w ON w.id=m.warehouse_id JOIN app.users u ON u.id=m.recorded_by CROSS JOIN dates WHERE m.occurred_at>=start_at AND m.occurred_at<end_at
), page AS (SELECT id, occurred_at, product, unit, batch_number, warehouse, movement_type, sellable_delta, reserved_delta, damaged_delta, reason, recorded_by FROM filtered ORDER BY occurred_at DESC,id LIMIT $4::int OFFSET $3::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'summary',(SELECT jsonb_build_object('movements',count(*)::text) FROM filtered),'rows',coalesce((SELECT jsonb_agg(app.report_decimal_row(to_jsonb(page)) ORDER BY occurred_at DESC,id) FROM page),'[]'))::jsonb
`

type ReportMovementsParams struct {
	StartOn    string
	EndOn      string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ReportMovements(ctx context.Context, arg ReportMovementsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, reportMovements,
		arg.StartOn,
		arg.EndOn,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
