// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_transportation.sql

package database

import (
	"context"
)

const reportTransportation = `-- name: ReportTransportation :one
WITH bounds AS (SELECT $1::text::date AS start_on,$2::text::date AS end_on), dates AS (SELECT start_on, end_on,start_on::timestamp AT TIME ZONE 'Asia/Yangon' AS start_at,(end_on+1)::timestamp AT TIME ZONE 'Asia/Yangon' AS end_at FROM bounds),
filtered AS (
SELECT t.id,coalesce(t.departed_at,t.created_at) AS occurred_at,s.shipment_number,t.stage_number,t.provider_name,t.start_location,t.destination,
 CASE WHEN s.costs_finalized_at IS NULL THEN 'PROVISIONAL' ELSE 'FINALIZED' END AS cost_status,
 t.transportation_fee_mmk,t.loading_fee_mmk,t.unloading_fee_mmk,t.other_fee_mmk,t.total_mmk
 FROM app.transportation_stages t JOIN app.shipments s ON s.id=t.shipment_id CROSS JOIN dates
 WHERE s.status<>'CANCELLED' AND coalesce(t.departed_at,t.created_at)>=start_at AND coalesce(t.departed_at,t.created_at)<end_at
), page AS (SELECT id, occurred_at, shipment_number, stage_number, provider_name, start_location, destination, cost_status, transportation_fee_mmk, loading_fee_mmk, unloading_fee_mmk, other_fee_mmk, total_mmk FROM filtered ORDER BY occurred_at DESC,id LIMIT $4::int OFFSET $3::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'summary',(SELECT jsonb_build_object('transportation_fee_mmk',round(coalesce(sum(transportation_fee_mmk),0),4)::text,'loading_fee_mmk',round(coalesce(sum(loading_fee_mmk),0),4)::text,'unloading_fee_mmk',round(coalesce(sum(unloading_fee_mmk),0),4)::text,'other_fee_mmk',round(coalesce(sum(other_fee_mmk),0),4)::text,'total_mmk',round(coalesce(sum(total_mmk),0),4)::text) FROM filtered),'rows',coalesce((SELECT jsonb_agg(app.report_decimal_row(to_jsonb(page)) ORDER BY occurred_at DESC,id) FROM page),'[]'))::jsonb
`

type ReportTransportationParams struct {
	StartOn    string
	EndOn      string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ReportTransportation(ctx context.Context, arg ReportTransportationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, reportTransportation,
		arg.StartOn,
		arg.EndOn,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
