// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: returns.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const purchaseReturnPost = `-- name: PurchaseReturnPost :one
SELECT app.purchase_return_post($1::jsonb,$2::uuid)::jsonb
`

type PurchaseReturnPostParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) PurchaseReturnPost(ctx context.Context, arg PurchaseReturnPostParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, purchaseReturnPost, arg.Data, arg.Actor)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const returnPurchaseChoices = `-- name: ReturnPurchaseChoices :one
SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb)::jsonb FROM(SELECT p.id,p.purchase_number,s.name AS supplier_name,p.currency_code FROM app.purchases p JOIN app.suppliers s ON s.id=p.supplier_id WHERE p.status='POSTED' AND ($1::text='' OR strpos(lower(p.purchase_number||' '||s.name),lower($1))>0) ORDER BY p.purchased_at DESC,p.id LIMIT 50)x
`

func (q *Queries) ReturnPurchaseChoices(ctx context.Context, search string) ([]byte, error) {
	row := q.db.QueryRow(ctx, returnPurchaseChoices, search)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const returnPurchaseSource = `-- name: ReturnPurchaseSource :one
SELECT jsonb_build_object('id',p.id,'purchase_number',p.purchase_number,'currency_code',p.currency_code,'mmk_per_unit',p.mmk_per_unit::text,'items',coalesce((SELECT jsonb_agg(jsonb_build_object('batch_id',b.id,'warehouse_id',i.warehouse_id,'warehouse_name',w.name,'product_name',pr.name,'batch_number',b.batch_number,'available_quantity',i.available_quantity::text,'damaged_quantity',i.damaged_quantity::text,'unit',pr.base_unit_code) ORDER BY pr.name,b.id,i.warehouse_id) FROM app.purchase_items pi JOIN app.shipment_items sh ON sh.purchase_item_id=pi.id JOIN app.goods_receiving_items gr ON gr.shipment_item_id=sh.id JOIN app.batches b ON b.receiving_item_id=gr.id JOIN app.inventory i ON i.batch_id=b.id JOIN app.warehouses w ON w.id=i.warehouse_id JOIN app.products pr ON pr.id=pi.product_id WHERE pi.purchase_id=p.id),'[]'))::jsonb FROM app.purchases p WHERE p.id=$1::uuid AND p.status='POSTED'
`

func (q *Queries) ReturnPurchaseSource(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, returnPurchaseSource, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const returnSaleChoices = `-- name: ReturnSaleChoices :one
SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb)::jsonb FROM(SELECT s.id,s.invoice_number,coalesce(c.name,'Walk-in customer') AS customer_name FROM app.sales s LEFT JOIN app.customers c ON c.id=s.customer_id WHERE s.status='POSTED' AND ($1::text='' OR strpos(lower(s.invoice_number||' '||coalesce(c.name,'')),lower($1))>0) ORDER BY s.sold_at DESC,s.id LIMIT 50)x
`

func (q *Queries) ReturnSaleChoices(ctx context.Context, search string) ([]byte, error) {
	row := q.db.QueryRow(ctx, returnSaleChoices, search)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const returnSaleSource = `-- name: ReturnSaleSource :one
SELECT jsonb_build_object('id',s.id,'invoice_number',s.invoice_number,'balance_mmk',app.sale_balance(s.id)::text,'items',coalesce((SELECT jsonb_agg(jsonb_build_object('sale_item_batch_id',sb.id,'product_name',p.name,'batch_number',b.batch_number,'quantity',sb.quantity::text,'remaining_quantity',(sb.quantity-coalesce((SELECT sum(ri.quantity) FROM app.sales_return_items ri JOIN app.sales_returns r ON r.id=ri.sales_return_id WHERE ri.sale_item_batch_id=sb.id AND r.status='POSTED'),0))::text,'unit',p.base_unit_code,'line_total_mmk',si.total_mmk::text,'line_base_quantity',si.base_quantity::text) ORDER BY si.line_number,b.received_at,b.id) FROM app.sale_items si JOIN app.sale_item_batches sb ON sb.sale_item_id=si.id JOIN app.products p ON p.id=si.product_id JOIN app.batches b ON b.id=sb.batch_id WHERE si.sale_id=s.id),'[]'))::jsonb FROM app.sales s WHERE id=$1::uuid AND status='POSTED'
`

func (q *Queries) ReturnSaleSource(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, returnSaleSource, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const returnsHistory = `-- name: ReturnsHistory :one
WITH filtered AS(SELECT request_id,kind,created_at,payload->>'reason' AS reason,result FROM app.stock_operations WHERE kind IN('returns.sale','returns.purchase') AND (kind='returns.sale' OR $1::boolean)),page AS(SELECT request_id, kind, created_at, reason, result FROM filtered ORDER BY created_at DESC,request_id LIMIT $3::int OFFSET $2::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'returns',coalesce((SELECT jsonb_agg(to_jsonb(page) ORDER BY created_at DESC,request_id) FROM page),'[]'))::jsonb
`

type ReturnsHistoryParams struct {
	PurchaseCosts bool
	PageOffset    int32
	PageSize      int32
}

func (q *Queries) ReturnsHistory(ctx context.Context, arg ReturnsHistoryParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, returnsHistory, arg.PurchaseCosts, arg.PageOffset, arg.PageSize)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const salesReturnPost = `-- name: SalesReturnPost :one
SELECT app.sales_return_post($1::jsonb,$2::uuid)::jsonb
`

type SalesReturnPostParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) SalesReturnPost(ctx context.Context, arg SalesReturnPostParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, salesReturnPost, arg.Data, arg.Actor)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const stockIssue = `-- name: StockIssue :one
SELECT app.stock_issue($1::jsonb,$2::uuid)::jsonb
`

type StockIssueParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) StockIssue(ctx context.Context, arg StockIssueParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, stockIssue, arg.Data, arg.Actor)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const stockIssueChoices = `-- name: StockIssueChoices :one
SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb)::jsonb FROM (
 SELECT i.warehouse_id,i.batch_id,i.version::text AS version,w.name AS warehouse_name,p.id AS product_id,p.name AS product_name,p.sku,p.base_unit_code,b.batch_number,i.available_quantity::text AS available_quantity,i.damaged_quantity::text AS damaged_quantity,u.retail_price_mmk::text AS original_price_mmk
 FROM app.inventory i JOIN app.batches b ON b.id=i.batch_id JOIN app.products p ON p.id=b.product_id JOIN app.warehouses w ON w.id=i.warehouse_id LEFT JOIN app.product_units u ON u.product_id=p.id AND u.unit_code=p.base_unit_code AND u.units_per_pack=1
 WHERE ($1::text='' OR strpos(lower(p.name||' '||p.sku||' '||b.batch_number),lower($1))>0) ORDER BY p.name,b.batch_number,i.warehouse_id LIMIT 100) x
`

func (q *Queries) StockIssueChoices(ctx context.Context, search string) ([]byte, error) {
	row := q.db.QueryRow(ctx, stockIssueChoices, search)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const stockIssuesHistory = `-- name: StockIssuesHistory :one
WITH history AS(
 SELECT d.id,'DAMAGE' AS kind,d.disposition,p.name AS product_name,b.batch_number,w.name AS warehouse_name,d.quantity::text AS quantity,d.reason,d.occurred_at,d.sale_id,d.original_price_mmk::text AS original_price_mmk,d.reduced_price_mmk::text AS reduced_price_mmk,CASE WHEN $1::boolean THEN d.estimated_loss_mmk::text END AS estimated_loss_mmk FROM app.damaged_products d JOIN app.products p ON p.id=d.product_id LEFT JOIN app.batches b ON b.id=d.batch_id LEFT JOIN app.warehouses w ON w.id=d.warehouse_id
 UNION ALL SELECT d.id,'MISSING','MISSING',p.name,b.batch_number,w.name,d.quantity::text,d.reason,d.occurred_at,NULL::uuid,NULL::text,NULL::text,CASE WHEN $1::boolean THEN d.estimated_loss_mmk::text END FROM app.missing_products d JOIN app.products p ON p.id=d.product_id LEFT JOIN app.batches b ON b.id=d.batch_id LEFT JOIN app.warehouses w ON w.id=d.warehouse_id
), filtered AS(SELECT id, kind, disposition, product_name, batch_number, warehouse_name, quantity, reason, occurred_at, sale_id, original_price_mmk, reduced_price_mmk, estimated_loss_mmk FROM history WHERE $2::text='' OR strpos(lower(product_name||' '||coalesce(batch_number,'')||' '||reason),lower($2))>0),page AS(SELECT id, kind, disposition, product_name, batch_number, warehouse_name, quantity, reason, occurred_at, sale_id, original_price_mmk, reduced_price_mmk, estimated_loss_mmk FROM filtered ORDER BY occurred_at DESC,id LIMIT $4::int OFFSET $3::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'records',coalesce((SELECT jsonb_agg(to_jsonb(page) ORDER BY occurred_at DESC,id) FROM page),'[]'))::jsonb
`

type StockIssuesHistoryParams struct {
	Costs      bool
	Search     string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) StockIssuesHistory(ctx context.Context, arg StockIssuesHistoryParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, stockIssuesHistory,
		arg.Costs,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
