// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShipmentWarehouse = `-- name: CreateShipmentWarehouse :one
INSERT INTO app.warehouses(code,name,address) VALUES($1,$2,$3) RETURNING id
`

type CreateShipmentWarehouseParams struct {
	Code    string
	Name    string
	Address pgtype.Text
}

func (q *Queries) CreateShipmentWarehouse(ctx context.Context, arg CreateShipmentWarehouseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createShipmentWarehouse, arg.Code, arg.Name, arg.Address)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getShipment = `-- name: GetShipment :one
SELECT app.shipment_document(s,$1::boolean)::jsonb FROM app.shipments s WHERE id=$2
`

type GetShipmentParams struct {
	Costs bool
	ID    pgtype.UUID
}

func (q *Queries) GetShipment(ctx context.Context, arg GetShipmentParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getShipment, arg.Costs, arg.ID)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const getShipmentExpense = `-- name: GetShipmentExpense :one
SELECT app.shipment_expense_document(e,true)::jsonb FROM app.shipment_expenses e WHERE id=$1 AND shipment_id=$2 FOR UPDATE
`

type GetShipmentExpenseParams struct {
	ID         pgtype.UUID
	ShipmentID pgtype.UUID
}

func (q *Queries) GetShipmentExpense(ctx context.Context, arg GetShipmentExpenseParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getShipmentExpense, arg.ID, arg.ShipmentID)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const getShipmentStage = `-- name: GetShipmentStage :one
SELECT app.stage_document(t,true)::jsonb FROM app.transportation_stages t WHERE id=$1 AND shipment_id=$2 FOR UPDATE
`

type GetShipmentStageParams struct {
	ID         pgtype.UUID
	ShipmentID pgtype.UUID
}

func (q *Queries) GetShipmentStage(ctx context.Context, arg GetShipmentStageParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getShipmentStage, arg.ID, arg.ShipmentID)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const insertShipment = `-- name: InsertShipment :one
INSERT INTO app.shipments(shipment_number,start_location,destination_warehouse_id,expected_arrival_at,created_by,notes,request_id)
SELECT d->>'shipment_number',d->>'start_location',(d->>'destination_warehouse_id')::uuid,NULLIF(d->>'expected_arrival_at','')::timestamptz,$1,NULLIF(d->>'notes',''),(d->>'request_id')::uuid FROM (SELECT $2::jsonb d) x RETURNING id
`

type InsertShipmentParams struct {
	Actor pgtype.UUID
	Data  []byte
}

func (q *Queries) InsertShipment(ctx context.Context, arg InsertShipmentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertShipment, arg.Actor, arg.Data)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertShipmentExpense = `-- name: InsertShipmentExpense :one
INSERT INTO app.shipment_expenses(shipment_id,category,description,currency_code,amount_original,mmk_per_unit,incurred_at,recorded_by,notes,request_id)
SELECT $1,d->>'category',d->>'description',d->>'currency_code',(d->>'amount_original')::numeric,(d->>'mmk_per_unit')::numeric,(d->>'incurred_at')::timestamptz,$2,NULLIF(d->>'notes',''),(d->>'request_id')::uuid FROM (SELECT $3::jsonb d) x RETURNING id
`

type InsertShipmentExpenseParams struct {
	ShipmentID pgtype.UUID
	Actor      pgtype.UUID
	Data       []byte
}

func (q *Queries) InsertShipmentExpense(ctx context.Context, arg InsertShipmentExpenseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertShipmentExpense, arg.ShipmentID, arg.Actor, arg.Data)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertShipmentItem = `-- name: InsertShipmentItem :exec
INSERT INTO app.shipment_items(shipment_id,purchase_item_id,product_id,expected_quantity) VALUES($1,$2,$3,$4)
`

type InsertShipmentItemParams struct {
	ShipmentID       pgtype.UUID
	PurchaseItemID   pgtype.UUID
	ProductID        pgtype.UUID
	ExpectedQuantity pgtype.Numeric
}

func (q *Queries) InsertShipmentItem(ctx context.Context, arg InsertShipmentItemParams) error {
	_, err := q.db.Exec(ctx, insertShipmentItem,
		arg.ShipmentID,
		arg.PurchaseItemID,
		arg.ProductID,
		arg.ExpectedQuantity,
	)
	return err
}

const insertShipmentStage = `-- name: InsertShipmentStage :one
INSERT INTO app.transportation_stages(shipment_id,stage_number,start_location,destination,provider_name,transportation_type,vehicle_information,departed_at,arrived_at,transportation_fee_mmk,loading_fee_mmk,unloading_fee_mmk,other_fee_mmk,notes,request_id)
SELECT $1,(SELECT COALESCE(max(stage_number),0)+1 FROM app.transportation_stages WHERE shipment_id=$1),d->>'start_location',d->>'destination',d->>'provider_name',NULLIF(d->>'transportation_type',''),NULLIF(d->>'vehicle_information',''),NULLIF(d->>'departed_at','')::timestamptz,NULLIF(d->>'arrived_at','')::timestamptz,(d->>'transportation_fee_mmk')::numeric,(d->>'loading_fee_mmk')::numeric,(d->>'unloading_fee_mmk')::numeric,(d->>'other_fee_mmk')::numeric,NULLIF(d->>'notes',''),(d->>'request_id')::uuid FROM (SELECT $2::jsonb d) x RETURNING id
`

type InsertShipmentStageParams struct {
	ShipmentID pgtype.UUID
	Data       []byte
}

func (q *Queries) InsertShipmentStage(ctx context.Context, arg InsertShipmentStageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertShipmentStage, arg.ShipmentID, arg.Data)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listShipments = `-- name: ListShipments :one
WITH filtered AS (SELECT id, shipment_number, start_location, destination_warehouse_id, shipped_at, expected_arrival_at, arrived_at, status, allocation_method, costs_finalized_at, costs_finalized_by, created_by, notes, created_at, updated_at, version, request_id FROM app.shipments WHERE ($2::text='' OR strpos(lower(shipment_number||' '||start_location),lower($2))>0) AND ($3::text='' OR status=$3)), page AS (SELECT id FROM filtered ORDER BY created_at DESC,id LIMIT $5::int OFFSET $4::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'shipments',COALESCE((SELECT jsonb_agg(app.shipment_document(s,$1::boolean) ORDER BY s.created_at DESC,s.id) FROM app.shipments s JOIN page USING(id)),'[]'::jsonb))::jsonb
`

type ListShipmentsParams struct {
	Costs      bool
	Search     string
	Status     string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ListShipments(ctx context.Context, arg ListShipmentsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, listShipments,
		arg.Costs,
		arg.Search,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const lockShipment = `-- name: LockShipment :one
SELECT id,status,version,costs_finalized_at,shipped_at FROM app.shipments WHERE id=$1 FOR UPDATE
`

type LockShipmentRow struct {
	ID               pgtype.UUID
	Status           string
	Version          int64
	CostsFinalizedAt pgtype.Timestamptz
	ShippedAt        pgtype.Timestamptz
}

func (q *Queries) LockShipment(ctx context.Context, id pgtype.UUID) (LockShipmentRow, error) {
	row := q.db.QueryRow(ctx, lockShipment, id)
	var i LockShipmentRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Version,
		&i.CostsFinalizedAt,
		&i.ShippedAt,
	)
	return i, err
}

const lockShipmentPurchaseItem = `-- name: LockShipmentPurchaseItem :one
SELECT i.product_id,i.base_quantity::text AS base_quantity FROM app.purchase_items i JOIN app.purchases p ON p.id=i.purchase_id WHERE i.id=$1 AND p.status='POSTED' FOR UPDATE OF i
`

type LockShipmentPurchaseItemRow struct {
	ProductID    pgtype.UUID
	BaseQuantity string
}

func (q *Queries) LockShipmentPurchaseItem(ctx context.Context, id pgtype.UUID) (LockShipmentPurchaseItemRow, error) {
	row := q.db.QueryRow(ctx, lockShipmentPurchaseItem, id)
	var i LockShipmentPurchaseItemRow
	err := row.Scan(&i.ProductID, &i.BaseQuantity)
	return i, err
}

const lockShipmentWarehouse = `-- name: LockShipmentWarehouse :one
SELECT id FROM app.warehouses WHERE id=$1 AND is_active FOR SHARE
`

func (q *Queries) LockShipmentWarehouse(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockShipmentWarehouse, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const shipmentChildHasPayment = `-- name: ShipmentChildHasPayment :one
SELECT EXISTS(SELECT 1 FROM app.payment_allocations WHERE transportation_stage_id=$1 OR shipment_expense_id=$1)::boolean
`

func (q *Queries) ShipmentChildHasPayment(ctx context.Context, transportationStageID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, shipmentChildHasPayment, transportationStageID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const shipmentExpenses = `-- name: ShipmentExpenses :one
SELECT jsonb_build_object('total',(SELECT count(*) FROM app.shipment_expenses cnt WHERE cnt.shipment_id=$1),'expenses',COALESCE((SELECT jsonb_agg(app.shipment_expense_document(e,$2::boolean) ORDER BY e.created_at,e.id) FROM app.shipment_expenses e JOIN (SELECT z.id FROM app.shipment_expenses z WHERE z.shipment_id=$1 ORDER BY z.created_at,z.id LIMIT $4::int OFFSET $3::int) page USING(id)),'[]'::jsonb))::jsonb
`

type ShipmentExpensesParams struct {
	ShipmentID pgtype.UUID
	Costs      bool
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ShipmentExpenses(ctx context.Context, arg ShipmentExpensesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, shipmentExpenses,
		arg.ShipmentID,
		arg.Costs,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const shipmentHasReceiving = `-- name: ShipmentHasReceiving :one
SELECT EXISTS(SELECT 1 FROM app.goods_receiving WHERE shipment_id=$1 AND status NOT IN ('CANCELLED','REVERSED'))::boolean
`

func (q *Queries) ShipmentHasReceiving(ctx context.Context, shipmentID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, shipmentHasReceiving, shipmentID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const shipmentItems = `-- name: ShipmentItems :one
SELECT COALESCE(jsonb_agg(jsonb_build_object('id',si.id,'purchase_number',p.purchase_number,'supplier_name',s.name,'product_name',COALESCE(i.product_name_snapshot,pr.name),'sku',COALESCE(i.sku_snapshot,pr.sku),'expected_quantity',si.expected_quantity::text,'base_unit_code',pr.base_unit_code) ORDER BY p.purchase_number,i.line_number),'[]'::jsonb)::jsonb FROM app.shipment_items si JOIN app.purchase_items i ON i.id=si.purchase_item_id JOIN app.purchases p ON p.id=i.purchase_id JOIN app.suppliers s ON s.id=p.supplier_id JOIN app.products pr ON pr.id=i.product_id WHERE si.shipment_id=$1
`

func (q *Queries) ShipmentItems(ctx context.Context, shipmentID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, shipmentItems, shipmentID)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const shipmentPurchaseChoices = `-- name: ShipmentPurchaseChoices :one
SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY purchase_number,line_number),'[]'::jsonb)::jsonb FROM (
 SELECT i.id,p.purchase_number,i.line_number,p.supplier_id,s.name AS supplier_name,COALESCE(i.product_name_snapshot,pr.name) AS product_name,COALESCE(i.sku_snapshot,pr.sku) AS sku,i.unit_code,i.quantity::text AS purchased_quantity,i.base_quantity::text AS base_quantity,
 (i.base_quantity-COALESCE((SELECT sum(si.expected_quantity) FROM app.shipment_items si JOIN app.shipments sh ON sh.id=si.shipment_id WHERE si.purchase_item_id=i.id AND sh.status<>'CANCELLED'),0))::text AS available_quantity
 FROM app.purchase_items i JOIN app.purchases p ON p.id=i.purchase_id JOIN app.suppliers s ON s.id=p.supplier_id JOIN app.products pr ON pr.id=i.product_id
 WHERE p.status='POSTED' AND ($1::text='' OR strpos(lower(p.purchase_number||' '||s.name||' '||pr.name),lower($1))>0)
 ORDER BY p.purchased_at DESC,i.line_number LIMIT 50) x
`

func (q *Queries) ShipmentPurchaseChoices(ctx context.Context, search string) ([]byte, error) {
	row := q.db.QueryRow(ctx, shipmentPurchaseChoices, search)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const shipmentReservedQuantity = `-- name: ShipmentReservedQuantity :one
SELECT COALESCE(sum(i.expected_quantity),0)::text FROM app.shipment_items i JOIN app.shipments s ON s.id=i.shipment_id WHERE i.purchase_item_id=$1 AND s.status<>'CANCELLED'
`

func (q *Queries) ShipmentReservedQuantity(ctx context.Context, purchaseItemID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, shipmentReservedQuantity, purchaseItemID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const shipmentStages = `-- name: ShipmentStages :one
SELECT jsonb_build_object('total',(SELECT count(*) FROM app.transportation_stages cnt WHERE cnt.shipment_id=$1),'stages',COALESCE((SELECT jsonb_agg(app.stage_document(t,$2::boolean) ORDER BY t.stage_number) FROM app.transportation_stages t JOIN (SELECT z.id FROM app.transportation_stages z WHERE z.shipment_id=$1 ORDER BY z.stage_number LIMIT $4::int OFFSET $3::int) page USING(id)),'[]'::jsonb))::jsonb
`

type ShipmentStagesParams struct {
	ShipmentID pgtype.UUID
	Costs      bool
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ShipmentStages(ctx context.Context, arg ShipmentStagesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, shipmentStages,
		arg.ShipmentID,
		arg.Costs,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const shipmentWarehouses = `-- name: ShipmentWarehouses :one
SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'code',code,'name',name) ORDER BY name),'[]'::jsonb)::jsonb FROM app.warehouses WHERE is_active
`

func (q *Queries) ShipmentWarehouses(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, shipmentWarehouses)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const touchShipment = `-- name: TouchShipment :exec
UPDATE app.shipments SET version=version+1 WHERE id=$1
`

func (q *Queries) TouchShipment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchShipment, id)
	return err
}

const updateShipmentStage = `-- name: UpdateShipmentStage :execrows
UPDATE app.transportation_stages SET start_location=d->>'start_location',destination=d->>'destination',provider_name=d->>'provider_name',transportation_type=NULLIF(d->>'transportation_type',''),vehicle_information=NULLIF(d->>'vehicle_information',''),departed_at=NULLIF(d->>'departed_at','')::timestamptz,arrived_at=NULLIF(d->>'arrived_at','')::timestamptz,transportation_fee_mmk=(d->>'transportation_fee_mmk')::numeric,loading_fee_mmk=(d->>'loading_fee_mmk')::numeric,unloading_fee_mmk=(d->>'unloading_fee_mmk')::numeric,other_fee_mmk=(d->>'other_fee_mmk')::numeric,notes=NULLIF(d->>'notes','') FROM (SELECT $3::jsonb d) x WHERE id=$1 AND shipment_id=$2
`

type UpdateShipmentStageParams struct {
	ID         pgtype.UUID
	ShipmentID pgtype.UUID
	Data       []byte
}

func (q *Queries) UpdateShipmentStage(ctx context.Context, arg UpdateShipmentStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateShipmentStage, arg.ID, arg.ShipmentID, arg.Data)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateShipmentStatus = `-- name: UpdateShipmentStatus :exec
UPDATE app.shipments SET status=$1,shipped_at=COALESCE(shipped_at,$2::timestamptz),arrived_at=$3::timestamptz WHERE id=$4
`

type UpdateShipmentStatusParams struct {
	Status    string
	ShippedAt pgtype.Timestamptz
	ArrivedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateShipmentStatus,
		arg.Status,
		arg.ShippedAt,
		arg.ArrivedAt,
		arg.ID,
	)
	return err
}

const voidShipmentExpense = `-- name: VoidShipmentExpense :execrows
UPDATE app.shipment_expenses SET voided_at=clock_timestamp(),void_reason=$1 WHERE id=$2 AND shipment_id=$3 AND voided_at IS NULL
`

type VoidShipmentExpenseParams struct {
	Reason     pgtype.Text
	ID         pgtype.UUID
	ShipmentID pgtype.UUID
}

func (q *Queries) VoidShipmentExpense(ctx context.Context, arg VoidShipmentExpenseParams) (int64, error) {
	result, err := q.db.Exec(ctx, voidShipmentExpense, arg.Reason, arg.ID, arg.ShipmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
