// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suppliers.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveSupplier = `-- name: ArchiveSupplier :exec
UPDATE app.suppliers SET is_active=false,archived_at=clock_timestamp() WHERE id=$1
`

func (q *Queries) ArchiveSupplier(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveSupplier, id)
	return err
}

const getSupplier = `-- name: GetSupplier :one
SELECT app.supplier_document(s)::jsonb FROM app.suppliers s WHERE id=$1
`

func (q *Queries) GetSupplier(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSupplier, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const insertSupplier = `-- name: InsertSupplier :one
INSERT INTO app.suppliers(code,name,contact_person,phone,address,country_code,supplier_type,payment_terms,notes,is_active)
SELECT d->>'code',d->>'name',NULLIF(d->>'contact_person',''),NULLIF(d->>'phone',''),NULLIF(d->>'address',''),NULLIF(d->>'country_code',''),NULLIF(d->>'supplier_type',''),NULLIF(d->>'payment_terms',''),NULLIF(d->>'notes',''),(d->>'is_active')::boolean FROM (SELECT $1::jsonb d) t RETURNING id
`

func (q *Queries) InsertSupplier(ctx context.Context, data []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertSupplier, data)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listSuppliers = `-- name: ListSuppliers :one
WITH filtered AS (
 SELECT s.id, s.code, s.name, s.contact_person, s.phone, s.address, s.country_code, s.supplier_type, s.payment_terms, s.notes, s.is_active, s.created_at, s.updated_at, s.archived_at, s.version FROM app.suppliers s WHERE
 (CASE $1::text WHEN 'archived' THEN s.archived_at IS NOT NULL WHEN 'active' THEN s.archived_at IS NULL AND s.is_active WHEN 'inactive' THEN s.archived_at IS NULL AND NOT s.is_active ELSE s.archived_at IS NULL END)
 AND ($2::text='' OR s.country_code=$2)
 AND ($3::text='' OR strpos(lower(s.name),lower($3))>0 OR strpos(lower(s.code),lower($3))>0 OR strpos(lower(COALESCE(s.contact_person,'')),lower($3))>0 OR strpos(COALESCE(s.phone,''),$3)>0)
), page AS (SELECT id, code, name, contact_person, phone, address, country_code, supplier_type, payment_terms, notes, is_active, created_at, updated_at, archived_at, version FROM filtered ORDER BY created_at DESC,id LIMIT $5::int OFFSET $4::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'suppliers',COALESCE((SELECT jsonb_agg(app.supplier_document(s) ORDER BY s.created_at DESC,s.id) FROM app.suppliers s JOIN page f USING(id)),'[]'::jsonb))::jsonb
`

type ListSuppliersParams struct {
	Status     string
	Country    string
	Search     string
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, listSuppliers,
		arg.Status,
		arg.Country,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const lockSupplier = `-- name: LockSupplier :one
SELECT id,version,archived_at FROM app.suppliers WHERE id=$1 FOR UPDATE
`

type LockSupplierRow struct {
	ID         pgtype.UUID
	Version    int64
	ArchivedAt pgtype.Timestamptz
}

func (q *Queries) LockSupplier(ctx context.Context, id pgtype.UUID) (LockSupplierRow, error) {
	row := q.db.QueryRow(ctx, lockSupplier, id)
	var i LockSupplierRow
	err := row.Scan(&i.ID, &i.Version, &i.ArchivedAt)
	return i, err
}

const supplierPurchaseHistory = `-- name: SupplierPurchaseHistory :one
WITH filtered AS (SELECT id, purchase_number, supplier_id, supplier_invoice_number, purchased_at, due_date, currency_code, exchange_rate_id, mmk_per_unit, status, posted_at, created_by, notes, created_at, updated_at FROM app.purchases WHERE supplier_id=$2),
page AS (SELECT id, purchase_number, supplier_id, supplier_invoice_number, purchased_at, due_date, currency_code, exchange_rate_id, mmk_per_unit, status, posted_at, created_by, notes, created_at, updated_at FROM filtered ORDER BY purchased_at DESC,id LIMIT $4::int OFFSET $3::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'can_view_cost',$1::boolean,'purchases',COALESCE((SELECT jsonb_agg(
 jsonb_build_object('id',p.id,'purchase_number',p.purchase_number,'supplier_invoice_number',p.supplier_invoice_number,'purchased_at',p.purchased_at,'due_date',p.due_date,'status',p.status,'currency_code',p.currency_code,'item_count',(SELECT count(*) FROM app.purchase_items i WHERE i.purchase_id=p.id))
 || CASE WHEN $1::boolean THEN jsonb_build_object('total_original',(SELECT COALESCE(sum(i.total_original),0)::text FROM app.purchase_items i WHERE i.purchase_id=p.id)) ELSE '{}'::jsonb END
 ORDER BY p.purchased_at DESC,p.id) FROM page p),'[]'::jsonb))::jsonb
`

type SupplierPurchaseHistoryParams struct {
	ViewCost   bool
	SupplierID pgtype.UUID
	PageOffset int32
	PageSize   int32
}

func (q *Queries) SupplierPurchaseHistory(ctx context.Context, arg SupplierPurchaseHistoryParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, supplierPurchaseHistory,
		arg.ViewCost,
		arg.SupplierID,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const updateSupplier = `-- name: UpdateSupplier :exec
UPDATE app.suppliers SET code=d->>'code',name=d->>'name',contact_person=NULLIF(d->>'contact_person',''),phone=NULLIF(d->>'phone',''),address=NULLIF(d->>'address',''),country_code=NULLIF(d->>'country_code',''),supplier_type=NULLIF(d->>'supplier_type',''),payment_terms=NULLIF(d->>'payment_terms',''),notes=NULLIF(d->>'notes',''),is_active=(d->>'is_active')::boolean FROM (SELECT $2::jsonb d) t WHERE id=$1
`

type UpdateSupplierParams struct {
	ID   pgtype.UUID
	Data []byte
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) error {
	_, err := q.db.Exec(ctx, updateSupplier, arg.ID, arg.Data)
	return err
}
