// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supplier_payments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSupplierPaymentMethod = `-- name: AddSupplierPaymentMethod :exec
INSERT INTO app.supplier_payment_methods(code,name,category) VALUES($1,$2,$3)
`

type AddSupplierPaymentMethodParams struct {
	Code     string
	Name     string
	Category string
}

func (q *Queries) AddSupplierPaymentMethod(ctx context.Context, arg AddSupplierPaymentMethodParams) error {
	_, err := q.db.Exec(ctx, addSupplierPaymentMethod, arg.Code, arg.Name, arg.Category)
	return err
}

const recordSupplierPayment = `-- name: RecordSupplierPayment :one
SELECT app.record_supplier_payment($1::uuid,$2::uuid,$3::jsonb)::uuid
`

type RecordSupplierPaymentParams struct {
	PurchaseID pgtype.UUID
	Actor      pgtype.UUID
	Data       []byte
}

func (q *Queries) RecordSupplierPayment(ctx context.Context, arg RecordSupplierPaymentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, recordSupplierPayment, arg.PurchaseID, arg.Actor, arg.Data)
	var column_1 pgtype.UUID
	err := row.Scan(&column_1)
	return column_1, err
}

const supplierPaymentHistory = `-- name: SupplierPaymentHistory :one
SELECT jsonb_build_object('payments',COALESCE(jsonb_agg(jsonb_build_object('id',p.id,'payment_number',p.payment_number,'amount',p.amount_original::text,'currency_code',p.currency_code,'amount_mmk',p.amount_mmk::text,'method',COALESCE(p.method_name_snapshot,p.method),'bank_account',p.bank_account,'paid_at',p.paid_at,'reference_number',p.reference_number,'notes',p.notes,'status',p.status,'created_at',p.created_at,'created_by',u.display_name) ORDER BY p.paid_at,p.created_at),'[]'::jsonb))::jsonb
FROM app.payments p JOIN app.payment_allocations a ON a.payment_id=p.id JOIN app.users u ON u.id=p.recorded_by WHERE a.purchase_id=$1
`

func (q *Queries) SupplierPaymentHistory(ctx context.Context, purchaseID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, supplierPaymentHistory, purchaseID)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const supplierPaymentMethods = `-- name: SupplierPaymentMethods :one
SELECT COALESCE(jsonb_agg(to_jsonb(m) ORDER BY name),'[]'::jsonb)::jsonb FROM app.supplier_payment_methods m
`

func (q *Queries) SupplierPaymentMethods(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, supplierPaymentMethods)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const supplierPaymentPurchases = `-- name: SupplierPaymentPurchases :one
WITH filtered AS (
 SELECT p.id, p.purchase_number, p.supplier_id, p.supplier_invoice_number, p.purchased_at, p.due_date, p.currency_code, p.exchange_rate_id, p.mmk_per_unit, p.status, p.posted_at, p.created_by, p.notes, p.created_at, p.updated_at, p.request_id, p.request_hash FROM app.purchases p JOIN app.supplier_payables b ON b.purchase_id=p.id JOIN app.suppliers s ON s.id=b.supplier_id
 WHERE ($1::text='' OR strpos(lower(p.purchase_number||' '||s.name),lower($1))>0)
 AND ($2::text='' OR CASE WHEN b.outstanding_original<=0 THEN 'PAID' WHEN b.amount_paid_mmk>0 THEN 'PARTIALLY_PAID' ELSE 'UNPAID' END=$2)
), page AS (SELECT id, purchase_number, supplier_id, supplier_invoice_number, purchased_at, due_date, currency_code, exchange_rate_id, mmk_per_unit, status, posted_at, created_by, notes, created_at, updated_at, request_id, request_hash FROM filtered ORDER BY purchased_at DESC,id LIMIT $4::int OFFSET $3::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'purchases',COALESCE((SELECT jsonb_agg(app.purchase_document(p,true,false) ORDER BY p.purchased_at DESC,p.id) FROM app.purchases p JOIN page f USING(id)),'[]'::jsonb))::jsonb
`

type SupplierPaymentPurchasesParams struct {
	Search        string
	PaymentStatus string
	PageOffset    int32
	PageSize      int32
}

func (q *Queries) SupplierPaymentPurchases(ctx context.Context, arg SupplierPaymentPurchasesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, supplierPaymentPurchases,
		arg.Search,
		arg.PaymentStatus,
		arg.PageOffset,
		arg.PageSize,
	)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
