// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelTransfer = `-- name: CancelTransfer :exec
SELECT app.cancel_transfer($1::jsonb,$2::uuid)
`

type CancelTransferParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) CancelTransfer(ctx context.Context, arg CancelTransferParams) error {
	_, err := q.db.Exec(ctx, cancelTransfer, arg.Data, arg.Actor)
	return err
}

const dispatchTransfer = `-- name: DispatchTransfer :one
SELECT app.dispatch_transfer($1::jsonb,$2::uuid)::uuid
`

type DispatchTransferParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) DispatchTransfer(ctx context.Context, arg DispatchTransferParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, dispatchTransfer, arg.Data, arg.Actor)
	var column_1 pgtype.UUID
	err := row.Scan(&column_1)
	return column_1, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT (jsonb_build_object('id',t.id,'shipment_id',s.id,'transfer_number',t.transfer_number,'from_warehouse_id',t.from_warehouse_id,'to_warehouse_id',t.to_warehouse_id,'from_warehouse',w.name,'status',t.status,'dispatched_at',t.dispatched_at,'received_at',t.received_at,
 'items',coalesce((SELECT jsonb_agg(jsonb_build_object('id',i.id,'batch_id',b.id,'product_name',p.name,'sku',p.sku,'base_unit',p.base_unit_code,'batch_number',b.batch_number,'quantity',i.quantity::text,'received_quantity',i.received_quantity::text,'damaged_quantity',i.damaged_quantity::text,'notes',i.notes,'destination_batch_id',dest.id) || CASE WHEN $1::boolean THEN jsonb_build_object('source_unit_cost_mmk',i.source_unit_cost_mmk::text,'destination_unit_cost_mmk',dest.actual_unit_cost_mmk::text) ELSE '{}'::jsonb END ORDER BY i.id) FROM app.stock_transfer_items i JOIN app.batches b ON b.id=i.batch_id JOIN app.products p ON p.id=b.product_id LEFT JOIN app.batches dest ON dest.transfer_item_id=i.id WHERE i.transfer_id=t.id),'[]')) || CASE WHEN $1::boolean THEN jsonb_build_object('cost_document',t.cost_document) ELSE '{}'::jsonb END)::jsonb
 FROM app.stock_transfers t JOIN app.shipments s ON s.id=t.shipment_id JOIN app.warehouses w ON w.id=t.from_warehouse_id WHERE s.id=$2
`

type GetTransferParams struct {
	Costs      bool
	ShipmentID pgtype.UUID
}

func (q *Queries) GetTransfer(ctx context.Context, arg GetTransferParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTransfer, arg.Costs, arg.ShipmentID)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const receiveTransfer = `-- name: ReceiveTransfer :one
SELECT app.receive_transfer($1::jsonb,$2::uuid)::uuid
`

type ReceiveTransferParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) ReceiveTransfer(ctx context.Context, arg ReceiveTransferParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, receiveTransfer, arg.Data, arg.Actor)
	var column_1 pgtype.UUID
	err := row.Scan(&column_1)
	return column_1, err
}
