// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warehouse_pricing.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const landedWarehousePricesSave = `-- name: LandedWarehousePricesSave :exec
SELECT app.landed_warehouse_prices_save($1::jsonb,$2::uuid)
`

type LandedWarehousePricesSaveParams struct {
	Data  []byte
	Actor pgtype.UUID
}

func (q *Queries) LandedWarehousePricesSave(ctx context.Context, arg LandedWarehousePricesSaveParams) error {
	_, err := q.db.Exec(ctx, landedWarehousePricesSave, arg.Data, arg.Actor)
	return err
}

const warehousePricingCosts = `-- name: WarehousePricingCosts :one
SELECT coalesce(jsonb_agg(jsonb_build_object(
 'shipment_item_id',shipment_item_id,'shipment_number',shipment_number,'shipment_id',shipment_id,'purchase_number',purchase_number,
 'finalized_at',costs_finalized_at,'purchase_cost_mmk',purchase_cost_mmk::text,'cargo_cost_mmk',cargo_cost_mmk::text,
 'additional_cost_mmk',additional_cost_mmk::text,'landed_cost_mmk',landed_cost_mmk::text,'sellable_quantity',sellable_quantity::text
) ORDER BY costs_finalized_at DESC,shipment_item_id),'[]'::jsonb)::jsonb FROM app.warehouse_pricing_costs
WHERE product_id=$1::uuid AND warehouse_id=$2::uuid
`

type WarehousePricingCostsParams struct {
	ProductID   pgtype.UUID
	WarehouseID pgtype.UUID
}

func (q *Queries) WarehousePricingCosts(ctx context.Context, arg WarehousePricingCostsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, warehousePricingCosts, arg.ProductID, arg.WarehouseID)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
