// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUnpaidShipmentStage = `-- name: DeleteUnpaidShipmentStage :execrows
DELETE FROM app.transportation_stages WHERE id=$1 AND shipment_id=$2
`

type DeleteUnpaidShipmentStageParams struct {
	ID         pgtype.UUID
	ShipmentID pgtype.UUID
}

func (q *Queries) DeleteUnpaidShipmentStage(ctx context.Context, arg DeleteUnpaidShipmentStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnpaidShipmentStage, arg.ID, arg.ShipmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getManagedWarehouse = `-- name: GetManagedWarehouse :one
SELECT to_jsonb(w)::jsonb FROM app.warehouses w WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetManagedWarehouse(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getManagedWarehouse, id)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const purchaseWorkflow = `-- name: PurchaseWorkflow :one
SELECT jsonb_build_object(
 'choices',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',i.id,'purchase_number',p.purchase_number,'supplier_name',s.name,'product_name',coalesce(i.product_name_snapshot,pr.name),'sku',coalesce(i.sku_snapshot,pr.sku),'base_unit_code',pr.base_unit_code,'carton_size',(CASE WHEN i.unit_code='CARTON' THEN i.units_per_pack ELSE (SELECT units_per_pack FROM app.product_units WHERE product_id=i.product_id AND unit_code='CARTON') END)::text,'unit_code',i.unit_code,'units_per_pack',i.units_per_pack::text,'quantity',i.quantity::text,'base_quantity',i.base_quantity::text,'available_quantity',(i.base_quantity-COALESCE((SELECT sum(si.expected_quantity) FROM app.shipment_items si JOIN app.shipments sh ON sh.id=si.shipment_id WHERE si.purchase_item_id=i.id AND sh.status<>'CANCELLED'),0))::text)||(SELECT jsonb_build_object('package_type',u.unit_code,'package_size',u.units_per_pack::text) FROM (SELECT i.unit_code,i.units_per_pack, true AS purchased UNION ALL SELECT pu.unit_code,pu.units_per_pack,false FROM app.product_units pu WHERE pu.product_id=i.product_id AND pu.unit_code<>i.unit_code) u ORDER BY (u.units_per_pack>1 AND u.purchased) DESC,u.units_per_pack DESC,u.unit_code LIMIT 1) ORDER BY i.line_number) FROM app.purchase_items i JOIN app.products pr ON pr.id=i.product_id JOIN app.suppliers s ON s.id=p.supplier_id WHERE i.purchase_id=p.id),'[]'::jsonb),
 'shipments',COALESCE((SELECT jsonb_agg(app.shipment_document(sh,$1::boolean) || jsonb_build_object('receipt_id',(SELECT id FROM app.goods_receiving WHERE shipment_id=sh.id AND status='POSTED'),'receipt_number',(SELECT receipt_number FROM app.goods_receiving WHERE shipment_id=sh.id AND status='POSTED')) ORDER BY sh.created_at,sh.id) FROM app.shipments sh WHERE EXISTS(SELECT 1 FROM app.shipment_items si JOIN app.purchase_items pi ON pi.id=si.purchase_item_id WHERE si.shipment_id=sh.id AND pi.purchase_id=p.id)),'[]'::jsonb)
)::jsonb FROM app.purchases p WHERE p.id=$2
`

type PurchaseWorkflowParams struct {
	Costs bool
	ID    pgtype.UUID
}

func (q *Queries) PurchaseWorkflow(ctx context.Context, arg PurchaseWorkflowParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, purchaseWorkflow, arg.Costs, arg.ID)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const reverseUnallocatedPurchase = `-- name: ReverseUnallocatedPurchase :exec
SELECT app.reverse_unallocated_purchase($1::uuid,$2::uuid,$3::text)
`

type ReverseUnallocatedPurchaseParams struct {
	ID     pgtype.UUID
	Actor  pgtype.UUID
	Reason string
}

func (q *Queries) ReverseUnallocatedPurchase(ctx context.Context, arg ReverseUnallocatedPurchaseParams) error {
	_, err := q.db.Exec(ctx, reverseUnallocatedPurchase, arg.ID, arg.Actor, arg.Reason)
	return err
}

const updateManagedWarehouse = `-- name: UpdateManagedWarehouse :exec
UPDATE app.warehouses SET name=d->>'name',address=nullif(d->>'address',''),is_active=(d->>'is_active')::boolean FROM (SELECT $2::jsonb d) x WHERE id=$1
`

type UpdateManagedWarehouseParams struct {
	ID   pgtype.UUID
	Data []byte
}

func (q *Queries) UpdateManagedWarehouse(ctx context.Context, arg UpdateManagedWarehouseParams) error {
	_, err := q.db.Exec(ctx, updateManagedWarehouse, arg.ID, arg.Data)
	return err
}

const updateOpenShipmentDetails = `-- name: UpdateOpenShipmentDetails :exec
UPDATE app.shipments SET start_location=d->>'start_location',destination_warehouse_id=(d->>'destination_warehouse_id')::uuid,expected_arrival_at=nullif(d->>'expected_arrival_at','')::timestamptz,fulfillment=coalesce(d->'fulfillment',fulfillment),notes=nullif(d->>'notes','') FROM (SELECT $2::jsonb d) x WHERE id=$1
`

type UpdateOpenShipmentDetailsParams struct {
	ID   pgtype.UUID
	Data []byte
}

func (q *Queries) UpdateOpenShipmentDetails(ctx context.Context, arg UpdateOpenShipmentDetailsParams) error {
	_, err := q.db.Exec(ctx, updateOpenShipmentDetails, arg.ID, arg.Data)
	return err
}
