import { useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Select,SelectItem } from '@/components/ui/select'
import { PageHeader,FormField,SearchInput,QuantityInput,Modal } from '@/components/shared'
import { requestJSON } from '@/services/api'
import { can,permissions,type CurrentUser } from '@/permissions'
import { amount } from '../purchases/types'
import { Field } from './Fields'
import { iso,type Choice } from './types'
export default function CreateShipment({current}:{current:CurrentUser}) {
 const client=useQueryClient(); const [requestID]=useState(()=>crypto.randomUUID())
 const [number,setNumber]=useState(''); const [origin,setOrigin]=useState(''); const [warehouse,setWarehouse]=useState(''); const [expected,setExpected]=useState(''); const [notes,setNotes]=useState(''); const [search,setSearch]=useState(''); const [rows,setRows]=useState<(Choice&{quantity:string})[]>([])
 const [adding,setAdding]=useState(false); const [code,setCode]=useState(''); const [name,setName]=useState(''); const [address,setAddress]=useState('')
 const warehouses=useQuery({queryKey:['shipment-warehouses'],queryFn:()=>requestJSON<{id:string;name:string}[]>('/shipment-options?kind=warehouses')})
 const choices=useQuery({queryKey:['shipment-choices',search],queryFn:({signal})=>requestJSON<Choice[]>(`/shipment-options?kind=purchases&q=${encodeURIComponent(search)}`,{signal})})
 const createWarehouse=useMutation({mutationFn:()=>requestJSON<{id:string}>('/warehouses',{method:'POST',body:JSON.stringify({code,name,address})}),onSuccess:async w=>{await client.invalidateQueries({queryKey:['shipment-warehouses']});setWarehouse(w.id);setAdding(false)}})
 const create=useMutation({mutationFn:()=>requestJSON<{id:string}>('/shipments',{method:'POST',body:JSON.stringify({request_id:requestID,shipment_number:number,start_location:origin,destination_warehouse_id:warehouse,expected_arrival_at:iso(expected),notes,items:rows.map(r=>({purchase_item_id:r.id,expected_quantity:r.quantity}))})}),onSuccess:s=>window.location.assign(`/shipments/${s.id}`)})
 return <><PageHeader eyebrow="Logistics / New shipment" title="Create shipment" description="Allocate purchased goods and choose their final warehouse." actions={<Button asChild variant="outline"><a href="/shipments">All shipments</a></Button>}/><form className="space-y-5" onSubmit={e=>{e.preventDefault();create.mutate()}}><fieldset disabled={create.isPending} className="panel grid min-w-0 grid-cols-1 gap-5 p-5 sm:grid-cols-2"><Field label="Shipment number" value={number} onChange={setNumber} required maxLength={100}/><Field label="Origin" value={origin} onChange={setOrigin} required/><FormField label="Final warehouse" required>{p=><Select {...p} value={warehouse} onValueChange={setWarehouse}><SelectItem value="">Choose warehouse</SelectItem>{warehouses.data?.map(w=><SelectItem key={w.id} value={w.id}>{w.name}</SelectItem>)}</Select>}</FormField><Field label="Expected arrival" type="datetime-local" value={expected} onChange={setExpected}/><Field label="Notes" value={notes} onChange={setNotes} maxLength={4000}/>{can(current,permissions.settingsManage)&&<Button type="button" variant="outline" onClick={()=>setAdding(true)}>Add warehouse</Button>}</fieldset>
 <section className="panel min-w-0 space-y-4 p-5"><h2 className="text-sm font-semibold">Purchased goods</h2><p className="text-xs text-muted-foreground">Quantities are base units. Only posted purchases are available; cancelled shipments release their allocation.</p><SearchInput label="Find purchased goods" value={search} onValueChange={setSearch} placeholder="Purchase, supplier or product…"/><Select aria-label="Add purchased item" value="" onValueChange={id=>{const c=choices.data?.find(r=>r.id===id);if(c)setRows([...rows,{...c,quantity:c.available_quantity}])}} disabled={rows.length>=100}><SelectItem value="">Choose purchased item</SelectItem>{choices.data?.filter(c=>!rows.some(r=>r.id===c.id)&&!/^0(?:\.0+)?$/.test(c.available_quantity)).map(c=><SelectItem key={c.id} value={c.id}>{c.purchase_number} · {c.product_name} · {amount(c.available_quantity)} available</SelectItem>)}</Select>{rows.map(r=><div key={r.id} className="grid min-w-0 grid-cols-1 items-end gap-3 border-t pt-4 sm:grid-cols-[1fr_10rem_auto]"><div className="min-w-0 text-sm"><p className="break-words font-medium">{r.product_name}</p><p className="text-xs text-muted-foreground">{r.purchase_number} · {r.supplier_name}</p></div><FormField label={`Quantity: ${r.sku}`} required>{p=><QuantityInput {...p} value={r.quantity} onValueChange={quantity=>setRows(rows.map(x=>x.id===r.id?{...x,quantity}:x))}/>}</FormField><Button type="button" variant="ghost" onClick={()=>setRows(rows.filter(x=>x.id!==r.id))}>Remove</Button></div>)}</section>
 {[warehouses.error,choices.error,create.error].filter(Boolean).map((e,i)=><p key={i} role="alert" className="text-sm text-destructive">{e?.message}</p>)}<Button disabled={create.isPending||!warehouse||rows.length===0}>{create.isPending?'Creating…':'Create shipment'}</Button></form>
 <Modal open={adding} onOpenChange={setAdding} title="Add warehouse" busy={createWarehouse.isPending}><form className="space-y-4" onSubmit={e=>{e.preventDefault();createWarehouse.mutate()}}><Field label="Warehouse code" value={code} onChange={setCode} required maxLength={100}/><Field label="Warehouse name" value={name} onChange={setName} required/><Field label="Address" value={address} onChange={setAddress} maxLength={2000}/>{createWarehouse.error&&<p role="alert">{createWarehouse.error.message}</p>}<Button disabled={createWarehouse.isPending}>Save warehouse</Button></form></Modal></>
}
