import { useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Select,SelectItem } from '@/components/ui/select'
import { PageHeader,FormField,SearchInput,QuantityInput,Modal } from '@/components/shared'
import { requestJSON } from '@/services/api'
import { can,permissions,type CurrentUser } from '@/permissions'
import { amount,baseQuantity,packageQuantity } from '../purchases/types'
import { Field } from './Fields'
import { iso,type Choice } from './types'
import { OptionalSection } from '@/components/shared/optional-section'
export default function CreateShipment({current, purchaseID, choices: suppliedChoices, done}:{current:CurrentUser;purchaseID?:string;choices?:Choice[];done?:(id:string)=>void}) {
 const client=useQueryClient(); const [requestID]=useState(()=>crypto.randomUUID())
 const [origin,setOrigin]=useState(''); const [warehouse,setWarehouse]=useState(''); const [expected,setExpected]=useState(''); const [notes,setNotes]=useState(''); const [search,setSearch]=useState(''); const [rows,setRows]=useState<(Choice&{quantity:string;packages?:boolean})[]>(()=>purchaseID?(suppliedChoices||[]).map(c=>({...c,quantity:c.available_quantity})):[])
 const [adding,setAdding]=useState(false);const [editing,setEditing]=useState(''); const [code,setCode]=useState(''); const [name,setName]=useState(''); const [address,setAddress]=useState('')
 const warehouses=useQuery({queryKey:['shipment-warehouses'],queryFn:()=>requestJSON<{id:string;name:string;address:string;code:string}[]>('/shipment-options?kind=warehouses')})
 const choices=useQuery({queryKey:['shipment-choices',search],queryFn:({signal})=>requestJSON<Choice[]>(`/shipment-options?kind=purchases&q=${encodeURIComponent(search)}`,{signal}),enabled:!purchaseID})
 const createWarehouse=useMutation({mutationFn:()=>requestJSON<{id:string}>(editing?`/warehouses/${editing}`:'/warehouses',{method:editing?'PUT':'POST',body:JSON.stringify(editing?{name,address,is_active:true}:{code,name,address})}),onSuccess:async w=>{await client.invalidateQueries({queryKey:['shipment-warehouses']});setWarehouse(editing||w.id);setAdding(false);setEditing('')}})
 const archiveWarehouse=useMutation({mutationFn:()=>requestJSON(`/warehouses/${editing}`,{method:'PUT',body:JSON.stringify({name,address,is_active:false})}),onSuccess:async()=>{await client.invalidateQueries({queryKey:['shipment-warehouses']});setWarehouse('');setAdding(false);setEditing('')}})
 const create=useMutation({mutationFn:()=>requestJSON<{id:string}>('/shipments',{method:'POST',body:JSON.stringify({request_id:requestID,start_location:origin,destination_warehouse_id:warehouse,expected_arrival_at:iso(expected),notes,items:rows.map(r=>({purchase_item_id:r.id,expected_quantity:r.packages?baseQuantity(r.quantity,r.units_per_pack!):r.quantity}))})}),onSuccess:s=>done?done(s.id):window.location.assign(`/shipments/${s.id}`)})
 const availableChoices=suppliedChoices||choices.data
 return <>{!purchaseID && <PageHeader eyebrow="Logistics / New shipment" title="Create shipment" description="Allocate purchased goods and choose their final warehouse." actions={<Button asChild variant="outline"><a href="/shipments">All shipments</a></Button>}/>}<form className="space-y-5" onSubmit={e=>{e.preventDefault();create.mutate()}}><fieldset disabled={create.isPending} className="panel grid min-w-0 grid-cols-1 gap-5 p-5 sm:grid-cols-2"><p className="text-xs text-muted-foreground">Shipment ID is generated automatically.</p><Field label="Origin" value={origin} onChange={setOrigin} required/><FormField label="Final warehouse" required>{p=><Select {...p} value={warehouse} onValueChange={setWarehouse}><SelectItem value="">Choose warehouse</SelectItem>{warehouses.data?.map(w=><SelectItem key={w.id} value={w.id}>{w.name}</SelectItem>)}</Select>}</FormField><OptionalSection title="Set expected arrival"><Field label="Expected arrival" type="datetime-local" value={expected} onChange={setExpected}/></OptionalSection><OptionalSection title="Add shipment notes"><Field label="Notes" value={notes} onChange={setNotes} maxLength={4000}/></OptionalSection>{can(current,permissions.settingsManage)&&<Button type="button" variant="outline" onClick={()=>{setEditing('');setCode('');setName('');setAddress('');setAdding(true)}}>Add warehouse</Button>}{can(current,permissions.settingsManage)&&warehouse&&<Button type="button" variant="outline" onClick={()=>{const w=warehouses.data?.find(w=>w.id===warehouse);if(w){setEditing(w.id);setCode(w.code);setName(w.name);setAddress(w.address||'');setAdding(true)}}}>Manage selected warehouse</Button>}</fieldset>
 <section className="panel min-w-0 space-y-4 p-5"><h2 className="text-sm font-semibold">Purchased goods</h2><p className="text-xs text-muted-foreground">Enter base units or select purchase packages. Only posted purchases are available; cancelled shipments release their allocation.</p><SearchInput label="Find purchased goods" value={search} onValueChange={setSearch} placeholder="Purchase, supplier or product…"/><Select aria-label="Add purchased item" value="" onValueChange={id=>{const c=availableChoices?.find(r=>r.id===id);if(c)setRows([...rows,{...c,quantity:c.available_quantity}])}} disabled={rows.length>=100}><SelectItem value="">Choose purchased item</SelectItem>{availableChoices?.filter(c=>!rows.some(r=>r.id===c.id)&&!/^0(?:\.0+)?$/.test(c.available_quantity)).map(c=><SelectItem key={c.id} value={c.id}>{c.purchase_number} · {c.product_name} · {amount(c.available_quantity)} available</SelectItem>)}</Select>{rows.map(r=><div key={r.id} className="grid min-w-0 grid-cols-1 items-end gap-3 border-t pt-4 sm:grid-cols-[1fr_10rem_auto]"><div className="min-w-0 text-sm"><p className="break-words font-medium">{r.product_name}</p><p className="text-xs text-muted-foreground">{r.purchase_number} · {r.supplier_name}</p></div><div>{r.units_per_pack&&r.unit_code&&r.units_per_pack!=='1.000000'&&<label className="mb-2 flex gap-2 text-xs"><input type="checkbox" checked={!!r.packages} onChange={e=>setRows(rows.map(x=>x.id===r.id?{...x,packages:e.target.checked,quantity:e.target.checked?packageQuantity(x.quantity,x.units_per_pack!):baseQuantity(x.quantity,x.units_per_pack!)}:x))}/>Enter {r.unit_code} packages</label>}<FormField label={`Quantity: ${r.sku}`} required hint={r.packages?`1 ${r.unit_code} = ${amount(r.units_per_pack)} base units`:'Base units'}>{p=><QuantityInput {...p} value={r.quantity} onValueChange={quantity=>setRows(rows.map(x=>x.id===r.id?{...x,quantity}:x))}/>}</FormField>{r.packages&&<p className="mt-1 text-xs">{amount(baseQuantity(r.quantity,r.units_per_pack!))} base units</p>}</div><Button type="button" variant="ghost" onClick={()=>setRows(rows.filter(x=>x.id!==r.id))}>Remove</Button></div>)}</section>
 {[warehouses.error,choices.error,create.error].filter(Boolean).map((e,i)=><p key={i} role="alert" className="text-sm text-destructive">{e?.message}</p>)}<Button disabled={create.isPending||!warehouse||rows.length===0}>{create.isPending?'Creating…':'Create shipment'}</Button></form>
 <Modal open={adding} onOpenChange={setAdding} title={editing?'Manage warehouse':'Add warehouse'} busy={createWarehouse.isPending}><form className="space-y-4" onSubmit={e=>{e.preventDefault();createWarehouse.mutate()}}>{!editing&&<Field label="Warehouse code" value={code} onChange={setCode} required maxLength={100}/>}<Field label="Warehouse name" value={name} onChange={setName} required/><Field label="Address" value={address} onChange={setAddress} maxLength={2000}/>{createWarehouse.error&&<p role="alert">{createWarehouse.error.message}</p>}<Button disabled={createWarehouse.isPending}>Save warehouse</Button>{editing&&<Button type="button" variant="outline" disabled={archiveWarehouse.isPending} onClick={()=>archiveWarehouse.mutate()}>Archive warehouse</Button>}{archiveWarehouse.error&&<p role="alert">{archiveWarehouse.error.message}</p>}</form></Modal></>
}
