import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Select,SelectItem } from '@/components/ui/select'
import { PageHeader,DataTable,FilterBar,SearchInput,StatusBadge,LoadingState,EmptyState,Modal } from '@/components/shared'
import { requestJSON } from '@/services/api'
import { can,permissions,type CurrentUser } from '@/permissions'
import { amount } from '../purchases/types'
import CreateShipment from './CreateShipment'
import ShipmentActions,{type Action} from './ShipmentActions'
import { dateLabel,label,type Shipment,type Stage,type Expense } from './types'
export default function Shipments({current}:{current:CurrentUser}) {
 const id=window.location.pathname.split('/')[2]
 if(id==='new')return <CreateShipment current={current}/>
 return id?<Details id={id} current={current}/>:<List current={current}/>
}
function List({current}:{current:CurrentUser}) {
 const [q,setQ]=useState('');const [status,setStatus]=useState('');const [page,setPage]=useState(1)
 const params=new URLSearchParams({q,status,page:String(page),page_size:'20'})
 const query=useQuery({queryKey:['shipments','list',params.toString()],queryFn:({signal})=>requestJSON<{shipments:Shipment[];total:number}>(`/shipments?${params}`,{signal})})
 return <><PageHeader eyebrow="Logistics / Transportation" title="Shipments" description="Follow purchased goods from their origin to the warehouse." actions={can(current,permissions.shipmentsManage)&&<Button asChild><a href="/shipments/new">Create shipment</a></Button>}/><FilterBar><SearchInput label="Search shipments" value={q} onValueChange={v=>{setQ(v);setPage(1)}} placeholder="Shipment or origin…"/><Select aria-label="Shipment status" value={status} onValueChange={v=>{setStatus(v);setPage(1)}} className="sm:w-48"><SelectItem value="">All statuses</SelectItem>{['PREPARING','IN_TRANSIT','ARRIVED','RECEIVED','CANCELLED'].map(s=><SelectItem key={s} value={s}>{label(s)}</SelectItem>)}</Select></FilterBar><DataTable caption="Shipments" rows={query.data?.shipments||[]} rowKey={s=>s.id} loading={query.isPending} error={query.error?.message} onRetry={()=>void query.refetch()} pagination={{page,pageSize:20,total:query.data?.total||0,onPageChange:setPage}} columns={[
 {id:'number',header:'Shipment',cell:s=><a className="font-medium text-primary" href={`/shipments/${s.id}`}>{s.shipment_number}</a>},
 {id:'route',header:'Origin → Warehouse',cell:s=><span>{s.start_location} → {s.destination_name}</span>},
 {id:'status',header:'Status',cell:s=><StatusBadge>{label(s.status)}</StatusBadge>},
 {id:'eta',header:'Expected arrival',cell:s=>dateLabel(s.expected_arrival_at)},
 {id:'cost',header:'Transport / Expenses (MMK)',cell:s=>s.can_view_cost?<span className="whitespace-nowrap tabular-nums">{amount(s.transport_total_mmk)} / {amount(s.expense_total_mmk)}</span>:'Restricted'},
 ]}/></>
}
function Details({id,current}:{id:string;current:CurrentUser}) {
 const [stagePage,setStagePage]=useState(1);const [expensePage,setExpensePage]=useState(1);const [action,setAction]=useState<Action|null>(null)
 const query=useQuery({queryKey:['shipments',id],queryFn:({signal})=>requestJSON<Shipment>(`/shipments/${id}`,{signal}),retry:false})
 const items=useQuery({queryKey:['shipments',id,'items'],queryFn:()=>requestJSON<{id:string;product_name:string;sku:string;purchase_number:string;supplier_name:string;expected_quantity:string;base_unit_code:string}[]>(`/shipments/${id}/items`)})
 const stages=useQuery({queryKey:['shipments',id,'stages',stagePage],queryFn:()=>requestJSON<{stages:Stage[];total:number}>(`/shipments/${id}/stages?page=${stagePage}&page_size=20`)})
 const expenses=useQuery({queryKey:['shipments',id,'expenses',expensePage],queryFn:()=>requestJSON<{expenses:Expense[];total:number}>(`/shipments/${id}/expenses?page=${expensePage}&page_size=20`)})
 if(query.isPending)return <LoadingState/>
 if(query.error)return <EmptyState title="Unable to load shipment" description={query.error.message} action={<Button onClick={()=>void query.refetch()}>Try again</Button>}/>
 const s=query.data;const open=!s.costs_finalized_at&&!['CANCELLED','RECEIVED'].includes(s.status)
 const costs=open&&s.can_view_cost&&can(current,permissions.transportationManage);const correct=costs&&can(current,permissions.changeTransportCost)
 return <><PageHeader eyebrow="Logistics / Shipment details" title={s.shipment_number} description={`${s.start_location} → ${s.destination_name}`} actions={<Button asChild variant="outline"><a href="/shipments">All shipments</a></Button>}/>
 <section className="panel mb-5 space-y-4 p-5"><div className="flex flex-wrap items-center gap-3"><StatusBadge>{label(s.status)}</StatusBadge>{open&&can(current,permissions.shipmentsManage)&&['PREPARING','IN_TRANSIT'].includes(s.status)&&<><Button size="sm" onClick={()=>setAction({kind:'status',status:s.status==='PREPARING'?'IN_TRANSIT':'ARRIVED'})}>{s.status==='PREPARING'?'Mark in transit':'Mark arrived'}</Button><Button size="sm" variant="outline" onClick={()=>setAction({kind:'status',status:'CANCELLED'})}>Cancel shipment</Button></>}</div><dl className="grid grid-cols-1 gap-4 sm:grid-cols-3">{[['Expected arrival',dateLabel(s.expected_arrival_at)],['Departure',dateLabel(s.shipped_at)],['Warehouse arrival',dateLabel(s.arrived_at)]].map(([k,v])=><div key={k}><dt className="text-xs text-muted-foreground">{k}</dt><dd className="mt-1 text-sm">{v}</dd></div>)}</dl>{s.notes&&<p className="whitespace-pre-wrap break-words text-sm">{s.notes}</p>}{s.can_view_cost&&<div className="grid grid-cols-1 gap-4 border-t pt-4 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Transportation total</p><p data-testid="transport-total" className="mt-1 text-xl font-semibold">{amount(s.transport_total_mmk)} MMK</p></div><div><p className="text-xs text-muted-foreground">Active shipment expenses</p><p data-testid="expense-total" className="mt-1 text-xl font-semibold">{amount(s.expense_total_mmk)} MMK</p></div></div>}</section>
 <h2 className="mb-3 text-sm font-semibold">Shipment goods</h2><DataTable caption="Shipment goods" rows={items.data||[]} rowKey={i=>i.id} loading={items.isPending} error={items.error?.message} onRetry={()=>void items.refetch()} columns={[{id:'product',header:'Product',cell:i=><div>{i.product_name}<p className="text-xs text-muted-foreground">{i.sku}</p></div>},{id:'source',header:'Purchase / Supplier',cell:i=><div>{i.purchase_number}<p className="text-xs text-muted-foreground">{i.supplier_name}</p></div>},{id:'quantity',header:'Expected base quantity',cell:i=>`${amount(i.expected_quantity)} ${i.base_unit_code}`} ]}/>
 <div className="mb-3 mt-6 flex items-center justify-between gap-3"><h2 className="text-sm font-semibold">Transportation timeline</h2>{costs&&<Button size="sm" onClick={()=>setAction({kind:'stage'})}>Add stage</Button>}</div>
 {stages.isPending?<LoadingState/>:stages.error?<p role="alert">{stages.error.message}<Button variant="ghost" onClick={()=>void stages.refetch()}>Retry</Button></p>:<section className="panel p-5"><ol className="space-y-5">{stages.data?.stages.map(t=><li key={t.id} className="relative border-l-2 border-brand-yellow pl-5"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-semibold text-muted-foreground">Stage {t.stage_number}</p><h3 className="mt-1 break-words text-sm font-semibold">{t.start_location} → {t.destination}</h3><p className="mt-1 text-xs">{[t.provider_name,t.transportation_type,t.vehicle_information].filter(Boolean).join(' · ')}</p></div>{correct&&<Button size="sm" variant="outline" onClick={()=>setAction({kind:'stage',stage:t})}>Edit stage {t.stage_number}</Button>}</div><p className="mt-3 text-xs text-muted-foreground">Departure: {dateLabel(t.departed_at)}<br/>Arrival: {dateLabel(t.arrived_at)}</p><div className="mt-3 flex flex-wrap items-center gap-3"><StatusBadge>{label(t.payment_status)}</StatusBadge>{s.can_view_cost&&<strong className="text-sm tabular-nums">{amount(t.total_mmk)} MMK</strong>}</div>{s.can_view_cost&&<p className="mt-2 text-xs text-muted-foreground">Transport {amount(t.transportation_fee_mmk)} · Loading {amount(t.loading_fee_mmk)} · Unloading {amount(t.unloading_fee_mmk)} · Additional {amount(t.other_fee_mmk)} MMK</p>}{t.notes&&<p className="mt-2 break-words text-sm">{t.notes}</p>}</li>)}</ol>{!stages.data?.total?<EmptyState title="No transportation stages" description="Add each leg of the journey as it is arranged."/>:<div className="mt-5 flex items-center justify-end gap-3 border-t pt-4 text-xs"><Button size="sm" variant="outline" disabled={stagePage===1} onClick={()=>setStagePage(stagePage-1)}>Previous stages</Button><span>{stagePage} / {Math.ceil(stages.data.total/20)}</span><Button size="sm" variant="outline" disabled={stagePage*20>=stages.data.total} onClick={()=>setStagePage(stagePage+1)}>Next stages</Button></div>}</section>}
 <div className="mb-3 mt-6 flex items-center justify-between"><h2 className="text-sm font-semibold">Shipment expenses</h2>{costs&&<Button size="sm" onClick={()=>setAction({kind:'expense'})}>Add expense</Button>}</div><DataTable caption="Shipment expenses" rows={expenses.data?.expenses||[]} rowKey={e=>e.id} loading={expenses.isPending} error={expenses.error?.message} onRetry={()=>void expenses.refetch()} pagination={{page:expensePage,pageSize:20,total:expenses.data?.total||0,onPageChange:setExpensePage}} columns={[
 {id:'description',header:'Expense',cell:e=><div className="min-w-40"><p className="font-medium">{e.description}</p><p className="text-xs text-muted-foreground">{e.category} · {dateLabel(e.incurred_at)}</p>{e.notes&&<p className="text-xs">{e.notes}</p>}{e.void_reason&&<p className="text-xs">Void reason: {e.void_reason}</p>}</div>},
 ...(s.can_view_cost?[{id:'amount',header:'Original / MMK',cell:(e:Expense)=><div className="whitespace-nowrap text-xs tabular-nums">{amount(e.amount_original)} {e.currency_code}<p>{amount(e.amount_mmk)} MMK</p><p className="text-muted-foreground">Rate: {amount(e.mmk_per_unit)}</p></div>}]:[]),
 {id:'status',header:'Status',cell:e=><StatusBadge>{e.voided_at?'VOIDED':label(e.payment_status)}</StatusBadge>},
 ...(correct?[{id:'actions',header:'Correction',cell:(e:Expense)=>!e.voided_at&&<Button size="sm" variant="outline" onClick={()=>setAction({kind:'void',id:e.id})}>Void expense</Button>}]:[]),
 ]}/><Modal open={!!action} onOpenChange={v=>{if(!v)setAction(null)}} title={action?.kind==='stage'?(action.stage?'Edit transportation stage':'Add transportation stage'):action?.kind==='expense'?'Add shipment expense':action?.kind==='void'?'Void shipment expense':'Update shipment status'}>{action&&<ShipmentActions s={s} action={action} current={current} done={()=>setAction(null)}/>}</Modal></>
}
