import { transportFee } from './transport-fee'
import { amount } from '../purchases/types'
import { FulfillmentFields, type Fulfillment } from '@/components/shared/fulfillment'
import { OptionalSection } from '@/components/shared/optional-section'
import { useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Select,SelectItem } from '@/components/ui/select'
import { FormField, QuantityInput } from '@/components/shared'
import { requestJSON } from '@/services/api'
import { can,permissions,type CurrentUser } from '@/permissions'
import { Field,Money } from './Fields'
import { iso,localDate,type Shipment,type Stage } from './types'
export type Action = {kind:'details'}|{kind:'delete-stage';stage:Stage}|{kind:'stage';stage?:Stage}|{kind:'expense'}|{kind:'void';id:string}|{kind:'status';status:string}
export default function ShipmentActions({s,action,current,done}:{s:Shipment;action:Action;current:CurrentUser;done:()=>void}) {
 const [fulfillment,setFulfillment]=useState<Fulfillment>(s.fulfillment||{mode:'DELIVERY'})
 const client=useQueryClient(); const old=action.kind==='stage'?action.stage:undefined
 const [requestID]=useState(()=>crypto.randomUUID()); const [version]=useState(s.version)
 const [values,setValues]=useState<Record<string,string>>(():Record<string,string>=>action.kind==='details'?{start_location:s.start_location,destination_warehouse_id:s.destination_warehouse_id,expected_arrival_at:localDate(s.expected_arrival_at),notes:s.notes||''}:action.kind==='stage'?{start_location:old?.start_location||s.last_destination||s.start_location,destination:old?.destination||'',provider_name:old?.provider_name||'',transportation_type:old?.transportation_type||'',vehicle_information:old?.vehicle_information||'',departed_at:localDate(old?.departed_at),arrived_at:localDate(old?.arrived_at),fee_basis:old?.fee_basis||'TOTAL',fee_per_carton_mmk:old?.fee_per_carton_mmk||'',charged_cartons:old?.charged_cartons||s.suggested_cartons||'',transportation_fee_mmk:old?.transportation_fee_mmk||'0',loading_fee_mmk:old?.loading_fee_mmk||'0',unloading_fee_mmk:old?.unloading_fee_mmk||'0',other_fee_mmk:old?.other_fee_mmk||'0',notes:old?.notes||''}:action.kind==='expense'?{category:'',description:'',currency_code:'MMK',amount_original:'',mmk_per_unit:'1',incurred_at:localDate(new Date().toISOString()),notes:''}:action.kind==='void'||action.kind==='delete-stage'?{reason:''}:{shipped_at:localDate(new Date().toISOString()),arrived_at:localDate(new Date().toISOString())})
 const set=(k:string,v:string)=>setValues(p=>({...p,[k]:v}))
 const currencies=useQuery({queryKey:['currencies'],queryFn:()=>requestJSON<{code:string}[]>('/currencies'),enabled:action.kind==='expense'})
 const warehouses=useQuery({queryKey:['shipment-warehouses'],queryFn:()=>requestJSON<{id:string;name:string}[]>('/shipment-options?kind=warehouses'),enabled:action.kind==='details'})
 const mutation=useMutation({mutationFn:()=>{
  let endpoint='',method='POST';let body:Record<string,unknown>={...values,version}
  if(action.kind==='details'){method='PUT';body={...body,fulfillment,expected_arrival_at:iso(values.expected_arrival_at)}}
  if(action.kind==='delete-stage'){endpoint=`stages/${action.stage.id}`;method='DELETE'}
  if(action.kind==='stage'){endpoint=`stages${old?`/${old.id}`:''}`;method=old?'PUT':'POST';body={...body,request_id:requestID,departed_at:iso(values.departed_at),arrived_at:iso(values.arrived_at)}}
  if(action.kind==='expense'){endpoint='expenses';body={...body,request_id:requestID,incurred_at:iso(values.incurred_at)}}
  if(action.kind==='void')endpoint=`expenses/${action.id}/void`
  if(action.kind==='status'){endpoint='status';method='PUT';body={version,status:action.status,shipped_at:action.status==='IN_TRANSIT'?iso(values.shipped_at):'',arrived_at:action.status==='ARRIVED'?iso(values.arrived_at):''}}
  return requestJSON(`/shipments/${s.id}${endpoint?`/${endpoint}`:''}`,{method,body:JSON.stringify(body)})
 },onSuccess:async()=>{await client.invalidateQueries({queryKey:['shipments']});await client.invalidateQueries({queryKey:['purchase-workflow']});done()}})
 const calculated=action.kind==='stage'?transportFee(values):null
 const field=(key:string,title:string,required=false,type='text',maxLength=200)=><Field key={key} label={title} value={values[key]||''} onChange={v=>set(key,v)} required={required} type={type} maxLength={maxLength}/>
 return <form className="space-y-4" onSubmit={e=>{e.preventDefault();if(action.kind!=='stage'||calculated)mutation.mutate()}}><fieldset disabled={mutation.isPending} className="grid min-w-0 grid-cols-1 gap-4">
 {action.kind==='details'&&<><FulfillmentFields inbound value={fulfillment} onChange={setFulfillment}/>{field('start_location','Shipment origin',true)}<FormField label="Destination warehouse" required>{p=><Select {...p} value={values.destination_warehouse_id} onValueChange={v=>set('destination_warehouse_id',v)}><SelectItem value="">Choose warehouse</SelectItem>{warehouses.data?.map(w=><SelectItem key={w.id} value={w.id}>{w.name}</SelectItem>)}</Select>}</FormField>{field('expected_arrival_at','Expected arrival',false,'datetime-local')}{field('notes','Shipment notes',false,'text',4000)}</>}
 {action.kind==='delete-stage'&&<><p className="text-sm">Remove this unpaid stage? Its previous values and your reason will stay in the audit history.</p>{field('reason','Removal reason',true,'text',1000)}</>}
 {action.kind==='stage'&&<>{field('start_location','Stage origin',true)}{field('destination','Destination',true)}{field('provider_name','Provider',true)}<p className="text-xs text-muted-foreground">Cargo terminal receiving the transport payment. This is separate from the merchandise supplier.</p><OptionalSection title="Vehicle & journey details" defaultOpen={!!(old?.vehicle_information||old?.departed_at||old?.arrived_at||old?.transportation_type)}>{field('transportation_type','Transport type',false,'text',100)}{field('vehicle_information','Vehicle information')}<div className="grid grid-cols-1 gap-4 sm:grid-cols-2">{field('departed_at','Stage departure',false,'datetime-local')}{field('arrived_at','Stage arrival',false,'datetime-local')}</div></OptionalSection><FormField label="Transport fee basis" required>{p=><Select {...p} value={values.fee_basis} onValueChange={v=>set('fee_basis',v)}><SelectItem value="TOTAL">Total for shipment (all cartons)</SelectItem><SelectItem value="PER_CARTON">Per carton</SelectItem></Select>}</FormField>
 {values.fee_basis==='PER_CARTON'?<><Money label="Fee per carton (MMK)" value={values.fee_per_carton_mmk} onChange={v=>set('fee_per_carton_mmk',v)}/><FormField label="Cartons charged" required hint={s.suggested_cartons?`Shipment packaging suggests ${amount(s.suggested_cartons)} cartons. Adjust to match the cargo bill, including partial cartons.`:'Enter the carton count from the cargo bill. Not every product has a carton conversion.'}>{p=><QuantityInput {...p} unit="cartons" value={values.charged_cartons} onValueChange={v=>set('charged_cartons',v)}/>}</FormField></>:<><Money label="Transportation fee (MMK)" value={values.transportation_fee_mmk} onChange={v=>set('transportation_fee_mmk',v)}/><p className="text-xs text-muted-foreground">The total fee covers all cartons in this shipment.</p></>}
 <div className="rounded-lg bg-muted p-3 text-sm" aria-live="polite">{calculated?<><p>Transport fee total: <strong>{amount(calculated.transport)} MMK</strong></p><p>Stage total including extra charges: <strong>{amount(calculated.total)} MMK</strong></p></>:<p>Enter a valid fee and, for per-carton billing, a positive carton count.</p>}</div><OptionalSection title="Loading, unloading & additional charges" defaultOpen={!!old&&[old.loading_fee_mmk,old.unloading_fee_mmk,old.other_fee_mmk].some(v=>v&&Number(v)>0)}>{[['loading_fee_mmk','Loading fee (MMK)'],['unloading_fee_mmk','Unloading fee (MMK)'],['other_fee_mmk','Additional charges (MMK)']].map(([k,l])=><Money key={k} label={l} value={values[k]} onChange={v=>set(k,v)}/>)}</OptionalSection><OptionalSection title="Add stage notes" defaultOpen={!!old?.notes}>{field('notes','Stage notes',false,'text',4000)}</OptionalSection><p className="text-xs text-muted-foreground">Payment status follows posted payment allocations. Paid stages cannot be edited here.</p></>}
 {action.kind==='expense'&&<>{field('category','Category',true,'text',100)}{field('description','Description',true,'text',1000)}<FormField label="Expense currency" required>{p=><Select {...p} value={values.currency_code} onValueChange={v=>{set('currency_code',v);set('mmk_per_unit',v==='MMK'?'1':'')}}>{(currencies.data||[{code:'MMK'}]).filter(c=>c.code==='MMK'||can(current,permissions.exchangeRatesManage)).map(c=><SelectItem key={c.code} value={c.code}>{c.code}</SelectItem>)}</Select>}</FormField><Money label="Original amount" value={values.amount_original} onChange={v=>set('amount_original',v)}/><Money label="MMK per currency unit" value={values.mmk_per_unit} onChange={v=>set('mmk_per_unit',v)} rate readOnly={values.currency_code==='MMK'}/>{field('incurred_at','Expense date',true,'datetime-local')}{field('notes','Expense notes',false,'text',4000)}<p className="text-xs text-muted-foreground">The transaction rate is saved permanently. To correct an expense, void it with a reason and add a replacement.</p>{currencies.error&&<p role="alert">{currencies.error.message}</p>}</>}
 {action.kind==='void'&&field('reason','Void reason',true,'text',1000)}
 {action.kind==='status'&&(action.status==='CANCELLED'?<p className="text-sm">Cancel this shipment and release its purchased quantities? Transportation and expense history will be retained.</p>:action.status==='IN_TRANSIT'?field('shipped_at','Shipment departure',true,'datetime-local'):field('arrived_at','Warehouse arrival',true,'datetime-local'))}
 </fieldset>{mutation.error&&<p role="alert" className="text-sm text-destructive">{mutation.error.message} If another user changed this shipment, close this form and reload before retrying.</p>}<Button disabled={mutation.isPending||(action.kind==='stage'&&!calculated)}>{mutation.isPending?'Saving…':'Save changes'}</Button></form>
}
