import { useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Select,SelectItem } from '@/components/ui/select'
import { PageHeader,FormField,QuantityInput,DataTable,Modal,LoadingState } from '@/components/shared'
import { requestJSON,ApiError } from '@/services/api'
import { can,permissions,type CurrentUser } from '@/permissions'
import { amount,quantityDifference } from '../purchases/types'
import type { Stock } from '../receiving/types'
import type { Shipment,Stage,Expense } from '../shipments/types'
import ShipmentActions,{type Action} from '../shipments/ShipmentActions'
type Item={id:string;batch_id:string;product_name:string;sku:string;base_unit:string;batch_number:string;quantity:string;received_quantity:string|null;damaged_quantity:string|null;source_unit_cost_mmk?:string;destination_unit_cost_mmk?:string;destination_batch_id:string|null}
type Transfer={id:string;transfer_number:string;from_warehouse:string;status:string;items:Item[]}
export default function CreateTransfer(){
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[notes,setNotes]=useState(''),[request]=useState(()=>crypto.randomUUID())
 const [lines,setLines]=useState<(Stock&{quantity:string})[]>([])
 const warehouses=useQuery({queryKey:['inventory-warehouses'],queryFn:()=>requestJSON<{id:string;name:string}[]>('/inventory/warehouses')})
 const stock=useQuery({queryKey:['transfer-stock',from,search,page],queryFn:()=>requestJSON<{stock:Stock[];total:number}>(`/inventory?warehouse_id=${from}&q=${encodeURIComponent(search)}&page=${page}&page_size=20`),enabled:!!from})
 const save=useMutation({mutationFn:()=>requestJSON<{id:string}>('/transfers',{method:'POST',body:JSON.stringify({request_id:request,from_warehouse_id:from,to_warehouse_id:to,notes,items:lines.map(l=>({batch_id:l.batch_id,version:l.version,quantity:l.quantity}))})}),onSuccess:r=>window.location.assign(`/shipments/${r.id}`)})
 const locked=save.isPending||(save.error instanceof ApiError&&(save.error.status===0||save.error.status>=500))
 return <><PageHeader eyebrow="Logistics / Warehouse shipment" title="Ship between warehouses" description="Dispatch all or part of available stock. Goods leave the source now and become sellable at the destination after receipt."/><form className="space-y-5" onSubmit={e=>{e.preventDefault();save.mutate()}}><fieldset disabled={locked} className="space-y-5"><div className="panel grid gap-4 p-5 sm:grid-cols-2">{[['From warehouse',from,(v:string)=>{setFrom(v);setLines([]);setPage(1)}],['To warehouse',to,setTo]].map(([label,value,set])=><FormField key={label as string} label={label as string} required>{p=><Select {...p} value={value as string} onValueChange={set as (v:string)=>void}><SelectItem value="">Choose warehouse</SelectItem>{warehouses.data?.map(w=><SelectItem key={w.id} value={w.id} disabled={label==='To warehouse'&&w.id===from}>{w.name}</SelectItem>)}</Select>}</FormField>)}<FormField label="Transfer notes">{p=><input {...p} className="field" value={notes} maxLength={4000} onChange={e=>setNotes(e.target.value)}/>}</FormField></div>
 {from&&<section className="panel space-y-4 p-5"><FormField label="Find source stock">{p=><input {...p} className="field" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Product, SKU or batch"/>}</FormField><DataTable caption="Available source batches" rows={stock.data?.stock||[]} rowKey={r=>r.batch_id} loading={stock.isPending} error={stock.error?.message} pagination={{page,pageSize:20,total:stock.data?.total||0,onPageChange:setPage}} columns={[{id:'product',header:'Product / Batch',cell:r=>`${r.product_name} · ${r.batch_number}`},{id:'available',header:'Available',cell:r=>`${amount(r.available_quantity)} ${r.base_unit}`},{id:'add',header:'Select',cell:r=><Button type="button" variant="outline" disabled={lines.some(l=>l.batch_id===r.batch_id)||/^0(?:\.0+)?$/.test(r.available_quantity)} onClick={()=>setLines([...lines,{...r,quantity:r.available_quantity}])}>Add batch</Button>}]}/></section>}
 <section className="panel space-y-4 p-5"><h2 className="font-semibold">Goods to dispatch</h2>{lines.map(l=><div key={l.batch_id} className="grid gap-3 border-t pt-3 sm:grid-cols-[1fr_12rem_auto]"><p>{l.product_name}<span className="block text-xs text-muted-foreground">{l.batch_number} · {amount(l.available_quantity)} {l.base_unit} available</span></p><FormField label={`Dispatch quantity ${l.sku}`} required>{p=><QuantityInput {...p} unit={l.base_unit} value={l.quantity} onValueChange={v=>setLines(lines.map(x=>x.batch_id===l.batch_id?{...x,quantity:v}:x))}/>}</FormField><Button type="button" variant="ghost" onClick={()=>setLines(lines.filter(x=>x.batch_id!==l.batch_id))}>Remove</Button></div>)}{!lines.length&&<p className="text-sm text-muted-foreground">Choose source batches above.</p>}</section></fieldset>{(save.error||warehouses.error)&&<p role="alert">{save.error?.message||warehouses.error?.message}</p>}<Button disabled={save.isPending||!from||!to||from===to||!lines.length}>{locked&&!save.isPending?'Retry same dispatch':'Dispatch shipment'}</Button></form></>
}
export function TransferDetails({s,current}:{s:Shipment;current:CurrentUser}){
 const client=useQueryClient(),[action,setAction]=useState<Action|null>(null),[receiving,setReceiving]=useState(false),[cancel,setCancel]=useState(false),[reason,setReason]=useState('')
 const transfer=useQuery({queryKey:['transfers',s.id],queryFn:()=>requestJSON<Transfer>(`/transfers/${s.id}`)})
 const stages=useQuery({queryKey:['shipments',s.id,'transfer-stages'],queryFn:()=>requestJSON<{stages:Stage[];total:number}>(`/shipments/${s.id}/stages?page_size=100`)})
 const expenses=useQuery({queryKey:['shipments',s.id,'transfer-expenses'],queryFn:()=>requestJSON<{expenses:Expense[]}>(`/shipments/${s.id}/expenses?page_size=100`)})
 const close=async()=>{await client.invalidateQueries({queryKey:['shipments']});await client.invalidateQueries({queryKey:['transfers']});await client.invalidateQueries({queryKey:['inventory']});setAction(null);setReceiving(false);setCancel(false)}
 const cancellation=useMutation({mutationFn:()=>requestJSON(`/transfers/${s.id}/cancel`,{method:'POST',body:JSON.stringify({version:s.version,reason})}),onSuccess:close})
 if(transfer.isPending)return <LoadingState/>
 if(transfer.error)return <p role="alert">{transfer.error.message}</p>
 const t=transfer.data,open=t.status==='IN_TRANSIT',manage=can(current,'stock_transfers.manage'),costs=open&&s.can_view_cost&&can(current,permissions.transportationManage)
 return <><PageHeader eyebrow="Logistics / Warehouse shipment" title={s.shipment_number} description={`${t.from_warehouse} → ${s.destination_name} · ${t.transfer_number}`} actions={<Button asChild variant="outline"><a href="/shipments">All shipments</a></Button>}/><section className="panel mb-5 space-y-3 p-5"><p className="font-semibold">{t.status.replaceAll('_',' ')}</p><p className="text-sm">Dispatched stock is unavailable at the source. Confirm cargo costs and arrival counts before making stock sellable at the destination.</p><div className="flex flex-wrap gap-3">{open&&manage&&can(current,permissions.receivingManage)&&can(current,permissions.costsFinalize)&&can(current,permissions.financeViewLandedCost)&&can(current,permissions.shipmentsViewCost)&&<Button onClick={()=>setReceiving(true)}>Receive warehouse shipment</Button>}{open&&manage&&<Button variant="outline" onClick={()=>setCancel(true)}>Return all goods to source</Button>}</div>{s.can_view_cost&&<p>Cargo stages: {amount(s.transport_total_mmk)} MMK · Additional costs: {amount(s.expense_total_mmk)} MMK</p>}</section>
 <DataTable caption="Warehouse shipment goods" rows={t.items} rowKey={r=>r.id} columns={[{id:'product',header:'Product / Source batch',cell:r=>`${r.product_name} · ${r.batch_number}`},{id:'sent',header:'Dispatched',cell:r=>`${amount(r.quantity)} ${r.base_unit}`},{id:'received',header:'Received / Damaged',cell:r=>`${amount(r.received_quantity)} / ${amount(r.damaged_quantity)}`},...(can(current,permissions.financeViewLandedCost)?[{id:'cost',header:'Source → Destination unit cost (MMK)',cell:(r:Item)=>`${amount(r.source_unit_cost_mmk)} → ${amount(r.destination_unit_cost_mmk)}`}]:[])]}/>
 <section className="panel mt-5 space-y-3 p-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold">Transportation timeline</h2>{costs&&<Button onClick={()=>setAction({kind:'stage'})}>Add stage</Button>}</div>{stages.error&&<p role="alert">{stages.error.message}</p>}{stages.data?.stages.map(stage=><div key={stage.id} className="space-y-2 border-t pt-3"><p>{stage.start_location} → {stage.destination} · {stage.provider_name}</p>{s.can_view_cost&&<p>{stage.package_type&&`${amount(stage.fee_per_package_mmk)} MMK per ${stage.package_type.toLowerCase()} × ${amount(stage.package_quantity)} packages · `}Total {amount(stage.total_mmk)} MMK</p>}{costs&&can(current,permissions.changeTransportCost)&&<Button variant="outline" onClick={()=>setAction({kind:'stage',stage})}>Edit stage {stage.stage_number}</Button>}</div>)}</section>
 <section className="panel mt-5 space-y-3 p-5"><h2 className="font-semibold">Additional costs</h2>{costs&&<Button variant="outline" onClick={()=>setAction({kind:'expense'})}>Add expense</Button>}{expenses.error&&<p role="alert">{expenses.error.message}</p>}{expenses.data?.expenses.map(e=><p key={e.id}>{e.description} {s.can_view_cost&&`· ${amount(e.amount_mmk)} MMK`}{e.voided_at?' · Voided':''}</p>)}<p className="text-xs text-muted-foreground">Cargo-terminal payments remain linked in the Payment centre.</p></section>
 {action&&<Modal open onOpenChange={v=>{if(!v)setAction(null)}} title={action.kind==='stage'?'Transportation stage':'Shipment cost'}><ShipmentActions key={JSON.stringify(action)} s={s} action={action} current={current} done={()=>void close()}/></Modal>}
 {receiving&&<ReceiveTransfer s={s} transfer={t} close={()=>setReceiving(false)} done={()=>void close()}/>}
 {cancel&&<Modal open onOpenChange={v=>{if(!v&&!cancellation.isPending)setCancel(false)}} title="Confirm goods returned to source" busy={cancellation.isPending}><form className="space-y-4" onSubmit={e=>{e.preventDefault();cancellation.mutate()}}><p>Confirm all dispatched goods have physically returned. This restores source stock through reversal movements. Cargo charges and payment history remain recorded.</p><FormField label="Return reason" required>{p=><input {...p} className="field" value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/>}</FormField>{cancellation.error&&<p role="alert">{cancellation.error.message}</p>}<Button disabled={cancellation.isPending}>Confirm return and cancel shipment</Button></form></Modal>}</>
}
function ReceiveTransfer({s,transfer,close,done}:{s:Shipment;transfer:Transfer;close:()=>void;done:()=>void}){
 const [rows,setRows]=useState(()=>transfer.items.map(i=>({...i,received_quantity:i.quantity,damaged_quantity:'0',notes:''})))
 const [version]=useState(s.version)
 const save=useMutation({mutationFn:()=>requestJSON(`/transfers/${s.id}/receive`,{method:'POST',body:JSON.stringify({version,items:rows.map(i=>({id:i.id,received_quantity:i.received_quantity,damaged_quantity:i.damaged_quantity,notes:i.notes}))})}),onSuccess:done})
 const uncertain=save.error instanceof ApiError&&(save.error.status===0||save.error.status>=500),locked=save.isPending||uncertain
 return <Modal open onOpenChange={v=>{if(!v&&!locked)close()}} title="Receive warehouse shipment" size="wide" busy={locked}><form className="space-y-4" onSubmit={e=>{e.preventDefault();save.mutate()}}><p className="text-sm">Cargo {amount(s.transport_total_mmk)} MMK + additional costs {amount(s.expense_total_mmk)} MMK will be allocated by dispatched base quantity and added to the carried batch costs. Sellable stock = received − damaged. Confirm all costs before posting; the resulting costs are immutable.</p><fieldset disabled={locked} className="space-y-4">{rows.map(i=><div key={i.id} className="space-y-3 rounded-xl border p-4"><p>{i.product_name} · {amount(i.quantity)} {i.base_unit} dispatched</p>{[['received_quantity','Received quantity'],['damaged_quantity','Damaged quantity'],['notes','Discrepancy notes']].map(([key,label])=><FormField key={key} label={`${label} ${i.sku}`} required={key!=='notes'}>{p=>key==='notes'?<input {...p} className="field" value={i.notes} maxLength={1000} onChange={e=>setRows(rows.map(r=>r.id===i.id?{...r,notes:e.target.value}:r))}/>:<QuantityInput {...p} unit={i.base_unit} value={i[key as 'received_quantity'|'damaged_quantity']} onValueChange={v=>setRows(rows.map(r=>r.id===i.id?{...r,[key]:v}:r))}/>}</FormField>)}<p className="text-sm">Sellable: {amount(quantityDifference(i.received_quantity,i.damaged_quantity))} {i.base_unit} · Missing: {amount(quantityDifference(i.quantity,i.received_quantity))} {i.base_unit}</p></div>)}</fieldset>{save.error&&<p role="alert">{save.error.message}</p>}<Button disabled={save.isPending}>{uncertain?'Retry same receipt':'Confirm receipt and landed costs'}</Button></form></Modal>
}
