package reports

var definitions = []Definition{
	{
		ID:          "sales",
		Title:       "Sales Report",
		Description: "Posted sales and return credits by event date. Credit sales count as revenue; collections do not count twice.",
		Columns: []Column{
			{Key: "occurred_at", Label: "Date", Kind: "datetime"},
			{Key: "reference", Label: "Reference", Kind: "text"},
			{Key: "event_type", Label: "Type", Kind: "text"},
			{Key: "customer", Label: "Customer", Kind: "text"},
			{Key: "pricing_mode", Label: "Mode", Kind: "text"},
			{Key: "revenue_mmk", Label: "Net revenue", Kind: "money"},
		},
		Metrics: []Column{
			{Key: "revenue_mmk", Label: "Net sales", Kind: "money"},
		},
	},
	{
		ID:          "purchases",
		Title:       "Purchase Report",
		Description: "Posted purchases, supplier returns and purchase reversals by event date, at stored transaction rates. Original amounts must be read with their currency.",
		Columns: []Column{
			{Key: "occurred_at", Label: "Date", Kind: "datetime"},
			{Key: "reference", Label: "Reference", Kind: "text"},
			{Key: "event_type", Label: "Type", Kind: "text"},
			{Key: "supplier", Label: "Supplier", Kind: "text"},
			{Key: "currency_code", Label: "Currency", Kind: "text"},
			{Key: "mmk_per_unit", Label: "Stored rate", Kind: "decimal"},
			{Key: "amount_original", Label: "Original amount", Kind: "decimal"},
			{Key: "amount_mmk", Label: "Net purchase", Kind: "money"},
		},
		Metrics: []Column{
			{Key: "amount_mmk", Label: "Net purchases", Kind: "money"},
		},
	},
	{
		ID:          "profit-loss",
		Title:       "Profit & Loss",
		Description: "Accrual sales less returns, historical landed costs and net operating expenses. Incomplete costs withhold profit.",
		Columns: []Column{
			{Key: "sales_mmk", Label: "Posted sales", Kind: "money"},
			{Key: "returns_mmk", Label: "Returns", Kind: "money"},
			{Key: "revenue_mmk", Label: "Net sales", Kind: "money"},
			{Key: "cogs_mmk", Label: "Cost of goods", Kind: "money"},
			{Key: "gross_profit_mmk", Label: "Gross profit", Kind: "money"},
			{Key: "expenses_mmk", Label: "Expenses", Kind: "money"},
			{Key: "net_profit_mmk", Label: "Net profit", Kind: "money"},
			{Key: "incomplete_cost_sales", Label: "Incomplete sales", Kind: "decimal"},
		},
		Metrics: []Column{
			{Key: "revenue_mmk", Label: "Net sales", Kind: "money"},
			{Key: "gross_profit_mmk", Label: "Gross profit", Kind: "money"},
			{Key: "expenses_mmk", Label: "Operating expenses", Kind: "money"},
			{Key: "net_profit_mmk", Label: "Net profit", Kind: "money"},
		},
	},
	{
		ID:          "product-profitability",
		Title:       "Product Profitability",
		Description: "Net quantities and revenue after returns, with recorded batch costs. Product profit is gross profit before business expenses.",
		Columns: []Column{
			{Key: "sku", Label: "SKU", Kind: "text"},
			{Key: "product", Label: "Product", Kind: "text"},
			{Key: "unit", Label: "Unit", Kind: "text"},
			{Key: "quantity", Label: "Net quantity", Kind: "decimal"},
			{Key: "revenue_mmk", Label: "Net sales", Kind: "money"},
			{Key: "cogs_mmk", Label: "Landed cost", Kind: "money"},
			{Key: "gross_profit_mmk", Label: "Gross profit", Kind: "money"},
			{Key: "incomplete_cost_lines", Label: "Incomplete lines", Kind: "decimal"},
		},
		Metrics: []Column{
			{Key: "revenue_mmk", Label: "Net sales", Kind: "money"},
			{Key: "gross_profit_mmk", Label: "Gross profit", Kind: "money"},
			{Key: "incomplete_cost_lines", Label: "Incomplete cost lines", Kind: "decimal"},
		},
	},
	{
		ID:          "transportation",
		Title:       "Transportation Cost",
		Description: "Stages by departure date, or creation date when departure is unset. Cancelled shipments are excluded; unfinalized costs are provisional.",
		Columns: []Column{
			{Key: "occurred_at", Label: "Date", Kind: "datetime"},
			{Key: "shipment_number", Label: "Shipment", Kind: "text"},
			{Key: "stage_number", Label: "Stage", Kind: "decimal"},
			{Key: "provider_name", Label: "Provider", Kind: "text"},
			{Key: "start_location", Label: "From", Kind: "text"},
			{Key: "destination", Label: "To", Kind: "text"},
			{Key: "cost_status", Label: "Cost status", Kind: "text"},
			{Key: "transportation_fee_mmk", Label: "Transport", Kind: "money"},
			{Key: "loading_fee_mmk", Label: "Loading", Kind: "money"},
			{Key: "unloading_fee_mmk", Label: "Unloading", Kind: "money"},
			{Key: "other_fee_mmk", Label: "Other", Kind: "money"},
			{Key: "total_mmk", Label: "Total", Kind: "money"},
		},
		Metrics: []Column{
			{Key: "transportation_fee_mmk", Label: "Transport", Kind: "money"},
			{Key: "loading_fee_mmk", Label: "Loading", Kind: "money"},
			{Key: "unloading_fee_mmk", Label: "Unloading", Kind: "money"},
			{Key: "other_fee_mmk", Label: "Other", Kind: "money"},
			{Key: "total_mmk", Label: "Total", Kind: "money"},
		},
	},
	{
		ID:          "shipments",
		Title:       "Shipment Report",
		Description: "Shipments created within the period, with their current lifecycle status and costing status. Cancelled records remain visible.",
		Columns: []Column{
			{Key: "occurred_at", Label: "Created", Kind: "datetime"},
			{Key: "shipment_number", Label: "Shipment", Kind: "text"},
			{Key: "start_location", Label: "From", Kind: "text"},
			{Key: "destination", Label: "Warehouse", Kind: "text"},
			{Key: "status", Label: "Status", Kind: "text"},
			{Key: "shipped_at", Label: "Shipped", Kind: "datetime"},
			{Key: "arrived_at", Label: "Arrived", Kind: "datetime"},
			{Key: "product_lines", Label: "Product lines", Kind: "decimal"},
			{Key: "stages", Label: "Stages", Kind: "decimal"},
			{Key: "cost_status", Label: "Cost status", Kind: "text"},
		},
		Metrics: []Column{
			{Key: "shipments", Label: "Shipments", Kind: "decimal"},
			{Key: "received", Label: "Received", Kind: "decimal"},
			{Key: "in_transit", Label: "In transit", Kind: "decimal"},
		},
	},
	{
		ID:          "inventory",
		Title:       "Inventory Report",
		Description: "Opening and closing stock reconstructed from immutable movements. Available means sellable minus reserved; expired stock is still included. Quantities use each product’s base unit.",
		Columns: []Column{
			{Key: "sku", Label: "SKU", Kind: "text"},
			{Key: "product", Label: "Product", Kind: "text"},
			{Key: "unit", Label: "Unit", Kind: "text"},
			{Key: "batch_number", Label: "Batch", Kind: "text"},
			{Key: "warehouse", Label: "Warehouse", Kind: "text"},
			{Key: "expires_on", Label: "Expiry", Kind: "date"},
			{Key: "opening_sellable", Label: "Opening sellable", Kind: "decimal"},
			{Key: "period_change", Label: "Period change", Kind: "decimal"},
			{Key: "closing_sellable", Label: "Closing sellable", Kind: "decimal"},
			{Key: "closing_reserved", Label: "Reserved", Kind: "decimal"},
			{Key: "closing_damaged", Label: "Damaged", Kind: "decimal"},
			{Key: "closing_available", Label: "Available", Kind: "decimal"},
		},
		Metrics: []Column{
			{Key: "stock_positions", Label: "Stock positions", Kind: "decimal"},
		},
	},
	{
		ID:          "stock-movements",
		Title:       "Stock Movement Report",
		Description: "Immutable stock movements within the period. Signed quantities retain their base units; reservations do not change physical stock.",
		Columns: []Column{
			{Key: "occurred_at", Label: "Date", Kind: "datetime"},
			{Key: "product", Label: "Product", Kind: "text"},
			{Key: "unit", Label: "Unit", Kind: "text"},
			{Key: "batch_number", Label: "Batch", Kind: "text"},
			{Key: "warehouse", Label: "Warehouse", Kind: "text"},
			{Key: "movement_type", Label: "Movement", Kind: "text"},
			{Key: "sellable_delta", Label: "Sellable delta", Kind: "decimal"},
			{Key: "reserved_delta", Label: "Reserved delta", Kind: "decimal"},
			{Key: "damaged_delta", Label: "Damaged delta", Kind: "decimal"},
			{Key: "reason", Label: "Reason", Kind: "text"},
			{Key: "recorded_by", Label: "Recorded by", Kind: "text"},
		},
		Metrics: []Column{
			{Key: "movements", Label: "Movements", Kind: "decimal"},
		},
	},
	{
		ID:          "damage",
		Title:       "Damage Report",
		Description: "Receiving, return and stock damage activity by event date. Repeated lifecycle events are separate; loss estimates are not additional operating expenses.",
		Columns: []Column{
			{Key: "occurred_at", Label: "Date", Kind: "datetime"},
			{Key: "product", Label: "Product", Kind: "text"},
			{Key: "unit", Label: "Unit", Kind: "text"},
			{Key: "batch_number", Label: "Batch", Kind: "text"},
			{Key: "warehouse", Label: "Warehouse", Kind: "text"},
			{Key: "quantity", Label: "Quantity", Kind: "decimal"},
			{Key: "source", Label: "Source", Kind: "text"},
			{Key: "disposition", Label: "Disposition", Kind: "text"},
			{Key: "estimated_loss_mmk", Label: "Estimated loss", Kind: "money"},
			{Key: "reason", Label: "Reason", Kind: "text"},
		},
		Metrics: []Column{
			{Key: "estimated_loss_mmk", Label: "Estimated loss", Kind: "money"},
		},
	},
	{
		ID:          "missing",
		Title:       "Missing Product Report",
		Description: "Receiving shortages and missing-stock events by occurrence date. Landed-cost loss estimates are separate from operating expenses; incomplete costs are withheld.",
		Columns: []Column{
			{Key: "occurred_at", Label: "Date", Kind: "datetime"},
			{Key: "product", Label: "Product", Kind: "text"},
			{Key: "unit", Label: "Unit", Kind: "text"},
			{Key: "batch_number", Label: "Batch", Kind: "text"},
			{Key: "warehouse", Label: "Warehouse", Kind: "text"},
			{Key: "quantity", Label: "Quantity", Kind: "decimal"},
			{Key: "source", Label: "Source", Kind: "text"},
			{Key: "estimated_loss_mmk", Label: "Estimated loss", Kind: "money"},
			{Key: "reason", Label: "Reason", Kind: "text"},
		},
		Metrics: []Column{
			{Key: "estimated_loss_mmk", Label: "Estimated loss", Kind: "money"},
		},
	},
	{
		ID:          "customer-debt",
		Title:       "Customer Debt",
		Description: "Outstanding invoices at the selected end date, including older opening invoices. Payments, returns and refunds after that date are excluded. Credits on another invoice do not cancel this debt.",
		Columns: []Column{
			{Key: "occurred_at", Label: "Invoice date", Kind: "datetime"},
			{Key: "reference", Label: "Invoice", Kind: "text"},
			{Key: "party", Label: "Account", Kind: "text"},
			{Key: "invoice_period", Label: "Invoice period", Kind: "text"},
			{Key: "due_date", Label: "Due", Kind: "date"},
			{Key: "total_mmk", Label: "Invoice total", Kind: "money"},
			{Key: "paid_mmk", Label: "Paid", Kind: "money"},
			{Key: "credits_mmk", Label: "Credits", Kind: "money"},
			{Key: "refunds_mmk", Label: "Refunds", Kind: "money"},
			{Key: "outstanding_mmk", Label: "Outstanding", Kind: "money"},
			{Key: "payment_status", Label: "Status", Kind: "text"},
		},
		Metrics: []Column{
			{Key: "outstanding_mmk", Label: "Outstanding", Kind: "money"},
		},
	},
	{
		ID:          "supplier-payables",
		Title:       "Supplier Payables",
		Description: "Outstanding invoices at the selected end date, including older opening invoices. Payments, returns and refunds after that date are excluded. Credits on another invoice do not cancel this debt.",
		Columns: []Column{
			{Key: "occurred_at", Label: "Invoice date", Kind: "datetime"},
			{Key: "reference", Label: "Invoice", Kind: "text"},
			{Key: "party", Label: "Account", Kind: "text"},
			{Key: "invoice_period", Label: "Invoice period", Kind: "text"},
			{Key: "due_date", Label: "Due", Kind: "date"},
			{Key: "total_mmk", Label: "Invoice total", Kind: "money"},
			{Key: "paid_mmk", Label: "Paid", Kind: "money"},
			{Key: "credits_mmk", Label: "Credits", Kind: "money"},
			{Key: "refunds_mmk", Label: "Refunds", Kind: "money"},
			{Key: "outstanding_mmk", Label: "Outstanding", Kind: "money"},
			{Key: "payment_status", Label: "Status", Kind: "text"},
		},
		Metrics: []Column{
			{Key: "outstanding_mmk", Label: "Outstanding", Kind: "money"},
		},
	},
	{
		ID:          "expenses",
		Title:       "Expense Report",
		Description: "Operating expenses and immutable reversal offsets by their own event dates. Original entries remain visible, with reversals shown as negative amounts.",
		Columns: []Column{
			{Key: "occurred_at", Label: "Date", Kind: "datetime"},
			{Key: "category", Label: "Category", Kind: "text"},
			{Key: "description", Label: "Description", Kind: "text"},
			{Key: "event_type", Label: "Type", Kind: "text"},
			{Key: "amount_mmk", Label: "Net expense", Kind: "money"},
		},
		Metrics: []Column{
			{Key: "amount_mmk", Label: "Net expenses", Kind: "money"},
		},
	},
	{
		ID:          "currency-purchases",
		Title:       "Currency Purchase Report",
		Description: "Purchases less supplier returns and purchase reversals by currency. MMK uses each recorded transaction rate. Original amounts are never combined across currencies.",
		Columns: []Column{
			{Key: "currency_code", Label: "Currency", Kind: "text"},
			{Key: "event_count", Label: "Events", Kind: "decimal"},
			{Key: "purchases_original", Label: "Purchased original", Kind: "decimal"},
			{Key: "returns_original", Label: "Returned original", Kind: "decimal"},
			{Key: "reversals_original", Label: "Reversed original", Kind: "decimal"},
			{Key: "net_original", Label: "Net original", Kind: "decimal"},
			{Key: "amount_mmk", Label: "Net MMK", Kind: "money"},
		},
		Metrics: []Column{
			{Key: "amount_mmk", Label: "Net purchases", Kind: "money"},
		},
	},
}
