-- name: TransportPaymentPost :one
SELECT app.transport_payment(sqlc.arg(data)::jsonb,sqlc.arg(actor)::uuid)::uuid;
-- name: TransportPaymentList :one
WITH filtered AS(SELECT id,kind,shipment_id,shipment_number,shipment_status,reference,payee,currency_code,total::text,paid::text,(total-paid)::text AS remaining FROM app.transport_balances WHERE (sqlc.arg(search)::text='' OR strpos(lower(shipment_number||' '||reference||' '||payee),lower(sqlc.arg(search)))>0) AND (sqlc.arg(status)::text='' OR CASE WHEN paid>=total THEN 'PAID' WHEN paid>0 THEN 'PARTIALLY_PAID' ELSE 'UNPAID' END=sqlc.arg(status))), page AS(SELECT * FROM filtered ORDER BY shipment_number DESC,id LIMIT sqlc.arg(page_size)::int OFFSET sqlc.arg(page_offset)::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'records',coalesce((SELECT jsonb_agg(to_jsonb(page)) FROM page),'[]'))::jsonb;
-- name: TransportPaymentHistory :one
SELECT coalesce(jsonb_agg(jsonb_build_object('id',p.id,'payment_number',p.payment_number,'amount',p.amount_original::text,'currency_code',p.currency_code,'method',coalesce(p.method_name_snapshot,p.method),'paid_at',p.paid_at,'reference_number',p.reference_number,'bank_account',p.bank_account,'notes',p.notes,'created_by',u.display_name) ORDER BY p.paid_at,p.id),'[]')::jsonb FROM app.payments p JOIN app.payment_allocations a ON a.payment_id=p.id JOIN app.users u ON u.id=p.recorded_by WHERE a.transportation_stage_id=sqlc.arg(id)::uuid OR a.shipment_expense_id=sqlc.arg(id)::uuid;
-- name: CustomerPaymentList :one
WITH filtered AS(SELECT s.id,s.customer_id,c.name AS customer_name,s.invoice_number,d.total_mmk::text AS total_mmk,d.amount_paid_mmk::text AS amount_paid_mmk,d.outstanding_mmk::text AS outstanding_mmk,d.payment_status FROM app.sales s JOIN app.customer_debts d ON d.sale_id=s.id JOIN app.customers c ON c.id=s.customer_id WHERE (sqlc.arg(search)::text='' OR strpos(lower(s.invoice_number||' '||c.name),lower(sqlc.arg(search)))>0) AND (sqlc.arg(status)::text='' OR d.payment_status=sqlc.arg(status))),page AS(SELECT * FROM filtered ORDER BY invoice_number DESC,id LIMIT sqlc.arg(page_size)::int OFFSET sqlc.arg(page_offset)::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM filtered),'invoices',coalesce((SELECT jsonb_agg(to_jsonb(page)) FROM page),'[]'))::jsonb;
