-- name: ShipmentJourneySources :one
SELECT coalesce(jsonb_agg(jsonb_build_object('amount',pi.total_original::text,'currency',p.currency_code,'rate',p.mmk_per_unit::text,'reference',p.purchase_number,'quantity',pi.base_quantity::text,'allocated_quantity',si.expected_quantity::text) ORDER BY p.purchase_number,pi.line_number),'[]'::jsonb)::jsonb FROM app.shipment_items si JOIN app.purchase_items pi ON pi.id=si.purchase_item_id JOIN app.purchases p ON p.id=pi.purchase_id WHERE si.shipment_id=$1;
-- name: CostJourneys :one
WITH matching AS (
 SELECT si.*,coalesce(pi.product_name_snapshot,pr.name) AS product_name,s.shipment_number,s.costs_finalized_at,pi.total_original,pi.base_quantity,p.currency_code,p.mmk_per_unit,p.purchase_number
 FROM app.shipment_items si JOIN app.shipments s ON s.id=si.shipment_id JOIN app.shipment_costings sc ON sc.shipment_id=s.id JOIN app.purchase_items pi ON pi.id=si.purchase_item_id JOIN app.purchases p ON p.id=pi.purchase_id JOIN app.products pr ON pr.id=si.product_id
 WHERE (sqlc.narg(product_id)::uuid IS NULL OR si.product_id=sqlc.narg(product_id)) AND (sqlc.narg(purchase_id)::uuid IS NULL OR pi.purchase_id=sqlc.narg(purchase_id))
), page AS (SELECT * FROM matching ORDER BY costs_finalized_at DESC,id LIMIT sqlc.arg(page_size)::int OFFSET sqlc.arg(page_offset)::int)
SELECT jsonb_build_object('total',(SELECT count(*) FROM matching),'journeys',coalesce((SELECT jsonb_agg(jsonb_build_object('id',id,'product_name',product_name,'shipment_id',shipment_id,'shipment_number',shipment_number,'purchase_mmk',purchase_cost_mmk::text,'transport_mmk',allocated_transport_mmk::text,'expense_mmk',allocated_expense_mmk::text,'landed_mmk',landed_cost_mmk::text,'sellable_quantity',costing_sellable_quantity::text,'unit_cost_mmk',actual_unit_cost_mmk::text,'sources',jsonb_build_array(jsonb_build_object('amount',total_original::text,'currency',currency_code,'rate',mmk_per_unit::text,'reference',purchase_number,'quantity',base_quantity::text,'allocated_quantity',expected_quantity::text))) ORDER BY costs_finalized_at DESC,id) FROM page),'[]'::jsonb))::jsonb;
