import { useState } from 'react'
import { useQuery,useMutation,useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Select,SelectItem } from '@/components/ui/select'
import { PageHeader,DataTable,SearchInput,Modal } from '@/components/shared'
import { Field } from '../shipments/Fields'
import { requestJSON,ApiError } from '@/services/api'
import { amount } from '../purchases/types'
import { fixed,scaled } from '../pos/cart'
import { can,permissions,type CurrentUser } from '@/permissions'
type Stock={warehouse_id:string;warehouse_name:string;batch_id:string;batch_number:string;version:string;product_id:string;product_name:string;sku:string;base_unit_code:string;available_quantity:string;damaged_quantity:string;original_price_mmk:string|null}
type Record={id:string;kind:string;disposition:string;product_name:string;batch_number:string;warehouse_name:string;quantity:string;reason:string;estimated_loss_mmk:string|null;original_price_mmk:string|null;reduced_price_mmk:string|null;sale_id:string|null}
export default function StockIssues({current}:{current:CurrentUser}){const[q,setQ]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<{stock:Stock;sale:boolean}|null>(null);const stock=useQuery({queryKey:['issue-stock',q],queryFn:()=>requestJSON<Stock[]>(`/stock-issues/choices?q=${encodeURIComponent(q)}`)});const history=useQuery({queryKey:['stock-issues',q,page],queryFn:()=>requestJSON<{records:Record[];total:number}>(`/stock-issues?q=${encodeURIComponent(q)}&page=${page}`)});return <><PageHeader eyebrow="Inventory / Exceptions" title="Damage & missing stock" description="Quarantine damage, record shortages, discard goods or sell usable damaged stock."/><SearchInput label="Find stock batch" value={q} onValueChange={v=>{setQ(v);setPage(1)}}/><div className="my-4"><DataTable caption="Stock available for action" rows={stock.data||[]} rowKey={r=>r.warehouse_id+r.batch_id} loading={stock.isPending} error={stock.error?.message} columns={[{id:'product',header:'Product / batch',cell:r=><>{r.product_name}<span className="block text-xs text-muted-foreground">{r.batch_number} · {r.warehouse_name}</span></>},{id:'available',header:'Available',cell:r=>`${amount(r.available_quantity)} ${r.base_unit_code}`},{id:'damaged',header:'Damaged',cell:r=>amount(r.damaged_quantity)},{id:'action',header:'Action',cell:r=><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setSelected({stock:r,sale:false})}>Record issue</Button>{can(current,permissions.salesCreate)&&can(current,permissions.paymentsManage)&&<Button size="sm" variant="outline" onClick={()=>setSelected({stock:r,sale:true})}>Reduced-price sale</Button>}</div>}]}/></div><h2 className="my-4 font-semibold">Issue history</h2><DataTable caption="Damage and missing history" rows={history.data?.records||[]} rowKey={r=>r.kind+r.id} error={history.error?.message} loading={history.isPending} pagination={{page,pageSize:20,total:history.data?.total||0,onPageChange:setPage}} columns={[{id:'kind',header:'Type',cell:r=>r.disposition},{id:'product',header:'Product / batch',cell:r=><>{r.product_name}<span className="block text-xs">{r.batch_number}</span></>},{id:'qty',header:'Quantity',cell:r=>amount(r.quantity)},{id:'reason',header:'Reason',cell:r=>r.reason},{id:'loss',header:'Estimated loss (MMK)',cell:r=>r.estimated_loss_mmk===null?'Restricted / not separately costed':amount(r.estimated_loss_mmk)},{id:'price',header:'Original → reduced',cell:r=>r.original_price_mmk!==null&&r.reduced_price_mmk!==null?`${amount(r.original_price_mmk)} → ${amount(r.reduced_price_mmk)}`:'—'},{id:'sale',header:'Invoice',cell:r=>r.sale_id&&<a className="text-primary" href={`/sales/${r.sale_id}`}>View sale</a>}]}/>{selected&&(selected.sale?<DamagedSale stock={selected.stock} close={()=>setSelected(null)}/>:<Issue stock={selected.stock} close={()=>setSelected(null)}/>)}</>}
function Issue({stock,close}:{stock:Stock;close:()=>void}){const[kind,setKind]=useState('DAMAGE'),[bucket,setBucket]=useState('SELLABLE'),[qty,setQty]=useState('1'),[reason,setReason]=useState(''),[notes,setNotes]=useState(''),[request]=useState(()=>crypto.randomUUID());const client=useQueryClient();const save=useMutation({mutationFn:()=>requestJSON('/stock-issues',{method:'POST',body:JSON.stringify({request_id:request,batch_id:stock.batch_id,warehouse_id:stock.warehouse_id,version:stock.version,kind,bucket:kind==='DAMAGE'?'SELLABLE':kind==='DISCARD'?'DAMAGED':bucket,quantity:qty,reason,notes})}),onSuccess:()=>{void client.invalidateQueries({queryKey:['issue-stock']});void client.invalidateQueries({queryKey:['stock-issues']});close()}});const uncertain=save.error instanceof ApiError&&(save.error.status===0||save.error.status>=500),locked=save.isPending||uncertain;return <Modal open onOpenChange={v=>!v&&!locked&&close()} title="Record stock issue" description={`${stock.product_name} · ${stock.batch_number}`} busy={locked} footer={<Button disabled={save.isPending} onClick={()=>save.mutate()}>{uncertain?'Retry same operation':'Post stock issue'}</Button>}><fieldset disabled={locked} className="space-y-3"><Select aria-label="Stock issue type" value={kind} onValueChange={setKind}><SelectItem value="DAMAGE">Move available stock to damaged</SelectItem><SelectItem value="MISSING">Missing stock</SelectItem><SelectItem value="DISCARD">Discard damaged stock</SelectItem></Select>{kind==='MISSING'&&<Select aria-label="Missing stock bucket" value={bucket} onValueChange={setBucket}><SelectItem value="SELLABLE">Available</SelectItem><SelectItem value="DAMAGED">Damaged</SelectItem></Select>}<Field label={`Issue quantity (${stock.base_unit_code})`} value={qty} onChange={setQty}/><Field label="Issue reason" value={reason} onChange={setReason}/><Field label="Issue notes" value={notes} onChange={setNotes}/><p className="text-xs text-muted-foreground">Posting permanently records the issue and its inventory movement. Reserved stock cannot be removed.</p></fieldset>{save.error&&<p role="alert">{save.error.message}</p>}</Modal>}
function DamagedSale({stock,close}:{stock:Stock;close:()=>void}){const[qty,setQty]=useState('1'),[price,setPrice]=useState(''),[reason,setReason]=useState(''),[approved,setApproved]=useState(false),[request]=useState(()=>crypto.randomUUID());const[review,setReview]=useState<{payload:object;quote:{quote_hash:string;total_mmk:string;cost_mmk?:string;requires_below_cost_approval:boolean;can_approve_below_cost:boolean}}|null>(null)
 const quote=useMutation({mutationFn:async()=>{const total=fixed((scaled(qty,6)*scaled(price,4)+500000n)/1000000n,4);const payload={request_id:request,warehouse_id:stock.warehouse_id,customer_id:'',pricing_mode:'RETAIL',tender_mmk:total,payment_method:'CASH',payment_reference:'',due_date:'',reason,quote_hash:'',items:[{product_id:stock.product_id,unit_code:stock.base_unit_code,units_per_pack:'1',quantity:qty,unit_price_mmk:price,discount_mmk:'0',stock_bucket:'DAMAGED',batch_id:stock.batch_id}]};const result=await requestJSON<NonNullable<typeof review>['quote']>('/pos/quote',{method:'POST',body:JSON.stringify(payload)});return{payload,quote:result}},onSuccess:r=>{setReview(r);setApproved(false)}})
 const sale=useMutation({mutationFn:()=>requestJSON<{id:string}>('/pos/checkout',{method:'POST',body:JSON.stringify({...review!.payload,quote_hash:review!.quote.quote_hash,approve_below_cost:approved})}),onSuccess:r=>location.assign(`/sales/${r.id}`)});const uncertain=sale.error instanceof ApiError&&(sale.error.status===0||sale.error.status>=500),locked=sale.isPending||uncertain
 return <Modal open onOpenChange={v=>!v&&!locked&&close()} title="Reduced-price damaged sale" description={`${stock.product_name} · ${stock.batch_number} · ${amount(stock.damaged_quantity)} damaged units`} busy={locked} animated={false} footer={review?<><Button variant="outline" disabled={locked} onClick={()=>{setReview(null);sale.reset()}}>Back</Button><Button disabled={sale.isPending||(review.quote.requires_below_cost_approval&&(!review.quote.can_approve_below_cost||!approved))} onClick={()=>sale.mutate()}>Complete damaged sale</Button></>:<Button disabled={quote.isPending} onClick={()=>quote.mutate()}>Review damaged sale</Button>}>{!review?<div className="space-y-3"><p className="text-sm">Original unit price: {stock.original_price_mmk===null?'Not configured':`${amount(stock.original_price_mmk)} MMK`}</p><Field label="Damaged sale quantity" value={qty} onChange={setQty}/><Field label="Reduced unit price (MMK)" value={price} onChange={setPrice}/><Field label="Damaged sale reason" value={reason} onChange={setReason}/><p className="text-xs text-muted-foreground">Only usable, non-expired goods. Cash, exact payment, walk-in customer. Stock is deducted directly from the damaged bucket.</p>{quote.error&&<p role="alert">{quote.error.message}</p>}</div>:<div className="space-y-3"><p>Total: {amount(review.quote.total_mmk)} MMK</p>{review.quote.cost_mmk!==undefined&&<p>Actual cost: {amount(review.quote.cost_mmk)} MMK</p>}{review.quote.requires_below_cost_approval&&<div role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800"><p>This sale is below actual batch cost.</p>{review.quote.can_approve_below_cost?<label><input type="checkbox" checked={approved} disabled={locked} onChange={e=>setApproved(e.target.checked)}/> I approve this below-cost damaged sale.</label>:<p>A Super Admin or explicitly authorized cashier must approve.</p>}</div>}{sale.error&&<p role="alert">{sale.error.message}{uncertain&&' Retry this same sale safely.'}</p>}</div>}</Modal>
}
