INSERT INTO app.permissions(code,description,is_sensitive) VALUES
('dashboard.view','dashboard — view',false),
('pos.use','pos — use',false),
('sales.create','sales — create',false),
('sales.view','sales — view',false),
('sales.sell_below_cost','sales — sell below cost',true),
('sales.large_discount','sales — large discount',true),
('products.view','products — view',false),
('products.manage','products — manage',false),
('customers.manage','customers — manage',false),
('suppliers.manage','suppliers — manage',false),
('purchases.manage','purchases — manage',false),
('costs.view_purchase','costs — view purchase',true),
('costs.view_landed','costs — view landed',true),
('costs.change_purchase','costs — change purchase',true),
('costs.change_transport','costs — change transport',true),
('exchange_rates.manage','exchange rates — manage',true),
('shipments.view','shipments — view',false),
('shipments.manage','shipments — manage',false),
('transportation.manage','transportation — manage',false),
('receiving.manage','receiving — manage',false),
('inventory.view','inventory — view',false),
('inventory.adjust','inventory — adjust',true),
('stock_taking.manage','stock taking — manage',false),
('stock_transfers.manage','stock transfers — manage',false),
('damage.manage','damage — manage',false),
('payments.manage','payments — manage',false),
('expenses.manage','expenses — manage',false),
('returns.manage','returns — manage',false),
('refunds.approve','refunds — approve',true),
('approvals.manage','approvals — manage',true),
('transactions.reverse','transactions — reverse',true),
('reports.sales','reports — sales',false),
('reports.inventory','reports — inventory',false),
('reports.profit','reports — profit',true),
('users.manage','users — manage',true),
('permissions.manage','permissions — manage',true),
('audit.view','audit — view',true),
('settings.manage','settings — manage',true),
('attachments.manage','attachments — manage',false);
