import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { PageHeader,DataTable,SearchInput,LoadingState,EmptyState } from '@/components/shared'
import { requestJSON } from '@/services/api'
import { amount } from '../purchases/types'
import { dateLabel } from '../shipments/types'
type Summary={id:string;invoice_number:string;sold_at:string;customer_name:string;total_mmk:string;paid_mmk:string;outstanding_mmk:string}
type Invoice=Summary&{warehouse_name:string;cashier:string;pricing_mode:string;status:string;payment_method:string;payment_reference:string;due_date:string|null;tender_mmk:string;change_mmk:string;cost_mmk?:string;profit_mmk?:string;reason:string;lines:{product_name:string;sku:string;unit_code:string;quantity:string;unit_price_mmk:string;discount_mmk:string;total_mmk:string}[]}
export default function Sales(){const id=window.location.pathname.split('/')[2];return id?<Details id={id}/>:<List/>}
function List(){const [q,setQ]=useState(''),[page,setPage]=useState(1);const query=useQuery({queryKey:['sales',q,page],queryFn:({signal})=>requestJSON<{sales:Summary[];total:number}>(`/sales?q=${encodeURIComponent(q)}&page=${page}&page_size=20`,{signal})});return <><PageHeader eyebrow="Sales / Posted invoices" title="Invoices" description="Historical invoices and payments recorded at checkout." actions={<Button asChild><a href="/pos">Open POS</a></Button>}/><div className="mb-4"><SearchInput label="Search invoices" value={q} onValueChange={v=>{setQ(v);setPage(1)}}/></div><DataTable caption="Invoices" rows={query.data?.sales||[]} rowKey={r=>r.id} loading={query.isPending} error={query.error?.message} onRetry={()=>void query.refetch()} pagination={{page,pageSize:20,total:query.data?.total||0,onPageChange:setPage}} columns={[{id:'number',header:'Invoice',cell:r=><a className="text-primary" href={`/sales/${r.id}`}>{r.invoice_number}</a>},{id:'date',header:'Sold',cell:r=>dateLabel(r.sold_at)},{id:'customer',header:'Customer',cell:r=>r.customer_name},...(['total_mmk','paid_mmk','outstanding_mmk'] as const).map((key,i)=>({id:key,header:['Total (MMK)','Paid at checkout','Debt at checkout'][i],cell:(r:Summary)=>amount(r[key])}))]}/></>}
function Details({id}:{id:string}){const q=useQuery({queryKey:['invoice',id],queryFn:()=>requestJSON<Invoice>(`/sales/${id}`),retry:false});if(q.isPending)return <LoadingState/>;if(q.error)return <EmptyState title="Unable to load invoice" description={q.error.message} action={<Button onClick={()=>void q.refetch()}>Retry</Button>}/>;const s=q.data;return <><div className="no-print"><PageHeader eyebrow="Sales / Invoice" title={s.invoice_number} description="Posted sale · historical prices and FIFO costs preserved" actions={<><Button asChild variant="outline"><a href="/pos">New sale</a></Button><Button onClick={()=>window.print()}>Print invoice</Button></>}/></div><article className="invoice-print panel p-5 sm:p-8"><div className="flex flex-wrap justify-between gap-4 border-b pb-5"><div><h1 className="text-lg font-bold">PWINT THIT DISTRIBUTION</h1><p className="mt-1 text-sm">{s.warehouse_name}</p></div><div className="text-sm"><h2 className="font-semibold">{s.invoice_number}</h2><p>{dateLabel(s.sold_at)}</p><p>Cashier: {s.cashier}</p></div></div><div className="my-5 grid gap-2 text-sm sm:grid-cols-2"><p>Customer: {s.customer_name}</p><p>Pricing: {s.pricing_mode}</p><p>Payment: {s.payment_method.replaceAll('_',' ')}</p>{s.payment_reference&&<p>Reference: {s.payment_reference}</p>}{s.due_date&&<p>Due date: {s.due_date}</p>}</div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-y bg-muted"><tr>{['Product','Quantity','Price (MMK)','Discount','Total (MMK)'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{s.lines.map((l,i)=><tr key={i} className="border-b"><td className="p-2">{l.product_name}<p className="text-xs text-muted-foreground">{l.sku}</p></td><td className="whitespace-nowrap p-2">{amount(l.quantity)} {l.unit_code}</td><td className="p-2 tabular-nums">{amount(l.unit_price_mmk)}</td><td className="p-2 tabular-nums">{amount(l.discount_mmk)}</td><td className="p-2 tabular-nums">{amount(l.total_mmk)}</td></tr>)}</tbody></table></div><dl className="ml-auto mt-5 max-w-sm space-y-3 text-sm">{[['Invoice total',s.total_mmk],['Tendered',s.tender_mmk],['Payment applied',s.paid_mmk],['Change',s.change_mmk],['Debt at checkout',s.outstanding_mmk]].map(([k,v])=><div key={k} className="flex justify-between gap-4"><dt>{k}</dt><dd className="font-semibold tabular-nums">{amount(v)} MMK</dd></div>)}</dl>{s.reason&&<p className="mt-5 text-xs">Note: {s.reason}</p>}<p className="mt-8 border-t pt-4 text-center text-xs text-muted-foreground">Thank you for your business.</p></article>{(s.cost_mmk!==undefined||s.profit_mmk!==undefined)&&<section className="no-print mt-4 rounded-lg border p-4 text-sm"><h2 className="font-semibold">Internal costing · excluded from print</h2>{s.cost_mmk!==undefined&&<p>FIFO cost: {amount(s.cost_mmk)} MMK</p>}{s.profit_mmk!==undefined&&<p>Gross profit: {amount(s.profit_mmk)} MMK</p>}</section>}</>}
