import { test,expect } from '@playwright/test'
import { signIn } from './session'
test('compact cost journey preserves exact profit, loss, zero and invalid scenarios',async({page})=>{
 await signIn(page,'browser-journey-owner')
 await page.goto('/design-system')
 const journey=page.getByRole('region',{name:'Cost journey',exact:true})
 await expect(journey).toContainText('10,000 INR')
 await expect(journey).toContainText('1 INR = 25 MMK')
 await expect(journey).toContainText('250,000 MMK')
 await expect(journey.getByTestId('landed-total')).toHaveText('300,000 MMK')
 await expect(journey.getByTestId('journey-profit')).toHaveText('40,000 MMK')
 await journey.screenshot({path:'/tmp/pwint-cost-journey-desktop.png'})
 const selling=journey.getByLabel('Scenario selling price (MMK)',{exact:true})
 await selling.fill('299999.9999')
 await expect(journey.getByTestId('journey-profit')).toHaveText('-0.0001 MMK')
 await expect(journey.getByText('Loss',{exact:true})).toBeVisible()
 await selling.fill('300000')
 await expect(journey.getByTestId('journey-profit')).toHaveText('0 MMK')
 await selling.fill('NaN')
 await expect(journey.getByText('Enter a valid amount',{exact:true})).toBeVisible()
 await expect(journey.getByTestId('journey-profit')).toHaveText('Not yet available')
 await selling.fill('')
 await expect(journey.getByTestId('journey-profit')).toHaveText('Not yet available')
 await selling.fill('340000')
 await page.setViewportSize({width:375,height:812})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await journey.screenshot({path:'/tmp/pwint-cost-journey-mobile.png',style:'header { visibility: hidden !important; }'})
 await page.reload()
 await expect(page.getByTestId('journey-profit')).toHaveText('40,000 MMK')
})
