import { test, expect } from '@playwright/test'
import { signIn, staff } from './session'

test('business menu scrolls independently and every destination loads', async ({ page }, testInfo) => {
  test.setTimeout(90000)
  await page.setViewportSize({ width: 1280, height: 600 })
  await signIn(page, 'browser-navigation-owner')
  const pageErrors: string[] = []
  const apiErrors: string[] = []
  page.on('pageerror', error => pageErrors.push(error.message))
  page.on('response', response => { if (response.url().includes('/api/v1/') && response.status() >= 400) apiErrors.push(`${response.status()} ${new URL(response.url()).pathname}`) })
  const sidebar = page.locator('aside')
  const nav = sidebar.getByRole('navigation', { name: 'Main navigation' })
  for (const name of ['Dashboard', 'Reports', 'User guide']) await expect(sidebar.getByRole('link', { name, exact: true })).toBeInViewport()
  for (const name of ['System status', 'UI library']) await expect(sidebar.getByRole('link', { name, exact: true })).toHaveCount(0)
  expect(await nav.evaluate(element => element.scrollHeight > element.clientHeight)).toBe(true)
  const bodyBefore = await page.evaluate(() => window.scrollY)
  await nav.hover()
  await page.mouse.wheel(0, 1600)
  await expect.poll(() => nav.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
  await expect(sidebar.getByRole('link', { name: 'Permissions', exact: true })).toBeInViewport()
  expect(await page.evaluate(() => window.scrollY)).toBe(bodyBefore)
  for (const name of ['Dashboard', 'Reports']) await expect(sidebar.getByRole('link', { name, exact: true })).toBeInViewport()
  const menuPosition = await nav.evaluate(element => element.scrollTop)
  await sidebar.getByRole('link', { name: 'Permissions', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Permission catalog', exact: true })).toBeVisible()
  await expect.poll(() => nav.evaluate(element => element.scrollTop)).toBeCloseTo(menuPosition, 0)
  await page.reload()
  await expect.poll(() => nav.evaluate(element => element.scrollTop)).toBeCloseTo(menuPosition, 0)
  await page.screenshot({ path: `/tmp/pwint-navigation-${testInfo.project.name}-desktop.png`, animations: 'disabled' })
  const links = await sidebar.getByRole('link').evaluateAll(elements => elements.map(element => element.getAttribute('href')!).filter(href => href !== '/'))
  expect(links).toContain('/purchasing-settings')
  for (const href of links) {
    await page.goto(href)
    await expect(page.locator('main h1')).toBeVisible()
    await expect(page.getByRole('heading', { name: /Page not found|Access restricted|Unable to check your session/ })).toHaveCount(0)
    await expect(page.getByText('Preparing report…', { exact: true })).toHaveCount(0)
  }
  // A new installation must explain the empty warehouse selector.
  await page.route('**/api/v1/pos/warehouses', route => route.fulfill({ json: [] }))
  await page.goto('/pos')
  await expect(page.getByRole('heading', { name: 'Set up a warehouse before selling' })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'POS warehouse' })).toContainText('No warehouse available')
  await page.getByRole('combobox', { name: 'Pricing mode', exact: true }).click()
  await page.getByRole('option', { name: 'Wholesale prices', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Pricing mode', exact: true })).toContainText('Wholesale prices')
  await page.unroute('**/api/v1/pos/warehouses')
  await page.goto('/products/new')
  await expect(page.getByText('1 · Fixed base conversion', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Add packaging', exact: true }).click()
  const quantity = page.getByLabel('Base units per pack 2', { exact: true })
  await quantity.pressSequentially('12.25')
  await expect(quantity).toHaveValue('12.25')
  await expect(quantity).toBeFocused()
  await quantity.fill('')
  await quantity.pressSequentially('24')
  await expect(quantity).toHaveValue('24')
  const barcode = page.getByLabel('Packaging barcode 2', { exact: true })
  await barcode.pressSequentially('000123456')
  await expect(barcode).toHaveValue('000123456')
  await expect(barcode).toBeFocused()
  await page.screenshot({ path: `/tmp/pwint-packaging-typing-${testInfo.project.name}.png`, fullPage: true })
  await page.getByLabel('Minimum stock', { exact: true }).pressSequentially('20.123456')
  await expect(page.getByLabel('Minimum stock', { exact: true })).toHaveValue('20.123456')
  await expect.poll(() => nav.evaluate(element => element.scrollTop)).toBeCloseTo(menuPosition, 0)
  await page.goto('/guide')
  await expect(page.getByRole('heading', { name: 'User guide', exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: 'Guide contents' }).getByRole('link', { name: '10. Missing pages, access and errors', exact: true }).click()
  await expect(page.getByRole('heading', { name: '10. Missing pages, access and errors', exact: true })).toBeInViewport()
  for (const viewport of [{ width: 375, height: 667 }, { width: 667, height: 375 }]) {
    await page.setViewportSize(viewport)
    await page.getByRole('button', { name: 'Open navigation', exact: true }).click()
    const menu = page.getByRole('dialog', { name: 'Navigation', exact: true })
    const mobileNav = menu.getByRole('navigation', { name: 'Main navigation' })
    for (const name of ['Dashboard', 'Reports']) await expect(menu.getByRole('link', { name, exact: true })).toBeInViewport()
    expect(await mobileNav.evaluate(element => element.clientHeight > 0 && element.scrollHeight > element.clientHeight)).toBe(true)
    await mobileNav.focus()
    await page.keyboard.press('End')
    await expect(menu.getByRole('link', { name: 'Permissions', exact: true })).toBeInViewport()
    await expect(menu.getByRole('link', { name: 'User guide', exact: true })).toBeInViewport()
    await page.screenshot({ path: `/tmp/pwint-navigation-${testInfo.project.name}-${viewport.width}.png`, animations: 'disabled' })
    const mobilePosition = await mobileNav.evaluate(element => element.scrollTop)
    await menu.getByRole('link', { name: 'Reports', exact: true }).click()
    await expect(menu).toHaveCount(0)
    await expect(page.getByRole('heading', { name: 'Business reports', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'Open navigation', exact: true }).click()
    // Safari can round/reflow the drawer by a few pixels as fonts settle.
    await expect.poll(async () => Math.abs(await mobileNav.evaluate(element => element.scrollTop) - mobilePosition)).toBeLessThan(12)
    await menu.getByRole('button', { name: 'Close', exact: true }).click()
  }
  expect(pageErrors).toEqual([])
  expect(apiErrors).toEqual([])
})

test('unassigned staff has an actionable home and guide', async ({ page }) => {
  await signIn(page, staff)
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Your workspace', exact: true })).toBeVisible()
  await expect(page.getByText('No business tools have been assigned yet.', { exact: false })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Dashboard', exact: true })).toHaveCount(0)
  await page.goto('/guide')
  await expect(page.getByRole('heading', { name: 'User guide', exact: true })).toBeVisible()
  await expect(page.getByText('Dashboard needs dashboard.view.', { exact: false })).toBeVisible()
})
