import { test, expect } from '@playwright/test'
import { signIn, testPassword } from './session'

test('complete product workflow: catalog, packaging, edit, search, pagination and archive', async ({ page, browser }) => {
  test.setTimeout(60000)
  await signIn(page)
  const suffix = String(Date.now())
  const name = `Tea ${suffix}`
  const sku = `TEA-${suffix}`
  const barcode = `000${suffix}`
  await page.goto('/catalog')
  await page.getByRole('button', { name: 'Add category', exact: true }).click()
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill(`Drinks ${suffix}`)
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByRole('button', { name: 'Brands', exact: true }).click()
  await page.getByRole('button', { name: 'Add brand', exact: true }).click()
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill(`Brand ${suffix}`)
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.goto('/products/new')
  await page.getByLabel('Product name', { exact: true }).fill(name)
  await page.getByLabel('SKU', { exact: true }).fill(sku)
  await page.getByLabel('Product barcode', { exact: true }).fill(barcode)
  await page.getByLabel('Category', { exact: true }).selectOption({ label: `Drinks ${suffix}` })
  await page.getByLabel('Brand', { exact: true }).selectOption({ label: `Brand ${suffix}` })
  await page.getByLabel('Base stock unit', { exact: true }).selectOption('BOTTLE')
  await page.getByRole('button', { name: 'Add packaging', exact: true }).click()
  await page.getByLabel('Base units per pack 2', { exact: true }).fill('12')
  await page.getByLabel('Packaging barcode 2', { exact: true }).fill(`${barcode}-C`)
  await page.getByLabel('Purchase default', { exact: true }).nth(1).check()
  await page.getByLabel('Minimum stock', { exact: true }).fill('20.123456')
  await page.getByRole('button', { name: 'Create product', exact: true }).click()
  await expect(page).toHaveURL(/\/products\/[a-f0-9-]{36}$/)
  const id = page.url().split('/').pop()!
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await expect(page.getByText('1 Carton = 12 Bottles', { exact: true })).toBeVisible()
  await expect(page.getByText(barcode, { exact: true })).toBeVisible()
  await page.screenshot({ path: '/tmp/pwint-product-details.png', fullPage: true })
  await page.getByRole('link', { name: 'Edit Product', exact: true }).click()
  await page.getByLabel('Product name', { exact: true }).fill(`${name} updated`)
  await page.getByLabel('Status', { exact: true }).selectOption('inactive')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('heading', { name: `${name} updated`, exact: true })).toBeVisible()
  await expect(page.getByText('Inactive', { exact: true })).toBeVisible()
  await page.goto('/products')
  await page.getByRole('searchbox', { name: 'Search products' }).fill(`${barcode}-C`)
  await page.getByLabel('Status', { exact: true }).selectOption('inactive')
  await expect(page.getByRole('link', { name: `${name} updated`, exact: true })).toBeVisible()
  await page.getByLabel('Status', { exact: true }).selectOption('active')
  await expect(page.getByRole('heading', { name: 'No matching products' })).toBeVisible()
  await page.getByRole('button', { name: 'Reset filters', exact: true }).click()
  const headers = { Origin: process.env.E2E_BASE_URL!, 'X-Pwint-Thit-Request': '1' }
  for (let i = 0; i < 11; i++) {
    const response = await page.request.post('/api/v1/products', { headers, data: { sku: `PAGE-${suffix}-${i}`, name: `Pagination ${suffix} ${i}`, base_unit_code: 'PIECE', is_active: true, packaging: [{ unit_code: 'PIECE', units_per_pack: '1', is_default_purchase: true, is_default_sale: true }] } })
    expect(response.status()).toBe(201)
  }
  await page.getByRole('searchbox', { name: 'Search products' }).fill(`Pagination ${suffix}`)
  await page.getByLabel('Rows per page', { exact: true }).selectOption('10')
  await expect(page.getByText('1–10 of 11 records', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.getByText('11–11 of 11 records', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Previous', exact: true }).click()
  await page.setViewportSize({ width: 375, height: 812 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '/tmp/pwint-products-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 800 })
  // Give a separate operator only read access; hiding alone is not security.
  const staffName = `product-reader-${suffix}`
  const created = await page.request.post('/api/v1/users', { headers, data: { username: staffName, display_name: 'Product reader', password: testPassword } })
  expect(created.status()).toBe(201)
  const staffID = (await created.json()).id
  expect((await page.request.put(`/api/v1/users/${staffID}/permissions`, { headers, data: { permissions: ['products.view'] } })).status()).toBe(204)
  const context = await browser.newContext({ baseURL: process.env.E2E_BASE_URL })
  try {
    const other = await context.newPage()
    await signIn(other, staffName)
    await other.goto(`/products/${id}`)
    await expect(other.getByRole('heading', { name: `${name} updated`, exact: true })).toBeVisible()
    await expect(other.getByRole('link', { name: 'Edit Product', exact: true })).not.toBeVisible()
    await other.goto('/products/new')
    await expect(other.getByRole('heading', { name: 'Access restricted' })).toBeVisible()
    expect((await other.request.delete(`/api/v1/products/${id}`, { headers, data: { version: '2' } })).status()).toBe(403)
  } finally { await context.close() }
  await page.goto(`/products/${id}`)
  await page.getByRole('button', { name: 'Archive product', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Archive product', exact: true }).click()
  await expect(page).toHaveURL(/\/products$/)
  await page.getByRole('searchbox', { name: 'Search products' }).fill(sku)
  await expect(page.getByRole('heading', { name: 'No matching products' })).toBeVisible()
  await page.getByLabel('Status', { exact: true }).selectOption('archived')
  await expect(page.getByRole('link', { name: `${name} updated`, exact: true })).toBeVisible()
  await page.screenshot({ path: '/tmp/pwint-products-list.png', fullPage: true })
})
