import {test,expect} from '@playwright/test'
import {signIn,testPassword} from './session'

test('purchase workspace resumes shipment, costs and receiving with generated IDs',async({page,browser})=>{
 test.setTimeout(90000)
 await signIn(page,'browser-workflow-owner')
 const suffix=String(Date.now())
 const headers={Origin:process.env.E2E_BASE_URL!,'X-Pwint-Thit-Request':'1'}
 const post=async(path:string,data:object)=>{const res=await page.request.post(`/api/v1${path}`,{headers,data});expect(res.status(),await res.text()).toBe(201);return res.json()}
 const supplier=await post('/suppliers',{name:`Workflow supplier ${suffix}`,is_active:true})
 expect(supplier.code).toMatch(/^SUP-\d{4}-\d{4,}$/)
 const product=await post('/products',{name:`Workflow goods ${suffix}`,base_unit_code:'PIECE',is_active:true,packaging:[{unit_code:'PIECE',units_per_pack:'1',is_default_purchase:true,is_default_sale:true},{unit_code:'PACK',units_per_pack:'2'}]})
 expect(product.sku).toMatch(/^PRD-\d{4}-\d{4,}$/)
 const purchase=await post('/purchases',{request_id:crypto.randomUUID(),supplier_id:supplier.id,purchased_at:'2026-01-15T00:00:00Z',currency_code:'MMK',mmk_per_unit:'1',items:[{product_id:product.id,unit_code:'PIECE',quantity:'10',units_per_pack:'1',unit_price_original:'100.123456'}]})
 expect(purchase.purchase_number).toMatch(/^PUR-\d{4}-\d{4,}$/)
 const warehouse=await post('/warehouses',{code:`WF-${suffix}`,name:`Workflow warehouse ${suffix}`})
 await page.goto(`/purchases/${purchase.id}`)
 const workspace=page.getByRole('region',{name:'Purchase workflow'})
 await expect(workspace).toContainText('Continue with transportation')
 await page.reload()
 await page.getByRole('button',{name:'Arrange shipment',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCSS('opacity','1')
 expect((await page.getByRole('dialog').boundingBox())!.width).toBeGreaterThan(900)
 await expect(page.getByLabel('Expected arrival',{exact:true})).toHaveCount(0)
 await page.getByLabel('Origin',{exact:true}).fill('Supplier warehouse')
 await page.getByRole('combobox',{name:'Final warehouse',exact:true}).click()
 await page.getByRole('option',{name:`Workflow warehouse ${suffix}`,exact:true}).click()
 await expect(page.getByLabel(`Quantity: ${product.sku}`,{exact:true})).toHaveValue('10.000000')
 await expect(page.getByText('In this shipment: 5 packs (10 pieces)',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Create shipment',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(page).toHaveURL(new RegExp(`/purchases/${purchase.id}$`))
 const workflow=await(await page.request.get(`/api/v1/purchases/${purchase.id}/workflow`)).json()
 const shipment=workflow.shipments[0]
 expect(shipment.shipment_number).toMatch(/^SHP-\d{4}-\d{4,}$/)
 expect(workflow.choices[0].available_quantity).toBe('0.000000')
 await page.getByRole('button',{name:'Edit shipment',exact:true}).click()
 await page.getByLabel('Shipment origin',{exact:true}).fill('Updated supplier warehouse')
 await page.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(page.getByRole('table',{name:'Shipment goods'})).toContainText('5 packs (10 pieces)')
 await page.getByLabel('Transportation timeline',{exact:true}).check()
 await page.getByRole('button',{name:'Add stage',exact:true}).click()
 await expect(page.getByLabel('Vehicle information',{exact:true})).toHaveCount(0)
 await page.getByLabel('Destination',{exact:true}).fill('Main warehouse')
 await page.getByLabel('Provider',{exact:true}).fill('Delivery service')
 await expect(page.getByRole('combobox',{name:'Package Type',exact:true})).toContainText('Pack')
 await expect(page.getByLabel('Package Quantity',{exact:true})).toHaveValue('5.000000')
 await page.getByLabel('Fee per Package (MMK)',{exact:true}).fill('10')
 await expect(page.getByRole('dialog')).toContainText('Total Cargo Fee: 50 MMK')
 await page.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(workspace).toContainText(/TRN-\d{4}-\d{4,}/)
 await page.getByRole('button',{name:'Remove stage 1',exact:true}).click()
 await page.getByLabel('Removal reason',{exact:true}).fill('Duplicate stage correction')
 await page.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(workspace.getByText('No transportation stages',{exact:true})).toBeVisible()
 await expect(page.getByLabel('Arrival received quantity 1',{exact:true})).toHaveCount(0)
 await expect(page.getByRole('combobox',{name:'Allocation method',exact:true})).toHaveCount(0)
 for(const name of ['Mark in transit','Mark arrived']){
  await page.getByRole('button',{name,exact:true}).click()
  await page.getByRole('button',{name:'Save changes',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
 }
 await page.getByRole('button',{name:'Receive goods',exact:true}).click()
 const receivingDialog=page.getByRole('dialog',{name:'Receive goods into inventory',exact:true})
 await expect(receivingDialog.getByRole('heading',{name:'Receipt details',exact:true})).toBeVisible()
 await expect(receivingDialog).toHaveCSS('opacity','1')
 expect((await receivingDialog.boundingBox())!.width).toBeGreaterThan(900)
 await page.screenshot({path:'/tmp/pwint-receiving-desktop.png'})
 await page.setViewportSize({width:375,height:812})
 expect(await receivingDialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
 await page.screenshot({path:'/tmp/pwint-receiving-dialog-mobile.png'})
 await page.setViewportSize({width:1280,height:720})
 await page.getByLabel('Batch number 1',{exact:true}).fill(`WF-BATCH-${suffix}`)
 await page.getByRole('button',{name:'Review receipt',exact:true}).click()
 await page.getByRole('button',{name:'Confirm receipt',exact:true}).click()
 await page.getByRole('button',{name:'Post receipt',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(page).toHaveURL(new RegExp(`/purchases/${purchase.id}$`))
 await expect(workspace).toContainText('Completed · goods received and inventory updated')
 await expect(workspace).toContainText(/GRN-\d{4}-\d{4,}/)
 await page.reload()
 await expect(workspace).toContainText('Completed · goods received and inventory updated')
 const stock=await(await page.request.get(`/api/v1/inventory?q=${suffix}`)).json()
 expect(stock.stock.find((s:{warehouse_id:string})=>s.warehouse_id===warehouse.id).available_quantity).toBe('10.000000')
 await page.setViewportSize({width:375,height:812})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'/tmp/pwint-v12-workflow-mobile.png',fullPage:true})
 // A staff reader cannot fetch the linked workflow or mutate records without grants.
 const staff=await post('/users',{username:`workflow-reader-${suffix}`,display_name:'Workflow reader',password:testPassword})
 expect((await page.request.put(`/api/v1/users/${staff.id}/permissions`,{headers,data:{permissions:['purchases.view']}})).status()).toBe(204)
 const ctx=await browser.newContext({baseURL:process.env.E2E_BASE_URL})
 try{const other=await ctx.newPage();await signIn(other,`workflow-reader-${suffix}`);expect((await other.request.get(`/api/v1/purchases/${purchase.id}/workflow`)).status()).toBe(403);expect((await other.request.post(`/api/v1/purchases/${purchase.id}/reverse`,{headers,data:{reason:'Forbidden'}})).status()).toBe(403)}finally{await ctx.close()}
 // Paid/shipped records keep their accounting history even for Super Admin.
 expect((await page.request.post(`/api/v1/purchases/${purchase.id}/reverse`,{headers,data:{reason:'Cannot erase received goods'}})).status()).toBe(409)
})
