import {test,expect} from '@playwright/test'
import {signIn,testPassword} from './session'
test('Super Admin corrects all completed purchase fields with required reason and immutable history',async({page,browser})=>{
 test.setTimeout(120000)
 await signIn(page,'browser-packaging-owner')
 const suffix=crypto.randomUUID().slice(0,8),headers={Origin:process.env.E2E_BASE_URL!,'X-Pwint-Thit-Request':'1'}
 const post=async(path:string,data:unknown,status=201)=>{const r=await page.request.post(`/api/v1${path}`,{headers,data});expect(r.status(),await r.text()).toBe(status);return r.json()}
 const get=async(path:string)=>{const r=await page.request.get(`/api/v1${path}`);expect(r.status()).toBe(200);return r.json()}
 const first=await post('/products',{name:`Original ${suffix}`,base_unit_code:'PIECE',is_active:true,packaging:[{unit_code:'PIECE',units_per_pack:'1',is_default_purchase:true,is_default_sale:true},{unit_code:'CARTON',units_per_pack:'12'}]})
 const second=await post('/products',{name:`Corrected ${suffix}`,base_unit_code:'BOTTLE',is_active:true,packaging:[{unit_code:'BOTTLE',units_per_pack:'1',is_default_sale:true},{unit_code:'CARTON',units_per_pack:'12',is_default_purchase:true}]})
 const supplier=await post('/suppliers',{name:`Original supplier ${suffix}`,is_active:true}),correctSupplier=await post('/suppliers',{name:`Correct supplier ${suffix}`,is_active:true})
 const warehouse=await post('/warehouses',{name:`Correction ${suffix}`,code:`CO-${suffix}`})
 const purchase=await post('/purchases',{request_id:crypto.randomUUID(),supplier_id:supplier.id,purchased_at:'2026-01-15T00:00:00Z',currency_code:'MMK',mmk_per_unit:'1',items:[{product_id:first.id,unit_code:'PIECE',quantity:'24',units_per_pack:'1',unit_price_original:'100'}]})
 const shipment=await post('/shipments',{request_id:crypto.randomUUID(),start_location:'Supplier',destination_warehouse_id:warehouse.id,items:[{purchase_item_id:purchase.items[0].id,expected_quantity:'24'}]})
 for(const status of ['IN_TRANSIT','ARRIVED']){const current=await get(`/shipments/${shipment.id}`);const r=await page.request.put(`/api/v1/shipments/${shipment.id}/status`,{headers,data:{version:current.version,status,shipped_at:'2026-01-16T00:00:00Z',arrived_at:'2026-01-17T00:00:00Z'}});expect(r.status(),await r.text()).toBe(204)}
 const receiving=await get(`/receiving/shipments/${shipment.id}`)
 const receipt={request_id:crypto.randomUUID(),shipment_id:shipment.id,version:receiving.version,finalize_costs:true,received_at:'2026-01-18T00:00:00Z',items:[{shipment_item_id:receiving.items[0].id,carton_size:'12',received_cartons:'2',received_units:'0',damaged_quantity:'0',batch_number:`CO-${suffix}`}]}
 const preview=await post('/receiving/preview',receipt,200);await post('/receiving',{...receipt,preview_token:preview.preview_token})
 const before=await get(`/inventory?warehouse_id=${warehouse.id}`)
 await page.goto(`/purchases/${purchase.id}`)
 await page.getByRole('link',{name:'Correct purchase',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Correct completed purchase',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Review correction',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(page.getByLabel('Correction reason',{exact:true})).toHaveAttribute('required','')
 await page.getByLabel('Purchase date',{exact:true}).fill('2026-01-14')
 await page.getByLabel('Set a payment due date',{exact:true}).check()
 await page.getByLabel('Payment due date',{exact:true}).fill('2026-02-15')
 await page.getByLabel('Add supplier invoice reference',{exact:true}).check()
 await page.getByLabel('Supplier invoice number',{exact:true}).fill(`CORRECT-${suffix}`)
 await page.getByLabel('Find supplier',{exact:true}).fill(`Correct supplier ${suffix}`)
 await page.getByRole('combobox',{name:'Supplier',exact:true}).click()
 await page.getByRole('option',{name:new RegExp(`Correct supplier ${suffix}`)}).click()
 await page.getByRole('combobox',{name:'Currency',exact:true}).click()
 await page.getByRole('option',{name:/^INR /}).click()
 await page.getByLabel('MMK per currency unit',{exact:true}).fill('30')
 await page.getByRole('button',{name:'Remove item 1',exact:true}).click()
 await page.getByLabel('Find product',{exact:true}).fill(`Corrected ${suffix}`)
 await page.getByRole('combobox',{name:'Product to add',exact:true}).click()
 await page.getByRole('option',{name:new RegExp(`Corrected ${suffix}`)}).click()
 await page.getByRole('button',{name:'Add item',exact:true}).click()
 await page.getByLabel('Quantity 1',{exact:true}).fill('3')
 await page.getByLabel('Units per pack 1',{exact:true}).fill('10')
 await page.getByLabel('Price per selected unit 1',{exact:true}).fill('4000')
 await page.getByLabel('Line discount 1',{exact:true}).fill('200')
 await page.getByLabel('Line tax 1',{exact:true}).fill('100')
 await page.getByLabel('Add purchase notes',{exact:true}).check()
 await page.getByLabel('Notes',{exact:true}).fill('Corrected purchase notes')
 await page.getByLabel('Correction reason',{exact:true}).fill('Supplier invoice had the wrong product, quantities and exchange rate')
 await page.getByRole('button',{name:'Review correction',exact:true}).click()
 await expect(page.getByRole('dialog')).toContainText('11,900 INR = 357,000 MMK')
 await page.getByRole('button',{name:'Save correction',exact:true}).click()
 await expect(page).toHaveURL(new RegExp(`/purchases/${purchase.id}$`))
 const corrected=await get(`/purchases/${purchase.id}`)
 expect(corrected.supplier_id).toBe(correctSupplier.id);expect(corrected.items[0].product_id).toBe(second.id);expect(corrected.items[0].base_quantity).toBe('30.000000');expect(corrected.total_mmk).toBe('357000.0000');expect(corrected.correction_version).toBe('1')
 expect((await get(`/inventory?warehouse_id=${warehouse.id}`)).stock).toEqual(before.stock)
 await page.getByText('Correction history · 1 revisions',{exact:true}).click()
 await expect(page.getByText('Reason: Supplier invoice had the wrong product, quantities and exchange rate',{exact:true})).toBeVisible()
 await expect(page.getByRole('heading',{name:'Before correction',exact:true})).toBeVisible()
 await expect(page.getByRole('heading',{name:'After correction',exact:true})).toBeVisible()
 await page.screenshot({path:'/tmp/pwint-purchase-correction-history.png',fullPage:true})
 await post(`/purchases/${purchase.id}/payments`,{request_id:crypto.randomUUID(),correction_version:'1',amount:'100',method_code:'CASH',paid_at:new Date().toISOString()},200)
 expect((await get(`/purchases/${purchase.id}`)).outstanding_original).toBe('11800.0000')
 const staff=await post('/users',{username:`correct-reader-${suffix}`,display_name:'Correction reader',password:testPassword})
 expect((await page.request.put(`/api/v1/users/${staff.id}/permissions`,{headers,data:{permissions:['purchases.view','purchases.view_cost','purchases.create','transactions.reverse']}})).status()).toBe(204)
 const ctx=await browser.newContext({baseURL:process.env.E2E_BASE_URL})
 try{const other=await ctx.newPage();await signIn(other,`correct-reader-${suffix}`);await other.goto(`/purchases/${purchase.id}`);await expect(other.getByRole('heading',{name:purchase.purchase_number,exact:true})).toBeVisible();await expect(other.getByRole('link',{name:'Correct purchase',exact:true})).toHaveCount(0);expect((await other.request.post(`/api/v1/purchases/${purchase.id}/corrections`,{headers,data:{}})).status()).toBe(403);await other.goto(`/purchases/${purchase.id}/edit`);await expect(other.getByRole('heading',{name:'Only Super Admin can correct purchases',exact:true})).toBeVisible()}finally{await ctx.close()}
})
