import { test, expect } from '@playwright/test'
import { signIn, testPassword } from './session'

test('purchase historical currency conversion, exact preview, balances and protected costs', async ({ page, browser }) => {
 test.setTimeout(60000)
 await signIn(page)
 const suffix = String(Date.now())
 const headers = { Origin: process.env.E2E_BASE_URL!, 'X-Pwint-Thit-Request': '1' }
 const s = await page.request.post('/api/v1/suppliers', { headers, data: { code: `BUY-${suffix}`, name: `Purchase supplier ${suffix}`, is_active: true } })
 expect(s.status()).toBe(201)
 const supplier = await s.json()
 const product = await page.request.post('/api/v1/products', { headers, data: { sku: `BUY-${suffix}`, name: `Purchase tea ${suffix}`, base_unit_code: 'BOTTLE', is_active: true, packaging: [{ unit_code: 'BOTTLE', units_per_pack: '1', is_default_sale: true }, { unit_code: 'CARTON', units_per_pack: '12', is_default_purchase: true }] } })
 expect(product.status()).toBe(201)
 await page.goto('/purchasing-settings')
 await page.getByLabel('Effective date', { exact: true }).fill('2026-01-01')
 await page.getByLabel('Exchange rate', { exact: true }).fill('25')
 await page.getByLabel('Rate source', { exact: true }).fill('January supplier quote')
 await page.getByRole('button', { name: 'Save new rate', exact: true }).click()
 await expect(page.getByText('Exchange rate saved. Existing purchases are unchanged.')).toBeVisible()
 await page.goto('/purchases/new')
 await page.getByLabel('Purchase number', { exact: true }).fill(`PO-${suffix}`)
 await page.getByLabel('Purchase date', { exact: true }).fill('2026-01-15')
 await page.getByLabel('Payment due date', { exact: true }).fill('2026-02-15')
 await page.getByLabel('Find supplier', { exact: true }).fill(suffix)
 await page.getByRole('combobox', { name: 'Supplier', exact: true }).click()
 await page.getByRole('option', { name: `Purchase supplier ${suffix} · BUY-${suffix}`, exact: true }).click()
 await page.getByRole('combobox', { name: 'Currency', exact: true }).click()
 await page.getByRole('option', { name: 'INR · Indian Rupee', exact: true }).click()
 await page.getByRole('combobox', { name: 'Historical quote', exact: true }).click()
 await page.getByRole('option', { name: /25 MMK.*January supplier quote/ }).click()
 await page.getByLabel('Find product', { exact: true }).fill(suffix)
 await page.getByRole('combobox', { name: 'Product to add', exact: true }).click()
 await page.getByRole('option', { name: `Purchase tea ${suffix} · BUY-${suffix}`, exact: true }).click()
 await page.getByRole('button', { name: 'Add item', exact: true }).click()
 await page.getByLabel('Quantity 1', { exact: true }).fill('0.1')
 await page.getByLabel('Price per selected unit 1', { exact: true }).fill('0.123456')
 await expect(page.getByTestId('original-preview')).toHaveText('0.0123 INR')
 await expect(page.getByTestId('mmk-preview')).toHaveText('0.3075 MMK')
 await page.getByLabel('Quantity 1', { exact: true }).fill('2')
 await page.getByLabel('Price per selected unit 1', { exact: true }).fill('5000')
 await expect(page.getByTestId('original-preview')).toHaveText('10,000 INR')
 await expect(page.getByTestId('mmk-preview')).toHaveText('250,000 MMK')
 await page.setViewportSize({ width: 375, height: 812 })
 await page.evaluate(() => window.scrollTo(0, 0))
 await page.screenshot({ path: '/tmp/pwint-purchase-mobile.png', fullPage: true })
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
 await page.setViewportSize({ width: 1280, height: 800 })
 await page.getByRole('button', { name: 'Review & post purchase', exact: true }).click()
 await page.getByRole('button', { name: 'Post purchase', exact: true }).click()
 await expect(page).toHaveURL(/\/purchases\/[a-f0-9-]{36}$/)
 const id = page.url().split('/').pop()!
 await expect(page.getByTestId('purchase-original')).toHaveText('10,000 INR')
 await expect(page.getByTestId('purchase-mmk')).toHaveText('250,000 MMK')
 await expect(page.getByText('× 12 = 24 base units', { exact: true })).toBeVisible()
 await page.screenshot({ path: '/tmp/pwint-purchase-details.png', fullPage: true })
 expect((await page.request.post('/api/v1/exchange-rates', { headers, data: { currency_code: 'INR', mmk_per_unit: '27', effective_at: '2026-03-01T00:00:00Z', source: 'March quote' } })).status()).toBe(201)
 await page.reload()
 await expect(page.getByTestId('purchase-mmk')).toHaveText('250,000 MMK')
 await page.goto(`/suppliers/${supplier.id}`)
 await expect(page.getByText('250,000 MMK outstanding', { exact: true })).toBeVisible()
 await page.getByRole('link', { name: `PO-${suffix}`, exact: true }).click()
 await expect(page.getByTestId('purchase-mmk')).toHaveText('250,000 MMK')
 await page.goto('/purchases')
 await page.getByRole('searchbox', { name: 'Search purchases' }).fill(`PO-${suffix}`)
 await expect(page.getByRole('link', { name: `PO-${suffix}`, exact: true })).toBeVisible()
 const staffName = `purchase-reader-${suffix}`
 const created = await page.request.post('/api/v1/users', { headers, data: { username: staffName, display_name: 'Purchase reader', password: testPassword } })
 expect(created.status()).toBe(201)
 const staffID = (await created.json()).id
 expect((await page.request.put(`/api/v1/users/${staffID}/permissions`, { headers, data: { permissions: ['purchases.view', 'suppliers.view'] } })).status()).toBe(204)
 const context = await browser.newContext({ baseURL: process.env.E2E_BASE_URL })
 try {
  const other = await context.newPage()
  await signIn(other, staffName)
  await other.goto(`/purchases/${id}`)
  await expect(other.getByText('Purchase costs require purchases.view_cost.', { exact: true })).toBeVisible()
  const hidden = await (await other.request.get(`/api/v1/purchases/${id}`)).json()
  expect(hidden).not.toHaveProperty('total_mmk')
  expect(hidden.items[0]).not.toHaveProperty('unit_price_original')
  expect((await other.request.get(`/api/v1/suppliers/${supplier.id}/balance`)).status()).toBe(403)
  await other.goto('/purchases/new')
  await expect(other.getByRole('heading', { name: 'Access restricted' })).toBeVisible()
 } finally { await context.close() }
})
