import { test,expect } from '@playwright/test'
import { signIn,testPassword } from './session'
test('shipment goods, transportation timeline, expenses and restricted staff access',async({page,browser})=>{
 test.setTimeout(90000)
 await signIn(page,'browser-shipping-owner')
 const suffix=String(Date.now());const headers={Origin:process.env.E2E_BASE_URL!,'X-Pwint-Thit-Request':'1'}
 const supplier=await page.request.post('/api/v1/suppliers',{headers,data:{code:`SH-${suffix}`,name:`Shipping supplier ${suffix}`,is_active:true}});expect(supplier.status()).toBe(201)
 const product=await page.request.post('/api/v1/products',{headers,data:{sku:`SH-${suffix}`,name:`Shipment tea ${suffix}`,barcode:`B${suffix}`,base_unit_code:'BOTTLE',is_active:true,packaging:[{unit_code:'BOTTLE',units_per_pack:'1',is_default_purchase:true,is_default_sale:true},{unit_code:'CARTON',units_per_pack:'12',barcode:`C${suffix}`,is_default_purchase:false,is_default_sale:false}]}});expect(product.status()).toBe(201)
 const purchase=await page.request.post('/api/v1/purchases',{headers,data:{request_id:crypto.randomUUID(),purchase_number:`SHIP-PO-${suffix}`,supplier_id:(await supplier.json()).id,purchased_at:'2026-01-15T00:00:00Z',currency_code:'MMK',mmk_per_unit:'1',items:[{product_id:(await product.json()).id,unit_code:'BOTTLE',quantity:'100',units_per_pack:'1',unit_price_original:'1000',discount_original:'0',tax_original:'0'}]}});expect(purchase.status()).toBe(201)
 await page.goto('/shipments/new')
 await page.getByLabel('Shipment number',{exact:true}).fill(`SH-${suffix}`)
 await page.getByLabel('Origin',{exact:true}).fill('India')
 await page.getByRole('button',{name:'Add warehouse',exact:true}).click()
 await page.getByLabel('Warehouse code',{exact:true}).fill(`WH-${suffix}`)
 await page.getByLabel('Warehouse name',{exact:true}).fill(`Pwint Thit Warehouse ${suffix}`)
 await page.getByRole('button',{name:'Save warehouse',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.getByRole('searchbox',{name:'Find purchased goods'}).fill(suffix)
 await page.getByRole('combobox',{name:'Add purchased item'}).click()
 await page.getByRole('option',{name:new RegExp(`SHIP-PO-${suffix}`)}).click()
 await page.getByLabel(`Quantity: SH-${suffix}`,{exact:true}).fill('60')
 await page.setViewportSize({width:375,height:812})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'/tmp/pwint-shipment-create-mobile.png',fullPage:true})
 await page.getByRole('button',{name:'Create shipment',exact:true}).click()
 await expect(page).toHaveURL(/\/shipments\/[a-f0-9-]{36}$/)
 const id=page.url().split('/').pop()!
 await page.setViewportSize({width:1280,height:900})
 for(const destination of ['City A',`Pwint Thit Warehouse ${suffix}`]){
  await page.getByRole('button',{name:'Add stage',exact:true}).click()
  await page.getByLabel('Destination',{exact:true}).fill(destination)
  await page.getByLabel('Provider',{exact:true}).fill('Regional transport')
  await page.getByLabel('Transportation fee (MMK)',{exact:true}).fill('30000.1234')
  await page.getByLabel('Loading fee (MMK)',{exact:true}).fill('350')
  await page.getByRole('button',{name:'Save changes',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
 }
 await expect(page.getByTestId('transport-total')).toHaveText('60,700.2468 MMK')
 await page.getByRole('button',{name:'Edit stage 1',exact:true}).click()
 await page.getByLabel('Additional charges (MMK)',{exact:true}).fill('100')
 await page.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(page.getByTestId('transport-total')).toHaveText('60,800.2468 MMK')
 await page.getByRole('button',{name:'Add expense',exact:true}).click()
 await page.getByLabel('Category',{exact:true}).fill('Customs')
 await page.getByLabel('Description',{exact:true}).fill('Border clearance')
 await page.getByRole('combobox',{name:'Expense currency',exact:true}).click()
 await page.getByRole('option',{name:'INR',exact:true}).click()
 await page.getByLabel('Original amount',{exact:true}).fill('100.1234')
 await page.getByLabel('MMK per currency unit',{exact:true}).fill('25')
 await page.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(page.getByTestId('expense-total')).toHaveText('2,503.085 MMK')
 await page.getByRole('button',{name:'Void expense',exact:true}).click()
 await page.getByLabel('Void reason',{exact:true}).fill('Duplicate receipt')
 await page.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(page.getByTestId('expense-total')).toHaveText('0 MMK')
 await expect(page.getByText('VOIDED',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Mark in transit',exact:true}).click()
 await page.getByLabel('Shipment departure',{exact:true}).fill('2026-01-16T09:00')
 await page.getByRole('button',{name:'Save changes',exact:true}).click()
 await page.getByRole('button',{name:'Mark arrived',exact:true}).click()
 await page.getByLabel('Warehouse arrival',{exact:true}).fill('2026-01-20T09:00')
 await page.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(page.getByText('ARRIVED',{exact:true})).toBeVisible()
 await page.screenshot({path:'/tmp/pwint-shipment-details.png',fullPage:true})
 await page.setViewportSize({width:375,height:812})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'/tmp/pwint-shipment-details-mobile.png',fullPage:true})
 const username=`ship-reader-${suffix}`
 const staff=await page.request.post('/api/v1/users',{headers,data:{username,display_name:'Shipment reader',password:testPassword}});expect(staff.status()).toBe(201)
 expect((await page.request.put(`/api/v1/users/${(await staff.json()).id}/permissions`,{headers,data:{permissions:['shipments.view']}})).status()).toBe(204)
 const context=await browser.newContext({baseURL:process.env.E2E_BASE_URL})
 try{const other=await context.newPage();await signIn(other,username);await other.goto(`/shipments/${id}`);await expect(other.getByRole('heading',{name:`SH-${suffix}`,exact:true})).toBeVisible();await expect(other.getByRole('button',{name:'Add stage',exact:true})).toHaveCount(0);await expect(other.getByTestId('transport-total')).toHaveCount(0)
 await expect(other.getByRole('region',{name:'Landed cost',exact:true})).toHaveCount(0);expect((await other.request.get(`/api/v1/shipments/${id}/landed-cost`)).status()).toBe(403)
 const hidden=await(await other.request.get(`/api/v1/shipments/${id}/stages`)).json();expect(hidden.stages[0]).not.toHaveProperty('total_mmk');expect((await other.request.post(`/api/v1/shipments/${id}/stages`,{headers,data:{}})).status()).toBe(403)
 }finally{await context.close()}

 await page.setViewportSize({width:1280,height:900})
 await page.getByLabel('Sellable quantity 1',{exact:true}).fill('50')
 await page.getByLabel('Costing confirmation note',{exact:true}).fill('Confirmed 50 sellable bottles; all costs complete')
 for(const method of ['Quantity','Purchase value','Weight','Carton quantity','Manual allocation']){
  await page.getByRole('combobox',{name:'Allocation method',exact:true}).click()
  await page.getByRole('option',{name:method,exact:true}).click()
  if(method==='Weight')await page.getByLabel('Total weight (kg) 1',{exact:true}).fill('12.5')
  if(method==='Carton quantity')await page.getByLabel('Carton quantity 1',{exact:true}).fill('5')
  if(method==='Manual allocation'){
   await page.getByLabel('Manual transport (MMK) 1',{exact:true}).fill('60800.2468')
   await page.getByLabel('Manual expenses (MMK) 1',{exact:true}).fill('0')
  }
  await page.getByRole('button',{name:'Calculate landed cost',exact:true}).click()
  await expect(page.getByTestId('landed-total')).toHaveText('120,800.2468 MMK')
  await expect(page.getByTestId('actual-unit-cost')).toHaveText('2,416.004936')
 }
 await page.setViewportSize({width:375,height:812})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('region',{name:'Landed cost',exact:true}).screenshot({path:'/tmp/pwint-landed-cost-mobile.png'})
 await page.setViewportSize({width:1280,height:900})
 await page.getByRole('button',{name:'Review finalization',exact:true}).click()
 await page.getByRole('button',{name:'Finalize landed cost',exact:true}).click()
 await expect(page.getByText('Finalized',{exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'Add stage',exact:true})).toHaveCount(0)
 await page.reload()
 await expect(page.getByTestId('landed-total')).toHaveText('120,800.2468 MMK')
 await expect(page.getByRole('button',{name:'Calculate landed cost',exact:true})).toHaveCount(0)
 await page.getByRole('region',{name:'Landed cost',exact:true}).screenshot({path:'/tmp/pwint-landed-cost-finalized.png'})

 await page.goto(`/products/${(await product.json()).id}`)
 await expect(page.getByRole('region',{name:'Cost journey',exact:true})).toContainText('120,800.2468 MMK')
 await page.getByText('Purchase sources · partial allocation',{exact:true}).click()
 await expect(page.getByText(/60 of 100 base units allocated/)).toBeVisible()
 await page.goto(`/purchases/${(await purchase.json()).id}`)
 await expect(page.getByRole('region',{name:'Cost journey',exact:true}).filter({hasText:'Finalized'})).toContainText('120,800.2468 MMK')
 await page.goto('/shipments');await page.getByRole('searchbox',{name:'Search shipments'}).fill(`SH-${suffix}`);await expect(page.getByRole('link',{name:`SH-${suffix}`,exact:true})).toBeVisible()
 await page.goto(`/receiving/new?shipment=${id}`)
 await page.getByLabel('Receipt number',{exact:true}).fill(`GR-${suffix}`)
 await page.getByLabel('Received cartons 1',{exact:true}).fill('4')
 await page.getByLabel('Received individual units 1',{exact:true}).fill('7')
 await page.getByLabel('Damaged units 1',{exact:true}).fill('5')
 await page.getByLabel('Batch number 1',{exact:true}).fill(`BATCH-${suffix}`)
 await page.getByLabel('Count discrepancy notes 1',{exact:true}).fill('Five bottles missing and five damaged in transit')
 await expect(page.getByTestId('receiving-preview-0')).toHaveText('Received 55 · Missing 5 · Sellable 50')
 await page.setViewportSize({width:375,height:812})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'/tmp/pwint-receiving-mobile.png',fullPage:true})
 await page.getByRole('button',{name:'Review receipt',exact:true}).click()
 await page.getByRole('button',{name:'Post receipt',exact:true}).click()
 await expect(page).toHaveURL(/\/receiving\/[a-f0-9-]{36}$/)
 await expect(page.getByRole('table')).toContainText(`BATCH-${suffix}`)
 await page.goto(`/inventory?q=${suffix}`)
 await expect(page.getByRole('table')).toContainText('4 cartons + 2 BOTTLE')
 await page.setViewportSize({width:1280,height:900})
 await page.getByRole('button',{name:'Adjust',exact:true}).click()
 await page.getByRole('combobox',{name:'Stock bucket',exact:true}).click()
 await page.getByRole('option',{name:'Reserved',exact:true}).click()
 await page.getByLabel('Quantity change',{exact:true}).fill('12')
 await page.getByLabel('Adjustment reason',{exact:true}).fill('Reserved for confirmed customer collection')
 await page.getByRole('button',{name:'Post adjustment',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(page.getByRole('table')).toContainText('3 cartons + 2 BOTTLE')
 await page.screenshot({path:'/tmp/pwint-inventory.png',fullPage:true})
 await page.getByRole('link',{name:'History',exact:true}).click()
 await expect(page.getByRole('table')).toContainText('Reserved for confirmed customer collection')
 await expect(page.getByRole('table')).toContainText('RECEIPT')
 await page.screenshot({path:'/tmp/pwint-stock-movements.png',fullPage:true})

 await page.goto('/batches')
 await page.getByRole('searchbox',{name:'Search batches'}).fill(suffix)
 await expect(page.getByRole('table')).toContainText(`BATCH-${suffix}`)
 await expect(page.getByRole('table')).toContainText('120,800.2468')
 await page.getByRole('button',{name:new RegExp(`BATCH-${suffix}`)}).click()
 await expect(page.getByRole('dialog')).toContainText('Initially sellable')
 await expect(page.getByRole('dialog')).toContainText('50')
 await page.getByRole('button',{name:'Close',exact:true}).click()
 await page.getByRole('combobox',{name:'Expiry filter'}).click()
 await page.getByRole('option',{name:'Expired',exact:true}).click()
 await expect(page.getByRole('heading',{name:'No records yet',exact:true})).toBeVisible()

 await page.goto('/pos')
 await page.getByRole('combobox',{name:'POS warehouse',exact:true}).click()
 await page.getByRole('option',{name:`Pwint Thit Warehouse ${suffix}`,exact:true}).click()
 await page.getByLabel('Scan barcode or search products',{exact:true}).fill(`SH-${suffix}`)
 await page.getByRole('button',{name:`Prices SH-${suffix}`,exact:true}).click()
 await page.getByLabel('Retail price',{exact:true}).fill('4000')
 await page.getByLabel('Wholesale price',{exact:true}).fill('3500')
 await page.getByRole('button',{name:'Save prices',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.getByRole('button',{name:`Prices SH-${suffix}`,exact:true}).click()
 await page.getByRole('combobox',{name:'Pricing unit',exact:true}).click()
 await page.getByRole('option',{name:/CARTON/}).click()
 await page.getByLabel('Retail price',{exact:true}).fill('48000')
 await page.getByLabel('Wholesale price',{exact:true}).fill('42000')
 await page.getByRole('button',{name:'Save prices',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.getByLabel('Scan barcode or search products',{exact:true}).fill(`C${suffix}`)
 await page.getByLabel('Scan barcode or search products',{exact:true}).press('Enter')
 await expect(page.getByTestId('pos-total')).toHaveText('48,000 MMK')
 await page.getByRole('combobox',{name:'Pricing mode',exact:true}).click()
 await page.getByRole('option',{name:'Wholesale prices',exact:true}).click()
 await expect(page.getByTestId('pos-total')).toHaveText('42,000 MMK')
 await page.getByLabel(`Discount SH-${suffix}`,{exact:true}).fill('1000')
 await page.getByLabel('Discount / approval reason',{exact:true}).fill('Approved wholesale loyalty discount')
 await page.getByLabel('Amount received (MMK)',{exact:true}).fill('50000')
 await page.getByRole('button',{name:'Add customer',exact:true}).click()
 await page.getByLabel('Customer name',{exact:true}).fill(`POS Customer ${suffix}`)
 await page.getByRole('button',{name:'Save customer',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.keyboard.press('F2')
 await expect(page.getByLabel('Scan barcode or search products',{exact:true})).toBeFocused()
 await page.screenshot({path:'/tmp/pwint-pos-desktop.png',fullPage:true})
 await page.setViewportSize({width:375,height:812})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'/tmp/pwint-pos-mobile.png',fullPage:true})
 await page.setViewportSize({width:1280,height:900})
 await page.keyboard.press('F8')
 await expect(page.getByRole('dialog',{name:'Review checkout',exact:true})).toContainText('9,000 MMK')
 await page.getByRole('button',{name:'Complete sale',exact:true}).click()
 await expect(page).toHaveURL(/\/sales\/[a-f0-9-]{36}$/)
 await expect(page.getByRole('article')).toContainText('41,000 MMK')
 await expect(page.getByRole('article')).toContainText(`POS Customer ${suffix}`)
 await page.screenshot({path:'/tmp/pwint-pos-invoice.png',fullPage:true})
 await page.emulateMedia({media:'print'})
 await expect(page.getByText('Internal costing · excluded from print')).not.toBeVisible()
 await expect(page.getByRole('button',{name:'Sign out',exact:true})).not.toBeVisible()
 await expect(page.getByRole('article')).toBeVisible()
 await page.screenshot({path:'/tmp/pwint-pos-invoice-print.png',fullPage:true})
 await page.emulateMedia({media:'screen'})
 await page.goto(`/inventory?q=${suffix}`)
 await expect(page.getByRole('table')).toContainText('2 cartons + 2 BOTTLE')
 await page.getByRole('link',{name:'History',exact:true}).click()
 await expect(page.getByRole('table')).toContainText('SALE')

})
