import {test,expect} from '@playwright/test'
import {signIn} from './session'
test('product packaging, independent prices and partial supplier payments',async({page})=>{
 test.setTimeout(90000)
 await signIn(page,'browser-packaging-owner')
 const suffix=String(Date.now()),headers={Origin:process.env.E2E_BASE_URL!,'X-Pwint-Thit-Request':'1'}
 await page.goto('/products/new')
 await page.getByLabel('Product name',{exact:true}).fill(`Shampoo ${suffix}`)
 await page.getByRole('combobox',{name:'Base stock unit',exact:true}).click()
 await page.getByRole('option',{name:'Bottle',exact:true}).click()
 await page.getByRole('combobox',{name:'Purchase packaging type',exact:true}).click()
 await page.getByRole('option',{name:'Carton',exact:true}).click()
 await page.getByLabel('Base units per pack 2',{exact:true}).fill('16')
 await page.getByLabel('Reference purchase price per Carton (MMK)',{exact:true}).fill('160000')
 await expect(page.getByText('10,000 MMK',{exact:true})).toBeVisible()
 await page.getByLabel('Retail price per Bottle (MMK)',{exact:true}).fill('12000')
 await page.getByLabel('Wholesale price per Bottle (MMK)',{exact:true}).fill('12000')
 await page.getByLabel('Retail price per Carton (MMK)',{exact:true}).fill('176000')
 await page.getByLabel('Wholesale price per Carton (MMK)',{exact:true}).fill('176000')
 await page.getByRole('button',{name:'Create product',exact:true}).click()
 await expect(page).toHaveURL(/\/products\/[a-f0-9-]{36}$/)
 const product=await(await page.request.get(`/api/v1/products/${page.url().split('/').pop()}`)).json()
 expect(product.packaging.find((p:{unit_code:string})=>p.unit_code==='CARTON').units_per_pack).toBe('16.000000')
 const supplier=await(await page.request.post('/api/v1/suppliers',{headers,data:{name:`Payments supplier ${suffix}`,is_active:true}})).json()
 const res=await page.request.post('/api/v1/purchases',{headers,data:{request_id:crypto.randomUUID(),supplier_id:supplier.id,purchased_at:'2026-01-15T00:00:00Z',currency_code:'MMK',mmk_per_unit:'1',items:[{product_id:product.id,unit_code:'CARTON',quantity:'80',units_per_pack:'16',unit_price_original:'160000'}]}})
 expect(res.status(),await res.text()).toBe(201)
 const purchase=await res.json()
 expect(purchase.items[0].base_quantity).toBe('1280.000000')
 await page.goto(`/purchases/${purchase.id}`)
 const wh=await(await page.request.post('/api/v1/warehouses',{headers,data:{code:`PACK-${suffix}`,name:`Packaging warehouse ${suffix}`}})).json()
 for(let shipment=0;shipment<2;shipment++){
  await page.getByRole('button',{name:'Arrange shipment',exact:true}).click()
  await page.getByLabel('Origin',{exact:true}).fill('Supplier')
  await page.getByRole('combobox',{name:'Final warehouse',exact:true}).click()
  await page.getByRole('option',{name:`Packaging warehouse ${suffix}`,exact:true}).click()
  await page.getByLabel('Enter CARTON packages',{exact:true}).check()
  await page.getByLabel(`Quantity: ${product.sku}`,{exact:true}).fill('40')
  await page.getByRole('button',{name:'Create shipment',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  if(shipment===0){
   const excess=await page.request.post('/api/v1/shipments',{headers,data:{request_id:crypto.randomUUID(),start_location:'Supplier',destination_warehouse_id:wh.id,items:[{purchase_item_id:purchase.items[0].id,expected_quantity:'656'}]}})
   expect(excess.status()).toBe(409)
  }
 }
 const workflow=await(await page.request.get(`/api/v1/purchases/${purchase.id}/workflow`)).json()
 expect(workflow.shipments).toHaveLength(2)
 expect(workflow.choices[0].available_quantity).toBe('0.000000')
 const section=page.getByRole('region',{name:'Supplier payments',exact:true})
 await section.getByRole('button',{name:'Record Payment',exact:true}).click()
 await page.getByLabel('Payment amount (MMK)',{exact:true}).fill('4000000')
 await page.getByRole('combobox',{name:'Payment method',exact:true}).click()
 await page.getByRole('option',{name:'KBZPay',exact:true}).click()
 await page.getByRole('button',{name:'Confirm Payment',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(section).toContainText('Partially Paid')
 await expect(section).toContainText('8,800,000 MMK')
 await page.goto('/supplier-payments')
 await page.getByRole('searchbox',{name:'Search supplier payments'}).fill(suffix)
 await page.getByRole('combobox',{name:'Payment status filter',exact:true}).click()
 await page.getByRole('option',{name:'PARTIALLY PAID',exact:true}).click()
 await page.getByRole('table').getByRole('button',{name:'Record Payment',exact:true}).click()
 await page.getByLabel('Payment amount (MMK)',{exact:true}).fill('8800001')
 await page.getByRole('button',{name:'Confirm Payment',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('Payment amount cannot exceed the remaining balance.')
 await page.getByLabel('Payment amount (MMK)',{exact:true}).fill('8800000')
 await page.getByRole('button',{name:'Confirm Payment',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(section.getByRole('button',{name:'Record Payment',exact:true})).toHaveCount(0)
 await expect(section.getByRole('table').getByRole('row')).toHaveCount(3)
 await page.goto(`/purchases/${purchase.id}`)
 await page.reload()
 await expect(section).toContainText('KBZPay')
 await page.goto('/supplier-payments')
 await page.getByRole('searchbox',{name:'Search supplier payments'}).fill(suffix)
 await expect(page.getByRole('table')).toContainText(purchase.purchase_number)
 await expect(page.getByRole('table')).toContainText('Paid')
 await page.setViewportSize({width:375,height:812})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'/tmp/pwint-supplier-payments-mobile.png',fullPage:true})
})
