import { test, expect } from '@playwright/test'
import { signIn, testPassword } from './session'

test('supplier CRUD, contacts, filters, purchase history and permission boundaries', async ({ page, browser }) => {
  test.setTimeout(60000)
  await signIn(page)
  const suffix = String(Date.now())
  const name = `Supplier ${suffix}`
  const code = `SUP-${suffix}`
  const headers = { Origin: process.env.E2E_BASE_URL!, 'X-Pwint-Thit-Request': '1' }
  await page.getByRole('link', { name: 'Suppliers', exact: true }).click()
  await page.getByRole('link', { name: 'Add Supplier', exact: true }).click()
  await page.getByLabel('Supplier name', { exact: true }).fill(name)
  await page.getByLabel('Supplier code', { exact: true }).fill(code)
  await page.getByLabel('Contact person', { exact: true }).fill('Daw May')
  await page.getByLabel('Phone number', { exact: true }).fill('+95 09123456')
  await page.getByLabel('Country', { exact: true }).fill('MM')
  await page.getByLabel('Supplier type', { exact: true }).fill('Wholesaler')
  await page.getByLabel('Address', { exact: true }).fill('Mandalay\nWarehouse 2')
  await page.getByLabel('Payment terms', { exact: true }).fill('Net 30 days')
  await page.getByLabel('Notes', { exact: true }).fill('Call before delivery')
  await page.getByRole('button', { name: 'Create supplier', exact: true }).click()
  await expect(page).toHaveURL(/\/suppliers\/[a-f0-9-]{36}$/)
  const id = page.url().split('/').pop()!
  await expect(page.getByText('Daw May', { exact: true })).toBeVisible()
  await expect(page.getByText('Net 30 days', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'No purchases recorded' })).toBeVisible()
  await page.getByRole('link', { name: 'Edit Supplier', exact: true }).click()
  await page.getByLabel('Supplier name', { exact: true }).fill(`${name} updated`)
  await page.getByLabel('Status', { exact: true }).selectOption('inactive')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('heading', { name: `${name} updated`, exact: true })).toBeVisible()
  await expect(page.getByText('Inactive', { exact: true })).toBeVisible()
  await page.screenshot({ path: '/tmp/pwint-supplier-details.png', fullPage: true })
  await page.goto('/suppliers')
  await page.getByRole('searchbox', { name: 'Search suppliers' }).fill(code)
  await page.getByLabel('Country filter', { exact: true }).fill('MM')
  await page.getByLabel('Status', { exact: true }).selectOption('inactive')
  await expect(page.getByRole('link', { name: `${name} updated`, exact: true })).toBeVisible()
  await page.getByLabel('Status', { exact: true }).selectOption('active')
  await expect(page.getByRole('heading', { name: 'No matching suppliers' })).toBeVisible()
  await page.getByRole('button', { name: 'Reset filters', exact: true }).click()
  for (let i = 0; i < 11; i++) {
    expect((await page.request.post('/api/v1/suppliers', { headers, data: { code: `SP-${suffix}-${i}`, name: `Page suppliers ${suffix} ${i}`, is_active: true } })).status()).toBe(201)
  }
  await page.getByRole('searchbox', { name: 'Search suppliers' }).fill(`Page suppliers ${suffix}`)
  await page.getByLabel('Rows per page', { exact: true }).selectOption('10')
  await expect(page.getByText('1–10 of 11 records', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.getByText('11–11 of 11 records', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 375, height: 812 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '/tmp/pwint-suppliers-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 800 })
  const historySupplier = (await (await page.request.get('/api/v1/suppliers?q=E2E-HISTORY')).json()).suppliers[0]
  await page.goto(`/suppliers/${historySupplier.id}`)
  await expect(page.getByText('E2E-PO-1', { exact: true })).toBeVisible()
  await expect(page.getByText('370370367.3704 MMK', { exact: true })).toHaveCount(10)
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.getByText('E2E-PO-11', { exact: true })).toBeVisible()
  await page.screenshot({ path: '/tmp/pwint-supplier-history.png', fullPage: true })
  const staffName = `supplier-reader-${suffix}`
  const created = await page.request.post('/api/v1/users', { headers, data: { username: staffName, display_name: 'Supplier reader', password: testPassword } })
  expect(created.status()).toBe(201)
  const staffID = (await created.json()).id
  expect((await page.request.put(`/api/v1/users/${staffID}/permissions`, { headers, data: { permissions: ['suppliers.view', 'purchases.view'] } })).status()).toBe(204)
  const context = await browser.newContext({ baseURL: process.env.E2E_BASE_URL })
  try {
    const other = await context.newPage()
    await signIn(other, staffName)
    await other.goto(`/suppliers/${historySupplier.id}`)
    await expect(other.getByText('E2E-PO-1', { exact: true })).toBeVisible()
    await expect(other.getByRole('columnheader', { name: 'Purchase total' })).not.toBeVisible()
    const history = await (await other.request.get(`/api/v1/suppliers/${historySupplier.id}/purchases`)).json()
    expect(history.purchases[0]).not.toHaveProperty('total_original')
    await expect(other.getByRole('link', { name: 'Edit Supplier', exact: true })).not.toBeVisible()
    await other.goto('/suppliers/new')
    await expect(other.getByRole('heading', { name: 'Access restricted' })).toBeVisible()
    expect((await other.request.delete(`/api/v1/suppliers/${id}`, { headers, data: { version: '2' } })).status()).toBe(403)
  } finally { await context.close() }
  await page.goto(`/suppliers/${id}`)
  await page.getByRole('button', { name: 'Archive supplier', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Archive supplier', exact: true }).click()
  await expect(page).toHaveURL(/\/suppliers$/)
  await page.getByRole('searchbox', { name: 'Search suppliers' }).fill(code)
  await expect(page.getByRole('heading', { name: 'No matching suppliers' })).toBeVisible()
  await page.getByLabel('Status', { exact: true }).selectOption('archived')
  await expect(page.getByRole('link', { name: `${name} updated`, exact: true })).toBeVisible()
})
