import { test,expect } from '@playwright/test'
import { signIn } from './session'
test('warehouse shipment preserves source cost, adds cargo on receipt and exposes business data and demo',async({page})=>{
 test.setTimeout(120000)
 await signIn(page,'browser-packaging-owner')
 const suffix=crypto.randomUUID().slice(0,8),headers={Origin:process.env.E2E_BASE_URL!,'X-Pwint-Thit-Request':'1'}
 const post=async(path:string,data:unknown,status=201)=>{const r=await page.request.post(`/api/v1${path}`,{headers,data});expect(r.status(),await r.text()).toBe(status);return status===204?null:r.json()}
 const get=async(path:string)=>{const r=await page.request.get(`/api/v1${path}`);expect(r.status(),await r.text()).toBe(200);return r.json()}
 const product=await post('/products',{name:`Transfer goods ${suffix}`,base_unit_code:'BOTTLE',is_active:true,packaging:[{unit_code:'BOTTLE',units_per_pack:'1',is_default_purchase:true,is_default_sale:true,retail_price_mmk:'150',wholesale_price_mmk:'150'},{unit_code:'CARTON',units_per_pack:'2'}]})
 const supplier=await post('/suppliers',{name:`Transfer supplier ${suffix}`,is_active:true})
 const source=await post('/warehouses',{name:`Source ${suffix}`,code:`S-${suffix}`}),destination=await post('/warehouses',{name:`Destination ${suffix}`,code:`D-${suffix}`})
 const purchase=await post('/purchases',{request_id:crypto.randomUUID(),supplier_id:supplier.id,purchased_at:'2026-01-15T00:00:00Z',currency_code:'MMK',mmk_per_unit:'1',items:[{product_id:product.id,unit_code:'BOTTLE',units_per_pack:'1',quantity:'10',unit_price_original:'100'}]})
 const shipment=await post('/shipments',{request_id:crypto.randomUUID(),start_location:'Supplier',destination_warehouse_id:source.id,items:[{purchase_item_id:purchase.items[0].id,expected_quantity:'10'}]})
 for(const status of ['IN_TRANSIT','ARRIVED']){const current=await get(`/shipments/${shipment.id}`);const r=await page.request.put(`/api/v1/shipments/${shipment.id}/status`,{headers,data:{version:current.version,status,shipped_at:'2026-01-16T00:00:00Z',arrived_at:status==='ARRIVED'?'2026-01-17T00:00:00Z':''}});expect(r.status(),await r.text()).toBe(204)}
 const cost=await get(`/shipments/${shipment.id}/landed-cost`),input={version:cost.source.version,method:'QUANTITY',notes:'Confirmed receipt of all source goods',items:[{id:cost.source.items[0].id,received_quantity:'10',damaged_quantity:'0'}]}
 const preview=await post(`/shipments/${shipment.id}/landed-cost/preview`,input,200)
 await post(`/shipments/${shipment.id}/landed-cost/finalize`,{...input,preview_token:preview.preview_token})
 const receipt=await get(`/receiving/shipments/${shipment.id}`)
 await post('/receiving',{request_id:crypto.randomUUID(),shipment_id:shipment.id,version:receipt.version,received_at:'2026-01-18T00:00:00Z',items:[{shipment_item_id:receipt.items[0].id,carton_size:'2',received_cartons:'5',received_units:'0',damaged_quantity:'0',batch_number:`LOT-${suffix}`,notes:''}]})
 await page.goto('/transfers/new')
 for(const [label,name] of [['From warehouse',`Source ${suffix}`],['To warehouse',`Destination ${suffix}`]]){await page.getByRole('combobox',{name:label,exact:true}).click();await page.getByRole('option',{name,exact:true}).click()}
 await page.getByRole('button',{name:'Add batch',exact:true}).click()
 await page.getByLabel(`Dispatch quantity ${product.sku}`,{exact:true}).fill('6')
 await page.getByRole('button',{name:'Dispatch shipment',exact:true}).click()
 await expect(page).toHaveURL(/\/shipments\/[a-f0-9-]{36}$/)
 const id=page.url().split('/').pop()!
 expect((await get(`/inventory?warehouse_id=${source.id}`)).stock[0].available_quantity).toBe('4.000000')
 expect((await get(`/inventory?warehouse_id=${destination.id}`)).stock).toHaveLength(0)
 await page.getByRole('button',{name:'Add stage',exact:true}).click()
 await page.getByLabel('Destination',{exact:true}).fill(`Destination ${suffix}`)
 await page.getByLabel('Provider',{exact:true}).fill(`Cargo ${suffix}`)
 await expect(page.getByLabel('Package Quantity',{exact:true})).toHaveValue('3.000000')
 await page.getByLabel('Fee per Package (MMK)',{exact:true}).fill('20')
 await expect(page.getByRole('dialog')).toContainText('Total Cargo Fee: 60 MMK')
 await page.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.getByRole('button',{name:'Receive warehouse shipment',exact:true}).click()
 await expect(page.getByRole('dialog')).toContainText('Sellable: 6 BOTTLE · Missing: 0 BOTTLE')
 await page.getByRole('button',{name:'Confirm receipt and landed costs',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(page.getByRole('table',{name:'Warehouse shipment goods'})).toContainText('100 → 110')
 await page.reload()
 expect((await get(`/inventory?warehouse_id=${source.id}`)).stock[0].unit_cost_mmk).toBe('100.00000000')
 const destStock=(await get(`/inventory?warehouse_id=${destination.id}`)).stock[0]
 expect(destStock.available_quantity).toBe('6.000000');expect(destStock.unit_cost_mmk).toBe('110.00000000')
 const quote=await post('/pos/quote',{request_id:crypto.randomUUID(),warehouse_id:destination.id,pricing_mode:'RETAIL',payment_method:'CASH',tender_mmk:'150',sell_on_credit:false,items:[{product_id:product.id,unit_code:'BOTTLE',units_per_pack:'1',quantity:'1',unit_price_mmk:'150',discount_mmk:'0'}]},200)
 expect(quote.lines[0].cost_mmk).toBe('110.0000')
 expect((await get(`/transfers/${id}`)).status).toBe('RECEIVED')
 await page.goto('/business-data')
 await expect(page.getByRole('heading',{name:'Business data',exact:true})).toBeVisible()
 await page.getByRole('combobox',{name:'Report',exact:true}).click();await page.getByRole('option',{name:'Inventory Report',exact:true}).click()
 await expect(page.getByRole('columnheader',{name:'Inbound sellable',exact:true})).toBeVisible()
 await expect(page.getByRole('columnheader',{name:'Outbound sellable',exact:true})).toBeVisible()
 await page.getByRole('combobox',{name:'Report',exact:true}).click();await page.getByRole('option',{name:'Payment Ledger',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Payment Ledger',exact:true})).toBeVisible()
 await page.goto('/assistant')
 await expect(page.getByRole('status')).toContainText('Sample responses')
 await page.getByRole('button',{name:'Summarize sales',exact:true}).click()
 await expect(page.getByRole('log')).toContainText('illustrative data only')
 await page.getByLabel('Ask a question',{exact:true}).fill('How are transfer costs calculated?')
 await page.getByRole('button',{name:'Send',exact:true}).click()
 await expect(page.getByRole('log')).toContainText('preserves the source batch cost')
 await page.setViewportSize({width:375,height:812})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'/tmp/pwint-assistant-demo.png',fullPage:true})
})
