import { CostJourney } from '@/components/costs/cost-journey'
import { useState } from 'react'
import { Package, Truck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { PageHeader, StatCard, DataTable, FilterBar, SearchInput, Modal, Drawer, ConfirmDialog, FormField, CurrencyInput, QuantityInput, StatusBadge, EmptyState, LoadingState, PermissionGuard } from '@/components/shared'
import { permissions, type CurrentUser } from '@/permissions'
const samples = [
  { id: 'DEMO-001', name: 'Bottled beverage', unit: 'Carton · 12 bottles', status: 'Preparing' },
  { id: 'DEMO-002', name: 'Household soap', unit: 'Carton · 24 packs', status: 'In transit' },
  { id: 'DEMO-003', name: 'Packaged tea', unit: 'Carton · 20 boxes', status: 'Received' },
]
export default function DesignSystem({ current }: { current: CurrentUser }) {
  const [search, setSearch] = useState('')
  const [overlay, setOverlay] = useState<'modal' | 'drawer' | 'confirm' | null>(null)
  const [amount, setAmount] = useState('250000.0000')
  const [quantity, setQuantity] = useState('12')
  const [saved, setSaved] = useState(false)
  const [confirmed, setConfirmed] = useState(false)
  const [fieldError, setFieldError] = useState('')
  return <><PageHeader eyebrow="System / Component reference" title="Pwint Thit UI library" description="Reusable patterns for distribution operations. Everything on this page is a preview; no business records are created." />
    <section className="mb-6 grid gap-4 sm:grid-cols-3"><StatCard label="Primary action" value="#ba0d0d" detail="Red · actions and active navigation" icon={<Package />} /><StatCard label="Attention & pending" value="#f7a712" detail="Yellow · warnings and secondary emphasis" icon={<Truck />} /><StatCard label="Financial figures" value="250,000.0000" detail="MMK · tabular numerals, exact decimal text" /></section>
    <div className="mb-6"><CostJourney sources={[{amount:'10000',currency:'INR',rate:'25',reference:'Illustrative purchase'}]} converted="250000" transport="40000" other="10000" landed="300000" scope="Illustrative example · one complete lot" canPreviewProfit examplePrice="340000"/></div><section className="panel mb-6 p-5"><h2 className="text-sm font-semibold">Actions & status</h2><div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => setOverlay('modal')}>Preview modal</Button><Button variant="outline" onClick={() => setOverlay('drawer')}>Preview drawer</Button><Button variant="outline" onClick={() => setOverlay('confirm')}>Preview confirmation</Button><Button disabled>Unavailable action</Button></div><div className="mt-5 flex flex-wrap gap-2"><StatusBadge>Draft</StatusBadge><StatusBadge tone="warning">Preparing</StatusBadge><StatusBadge tone="info">In transit</StatusBadge><StatusBadge tone="success">Received</StatusBadge><StatusBadge tone="danger">Cancelled</StatusBadge></div>{confirmed && <p role="status" className="mt-4 text-xs text-emerald-800">Preview confirmed. No records changed.</p>}</section>
    <section className="mb-6"><h2 className="mb-4 text-sm font-semibold">Searchable, sortable records</h2><FilterBar onReset={search ? () => setSearch('') : undefined} summary="Sample records"><SearchInput value={search} onValueChange={setSearch} label="Search sample records" /></FilterBar><DataTable key={search} caption="Sample distribution records" rows={samples.filter(r => r.name.toLowerCase().includes(search.toLowerCase()))} rowKey={r => r.id} pageSize={2} columns={[{ id: 'name', header: 'Product', compare: (a, b) => a.name.localeCompare(b.name), cell: r => <div className="min-w-36"><p className="font-medium">{r.name}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{r.id}</p></div> }, { id: 'unit', header: 'Packaging', cell: r => <span className="whitespace-nowrap text-xs">{r.unit}</span> }, { id: 'status', header: 'Status', cell: r => <StatusBadge tone={r.status === 'Received' ? 'success' : r.status === 'Preparing' ? 'warning' : 'info'}>{r.status}</StatusBadge> }]} /></section>
    <div className="grid items-start gap-6 xl:grid-cols-2"><section className="panel p-5"><h2 className="text-sm font-semibold">Exact-value inputs</h2><p className="mb-5 mt-2 text-xs leading-5 text-muted-foreground">Amounts and quantities retain their entered decimal precision. Preview validation only.</p><form className="space-y-4" onSubmit={e => { e.preventDefault(); setSaved(true) }}><FormField label="Purchase amount (MMK)" required hint="Up to 4 decimal places.">{p => <CurrencyInput {...p} value={amount} onValueChange={v => { setAmount(v); setSaved(false) }} />}</FormField><FormField label="Received quantity (bottles)" required hint="Up to 6 decimal places.">{p => <QuantityInput {...p} unit="bottles" value={quantity} onValueChange={v => { setQuantity(v); setSaved(false) }} />}</FormField><FormField label="Reference" error={fieldError} hint="Optional shipment reference.">{p => <input {...p} className="field" placeholder="e.g. SHP-0001" onChange={() => setFieldError('')} />}</FormField><div className="flex flex-wrap gap-2"><Button type="submit">Validate preview</Button><Button type="button" variant="ghost" onClick={() => setFieldError('A shipment reference is required for this example.')}>Show field error</Button></div>{saved && <p role="status" className="break-all text-xs text-emerald-800">Valid preview: {amount} MMK · {quantity} bottles</p>}</form></section><div className="space-y-6"><section className="panel"><EmptyState title="No shipments to receive" description="Incoming shipments will appear here when receiving is connected." /></section><section className="panel"><LoadingState label="Loading preview…" /></section><PermissionGuard user={current} permission={permissions.settingsManage}><p className="text-xs text-muted-foreground">This component reference is visible with settings.manage access.</p></PermissionGuard></div></div>
    <Modal fullScreen open={overlay === 'modal'} onOpenChange={open => { if (!open) setOverlay(null) }} title="Shipment note preview" description="Modal pattern for focused forms. This does not save a shipment." footer={<Button variant="outline" onClick={() => setOverlay(null)}>Done</Button>}><FormField label="Note">{p => <textarea {...p} className="field min-h-28" placeholder="Add context for receiving…" />}</FormField></Modal>
    <Drawer open={overlay === 'drawer'} onOpenChange={open => { if (!open) setOverlay(null) }} title="Shipment detail preview" description="A side panel keeps context close to the record."><StatusBadge tone="info">Sample · In transit</StatusBadge><h3 className="mt-6 text-sm font-semibold">Source → warehouse</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Transportation stages and actual costs will appear here when those modules are built.</p></Drawer>
    <ConfirmDialog open={overlay === 'confirm'} onOpenChange={open => { if (!open) setOverlay(null) }} title="Confirm preview action?" description="This demonstrates a deliberate confirmation step. It does not update business data." confirmLabel="Confirm preview" onConfirm={() => { setConfirmed(true); setOverlay(null) }} />
  </>
}
