import { Check, ChevronDown, Database, RefreshCw, Server, ShieldCheck, Package, Truck, Warehouse, ShoppingBag } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { PageHeader, StatCard, StatusBadge } from '@/components/shared'
import { useHealth } from '@/hooks/use-health'
import { useUIStore } from '@/stores/ui'
export default function Workspace() {
  const health = useHealth()
  const { detailsOpen, toggleDetails } = useUIStore()
  const connected = health.isSuccess && !health.isError
  return <><PageHeader eyebrow="Overview" title="Distribution workspace" description="A clear view of your workspace, from purchase through to sale." actions={<Button variant="outline" onClick={() => void health.refetch()} disabled={health.isFetching}><RefreshCw />{health.isFetching ? 'Checking…' : 'Check again'}</Button>} />
    <div className="grid gap-4 sm:grid-cols-3"><StatCard label="Workspace" value="Ready" detail="Your secure workspace is open" icon={<ShieldCheck />} /><StatCard label="API connection" value={connected ? 'Connected' : health.isError ? 'Unavailable' : 'Checking…'} detail="Live service connection" icon={<Server />} /><StatCard label="Database" value={connected ? 'Connected' : health.isError ? 'Unavailable' : 'Checking…'} detail={connected ? 'PostgreSQL is connected' : 'Waiting for a healthy connection'} icon={<Database />} /></div>
    <div role="status" aria-live="polite" className={`mt-4 flex items-center gap-2 rounded-lg border px-4 py-3 text-xs ${health.isError ? 'border-brand-yellow/40 bg-accent text-amber-900' : connected ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'bg-muted text-muted-foreground'}`}><Check className="size-3.5 shrink-0" />{health.isError ? health.error.message : connected ? 'All systems connected. The foundation is ready.' : 'Checking the workspace connection…'}</div>
    <section className="panel mt-7"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="text-sm font-semibold">The distribution journey</h2><p className="mt-1 text-xs text-muted-foreground">One connected path from supplier purchase to actual cost and sales.</p></div><StatusBadge>Modules ahead</StatusBadge></div><div className="grid gap-0 sm:grid-cols-2 xl:grid-cols-4">{[{ title: 'Purchase', icon: Package, note: 'Supplier prices & currencies' }, { title: 'Transport', icon: Truck, note: 'Stages, expenses & landed cost' }, { title: 'Receive', icon: Warehouse, note: 'Batches & sellable inventory' }, { title: 'Sell', icon: ShoppingBag, note: 'Retail, wholesale & payments' }].map((item, i) => <div key={item.title} className="border-b p-6 last:border-0 xl:border-b-0 xl:border-r"><div className="flex items-center justify-between"><item.icon className="size-5 text-muted-foreground" /><span className="font-mono text-[10px] text-muted-foreground">0{i + 1}</span></div><h3 className="mt-5 text-sm font-semibold">{item.title}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.note}</p></div>)}</div><p className="border-t px-5 py-4 text-xs leading-5 text-muted-foreground">Business modules will be added phase by phase. Financial totals will appear when their workflows are connected.</p></section>
    <div className="mt-6 grid gap-5 sm:grid-cols-[1.5fr_1fr]"><section className="rounded-xl border border-dashed p-5"><h2 className="text-sm font-semibold">Actual cost. Better decisions.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Purchase price is only the beginning. Transportation and shipment expenses stay connected to each batch so the real cost stays visible.</p></section><section className="panel p-2"><Button variant="ghost" onClick={toggleDetails} aria-expanded={detailsOpen} aria-controls="foundation-details" className="w-full justify-between">Foundation details<ChevronDown className="size-4" /></Button>{detailsOpen && <div id="foundation-details" className="px-3 pb-3 text-xs leading-7 text-muted-foreground"><p>React · TypeScript · Go · PostgreSQL</p><p>MMK base currency</p><p>Permission enforcement in the Go API</p></div>}</section></div>
  </>
}
