import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { PageHeader,FormField } from '@/components/shared'
type Message={role:'user'|'assistant';text:string}
const examples=['Summarize sales','Show inbound and outbound stock','Explain customer payments','How are transfer costs calculated?']
function demoAnswer(question:string){
 const q=question.toLowerCase()
 if(/sales|revenue/.test(q))return 'Sample response — illustrative data only: Sales were 1,200,000 MMK, with 900,000 MMK collected and 300,000 MMK outstanding. Customer collections settle invoices and do not count as additional sales. Use Business data → Sales Report for your real recorded figures.'
 if(/stock|inventory|inbound|outbound/.test(q))return 'Sample response — illustrative data only: Warehouse B opened with 100 bottles, received 40 and dispatched or sold 25, leaving 115 sellable bottles. Reserved and damaged quantities are separate. Use Business data → Inventory Report and Stock Movement History for your real figures.'
 if(/payment|debt|credit/.test(q))return 'Sample response — illustrative data only: An invoice of 500,000 MMK with 300,000 MMK paid has 200,000 MMK remaining. Each collection links to its invoice. Supplier and cargo payments are separate. Use Business data to review your real payment ledger and outstanding balances.'
 if(/transfer|cargo|cost/.test(q))return 'Workflow demonstration: a warehouse transfer preserves the source batch cost. Its allocated cargo and additional costs increase the new destination batch’s landed cost. Goods leave source availability at dispatch and become sellable at the destination after receipt. This answer describes the workflow; it does not inspect a real shipment.'
 return 'This demo supports sample questions about sales, inventory, payments and warehouse transfer costs. It does not query your business data or call an AI provider. Try one of the example questions. An API connection will enable broader questions in a later step.'
}
export default function Assistant(){
 const [input,setInput]=useState(''),[messages,setMessages]=useState<Message[]>([])
 const ask=(text:string)=>{const value=text.trim();if(!value)return;setMessages(m=>[...m.slice(-38),{role:'user',text:value},{role:'assistant',text:demoAnswer(value)}]);setInput('')}
 return <><PageHeader eyebrow="Insights / Demo" title="AI assistant demo" description="Try the conversation flow before connecting your AI API." actions={<Button variant="outline" onClick={()=>setMessages([])}>Clear conversation</Button>}/><div className="mx-auto max-w-4xl space-y-4"><p role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm">Demo mode · Sample responses and illustrative figures only. No AI API is connected, no business data is queried, and messages stay in this page until you leave or clear them.</p><div className="flex flex-wrap gap-2">{examples.map(q=><Button key={q} variant="outline" size="sm" onClick={()=>ask(q)}>{q}</Button>)}</div><section role="log" aria-label="Demo conversation" aria-live="polite" className="panel min-h-64 space-y-4 p-5">{!messages.length&&<p className="text-sm text-muted-foreground">Choose a sample question or type your own.</p>}{messages.map((m,i)=><article key={i} className={`max-w-[95%] rounded-xl p-4 sm:max-w-[85%] ${m.role==='user'?'ml-auto bg-primary/5':'border bg-white'}`}><p className="mb-1 text-xs font-semibold">{m.role==='user'?'You':'Demo assistant'}</p><p className="whitespace-pre-wrap break-words text-sm leading-6">{m.text}</p></article>)}</section><form className="flex items-end gap-3" onSubmit={e=>{e.preventDefault();ask(input)}}><div className="min-w-0 flex-1"><FormField label="Ask a question">{p=><textarea {...p} className="field min-h-20" value={input} maxLength={2000} onChange={e=>setInput(e.target.value)} placeholder="Ask about sales, stock, payments or transfers…"/>}</FormField></div><Button disabled={!input.trim()}>Send</Button></form><p className="text-xs text-muted-foreground">Real records are available in <a className="underline" href="/business-data">Business data</a>. API credentials will be configured on the server when a provider is selected.</p></div></>
}
