import { useState } from 'react'
import { useQuery,useMutation,useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Select,SelectItem } from '@/components/ui/select'
import { PageHeader,DataTable,SearchInput,Modal } from '@/components/shared'
import { Field } from '../shipments/Fields'
import { requestJSON,ApiError } from '@/services/api'
import { amount } from '../purchases/types'
import { can,permissions,type CurrentUser } from '@/permissions'
type Expense={id:string;category:string;description:string;incurred_at:string;amount_mmk:string;paid_mmk:string;status:string;notes:string;recorded_by:string}
function businessDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Yangon',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
export default function Expenses({current}:{current:CurrentUser}){const[q,setQ]=useState(''),[page,setPage]=useState(1),[from,setFrom]=useState(''),[to,setTo]=useState(''),[add,setAdd]=useState(false),[reverse,setReverse]=useState<Expense|null>(null);const data=useQuery({queryKey:['expenses',q,page,from,to],queryFn:()=>requestJSON<{expenses:Expense[];total:number}>(`/expenses?q=${encodeURIComponent(q)}&page=${page}&from=${from}&to=${to}`)});return <><PageHeader eyebrow="Finance / Daily costs" title="Operating expenses" description="Business expenses kept separate from purchases and shipment landed costs." actions={<>{can(current,permissions.financeViewProfit)&&<Button asChild variant="outline"><a href="/finance/profit">Profit report</a></Button>}<Button onClick={()=>setAdd(true)}>Record expense</Button></>}/><div className="mb-5 grid items-end gap-3 sm:grid-cols-3"><SearchInput label="Search expenses" value={q} onValueChange={v=>{setQ(v);setPage(1)}}/><Field label="Expenses from" type="date" value={from} onChange={v=>{setFrom(v);setPage(1)}}/><Field label="Expenses to" type="date" value={to} onChange={v=>{setTo(v);setPage(1)}}/></div><p className="mb-3 text-xs text-muted-foreground">Blank dates show the current Myanmar month. Correct posted entries using a reversal.</p><DataTable caption="Operating expenses" rows={data.data?.expenses||[]} rowKey={r=>r.id} loading={data.isPending} error={data.error?.message} pagination={{page,pageSize:20,total:data.data?.total||0,onPageChange:setPage}} columns={[{id:'description',header:'Expense',cell:r=><>{r.description}<span className="block text-xs text-muted-foreground">{r.category} · {r.recorded_by}</span></>},{id:'date',header:'Incurred',cell:r=>new Date(r.incurred_at).toLocaleDateString('en-GB',{timeZone:'Asia/Yangon'})},{id:'amount',header:'Amount (MMK)',cell:r=>amount(r.amount_mmk)},{id:'paid',header:'Paid (MMK)',cell:r=>amount(r.paid_mmk)},{id:'status',header:'Status',cell:r=><span className="rounded-full bg-muted px-2 py-1 text-xs">{r.status}</span>},{id:'actions',header:'Correction',cell:r=>r.status==='POSTED'&&can(current,permissions.transactionsReverse)&&can(current,permissions.paymentsManage)&&<Button size="sm" variant="outline" onClick={()=>setReverse(r)}>Reverse</Button>}]}/>{add&&<Post current={current} close={()=>setAdd(false)}/>} {reverse&&<Reverse expense={reverse} close={()=>setReverse(null)}/>}</>}
function Post({current,close}:{current:CurrentUser;close:()=>void}){const[request]=useState(()=>crypto.randomUUID()),[category,setCategory]=useState(''),[description,setDescription]=useState(''),[date,setDate]=useState(businessDate),[amount,setAmount]=useState(''),[notes,setNotes]=useState(''),[paid,setPaid]=useState(can(current,permissions.paymentsManage)),[method,setMethod]=useState('CASH'),[reference,setReference]=useState('');const client=useQueryClient();const categories=useQuery({queryKey:['expense-categories'],queryFn:()=>requestJSON<{id:string;name:string}[]>('/expenses/categories')});const save=useMutation({mutationFn:()=>requestJSON('/expenses',{method:'POST',body:JSON.stringify({request_id:request,category_id:category,description,incurred_on:date,amount_mmk:amount,notes,paid_now:paid,method,reference})}),onSuccess:()=>{void client.invalidateQueries({queryKey:['expenses']});void client.invalidateQueries({queryKey:['profit']});close()}});const uncertain=save.error instanceof ApiError&&(save.error.status===0||save.error.status>=500),locked=save.isPending||uncertain;return <Modal open onOpenChange={v=>!v&&!locked&&close()} title="Record operating expense" busy={locked} footer={<Button disabled={save.isPending} onClick={()=>save.mutate()}>{uncertain?'Retry same expense':'Post expense'}</Button>}><fieldset disabled={locked} className="space-y-3"><Select aria-label="Expense category" value={category} onValueChange={setCategory}>{categories.data?.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</Select><Field label="Expense description" value={description} onChange={setDescription}/><div className="grid grid-cols-2 gap-3"><Field label="Incurred date" type="date" value={date} onChange={setDate}/><Field label="Expense amount (MMK)" value={amount} onChange={setAmount}/></div><Field label="Expense notes" value={notes} onChange={setNotes}/>{can(current,permissions.paymentsManage)&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={paid} onChange={e=>setPaid(e.target.checked)}/>Paid now</label>}{paid&&<><Select aria-label="Expense payment method" value={method} onValueChange={setMethod}>{['CASH','BANK_TRANSFER','MOBILE_PAYMENT','OTHER'].map(m=><SelectItem key={m} value={m}>{m.replaceAll('_',' ')}</SelectItem>)}</Select><Field label="Expense payment reference" value={reference} onChange={setReference}/></>}<p className="text-xs text-muted-foreground">Expenses affect profit on the incurred date, whether paid or unpaid.</p></fieldset>{categories.error&&<p role="alert">{categories.error.message}</p>}{save.error&&<p role="alert">{save.error.message}{uncertain&&' Retry the unchanged expense safely.'}</p>}</Modal>}
function Reverse({expense,close}:{expense:Expense;close:()=>void}){const[request]=useState(()=>crypto.randomUUID()),[reason,setReason]=useState('');const client=useQueryClient();const save=useMutation({mutationFn:()=>requestJSON(`/expenses/${expense.id}/reverse`,{method:'POST',body:JSON.stringify({request_id:request,reason})}),onSuccess:()=>{void client.invalidateQueries({queryKey:['expenses']});void client.invalidateQueries({queryKey:['profit']});close()}});const uncertain=save.error instanceof ApiError&&(save.error.status===0||save.error.status>=500),locked=save.isPending||uncertain;return <Modal open onOpenChange={v=>!v&&!locked&&close()} title="Reverse incorrect expense" busy={locked} footer={<Button disabled={save.isPending} onClick={()=>save.mutate()}>Confirm reversal</Button>}><p className="mb-4 text-sm">{expense.description} · {amount(expense.amount_mmk)} MMK. This preserves the original record and posts an offset today, including reversal of its recorded payment.</p><fieldset disabled={locked}><Field label="Expense reversal reason" value={reason} onChange={setReason}/></fieldset>{save.error&&<p role="alert">{save.error.message}</p>}</Modal>}
