import { baseQuantity, basePurchaseCost } from './types'
import { OptionalSection } from '@/components/shared/optional-section'
import { useState, type FormEvent } from 'react'
import { useQuery, useMutation } from '@tanstack/react-query'
import { Plus, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Select, SelectItem } from '@/components/ui/select'
import { PageHeader, FormField, CurrencyInput, QuantityInput, ConfirmDialog, EmptyState } from '@/components/shared'
import { DecimalInput } from '@/components/shared/decimal-input'
import { requestJSON } from '@/services/api'
import { can, permissions, type CurrentUser } from '@/permissions'
import { amount, preview, today, type Currency, type Rate, type SupplierOption, type ProductOption, type LineInput, type Purchase } from './types'

type Row = LineInput & { product: ProductOption; key: string }
export default function PurchaseForm({ current,purchase }: { current: CurrentUser;purchase?:Purchase }) {
 const initialDate=purchase?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Yangon',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(purchase.purchased_at)):today()
 const [reason,setReason]=useState('')
 const [requestID] = useState(() => crypto.randomUUID())
 const [date, setDate] = useState(initialDate)
 const [due, setDue] = useState(purchase?.due_date||'')
 const [invoice, setInvoice] = useState(purchase?.supplier_invoice_number||'')
 const [notes, setNotes] = useState(purchase?.notes||'')
 const [supplierSearch, setSupplierSearch] = useState('')
 const [supplier, setSupplier] = useState<SupplierOption | null>(purchase?{id:purchase.supplier_id,name:purchase.supplier_name,code:''}:null)
 const [productSearch, setProductSearch] = useState('')
 const [productID, setProductID] = useState('')
 const [currency, setCurrency] = useState(purchase?.currency_code||'MMK')
 const [rateID, setRateID] = useState(purchase?.exchange_rate_id||'')
 const [rate, setRate] = useState(purchase?.mmk_per_unit||'1')
 const [rows, setRows] = useState<Row[]>(()=>purchase?.items?.map(i=>({...i,key:i.id,unit_price_original:i.unit_price_original||'0',discount_original:i.discount_original||'0',tax_original:i.tax_original||'0',product:{id:i.product_id,name:i.product_name,sku:i.sku,packaging:[{unit_code:i.unit_code,unit_name:i.unit_name,units_per_pack:i.units_per_pack,is_default_purchase:true}]}}))||[])
 const originalProducts=useQuery({queryKey:['correction-products',purchase?.id],enabled:!!purchase,queryFn:async()=>Promise.all(Array.from(new Set(purchase!.items!.map(i=>i.product_id))).map(id=>requestJSON<ProductOption>(`/products/${id}`)))})
 const [confirm, setConfirm] = useState(false)
 const [validation, setValidation] = useState('')
 const manual = can(current, permissions.exchangeRatesManage)
 const currencies = useQuery({ queryKey: ['currencies'], queryFn: ({ signal }) => requestJSON<Currency[]>('/currencies', { signal }) })
 const suppliers = useQuery({ queryKey: ['purchase-suppliers', supplierSearch], queryFn: ({ signal }) => requestJSON<SupplierOption[]>(`/purchase-options?kind=suppliers&q=${encodeURIComponent(supplierSearch)}`, { signal }) })
 const products = useQuery({ queryKey: ['purchase-products', productSearch], queryFn: ({ signal }) => requestJSON<ProductOption[]>(`/purchase-options?kind=products&q=${encodeURIComponent(productSearch)}`, { signal }) })
 const rates = useQuery({ queryKey: ['rates', currency, date], queryFn: ({ signal }) => requestJSON<Rate[]>(`/exchange-rates?currency=${currency}&as_of=${encodeURIComponent(`${date}T23:59:59+06:30`)}`, { signal }), enabled: currency !== 'MMK' && !!date })
 const lines: LineInput[] = rows.map(({ product_id, unit_code, quantity, units_per_pack, unit_price_original, discount_original, tax_original }) => ({ product_id, unit_code, quantity, units_per_pack, unit_price_original, discount_original, tax_original }))
 const totals = preview(lines, rate)
 const save = useMutation({ mutationFn: () => {const body={request_id:requestID,supplier_id:supplier?.id,supplier_invoice_number:invoice,purchased_at:purchase&&date===initialDate?purchase.purchased_at:`${date}T23:59:59+06:30`,due_date:due,currency_code:currency,exchange_rate_id:rateID,mmk_per_unit:rate,notes,items:lines};return requestJSON<Purchase>(purchase?`/purchases/${purchase.id}/corrections`:'/purchases',{method:'POST',body:JSON.stringify(purchase?{version:purchase.correction_version||'0',reason,purchase:body}:body)})},onSuccess:p=>window.location.assign(`/purchases/${p.id}`) })
 function patch(index: number, patch: Partial<Row>) { setRows(r => r.map((v, i) => i === index ? { ...v, ...patch } : v)) }
 function submit(e: FormEvent) { e.preventDefault();if(purchase&&!reason.trim()){setValidation('Enter a correction reason.');return} if (!supplier || !rows.length || !totals || (currency !== 'MMK' && !rateID && !manual)) { setValidation('Choose a supplier, at least one product, and valid amounts and exchange rate.'); return }; setValidation(''); setConfirm(true) }
 if(purchase&&current.role!=='SUPER_ADMIN')return <EmptyState title="Only Super Admin can correct purchases"/>
 if (!can(current, permissions.purchasesViewCost)) return <EmptyState title="Purchase costs restricted" description="Creating a purchase requires purchases.view_cost as well as purchases.create." />
 const supplierOptions = supplier && !suppliers.data?.some(s => s.id === supplier.id) ? [supplier, ...(suppliers.data || [])] : suppliers.data || []
 return <>
  <PageHeader eyebrow="Purchasing / New transaction" title={purchase?"Correct completed purchase":"Create Purchase"} description={purchase?`${purchase.purchase_number} · Revision ${purchase.correction_version||'0'} · Super Admin correction`:"Record supplier costs in their original currency, with a fixed MMK conversion."} actions={<Button variant="outline" asChild><a href={purchase?`/purchases/${purchase.id}`:"/purchases"}>Cancel</a></Button>} />
  <form onSubmit={submit} className="space-y-5"><fieldset disabled={save.isPending || confirm} className="min-w-0 space-y-5">
   <section className="panel min-w-0 p-5"><h2 className="mb-5 text-sm font-semibold">Purchase information</h2><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
    <div className="text-sm"><p className="text-xs text-muted-foreground">Purchase ID</p><p className="mt-2 font-medium">{purchase?.purchase_number||'Generated automatically when saved'}</p></div>
    <FormField label="Purchase date" required>{p => <input {...p} type="date" className="field" value={date} onChange={e => { setDate(e.target.value); setRateID(''); if (currency !== 'MMK') setRate('') }} />}</FormField>
    <OptionalSection title="Set a payment due date" defaultOpen={!!purchase?.due_date}><FormField label="Payment due date">{p => <input {...p} type="date" min={date} className="field" value={due} onChange={e => setDue(e.target.value)} />}</FormField></OptionalSection>
    <div className="min-w-0 space-y-2"><FormField label="Find supplier">{p => <input {...p} className="field" placeholder="Search name or code…" value={supplierSearch} onChange={e => setSupplierSearch(e.target.value)} />}</FormField><FormField label="Supplier" required>{p => <Select {...p} value={supplier?.id || ''} onValueChange={id => setSupplier(supplierOptions.find(s => s.id === id) || null)}><SelectItem value="">Choose supplier</SelectItem>{supplierOptions.map(s => <SelectItem key={s.id} value={s.id}>{s.name} · {s.code}</SelectItem>)}</Select>}</FormField></div>
    <OptionalSection title="Add supplier invoice reference" defaultOpen={!!purchase?.supplier_invoice_number}><FormField label="Supplier invoice number">{p => <input {...p} className="field" value={invoice} maxLength={200} onChange={e => setInvoice(e.target.value)} />}</FormField></OptionalSection>
    <FormField label="Currency" required>{p => <Select {...p} value={currency} onValueChange={v => { setCurrency(v); setRateID(''); setRate(v === 'MMK' ? '1' : '') }} >{(currencies.data || []).map(c => <SelectItem key={c.code} value={c.code}>{c.code} · {c.name}</SelectItem>)}</Select>}</FormField>
   </div></section>
   {currency !== 'MMK' && <section className="panel min-w-0 p-5"><h2 className="mb-2 text-sm font-semibold">Transaction exchange rate</h2><p className="mb-5 text-xs text-muted-foreground">This rate stays with the purchase. Adding a future rate never changes it.</p><div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
    {currency !== 'MMK' && <FormField label="Historical quote" hint="Quotes effective on or before the purchase date.">{p => <Select {...p} value={rateID} onValueChange={id => { setRateID(id); setRate(rates.data?.find(r => r.id === id)?.mmk_per_unit || '') }}><SelectItem value="">{manual ? 'Enter custom rate' : 'Choose saved quote'}</SelectItem>{(rates.data || []).map(r => <SelectItem key={r.id} value={r.id}>{amount(r.mmk_per_unit)} MMK · {new Date(r.effective_at).toLocaleDateString()} · {r.source}</SelectItem>)}</Select>}</FormField>}
    <FormField label="MMK per currency unit" required hint={currency === 'MMK' ? 'MMK purchases use 1. Choose INR or another foreign currency in Purchase information to enter its exchange rate.' : rateID ? (manual ? 'You can type a different rate here. Editing uses a custom rate for this purchase; the saved quote stays unchanged.' : 'Saved historical rate. Choose another Historical quote to change it.') : `1 ${currency} = this many MMK`}>{p => <DecimalInput {...p} scale={10} integerDigits={14} suffix="MMK" value={rate} readOnly={currency === 'MMK' || !manual} onValueChange={v => { setRateID(''); setRate(v) }} />}</FormField>
   </div>{rates.error && <p role="alert" className="mt-3 text-sm text-destructive">{rates.error.message}</p>}</section>}
   <section className="panel min-w-0 p-5"><h2 className="mb-4 text-sm font-semibold">Purchase items</h2><div className="mb-5 grid grid-cols-1 items-end gap-3 sm:grid-cols-[1fr_1.5fr_auto]">
    <FormField label="Find product">{p => <input {...p} className="field" placeholder="Search name or SKU…" value={productSearch} onChange={e => { setProductSearch(e.target.value); setProductID('') }} />}</FormField>
    <FormField label="Product to add">{p => <Select {...p} value={productID} onValueChange={setProductID}><SelectItem value="">Choose product</SelectItem>{(products.data || []).filter(p => p.packaging.length).map(p => <SelectItem key={p.id} value={p.id}>{p.name} · {p.sku}</SelectItem>)}</Select>}</FormField>
    <Button type="button" variant="outline" disabled={!productID || rows.length >= 100} onClick={() => { const p = products.data?.find(p => p.id === productID); if (!p) return; const pack = p.packaging.find(p => p.is_default_purchase) || p.packaging[0]; setRows(r => [...r, { key: crypto.randomUUID(), product: p, product_id: p.id, unit_code: pack.unit_code, units_per_pack: pack.units_per_pack, quantity: '1', unit_price_original: currency==='MMK'?(pack.purchase_price_mmk||''):'', discount_original: '0', tax_original: '0' }]); setProductID('') }}><Plus />Add item</Button>
   </div>
   {!rows.length && <p className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">Choose a product to start your purchase.</p>}
   <div className="space-y-4">{rows.map((row, i) => <div key={row.key} className="rounded-xl border p-4"><div className="mb-4 flex items-center justify-between gap-3"><div><h3 className="text-sm font-semibold">{row.product.name}</h3><p className="mt-1 text-xs text-muted-foreground">{row.product.sku} · 1 pack = {amount(row.units_per_pack)} base units</p></div><Button type="button" variant="ghost" size="sm" aria-label={`Remove item ${i + 1}`} onClick={() => setRows(r => r.filter(v => v.key !== row.key))}><Trash2 /></Button></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5">
    <FormField label={`Unit ${i + 1}`} required>{p => <Select {...p} value={row.unit_code} onValueChange={v => { const pack = (originalProducts.data?.find(p=>p.id===row.product_id)?.packaging||row.product.packaging).find(p => p.unit_code === v)!; patch(i, { unit_code: v, units_per_pack: pack.units_per_pack, unit_price_original: currency==='MMK'?(pack.purchase_price_mmk||''):'' }) }}>{(originalProducts.data?.find(p=>p.id===row.product_id)?.packaging||row.product.packaging).map(p => <SelectItem key={p.unit_code} value={p.unit_code}>{p.unit_name||p.unit_code}</SelectItem>)}</Select>}</FormField>
    {purchase&&<FormField label={`Units per pack ${i+1}`} required hint="Correct the recorded conversion; product packaging and received batches stay unchanged.">{p=><QuantityInput {...p} value={row.units_per_pack} onValueChange={v=>patch(i,{units_per_pack:v})}/>}</FormField>}
    <FormField label={`Quantity ${i + 1}`} required>{p => <QuantityInput {...p} value={row.quantity} onValueChange={v => patch(i, { quantity: v })} />}</FormField>
    <FormField label={`Price per selected unit ${i + 1}`} required>{p => <CurrencyInput {...p} scale={6} integerDigits={14} currency={currency} value={row.unit_price_original} onValueChange={v => patch(i, { unit_price_original: v })} />}</FormField>
    <OptionalSection title={`Discount / tax ${i + 1}`} defaultOpen={!!purchase}><FormField label={`Line discount ${i + 1}`}>{p => <CurrencyInput {...p} currency={currency} value={row.discount_original} onValueChange={v => patch(i, { discount_original: v })} />}</FormField>
    <FormField label={`Line tax ${i + 1}`}>{p => <CurrencyInput {...p} currency={currency} value={row.tax_original} onValueChange={v => patch(i, { tax_original: v })} />}</FormField></OptionalSection>
   </div><p className="mt-4 text-xs text-muted-foreground">Stock represented: {amount(baseQuantity(row.quantity,row.units_per_pack))} base units · Purchase cost per base unit: {amount(basePurchaseCost(row.unit_price_original,row.units_per_pack))} {currency} before discounts, tax and transport.</p><p className="mt-4 text-right text-sm font-medium">Line total: {amount(totals?.lines[i])} {currency}</p></div>)}</div></section>
   <div className="grid grid-cols-1 gap-5 lg:grid-cols-2"><OptionalSection title="Add purchase notes" defaultOpen={!!purchase?.notes}><FormField label="Notes">{p => <textarea {...p} className="field min-h-28" maxLength={4000} value={notes} onChange={e => setNotes(e.target.value)} />}</FormField></OptionalSection><section className="panel min-w-0 border-primary/15 p-5"><p className="text-xs font-medium text-muted-foreground">Purchase conversion preview</p><p data-testid="original-preview" className="mt-3 break-words text-2xl font-semibold tabular-nums">{amount(totals?.original)} {currency}</p><p data-testid="mmk-preview" className="mt-2 break-words text-lg font-semibold tabular-nums text-primary">{amount(totals?.mmk)} MMK</p><p className="mt-3 text-xs leading-5 text-muted-foreground">{purchase?'Corrected original amount × corrected transaction rate. Saving updates the purchase and supplier balance, with a permanent revision history.':'Original amount × transaction rate. Continue transportation, costing and receiving from this purchase after saving. Posting adds this purchase to the supplier balance; it does not receive stock or record payment.'}</p></section></div>
  {purchase&&<section className="panel space-y-3 p-5"><FormField label="Correction reason" required hint="Saved permanently with your name, timestamp and before/after values.">{p=><textarea {...p} className="field min-h-28" maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/>}</FormField><p className="text-sm text-muted-foreground">This corrects the purchase record and supplier balance. Existing payments remain linked with their original amounts and rates. Received quantities, finalized batch costs and past invoices remain recorded facts; physical stock discrepancies require a separate inventory adjustment. A lower corrected total can leave supplier credit.</p></section>}
  </fieldset>
  {(validation || currencies.error || suppliers.error || products.error) && <p role="alert" className="text-sm text-destructive">{validation || currencies.error?.message || suppliers.error?.message || products.error?.message}</p>}
  <div className="flex justify-end"><Button type="submit" disabled={save.isPending || currencies.isPending}>{purchase?'Review correction':'Review & post purchase'}</Button></div></form>
  <ConfirmDialog open={confirm} onOpenChange={setConfirm} title={purchase?"Save purchase correction?":"Post this purchase?"} description={purchase?`Corrected total: ${amount(totals?.original)} ${currency} = ${amount(totals?.mmk)} MMK. Reason: ${reason}. The original purchase remains in revision history.`:`New purchase: ${amount(totals?.original)} ${currency} = ${amount(totals?.mmk)} MMK. The posted amounts and exchange rate will be locked.`} confirmLabel={purchase?"Save correction":"Post purchase"} busy={save.isPending} error={save.error?.message} onConfirm={() => save.mutate()} />
 </>
}
