import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Select, SelectItem } from '@/components/ui/select'
import { DataTable, FormField, Modal, PageHeader, SearchInput } from '@/components/shared'
import { requestJSON } from '@/services/api'
import { can, permissions, type CurrentUser } from '@/permissions'
import { amount, today, type Purchase } from './types'

type Payment = { id:string; payment_number:string; amount:string; currency_code:string; method:string; paid_at:string; reference_number:string|null; bank_account:string|null; notes:string|null; created_by:string; created_at:string; status:string }
type Method = { code:string; name:string; category:string }
const paymentStatus = (p:Purchase) => !p.outstanding_original ? 'Not posted' : /^0+(\.0+)?$/.test(p.outstanding_original) ? 'Paid' : p.amount_paid_mmk && !/^0+(\.0+)?$/.test(p.amount_paid_mmk) ? 'Partially Paid' : 'Unpaid'
export function PurchasePayments({purchase:p,current}:{purchase:Purchase;current:CurrentUser}) {
 const [open,setOpen]=useState(false)
 const history=useQuery({queryKey:['purchase-payments',p.id],queryFn:({signal})=>requestJSON<{payments:Payment[]}>(`/purchases/${p.id}/payments`,{signal}),retry:false})
 return <section className="panel mb-5 space-y-4 p-5" aria-label="Supplier payments"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Supplier payments</h2>{p.status==='POSTED'&&paymentStatus(p)!=='Paid'&&can(current,permissions.paymentsManage)&&<Button onClick={()=>setOpen(true)}>Record Payment</Button>}</div><div className="grid gap-4 sm:grid-cols-4">{[['Purchase total',`${amount(p.total_original)} ${p.currency_code}`],['Paid',`${amount(p.amount_paid_mmk)} MMK`],['Remaining',`${amount(p.outstanding_original)} ${p.currency_code}`],['Payment status',paymentStatus(p)]].map(([label,value])=><div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>)}</div><p className="text-xs text-muted-foreground">Supplier invoice balance. Transport-provider payments are separate; transport still contributes to landed cost.</p><DataTable caption="Payment history" rows={history.data?.payments||[]} rowKey={r=>r.id} loading={history.isPending} error={history.error?.message} onRetry={()=>void history.refetch()} columns={[
 {id:'id',header:'Payment / Date',cell:r=><div>{r.payment_number}<p className="text-xs">{new Date(r.paid_at).toLocaleDateString()}</p></div>},
 {id:'amount',header:'Amount',cell:r=>`${amount(r.amount)} ${r.currency_code}`},
 {id:'method',header:'Method / Reference',cell:r=><div>{r.method}<p className="text-xs">{r.reference_number} {r.bank_account}</p></div>},
 {id:'audit',header:'Recorded by / Status',cell:r=><div>{r.created_by} · {r.status}<p className="text-xs">{new Date(r.created_at).toLocaleString()}</p><p className="text-xs">{r.notes}</p></div>}
 ]}/><Modal open={open} onOpenChange={setOpen} title="Record supplier payment">{open&&<PaymentForm purchase={p} done={()=>setOpen(false)}/>}</Modal></section>
}
function PaymentForm({purchase:p,done}:{purchase:Purchase;done:()=>void}) {
 const client=useQueryClient()
 const [requestID]=useState(()=>crypto.randomUUID())
 const [value,setValue]=useState('');const [method,setMethod]=useState('CASH');const [date,setDate]=useState(today());const [reference,setReference]=useState('');const [bank,setBank]=useState('');const [notes,setNotes]=useState('')
 const methods=useQuery({queryKey:['supplier-payment-methods'],queryFn:()=>requestJSON<Method[]>('/supplier-payment-methods')})
 const save=useMutation({mutationFn:()=>requestJSON(`/purchases/${p.id}/payments`,{method:'POST',body:JSON.stringify({request_id:requestID,amount:value,method_code:method,paid_at:`${date}T23:59:59+06:30`,reference_number:reference,bank_account:bank,notes})}),onSuccess:async()=>{await client.invalidateQueries();done()}})
 return <form className="space-y-4" onSubmit={e=>{e.preventDefault();if(!save.isPending)save.mutate()}}><p className="text-sm">{p.purchase_number} · {p.supplier_name}</p><p className="text-sm">Total: {amount(p.total_original)} {p.currency_code} · Paid: {amount(p.amount_paid_mmk)} MMK · Remaining: {amount(p.outstanding_original)} {p.currency_code}</p><fieldset disabled={save.isPending} className="space-y-4"><FormField label={`Payment amount (${p.currency_code})`} required>{props=><input {...props} className="field" inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)} />}</FormField><p className="text-xs text-muted-foreground">Pay in the invoice currency. Historical rate: 1 {p.currency_code} = {amount(p.mmk_per_unit)} MMK.</p><FormField label="Payment method" required>{props=><Select {...props} value={method} onValueChange={setMethod}>{(methods.data||[]).map(m=><SelectItem key={m.code} value={m.code}>{m.name}</SelectItem>)}</Select>}</FormField><FormField label="Payment date" required>{props=><input {...props} className="field" type="date" value={date} onChange={e=>setDate(e.target.value)}/>}</FormField><FormField label="Transaction / Reference number">{props=><input {...props} className="field" maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/>}</FormField><FormField label="Bank account">{props=><input {...props} className="field" maxLength={200} value={bank} onChange={e=>setBank(e.target.value)}/>}</FormField><FormField label="Payment notes">{props=><textarea {...props} className="field" maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)}/>}</FormField></fieldset>{(save.error||methods.error)&&<p role="alert" className="text-sm text-destructive">{save.error?.message||methods.error?.message}</p>}<Button disabled={save.isPending||!methods.data}>Confirm Payment</Button></form>
}
export default function SupplierPayments({current,embedded=false}:{current:CurrentUser;embedded?:boolean}) {
 const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [page,setPage]=useState(1);const [selected,setSelected]=useState<Purchase|null>(null);const [recording,setRecording]=useState<Purchase|null>(null)
 const params=new URLSearchParams({q:search,payment_status:status,page:String(page),page_size:'20'})
 const query=useQuery({queryKey:['supplier-payments',params.toString()],queryFn:({signal})=>requestJSON<{purchases:Purchase[];total:number}>(`/supplier-payments?${params}`,{signal}),retry:false})
 const selectedPurchase=useQuery({queryKey:['purchase',selected?.id],queryFn:({signal})=>requestJSON<Purchase>(`/purchases/${selected!.id}`,{signal}),enabled:!!selected,retry:false})
 const fresh=selected&&(selectedPurchase.data||query.data?.purchases.find(p=>p.id===selected.id)||selected)
 return <>{!embedded&&<PageHeader title="Supplier Payments" eyebrow="Purchasing / Payments" description="Record partial or full payments and review supplier invoice balances."/>}<div className="mb-5 flex flex-wrap gap-4"><SearchInput label="Search supplier payments" value={search} onValueChange={v=>{setSearch(v);setPage(1)}} placeholder="Supplier or purchase…"/><Select aria-label="Payment status filter" value={status} onValueChange={v=>{setStatus(v);setPage(1)}}><SelectItem value="">All payment statuses</SelectItem>{['UNPAID','PARTIALLY_PAID','PAID'].map(s=><SelectItem key={s} value={s}>{s.replaceAll('_',' ')}</SelectItem>)}</Select></div><DataTable caption="Supplier purchase balances" rows={query.data?.purchases||[]} rowKey={p=>p.id} loading={query.isPending} error={query.error?.message} onRetry={()=>void query.refetch()} pagination={{page,pageSize:20,total:query.data?.total||0,onPageChange:setPage}} columns={[
 {id:'purchase',header:'Purchase / Date',cell:p=><div><a className="text-primary underline" href={`/purchases/${p.id}`}>{p.purchase_number}</a><p>{new Date(p.purchased_at).toLocaleDateString()}</p></div>},
 {id:'supplier',header:'Supplier',cell:p=>p.supplier_name},{id:'total',header:'Total',cell:p=>`${amount(p.total_original)} ${p.currency_code}`},{id:'paid',header:'Paid (MMK)',cell:p=>amount(p.amount_paid_mmk)},{id:'remaining',header:'Remaining',cell:p=>`${amount(p.outstanding_original)} ${p.currency_code}`},{id:'status',header:'Payment status',cell:paymentStatus},{id:'action',header:'Next action',cell:p=><Button size="sm" variant="outline" onClick={()=>{setSelected(p);if(paymentStatus(p)!=='Paid'&&can(current,permissions.paymentsManage))setRecording(p)}}>{paymentStatus(p)==='Paid'||!can(current,permissions.paymentsManage)?'Payment history':'Record Payment'}</Button>}
 ]}/><Modal open={!!recording} onOpenChange={v=>{if(!v)setRecording(null)}} title="Record supplier payment">{recording&&<PaymentForm purchase={recording} done={()=>setRecording(null)}/>}</Modal>{fresh&&<div className="mt-5"><PurchasePayments key={fresh.id} purchase={fresh} current={current}/></div>}{can(current,permissions.settingsManage)&&<MethodSettings/>}</>
}
function MethodSettings(){
 const client=useQueryClient();const [name,setName]=useState('');const [code,setCode]=useState('');const [category,setCategory]=useState('BANK_TRANSFER')
 const save=useMutation({mutationFn:()=>requestJSON('/supplier-payment-methods',{method:'POST',body:JSON.stringify({name,code,category})}),onSuccess:async()=>{await client.invalidateQueries({queryKey:['supplier-payment-methods']});setName('');setCode('')}})
 return <details className="panel mt-5 p-5"><summary className="cursor-pointer text-sm font-semibold">Add payment method</summary><form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();save.mutate()}}><FormField label="Method name" required>{p=><input {...p} className="field" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/>}</FormField><FormField label="Method code" required>{p=><input {...p} className="field" maxLength={40} pattern="[A-Z][A-Z0-9_]*" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/>}</FormField><Select aria-label="Method category" value={category} onValueChange={setCategory}>{['CASH','BANK_TRANSFER','MOBILE_PAYMENT','OTHER'].map(v=><SelectItem key={v} value={v}>{v.replaceAll('_',' ')}</SelectItem>)}</Select>{save.error&&<p role="alert">{save.error.message}</p>}{save.isSuccess&&<p role="status">Payment method added.</p>}<Button disabled={save.isPending}>Add method</Button></form></details>
}
