import { Select, SelectItem } from '@/components/ui/select'
import { useState, type FormEvent } from 'react'
import { useMutation } from '@tanstack/react-query'
import { Plus, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { FormField, PageHeader, QuantityInput } from '@/components/shared'
import { requestJSON } from '@/services/api'
import { can, permissions, type CurrentUser } from '@/permissions'
import { conversion, type Product, type ProductInput, type Catalog, type Packaging } from './types'

export function ProductForm({ product, catalog, current }: { product?: Product; catalog: Catalog; current: CurrentUser }) {
  const [form, setForm] = useState<ProductInput>(() => product ? {
    sku: product.sku, name: product.name, barcode: product.barcode || '', category_id: product.category_id || '', brand_id: product.brand_id || '', country_code: product.country_code || '', description: product.description || '', base_unit_code: product.base_unit_code, minimum_stock: product.minimum_stock || '', tracks_expiry: product.tracks_expiry, is_active: product.is_active, version: product.version, packaging: product.packaging.map(p => ({ ...p, barcode: p.barcode || '' })),
  } : { sku: '', name: '', barcode: '', category_id: '', brand_id: '', country_code: '', description: '', base_unit_code: 'PIECE', minimum_stock: '', tracks_expiry: false, is_active: true, version: '', packaging: [{ unit_code: 'PIECE', units_per_pack: '1', barcode: '', is_default_purchase: true, is_default_sale: true }] })
  const save = useMutation({ mutationFn: () => requestJSON<Product>(product ? `/products/${product.id}` : '/products', { method: product ? 'PUT' : 'POST', body: JSON.stringify(form) }), onSuccess: p => window.location.assign(`/products/${p.id}`) })
  function set<K extends keyof ProductInput>(key: K, value: ProductInput[K]) { setForm(f => ({ ...f, [key]: value })) }
  function pack(index: number, patch: Partial<Packaging>) { setForm(f => ({ ...f, packaging: f.packaging.map((p, i) => i === index ? { ...p, ...patch } : p) })) }
  function defaultPack(index: number, key: 'is_default_purchase' | 'is_default_sale') { set('packaging', form.packaging.map((p, i) => ({ ...p, [key]: i === index }))) }
  function base(code: string) { setForm(f => ({ ...f, base_unit_code: code, packaging: f.packaging.map(p => p.unit_code === f.base_unit_code ? { ...p, unit_code: code, units_per_pack: '1' } : p) })) }
  function submit(e: FormEvent) { e.preventDefault(); if (!save.isPending) save.mutate() }
  const back = product ? `/products/${product.id}` : '/products'
  return <><PageHeader eyebrow="Product & stock / Catalog" title={product ? 'Edit Product' : 'Add Product'} description="Define the product once, then connect its packaging to purchases and sales." actions={<Button asChild variant="outline"><a href={back}>Cancel</a></Button>} />
    <form onSubmit={submit} className="space-y-5"><fieldset disabled={save.isPending} className="space-y-5"><section className="panel p-5"><h2 className="mb-5 text-sm font-semibold">Product identity</h2><div className="grid gap-5 sm:grid-cols-2"><FormField label="Product name" required>{p => <input {...p} className="field" value={form.name} onChange={e => set('name', e.target.value)} maxLength={200} />}</FormField><FormField label="SKU" required hint="Unique product code. Case-insensitive.">{p => <input {...p} className="field font-mono" value={form.sku} onChange={e => set('sku', e.target.value)} maxLength={100} />}</FormField><FormField label="Product barcode" hint="For the base unit. Leading zeros are preserved.">{p => <input {...p} className="field font-mono" value={form.barcode} onChange={e => set('barcode', e.target.value)} maxLength={100} />}</FormField><FormField label="Country of origin" hint="Optional two-letter code, e.g. IN, TH, CN.">{p => <input {...p} className="field uppercase" value={form.country_code} onChange={e => set('country_code', e.target.value.toUpperCase())} maxLength={2} pattern="[A-Za-z]{2}" />}</FormField>
    {(['categories', 'brands'] as const).map(kind => { const key = kind === 'categories' ? 'category_id' : 'brand_id'; return <FormField key={kind} label={kind === 'categories' ? 'Category' : 'Brand'}>{p => <Select {...p}  value={form[key]} onValueChange={value => set(key, value)}><SelectItem value="">Not assigned</SelectItem>{catalog[kind].filter(v => v.is_active || v.id === form[key]).map(v => <SelectItem key={v.id} value={v.id} disabled={!v.is_active}>{v.name}{v.is_active ? '' : ' (inactive — choose another)'}</SelectItem>)}</Select>}</FormField> })}
    </div>{can(current, permissions.catalogManage) && <a className="mt-4 inline-block text-xs text-primary underline" href="/catalog" target="_blank" rel="noreferrer">Manage categories, brands & units in a new tab</a>}<div className="mt-5"><FormField label="Description">{p => <textarea {...p} className="field min-h-24" maxLength={4000} value={form.description} onChange={e => set('description', e.target.value)} />}</FormField></div></section>
    <section className="panel p-5"><h2 className="mb-2 text-sm font-semibold">Packaging & conversions</h2><p className="mb-5 text-xs leading-5 text-muted-foreground">All conversions use the smallest stock unit. Example: 1 Carton = 12 Bottles. Choose one purchase default and one sale default.</p><div className="mb-5 max-w-sm"><FormField label="Base stock unit" required hint="Cannot change after the product is used in transactions.">{p => <Select {...p}  value={form.base_unit_code} onValueChange={value => base(value)}>{catalog.units.map(u => <SelectItem key={u.code} value={u.code} disabled={form.packaging.some(p => p.unit_code === u.code && u.code !== form.base_unit_code)}>{u.name}</SelectItem>)}</Select>}</FormField></div>
    <div className="space-y-3">{form.packaging.map((row, i) => <fieldset key={i} className="rounded-xl border p-4"><legend className="px-1 text-xs font-medium">Packaging {i + 1}{row.unit_code === form.base_unit_code ? ' · Base unit' : ''}</legend><div className="grid gap-4 sm:grid-cols-3"><FormField label={`Packaging unit ${i + 1}`} required>{p => <Select {...p}  value={row.unit_code} disabled={row.unit_code === form.base_unit_code} onValueChange={value => pack(i, { unit_code: value })}>{catalog.units.map(u => <SelectItem key={u.code} value={u.code} disabled={form.packaging.some((other, j) => other.unit_code === u.code && i !== j)}>{u.name}</SelectItem>)}</Select>}</FormField><FormField label={`Base units per pack ${i + 1}`} required>{p => <QuantityInput {...p} unit={form.base_unit_code} value={row.units_per_pack} readOnly={row.unit_code === form.base_unit_code} onValueChange={value => pack(i, { units_per_pack: value })} />}</FormField><FormField label={`Packaging barcode ${i + 1}`} hint="Optional; distinct from the product barcode.">{p => <input {...p} className="field font-mono" maxLength={100} value={row.barcode || ''} onChange={e => pack(i, { barcode: e.target.value })} />}</FormField></div><div className="mt-4 flex flex-wrap items-center gap-4 text-xs"><label className="flex gap-2"><input type="radio" name="purchase-default" className="accent-primary" checked={row.is_default_purchase} onChange={() => defaultPack(i, 'is_default_purchase')} />Purchase default</label><label className="flex gap-2"><input type="radio" name="sale-default" className="accent-primary" checked={row.is_default_sale} onChange={() => defaultPack(i, 'is_default_sale')} />Sale default</label><span className="text-muted-foreground">{conversion(row, form.base_unit_code, catalog)}</span>{row.unit_code !== form.base_unit_code && <Button type="button" variant="ghost" size="sm" aria-label={`Remove packaging ${i + 1}`} onClick={() => { const next = form.packaging.filter((_, j) => i !== j); if (row.is_default_purchase) next[0] = { ...next[0], is_default_purchase: true }; if (row.is_default_sale) next[0] = { ...next[0], is_default_sale: true }; set('packaging', next) }}><Trash2 />Remove</Button>}</div></fieldset>)}</div>
    <Button type="button" variant="outline" className="mt-4" disabled={form.packaging.length >= 20 || form.packaging.length >= catalog.units.length} onClick={() => { const next = catalog.units.find(u => u.code === 'CARTON' && !form.packaging.some(p => p.unit_code === u.code)) || catalog.units.find(u => !form.packaging.some(p => p.unit_code === u.code)); if (next) set('packaging', [...form.packaging, { unit_code: next.code, units_per_pack: '', barcode: '', is_default_purchase: false, is_default_sale: false }]) }}><Plus />Add packaging</Button></section>
    <section className="panel p-5"><h2 className="mb-5 text-sm font-semibold">Stock settings</h2><div className="grid gap-5 sm:grid-cols-2"><FormField label="Minimum stock" hint="Optional threshold in base stock units. This does not set current stock.">{p => <QuantityInput {...p} value={form.minimum_stock} unit={form.base_unit_code} onValueChange={v => set('minimum_stock', v)} />}</FormField><FormField label="Status" required>{p => <Select {...p}  value={form.is_active ? 'active' : 'inactive'} onValueChange={value => set('is_active', value === 'active')}><SelectItem value="active">Active</SelectItem><SelectItem value="inactive">Inactive</SelectItem></Select>}</FormField></div><label className="mt-5 flex items-center gap-2 text-sm"><input type="checkbox" className="accent-primary" checked={form.tracks_expiry} onChange={e => set('tracks_expiry', e.target.checked)} />Track batch expiry</label></section></fieldset>
    {save.error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-destructive">{save.error.message} {product && <a className="underline" href={window.location.pathname}>Reload product</a>}</p>}<div className="flex justify-end gap-3"><Button asChild variant="outline"><a href={back}>Cancel</a></Button><Button type="submit" disabled={save.isPending}>{save.isPending ? 'Saving…' : product ? 'Save changes' : 'Create product'}</Button></div></form>
  </>
}
